### PR TITLE
fix: replace all escaped `\n` with an actual `\n` character

### LINKED ISSUE #13093: Default value field strips newlines
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.0.7
- Database: Sqlite
- Operating system: Ubuntu 20.04

### Describe the bug

The default value option strips newlines, making it impossible to define multiline default values for Rich Text fields.

### Steps to reproduce the behavior

1. Create a Collection Type with a Rich Text field.
2. In the Rich Text field's settings, set the default value to "lineone\nlinetwo"
3. Save the new Collection Type.
4. Go to the Content Manager and create a new object from the Collection Type
5. In the Rich Text field, it'll show "lineonelinetwo", with no newline between the lines.

### Expected behavior
In step 5, I expected to see
```
lineone
linetwo
```

### Screenshots
N/A

### Code snippets
N/A

### Additional context
I'm using the Toast UI Editor plugin, but the bug occurs with Strapi's default markdown editor as well.

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

When our objects are stringified they're parsed so the `\n` becomes `\\n`, which means when it's parsed, it's no longer recognised as a line-break character, instead it's recognised as a `\` and `n` separately. This PR replaces those string sections, with the line-break character again.

### Why is it needed?

IMO it's a little confusing because `\n` isn't strictly markdown and if people use `<br>` instead, everything works fine. But this solution does solve the issue brought up by the community.

### How to test it?

* Add richtext content field to a content type
* Set a default value of something like `hello\nthere`
* Create new content entry based on initial type
* Select preview mode
* There should be a line break.

This will also work if you type out line breaks in the editor itself.

### Related issue(s)/PR(s)

* resolves #13093

### CODE REVIEW

**Review by ronronscelestes — COMMENTED** [review]
mmh so `codemirror` automatically escaping any `\` by replacing it with `\\` but then we reverse it for preview with `markdown it`? 👀
works well though well done!

**Comment by joshuaellis** [comment]
> mmh so `codemirror` automatically escaping any `\` by replacing it with `\\` but then we reverse it for preview with `markdown it`? 👀 works well though well done!

It seems to be when the value is part of an action dispatched that it's serialized along the way & then it's put in the store, but the same is to be said when we get the default value from the API response on initial launch, CodeMirror doesn't really do much in this case I believe.

**Review by ronronscelestes — APPROVED** [review]
LGTM - nice catch 💃

File: packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ import sanitizeHtml from './utils/satinizeHtml';
 import Wrapper from './Wrapper';
 
 const PreviewWysiwyg = ({ data }) => {
-  const html = useMemo(() => sanitizeHtml(md.render(data || '')), [data]);
+  const html = useMemo(() => sanitizeHtml(md.render(data.replaceAll('\\n', '\n') || '')), [data]);
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16]: I'm wondering if this applies to `\\n` only, or also other ASCII operators such as `\\r` or `\\t`?

Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16]: Yeah other characters need fixing like `\r` but IMO it's all not markdown and I don't think we should support this. Otherwise, we have to re-add all the characters here. wdyt?

Comment (gu-stav) [reply packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16]: Sorry, I didn't know you were waiting for me here. Alright, then let's go with what you have!
