### PR TITLE
Fixing GraphQL timestamps

### LINKED ISSUE #2688: Timestamps missing in GraphQL queries
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.21
- **Database**:  10.0.36-MariaDB
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**

The GraphQL plugin is generating schemas without createdAt and updatedAt field, but they're correct in the database and model is correctly configured (timestamps: true in options)

**Steps to reproduce the problem**

Used a fresh install, migrated my models to it, installed GraphQL plugin and still starting the app.

**What is the expected behavior?**

Should have createdAt and updatedAt in graphql schemas to query these fields.

**Suggested solutions**

### PR DESCRIPTION
**Pull request by NeOMakinG**
**My PR is a:**
- [ ] 💥 Breaking change
- [x] 🐛 Bug fix #2688
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

**Manual testing done on the following databases:**
- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [x] Postgres

**Description:**

#2688 

Applying custom timestamps fields to GraphQL plugin

### CODE REVIEW

File: packages/strapi-plugin-graphql/services/Resolvers.js [hunk 1]
```diff
@@ -59,7 +59,9 @@ module.exports = {
       }
 
       // Add timestamps attributes.
-      if (_.get(model, 'options.timestamps') === true) {
+      const isArrayTimestamps = _.isArray(_.get(model, 'options.timestamps'));
```
Comment (lauriejim) [inline packages/strapi-plugin-graphql/services/Resolvers.js]: Since I worked on that point `_.get(model, 'options.timestamps')` will be an `array` or `false`.
So we can remove this line and use `_.isArray(_.get(model, 'options.timestamps')` for the `if condition`

File: packages/strapi-plugin-graphql/services/Resolvers.js [hunk 2]
```diff
@@ -59,7 +59,9 @@ module.exports = {
...
+
+      if (isArrayTimestamps || _.get(model, 'options.timestamps') == true) {
```
Comment (lauriejim) [inline packages/strapi-plugin-graphql/services/Resolvers.js]: See my previous comment.
`if (_.isArray(_.get(model, 'options.timestamps')) {`

File: packages/strapi-plugin-graphql/services/Resolvers.js [hunk 3]
```diff
@@ -59,7 +59,9 @@ module.exports = {
...
         Object.assign(initialState, {
           createdAt: 'DateTime!',
```
Comment (lauriejim) [inline packages/strapi-plugin-graphql/services/Resolvers.js]: We also have to update this key.

File: packages/strapi-plugin-graphql/services/Resolvers.js [hunk 4]
```diff
@@ -68,11 +70,11 @@ module.exports = {
         Object.assign(acc.resolver[globalId], {
           createdAt: (obj) => {
             // eslint-disable-line no-unused-vars
-            return obj.createdAt || obj.created_at;
+            return isArrayTimestamps ? obj[_.get(model, 'options.timestamps[0]')] : obj.createdAt || obj.created_at;
```
Comment (lauriejim) [inline packages/strapi-plugin-graphql/services/Resolvers.js]: Here we already check that `options.timestamps` is an array so we don't need to check it again.
So we just need to return `obj[_.get(model, 'options.timestamps[0]')]`

File: packages/strapi-plugin-graphql/services/Resolvers.js [hunk 5]
```diff
@@ -68,11 +70,11 @@ module.exports = {
...
           },
           updatedAt: (obj) => {
             // eslint-disable-line no-unused-vars
-            return obj.updatedAt || obj.updated_at;
+            return isArrayTimestamps ? obj[_.get(model, 'options.timestamps[1]')] : obj.updatedAt || obj.updated_at;
```
Comment (lauriejim) [inline packages/strapi-plugin-graphql/services/Resolvers.js]: Here we already check that `options.timestamps` is an array so we don't need to check it again.
So we just need to return `obj[_.get(model, 'options.timestamps[1]')]`

File: packages/strapi-plugin-graphql/services/Resolvers.js (hunk 1 above)
Comment (NeOMakinG) [reply packages/strapi-plugin-graphql/services/Resolvers.js]: options.timestamps will not be a boolean anymore ? It seems like my models got bool by default, that's why I was checking if this options was true or an array

File: packages/strapi-plugin-graphql/services/Resolvers.js [hunk 6]
```diff
@@ -59,7 +59,9 @@ module.exports = {
       }
 
       // Add timestamps attributes.
-      if (_.get(model, 'options.timestamps') === true) {
+      const isArrayTimestamps = _.isArray(_.get(model, 'options.timestamps'));
+
+      if (isArrayTimestamps || _.get(model, 'options.timestamps') == true) {
         Object.assign(initialState, {
           createdAt: 'DateTime!',
           updatedAt: 'DateTime!',
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply packages/strapi-plugin-graphql/services/Resolvers.js]: Oh well, sorry for that, I used to test it with createdAt and updatedAt, that's why it didn't return any errors.

**Comment by NeOMakinG** [comment]
Could you please check my comment on your first one ? So I can update the PR.

Thanks

File: packages/strapi-plugin-graphql/services/Resolvers.js (hunk 4 above)
Comment (NeOMakinG) [reply packages/strapi-plugin-graphql/services/Resolvers.js]: with of course createdAt and create_at fallbacks because of default values of options.timestamps with mongo or mariadb ?

**Comment by alexKwonIsAwesome** [comment]
Thanks for the work🎉 I'm waiting for the bugfix

**Comment by NeOMakinG** [comment]
Let me know if that's ok, I was wondering what's the best way to assign vars in keys, hopefully that's right.

Do we need to check the length of the array ?
