### PR TITLE
Fix schema support for postgres when using raw queries

### LINKED ISSUE #14038: Relations upload_folders does not exist happening after updating Strapi
### Required System information

- Node.js version:  16.15.1
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: Postgres 12.11, 14.2
- Operating system: Ubuntu Linux 20.04, MacOS Catalina

### Describe the bug

Updated Strapi version from 4.2.0 to 4.3.2, just changed this entries in the `package.json` file :
```
"@strapi/plugin-i18n": "4.3.2",
"@strapi/plugin-users-permissions": "4.3.2",
"@strapi/strapi": "4.3.2",
```
Installed the packages using `yarn install`, and rebuilt the Strapi admin panel using `yarn strapi build`
After a while running the server and navigating in the Content Manager started to get this error message:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
error: select LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE("path", $1, $2), $3, $4), $5, $6), $7, $8), $9, $10), $11, $12), $13, $14), $15, $16), $17, $18), $19, $20)) AS depth, COUNT(*) AS occurence from "upload_folders" group by "depth" - relation "upload_folders" does not exist
    at Parser.parseErrorMessage (/opt/queplan/apps/strapi.new/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/queplan/apps/strapi.new/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/queplan/apps/strapi.new/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/opt/queplan/apps/strapi.new/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

Checked the database tables and the upload_folders  table does exist.

### Steps to reproduce the behavior

Sorry about not having the precise steps, it happens after a while when navigating inside the Content Manager.

### Expected behavior

- No errors are expected due to the  database already seem to have all the required relations.
- Double checking the  existing database relations  before  sending an error.
- A more explicit error message in order to be able to look for a workaround.

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

It correctly adds the Postgres schema when doing raw queries

### Why is it needed?

Because it breaks some raw queries (relations, Media Library)

### How to test it?

Add a schema in your database config `config/database.js` and try to use the relations and manipulate folders.

### Related issue(s)/PR(s)
fix #14038

### CODE REVIEW

File: packages/core/upload/server/services/metrics.js [hunk 1]
```diff
@@ -49,9 +47,10 @@ module.exports = ({ strapi }) => ({
     */
 
     const folderLevelsArray = (
-      await knex(folderTable)
+      await strapi.db
+        .getConnection(folderTable)
         .select(
-          knex.raw(
+          strapi.db.connection.raw(
```
Comment (alexandrebodin) [inline packages/core/upload/server/services/metrics.js:53]: why not getConnection() here ?

Comment (petersg83) [reply packages/core/upload/server/services/metrics.js:53]: Because `getConnection()` automatically adds the schema (`.addSchema()`) if it exists and `.raw` and `.addSchema` are incompatible.

`.addSchema` is same as `select`, `update` etc., it starts a regular query.

So :
- `connection`always returns a knex object
- `getConnection()` returns a knex object or a knex queryBuilder object (if there is a schema)

**Comment by zodman** [comment]
on my radar for testing ...

File: packages/plugins/i18n/server/migrations/field/migrate-for-bookshelf.js [hunk 2]
```diff
@@ -18,6 +18,7 @@ const batchInsertInTmpTable = async ({ updatesInfo }, { transacting: trx }) => {
 const updateFromTmpTable = async ({ model, attributesToMigrate }, { transacting: trx }) => {
   const { collectionName } = model;
   if (model.client === 'pg') {
+    // IMPORTANT TODO: use postgres schema
```
Comment (alexandrebodin) [inline packages/plugins/i18n/server/migrations/field/migrate-for-bookshelf.js:21]: migration-for-bookshelf ? we probably didn't delete this file with the v4 release

File: packages/core/upload/server/services/metrics.js (hunk 1 above)
Comment (alexandrebodin) [reply packages/core/upload/server/services/metrics.js:53]: Ok for the sake of clarity I'm wondering if we may want to expose a db.raw() directly later on. TBD not urgent

File: packages/plugins/i18n/server/migrations/field/migrate-for-bookshelf.js (hunk 2 above)
Comment (alexandrebodin) [reply packages/plugins/i18n/server/migrations/field/migrate-for-bookshelf.js:21]: Yes it was intentionnal not to do it as it was supposed to be automatically be updated as soon as there was an edit or sth I believe

File: packages/core/upload/server/services/metrics.js (hunk 1 above)
Comment (petersg83) [reply packages/core/upload/server/services/metrics.js:53]: I like the idea. I probably can do it now

**Comment by jhoward1994** [comment]
Working for me, tested with PG and a custom DB schema 👍🏻

Just wondering if you think we need to wrap any of the raw query table names in `postgresql/schema-inspector.js` with `addSchema`? All the queries make sense to me without, just wanted to flag it in case you hadn't looked at that file

**Review by jhoward1994 — APPROVED** [review]

**Review by Marc-Roig — COMMENTED** [review]
LGTM! It works ok for me too.
I added a minor comment only.

**Comment by zodman** [comment]
I have testing on our repository this branch and *works* :+1:  thanks


cc @alexghattas

**Review by Marc-Roig — APPROVED** [review]
