### PR TITLE
fix: add support for private upload providers

### LINKED ISSUE #17571: Strapi Export/Transfer when using a private upload provider will fail to fetch files and stall
### Required System information

- Node.js version: 18
- NPM version: 8
- Strapi version: 4.12.1
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When an upload provider that uses some kind of private access to the files is used the Strapi export command will fail with a 4xx error (depends on configuration) but generally a 400, 401, or 403.

### Steps to reproduce the behavior

1. Install the `@strapi/provider-upload-aws-s3` provider
2. Configure it for private signed urls (sample config below)
3. Setup or use an example S3 private bucket (for Strapi team members see 1password for a private testing S3 bucket)
4. Upload a file
5. Try to run a strapi export ex: `yarn strapi export --no-encrypt --no-compress -f testPrivate`
6. See error

### Expected behavior

File export should work properly regardless of the provider configs if the admin is able to fetch the file, we may need to add an option or default to fetching the files proxied through the Strapi instance or adding a `get()` function to the providers to enable secure downloads.

### Screenshots

image

### Code snippets

Sample config for private S3 bucket:

```js
module.exports = ({ env }) => ({
  // ...
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          ACL: "private", // <== set ACL to private
          signedUrlExpires: env("AWS_SIGNED_URL_EXPIRES", 15 * 60),
          Bucket: env("AWS_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
  // ...
});
```

### Additional context

Related to two EE tickets:
- TID4484
- TID4490

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- Signs urls when they are coming from a private upload provider

### Why is it needed?

- users can't export and transfer files from private upload providers

### How to test it?

- create a private upload provider and attempt to export, import and transfer
- make sure that normal transfer work the same and are not affected by the changes

you can follow the example provided in this issue #17571 

### Related issue(s)/PR(s)

fix #17571

### CODE REVIEW

File: packages/core/data-transfer/src/strapi/providers/local-source/assets.ts [hunk 1]
```diff
@@ -76,6 +100,7 @@ export const createAssetsStream = (strapi: LoadedStrapi): Duplex => {
 
     for await (const file of stream) {
       const isLocalProvider = file.provider === 'local';
+      await signUrl(isLocalProvider, file);
```
Comment (innerdvations) [inline packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:103]: It might more sense to move the isLocalProvider conditional around this instead of inside it

File: packages/core/data-transfer/src/strapi/providers/local-source/assets.ts [hunk 2]
```diff
@@ -61,6 +61,30 @@ function getFileStats(filepath: string, isLocal = false): Promise<{ size: number
...
   });
 }
+
+async function signUrl(isLocalProvider: boolean, file: any) {
+  if (isLocalProvider) return;
+  const { provider } = strapi.plugins.upload;
+  const { provider: providerName } = strapi.config.get('plugin.upload') as any;
+  const isPrivate = await provider.isPrivate();
+  if (file.provider === providerName && isPrivate) {
+    const signUrl = async (file: any) => {
```
Comment (Convly) [inline packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:71]: It's a bit confusing to have this function being named the same as the parent one

Comment (Convly) [reply packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:71]: Also, could we use unknown instead of any when possible?

**Review by Convly — COMMENTED** [review]
I'm a bit surprised that the upload plugin doesn't handle the signature itself :slightly_frowning_face:

**Comment by Bassel17** [comment]
> I'm a bit surprised that the upload plugin doesn't handle the signature itself 🙁

it does, just at a different level, we only use the upload from the plugin itself, 
fetching and getting the file itself we get based on the file entity data, in which we have a url that is not signed

**Review by innerdvations — COMMENTED** [review]
Code LGTM but won't have time to QA until tomorrow

**Review by christiancp100 — APPROVED** [review]
Code LGTM! Good job!

**Comment by derrickmehaffy** [comment]
FYI for functional QA testing there is a private S3 bucket we use in our internal AWS for specifically testing this stuff, take a look in the company shared password manager.
