### PR TITLE
Fix error on adding relations

### LINKED ISSUE #17260: Error when adding a relation in Strapi
Bug report
Required System information
Node.js version: v16.19.0
NPM version: 8.19.3
Strapi version: 4.11.4
Database: MariaDB 10.4.21
Operating system: macOS
Is your project Javascript or Typescript: (Please specify)
Describe the bug
I encountered the following errors when trying to add a relation:

vbnet
Copy code
TypeError: ur.normalize is not a function
    at startsWith

TypeError: ur.normalize is not a function
    at startsWith
Steps to reproduce the behavior
1. Attempt to add a relation.
2. Receive an error indicating that something went wrong.

Screenshots
Ekran Resmi 2023-07-11 11 08 36
Ekran Resmi 2023-07-11 11 08 45

Code snippets
------

Additional context
-----

### PR DESCRIPTION
**Pull request by hasebsiddiqui**
### What does it do?

Stringify `mainField ?? id` before using because `ComboboxOption` is expecting `string` in `textValue` prop.

### Why is it needed?

Users were unable to add content for tables who have relations with tables containing only numbers or relations

### How to test it?

Create a table Table 1 with only `Number` or `Relations` fields.
Add some content in Table 1.
Create an other table Table 2 and add relation of `Table 1` in it.
Now add content in Table 2. Notice when you select `Table 1` dropdown it will give error.

### Related issue(s)/PR(s)

* resolves #17260
* closes #17315

### CODE REVIEW

**Comment by joshuaellis** [comment]
Can you add a test case for this please so we can ensure there's no regression? :)

**Comment by joshuaellis** [comment]
Also can you actually fill out the "What does it do?" section explaining technically, I know it's a small PR so a single sentence will be fine, but it's a lot easier to skim read the description over checking the code

File: packages/core/admin/admin/src/content-manager/components/RelationInput/components/Option.js [hunk 1]
```diff
@@ -20,6 +20,7 @@ const StyledBullet = styled.div`
 
 export const Option = ({ publicationState, mainField, id }) => {
   const { formatMessage } = useIntl();
+  const mainFieldString = (mainField ?? id).toString();
```
Comment (joshuaellis) [inline packages/core/admin/admin/src/content-manager/components/RelationInput/components/Option.js:23]: I think `stringifiedDisplayValue` is clearer imo, it shows its stringified and `mainField` is already used but this could be the `id` instead

File: packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js [hunk 2]
```diff
@@ -44,4 +44,14 @@ describe('Content-Manager || RelationInput || Option', () => {
...
   });
+
+  it('should render custom Option with mainField prop as number type', async () => {
+    const { user, getByRole, getByTitle } = setup({
+      options: [{ id: 1, mainField: 1, publicationState: 'published' }],
+    });
+
+    await user.click(getByRole('combobox'));
+
+    expect(getByTitle('State: Published')).toBeInTheDocument();
```
Comment (joshuaellis) [inline packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js:55]:
```suggestion
    expect(getByRole('option', { name: 'State: Published' })).toBeInTheDocument();
```

lets tweak this then we're confident we're targeting the option :)

Comment (hasebsiddiqui) [reply packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js]: Fixed

**Review by joshuaellis — APPROVED** [review]
Great work & thanks for adding a test ⭐

**Comment by hasebsiddiqui** [comment]
Thanks. This is my first Open Source PR in a big project and I am very happy :smiley:

**Comment by derrickmehaffy** [comment]
> Thanks. This is my first Open Source PR in a big project and I am very happy :smiley:

Congratulations and nice job!

**Comment by ahmadjoya** [comment]
when the v 12 will release?
