### PR TITLE
Fixes server restarting when modifying admin files

### LINKED ISSUE #11645: Admin UI refreshes on file change in public folder
### Describe the bug

Whenever I change a file that's located in the public folder of my Strapi instance the admin UI in my browser refreshes.
Like a hard refresh, not like a fancy SPA refresh 😛

It's only happening when I change an existing file. When I create a new file the Admin does not refresh.

Issue seems to have started happening since version `4.0.0-beta.12`.

### Steps to reproduce the behavior

To reproduce the bug you can create a file in the public folder and afterwards make a change to its content.
Another way, that's probably more likely to really happen when using Strapi, is by creating a media item in the media library and afterwards changing the file of the media item by clicking `Replace media`.

### Expected behavior

For the Admin UI not to refresh

### System

- Node.js version: v14.7.0
- NPM version: 6.14.7
- Strapi version: 4.0.0-beta.14
- Database: Postgres
- Operating system: Mac OS

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril@strapi.io>

### What does it do?

It applies the correct patterns in order to prevent the server from watching front end files updates.

### Why is it needed?

In order to improve the experience when developing plugins.

### How to test it?

1. Launch the getstarted app with the `--watch-admin` file. 
2. Make some modifications to one of the `./src/plugins/myplugin/admin/src/**/*.js` file.
3. Observe that the server is not restarting.

An other method is to : 
- Generate a Strapi app with `yarn create strapi-app my-app --quickstart --no-run`
- Apply the modification to the `node_modules/@strapi/strapi/lib/commands/develop`
- Generate a plugin
- Make some modification to one of the admin file
- Observe that the server is not restarting.

### Related issue(s)/PR(s)

Fixes #11645

### CODE REVIEW

File: packages/core/strapi/lib/commands/develop.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ function watchFileChanges({ dir, strapiInstance, watchIgnoreFiles, polling }) {
       /(^|[/\\])\../, // dot files
       /tmp/,
       '**/src/admin/**',
-      '**/src/plugins/**/admin/',
+      '**/src/plugins/**/admin/**',
       '**/documentation',
```
Comment (Convly) [inline packages/core/strapi/lib/commands/develop.js:124]: Why does it work for `documentation` & `node_modules` but not for the plugins though?

Comment (soupette) [reply packages/core/strapi/lib/commands/develop.js:124]: Here's the [documentation](https://github.com/micromatch/anymatch) of the library chokidar uses so I guess it was because the pattern was incorrect
