### PR TITLE
Fix default role provider and for create user

### LINKED ISSUE #1212: Default role not working on user create
**Informations**
- **Node.js version**:v10.1.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:Mongo
- **Operating system**:Linux

**What is the current behavior?**
Default role not working.

**Steps to reproduce the problem**
* create new role.
* Set that as a default role.
* Create new user and not set role for that.
* Default role not set for that after save.

**What is the expected behavior?**
We need default role set for role field when user not set.

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

### PR DESCRIPTION
**Pull request by lauriejim**
My PR is a: 🐛 Bug fix 

Main update on the:  Plugin

This issue fix default role apply to provider login. And set default role when user are create via the user API or via the content manager.

Related issue: https://github.com/strapi/strapi/issues/1212

### CODE REVIEW

File: packages/strapi-plugin-users-permissions/controllers/User.js [hunk 1]
```diff
@@ -70,19 +70,27 @@ module.exports = {
...
 
       if (user) {
         return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Auth.form.error.email.taken', field: ['email'] }] }] : 'Email is already taken.');
       }
     }
 
+    if (!ctx.request.body.role) {
+      const defaultRole = await strapi.query('role', 'users-permissions').findOne({ type: advanced.default_role }, []);
+
+      ctx.request.body.role = defaultRole._id || defaultRole.id;
```
Comment (Aurelsicoko) [inline packages/strapi-plugin-users-permissions/controllers/User.js]: FYI, we need to check `_id || id` because Mongoose has a default getter on the `id` attribute (if the lean() method isn't enabled) (see http://mongoosejs.com/docs/guide.html#id)

Comment (lauriejim) [reply packages/strapi-plugin-users-permissions/controllers/User.js]: Yap ! Just copy and past it from an other file.
