### PR TITLE
Fetch all entries with limit -1

### LINKED ISSUE #11473: [V4] A way of getting full data is missing
### Describe the bug

Unable to get full data from content-type with limit.

### Expected behavior

In **v3** we were able to retrieve every data from a content type by passing a limit equal to `-1`.
For static site generation or when you can't have an API running all the time, it is great to be able to retrieve all data and just bypass the pagination

### Code snippets

Tried to get all data by bypassing the limit thanks
```js
pagination[start]=0&pagination[limit]=-1
```

### System

- Node.js version: v14.18.1
- Strapi version: 4.0.0-beta.6
- Database: PG
- Operating system: MacOS BigSur

### PR DESCRIPTION
**Pull request by vincentbpro**
### What does it do?

It fixes a bug preventing from fetching all the entries of a collection when setting `?pagination[limit]=-1` in the API query.
The limit was maxed to `1` before checking `limit === -1`.

### Why is it needed?

Being able to fetch all entries is the expected behavior.

### Related issue(s)/PR(s)

fix #11473

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
You selected wing branch as Target merge :)

File: packages/plugins/graphql/server/services/internals/types/response-collection-meta.js [hunk 1]
```diff
@@ -25,9 +25,9 @@ module.exports = ({ strapi }) => {
             const { start, limit } = args;
 
             const total = await strapi.entityService.count(resourceUID, args);
-            const pageSize = limit;
-            const pageCount = limit === 0 ? 0 : Math.ceil(total / limit);
-            const page = limit === 0 ? 1 : Math.floor(start / limit) + 1;
+            const pageSize = limit === -1 ? total : limit;
```
Comment (Convly) [inline packages/plugins/graphql/server/services/internals/types/response-collection-meta.js:28]: I was wondering if it wouldn't be better to set the pageSize to `(limit || total) - start` (total if limit === -1 else limit). I think it would better reflect the actual size of the returned page.
What do you think?

**Review by Convly — COMMENTED** [review]
I only had one question

**Review by Convly — CHANGES_REQUESTED** [review]
Looks like some tests are broken since the last commit, otherwise looks good to me, waiting for Alexandre's review before merging.

File: packages/core/strapi/lib/core-api/__tests__/service.test.js [hunk 2]
```diff
@@ -146,3 +147,119 @@ describe('Default Service', () => {
     });
   });
 });
+
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/core-api/__tests__/service.test.js:150]: to be a bit more consistent now that the service is a folder in core-api can you move those tests in core-api/service/__tests__ and split the index & paginationt tests in 2 files

File: packages/core/strapi/lib/core-api/service/pagination.js [hunk 3]
```diff
@@ -18,12 +18,12 @@ const getLimitConfigDefaults = () => ({
  * @param {number?} maxLimit - maxlimit used has capping
  * @returns {number}
  */
-const applyMaxLimit = (limit, maxLimit) => {
-  if (maxLimit && (limit === -1 || limit > maxLimit)) {
-    return maxLimit;
+const applyMaxLimit = (limit, maxLimit = null) => {
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/core-api/service/pagination.js:21]: The Math.max doesn't really make sense in the applyMaxLimit function. You should keep this out of this function

File: packages/plugins/graphql/server/services/internals/types/response-collection-meta.js [hunk 4]
```diff
@@ -25,9 +25,9 @@ module.exports = ({ strapi }) => {
             const { start, limit } = args;
 
             const total = await strapi.entityService.count(resourceUID, args);
-            const pageSize = limit;
-            const pageCount = limit === 0 ? 0 : Math.ceil(total / limit);
-            const page = limit === 0 ? 1 : Math.floor(start / limit) + 1;
+            const pageSize = limit === -1 ? total - start : limit;
+            const pageCount = limit === -1 ? 1 : Math.ceil(total / limit);
+            const page = limit === -1 ? 1 : Math.floor(start / limit) + 1;
```
Comment (alexandrebodin) [inline packages/plugins/graphql/server/services/internals/types/response-collection-meta.js:30]: this will break if you don't keep the === 0 case too.

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/core/strapi/lib/core-api/service/__tests__/index.test.js [hunk 5]
```diff
@@ -1,25 +1,6 @@
...
-    },
-    api: {
-      rest: {
-        defaultLimit,
-        maxLimit,
-      },
-    },
-  },
-};
+const { createService } = require('..');
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/core-api/service/__tests__/index.test.js:3]: Just to be more explicit 

```suggestion
const { createService } = require('../index');
```

**Comment by alexandrebodin** [comment]
As discussed in the REST side we will only handle limit = -1 and not pageSize = -1 to make things a bit more consistent.

File: packages/plugins/graphql/server/services/internals/types/response-collection-meta.js (hunk 4 above)
Comment (alexandrebodin) [reply packages/plugins/graphql/server/services/internals/types/response-collection-meta.js:30]: ping on the divided by 0 issue here

File: packages/plugins/graphql/server/services/internals/types/response-collection-meta.js [hunk 6]
```diff
@@ -23,11 +23,12 @@ module.exports = ({ strapi }) => {
           async resolve(parent) {
             const { args, resourceUID } = parent;
             const { start, limit } = args;
+            const safeLimit = Math.max(limit, 1);
```
Comment (alexandrebodin) [inline packages/plugins/graphql/server/services/internals/types/response-collection-meta.js:26]: what happens with a limit = 0 with pageCount now ?

**Review by alexandrebodin — APPROVED** [review]
LGTM
