### PR TITLE
fix(admin): batch content manager permission checks and reuse session…

### LINKED ISSUE #22725: Slow permission checks after migration to Strapi V5
### Node Version

18-alpine

### NPM/Yarn/PNPM Version

pnpm 9.5

### Strapi Version

5.8.0

### Operating System

Linux (Other)

### Database

PostgreSQL

### Javascript or Typescript

Javascript

### Reproduction URL

_No response_

### Slow Admin Panel Performance After Migration to Strapi V5 for Users with Multiple Roles

After migrating to Strapi V5, we’ve encountered severe performance issues for users with multiple roles. The admin panel becomes significantly slower, with delays of up to **20 seconds** when clicking on the "Content Manager" or navigating to individual content types.  

Our server logs show frequent and sequential calls to `/admin/permissions/check` when accessing the Content Manager. Each subsequent call takes progressively longer to complete, as shown below:

### Steps to Reproduce

NA

### Expected Behavior

The admin panel and "Content Manager" should load quickly, regardless of the number of roles assigned to the user.

### Logs

```shell
[2025-01-24 12:10:13.633] http: GET /content-manager/content-types-settings (1557 ms) 200
[2025-01-24 12:10:14.445] http: POST /admin/permissions/check (706 ms) 200
[2025-01-24 12:10:14.920] http: POST /admin/permissions/check (1194 ms) 200
[2025-01-24 12:10:15.413] http: POST /admin/permissions/check (1680 ms) 200
[2025-01-24 12:10:16.116] http: POST /admin/permissions/check (2365 ms) 200
[2025-01-24 12:10:16.541] http: POST /admin/permissions/check (2743 ms) 200
[2025-01-24 12:10:16.981] http: POST /admin/permissions/check (3200 ms) 200
[2025-01-24 12:10:17.415] http: POST /admin/permissions/check (3622 ms) 200
[2025-01-24 12:10:17.838] http: POST /admin/permissions/check (4052 ms) 200
[2025-01-24 12:10:18.256] http: POST /admin/permissions/check (4485 ms) 200
[2025-01-24 12:10:18.669] http: POST /admin/permissions/check (4908 ms) 200
[2025-01-24 12:10:19.123] http: POST /admin/permissions/check (5367 ms) 200
[2025-01-24 12:10:19.586] http: POST /admin/permissions/check (5797 ms) 200
[2025-01-24 12:10:20.054] http: POST /admin/permissions/check (6278 ms) 200
[2025-01-24 12:10:20.514] http: POST /admin/permissions/check (6748 ms) 200
[2025-01-24 12:10:21.109] http: POST /admin/permissions/check (7305 ms) 200
[2025-01-24 12:10:21.573] http: POST /admin/permissions/check (7765 ms) 200
[2025-01-24 12:10:22.047] http: POST /admin/permissions/check (8234 ms) 200
[2025-01-24 12:10:22.494] http: POST /admin/permissions/check (8677 ms) 200
[2025-01-24 12:10:22.949] http: POST /admin/permissions/check (9124 ms) 200
[2025-01-24 12:10:23.413] http: POST /admin/permissions/check (9584 ms) 200
[2025-01-24 12:10:23.929] http: POST /admin/permissions/check (10061 ms) 200
[2025-01-24 12:10:24.412] http: POST /admin/permissions/check (10513 ms) 200
[2025-01-24 12:10:24.903] http: POST /admin/permissions/check (11039 ms) 200
[2025-01-24 12:10:25.390] http: POST /admin/permissions/check (11503 ms) 200
[2025-01-24 12:10:25.882] http: POST /admin/permissions/check (12022 ms) 200
[2025-01-24 12:10:26.544] http: POST /admin/permissions/check (12665 ms) 200
[2025-01-24 12:10:26.961] http: POST /admin/permissions/check (13071 ms) 200
[2025-01-24 12:10:27.387] http: POST /admin/permissions/check (13493 ms) 200
[2025-01-24 12:10:27.808] http: POST /admin/permissions/check (13933 ms) 200
[2025-01-24 12:10:28.226] http: POST /admin/permissions/check (14343 ms) 200
[2025-01-24 12:10:28.643] http: POST /admin/permissions/check (14771 ms) 200
[2025-01-24 12:10:29.106] http: POST /admin/permissions/check (15204 ms) 200
[2025-01-24 12:10:29.580] http: POST /admin/permissions/check (15673 ms) 200
[2025-01-24 12:10:30.033] http: POST /admin/permissions/check (16122 ms) 200
[2025-01-24 12:10:30.428] http: POST /admin/permissions/check (16513 ms) 200
[2025-01-24 12:10:30.758] http: POST /admin/permissions/check (16839 ms) 200
[2025-01-24 12:10:31.344] http: POST /admin/permissions/check (17421 ms) 200
[2025-01-24 12:10:31.815] http: POST /admin/permissions/check (17888 ms) 200
[2025-01-24 12:10:32.267] http: POST /admin/permissions/check (18336 ms) 200
[2025-01-24 12:10:32.719] http: POST /admin/permissions/check (18784 ms) 200
[2025-01-24 12:10:33.216] http: POST /admin/permissions/check (19277 ms) 200
[2025-01-24 12:10:33.675] http: POST /admin/permissions/check (19724 ms) 200
[2025-01-24 12:10:34.113] http: POST /admin/permissions/check (20158 ms) 200
```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

This change addresses the admin permission performance regression from two sides:

- It batches Content Manager link authorization during initialization, instead of calling `checkUserHasPermissions()` once per visible content type.
- It reuses the computed admin ability for repeated authenticated requests from the same admin session, instead of rebuilding the same ability on every request.
- It adds focused regression tests for both behaviors.

### Why is it needed?

After the Strapi v5 migration, users with multiple roles can experience slow admin navigation when opening Content Manager or moving to individual content types.

The issue comes from two compounding factors:

- Content Manager initialization was issuing multiple `/admin/permissions/check` requests, effectively one per visible content type when conditional permissions were involved.
- Each of those requests also rebuilt the admin user's ability on the server, which becomes increasingly expensive for users with multiple roles and permissions.

This change reduces the number of permission-check requests on the frontend and avoids recomputing the same ability repeatedly for the same active admin session on the backend.

### How to test it?

run tests:

```sh
yarn test:front packages/core/content-manager/admin/src/hooks/tests/useContentManagerInitData.test.tsx
yarn test:unit packages/core/admin/server/src/strategies/__tests__/admin.test.ts
```

Manual verification path:

1. Start Strapi with an admin user that has multiple roles and conditional permissions on several content types.
2. Open the admin panel and navigate to `Content Manager`.
3. Confirm that Content Manager loads without a burst of one `/admin/permissions/check` request per visible content type.
4. Confirm that repeated authenticated admin requests no longer rebuild the same ability on every request for the same active session.
5. Update an admin user, role, or permission and confirm behavior still reflects the change correctly after cache invalidation.

### Related issue(s)/PR(s)

fixes #22725

### CODE REVIEW

File: packages/core/admin/server/src/bootstrap.ts [hunk 1]
```diff
@@ -44,6 +45,22 @@ const registerModelHooks = () => {
   });
 };
 
+const registerAdminAuthCacheInvalidation = () => {
+  const invalidate = async () => {
```
Comment (jhoward1994) [inline packages/core/admin/server/src/bootstrap.ts:49]: I dont think this needs to be async?

File: packages/core/content-manager/admin/src/hooks/useContentManagerInitData.ts [hunk 2]
```diff
@@ -92,76 +112,71 @@ const useContentManagerInitData = (): AppState => {
...
-    );
-  };
+      const authorizedCollectionTypeLinks = await authorizeLinks(
+        collectionTypeSectionLinks,
+        checkUserHasPermissions
+      );
+      const authorizedSingleTypeLinks = await authorizeLinks(
+        singleTypeSectionLinks,
+        checkUserHasPermissions
+      );
```
Comment (jhoward1994) [inline packages/core/content-manager/admin/src/hooks/useContentManagerInitData.ts]: Would something like this work and be a bit more performant ?

```suggestion
      const allLinks = [...collectionTypeSectionLinks, ...singleTypeSectionLinks];
      const authorizedLinks = await authorizeLinks(allLinks, checkUserHasPermissions);

      const authorizedCollectionTypeLinks = authorizedLinks.filter(
        (link) => link.kind === 'collectionType'
      );
      const authorizedSingleTypeLinks = authorizedLinks.filter(
        (link) => link.kind === 'singleType'
      );
```

**Review by markkaylor — COMMENTED** [review]
I tested it and looks good to me, I'll leave the approval to Jamie since he had some feedback on the code

File: packages/core/admin/server/src/bootstrap.ts (hunk 1 above)
Comment (Bassel17) [reply packages/core/admin/server/src/bootstrap.ts:49]: the problem is more on the typing `strapi.eventHub.on('permission.create', invalidate);` would expect an async callback

File: packages/core/content-manager/admin/src/hooks/useContentManagerInitData.ts (hunk 2 above)
Comment (Bassel17) [reply packages/core/content-manager/admin/src/hooks/useContentManagerInitData.ts]: indeed I'll try it out

**Review by jhoward1994 — APPROVED** [review]
