### PR TITLE
Make updateContentTypeConfiguration endpoint return full data

### LINKED ISSUE #13675: Updating view configuration for a Single-type fails if it contains components
### Required System information
- Node.js version: 16.14.0
- Yarn version: 1.22.18
- Strapi version: 4.2.2
- Database: MySQL
- Operating system: Mac

### Describe the bug

**Updating view configuration for a Single-type fails if it contains components**

If there is a single-type entry and it contains components, when attempting to save the changes after configuring the view will fail.

### Steps to reproduce the behaviour

1. Create a fresh new project with Strapi.
2. Create a new component.
3. Create a single-type model
4. Go to Content Manager, and click the "Configure the view" button.
5. Shuffle the fields around and click save button
6. Confirm the action in the dialog

### Expected behaviour

The changes are successfully applied

### Actual behaviour

The error is shown as seen on the provided screenshot.
Also, the console has an error (screenshot provided).

### Screenshots
Screen Shot 2022-07-02 at 11 10 27 PM

Screen Shot 2022-07-02 at 11 14 13 PM

### Additional context

The problem happens because the response from the content-manager API after the new layout is applied does not contain "components" data but the handler in the Admin part requires the components data to be populated.

### PR DESCRIPTION
**Pull request by benderillo**
This PR fixes the issue #13675 

The Content-type controller returns the same response object as the "findConfiguration" now.

### What does it do?

This PR changes the response of the `PUT /content-types/:uid/configuration` to be the same as `GET /content-types/:uid/configuration`.

*In general it is a good practice for the REST APIs to have the same response object for `GET` and `PUT` for the same route with the `PUT` returning modified resource.*

### Why is it needed?

As described in the linked issue, attempting to change view configuration for a single-type entry will fail if the entry contains components.
What happens is that the `PUT /content-types/:uid/configuration` responds with only half of the data that the "Admin" UI package needs for correct behaviour. And the `updateLayout` method simply hardcodes the missing piece with an empty object `components: {}`.
The problem happens when later in the execution flow tree there is an attempt to dereference a null pointer:
https://github.com/strapi/strapi/blob/8b719b12e917cba7ef2d50b458331c59bd7a94c9/packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/formatLayouts.js#L167-L170

Here the `components` is an empty object, hence the `component` is undefined. Which means `component.settings` expression is doomed to fail.

### How to test it?

1. Create a fresh new project with Strapi.
2. Create a new component.
3. Create a single-type model
4. Go to Content Manager, and click the "Configure the view" button.
5. Shuffle the fields around and click save button
6. Confirm the action in the dialog

### Related issue(s)/PR(s)

fixes #13675

Note: No tests have been added for this code change. I don't have capacity to look into and update/add tests, sorry.

### CODE REVIEW

File: packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js [hunk 1]
```diff
@@ -68,10 +68,10 @@ const useFetchContentTypeLayout = contentTypeUID => {
   }, [contentTypeUID, getData]);
 
   const updateLayout = useCallback(
-    newLayout => {
+    data => {
       dispatch({
         type: 'UPDATE_LAYOUT',
-        newLayout: formatLayouts({ contentType: newLayout, components: {} }, schemas),
```
Comment (alexandrebodin) [inline packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js:74]: I'm wondering if the problem could be solved here by reusing the previously received components info as they won't have changed 🤔

Comment (alexandrebodin) [inline packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js:74]: I'm wondering if the problem could be solved here by reusing the previously received components info as they won't have changed 🤔

**Review by alexandrebodin — COMMENTED** [review]
That looks fairly straight forward. Just an open question as maybe we can avoid refecthing everything

File: packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js (hunk 1 above)
Comment (benderillo) [reply packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js:74]: Well, yes I wanted to do that at first. 
But I allocate myself only a very limited time to look into issues found in external software as I have a massive backlog of things I need to do in my own code base. 

**I could not figure out where the components data is stored on the frontend for reuse** so I figure I could just change 
 the endpoint to return the same object as the GET does. It aligned with the practice we have been following in my work places throughout my career where the PUT to an endpoint will return the modified resource.
In this case GET /configuration returns full configuration, so I made PUT /configuration return full configuration too. 
Yes, it is less efficient in terms of network use but it was quick and straightforward.

**Review by alexandrebodin — APPROVED** [review]
LGTM

**Comment by alexandrebodin** [comment]
Thanks for the fix 👍
