### PR TITLE
fix: cannot clear date-field

### LINKED ISSUE #16493: Cannot clear date field
### Required System information

- Node.js version: 16.x
- NPM version: 7.19.1
- Strapi version: 4.9.1
- Database: SQL
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

It's not possible to clear any date field (at least tested with date-time field) with the 'x'. So once you choose a date, you can only change it, but not clear it.

Here's the console output when pressing the X button.

image

Note: The 'time' part of the field works fine, it clears the field to 00:00

### Steps to reproduce the behavior

1. Create a content-type with a date field on it (date + time)
2. Get to the content-manager and pick any date on that field.
3. Click the X to clear the field
image
4. You won't be able to clear it.

### Expected behavior

I expect the field to be cleared, just like before I picked any date.

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

When a date field is cleared we pass `null` as the onChange value, however we weren't checking this before trying to use `formatISO`, we now do this. It also fixes a rogue `module.exports` declaration we have in the codebase.

### Why is it needed?

* Users were unable to clear date fields

### How to test it?

* Go to entry with date field & date time field
* clear the date
* see no errors

### Related issue(s)/PR(s)

* resolves #16493
* partially resolves CONTENT-1639

### CODE REVIEW

**Review by markkaylor — APPROVED** [review]
lgtm, I tested it locally.

File: packages/core/helper-plugin/src/components/GenericInput.jsx [hunk 1]
```diff
@@ -249,7 +249,11 @@ const GenericInput = ({
           name={name}
           onChange={(date) => {
             onChange({
-              target: { name, value: formatISO(date, { representation: 'date' }), type },
+              target: {
+                name,
+                value: date ? formatISO(date, { representation: 'date' }) : null,
```
Comment (gu-stav) [inline packages/core/helper-plugin/src/components/GenericInput.jsx:254]: What do you think about adding a test? 🙏🏼

Comment (joshuaellis) [reply packages/core/helper-plugin/src/components/GenericInput.jsx:254]: done ✅

**Comment by joshuaellis** [comment]
Added test ✅

**Review by gu-stav — APPROVED** [review]
<3

**Review by jhoward1994 — APPROVED** [review]
