### PR TITLE
[DTS] Retry sending messages if no response was recieved

### LINKED ISSUE #16473: Transfer feature hangs on asset transfer
### Required System information

- Node.js version: 16+
- NPM version: 8+
- Strapi version: 4.9.2
- Is your project Javascript or Typescript: JS

### Describe the bug

Edit: Based on issue #16437 this does not seem to be limited to cloud.

When attempting to transfer from a local Strapi instance to a Strapi Cloud project, using:

`yarn strapi transfer --to <url> --to-token <token> `
or
`npm run strapi transfer --to <url> --to-token <token>`

The transfer hangs when it gets to the `assets` transfer. Only killing the process will stop it, which then produces an error.

### Steps to reproduce the behavior

1. Go to a local Strapi project, running on 4.8+
2. Login to Strapi Cloud and ensure both local and cloud projects have same schema
3. Try to transfer from local to cloud using either:
`yarn strapi transfer --to <url> --to-token <token> `
or
`npm run strapi transfer --to<url> --to-token <token>`

### Expected behavior

That the transfer would go through successfully. 

### Screenshots

image

image

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- If for any reason a message failed and got lost we try to re-send it after some time
- if no response was given after multiple retries we throw an error

### Why is it needed?

- make sure that the transfer doesn't get stuck if one message failed and make sure to try again and continue the process

### How to test it?

- Try the push or pull against a deployed strapi no issues should occur

### Related issue(s)/PR(s)
fixes #16473

### CODE REVIEW

File: packages/core/data-transfer/src/strapi/providers/utils.ts [hunk 1]
```diff
@@ -34,26 +34,40 @@ export const createDispatcher = (ws: WebSocket) => {
...
+          ws.send(stringifiedPayload, (error) => {
+            if (error) {
+              reject(error);
+            }
+          });
+        } else {
+          reject(new ProviderError('error', 'Request timed out'));
+        }
+      };
+      const interval = setInterval(sendPeriodically, 30000);
```
Comment (innerdvations) [inline packages/core/data-transfer/src/strapi/providers/utils.ts:62]: Can we set this in a variable (ideally a config option passed in when the connection is created) so we know what it's referring to?

Comment (innerdvations) [inline packages/core/data-transfer/src/strapi/providers/utils.ts:62]: I think 30s is too long. I forget if we have a max size for a message, but they shouldn't be very large should they? I think 10s should be fine, but we should do some testing.

**Review by innerdvations — COMMENTED** [review]
This repeats messages from client -> server, but what happens if a server -> client message gets lost? Do we need to add the same repeater logic [to the remote host send](https://github.com/strapi/strapi/blob/660d83c463a688cd599abd562e1180e0e4b9f4d4/packages/core/data-transfer/src/strapi/remote/handlers/utils.ts#L158)?

File: packages/core/data-transfer/src/strapi/providers/utils.ts (hunk 1 above)
Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/utils.ts:62]: yeah we can reduce, but 30s does work I did test it intensively but maybe we can drop it to half or something should be fine, I just don't want it to execute to quickly either

**Comment by Bassel17** [comment]
> This repeats messages from client -> server, but what happens if a server -> client message gets lost? Do we need to add the same repeater logic [to the remote host send](https://github.com/strapi/strapi/blob/660d83c463a688cd599abd562e1180e0e4b9f4d4/packages/core/data-transfer/src/strapi/remote/handlers/utils.ts#L158)?

no not really, we await for a response on the client if we don't receive a response, we re-send the message and on the server it checks if the message has been handled already or not, if it has it re-sends the previous response.

File: packages/core/data-transfer/src/strapi/providers/utils.ts (hunk 1 above)
Comment (innerdvations) [reply packages/core/data-transfer/src/strapi/providers/utils.ts:62]: > yeah we can reduce, but 30s does work I did test it intensively but maybe we can drop it to half or something should be fine, I just don't want it too execute to quickly either

What happens if two messages get sent and both are actually received?

**Review by christiancp100 — COMMENTED** [review]
Are all these changes yours?

**Review by innerdvations — CHANGES_REQUESTED** [review]
What happens if the same message gets sent twice, like a laggy connection but the message isn't actually dropped, and both are actually received by the server? Do we process it twice? We can ensure the resend timer (15s) is longer than the ws call timeout (apparently 10s by default, though we should be explicit).

If we can be sure that the worst case is that the connection errors and drops, I would accept it because it's rare enough that it wouldn't be too bad. But if it's possible to silently create duplicate data then I think we have to be sure it can't happen. 

So in that case, we need to add a lock based on message uuid so that as soon as a message starts processing (in `executeAndRespond`?) it sets a state that it's processing that message id, and then when it sends the reply it can set the state as "reply sent for xxxx". If it then gets another message with the same uuid, it knows it was already processed, and can just send the "success" reply without actually processing the message again.

File: packages/core/data-transfer/src/strapi/providers/remote-source/index.ts [hunk 2]
```diff
@@ -210,7 +212,8 @@ class RemoteStrapiSourceProvider implements ISourceProvider {
     }
 
     this.ws = ws;
-    this.dispatcher = createDispatcher(this.ws);
+    const { retryMessageMaxRetries, retryMessageTimeout } = this.options;
```
Comment (christiancp100) [inline packages/core/data-transfer/src/strapi/providers/remote-source/index.ts:215]: Should we check the numbers? that they are positive and reasonable? wdyt?

**Comment by Bassel17** [comment]
> If it then gets another message with the same uuid, it knows it was already processed, and can just send the "success" reply without actually processing the message again.

well in the in the current behavior, if there is a duplicate message and no response already exists for it, it just gets ignored, we are saving the uuids at the moment we receive the message, so the first message is added to the set, if it's sent again but the first one was still being processed (sent another one too soon) we simply ignore the second message because it exists in the Set already and no response is ready yet. in case a respond was ready we send it. the response also contains the uuid so we know what response corresponds to what message

File: packages/core/data-transfer/src/strapi/providers/remote-source/index.ts (hunk 2 above)
Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/remote-source/index.ts:215]: yeah maybe for the time out, if the max retries is 0 or under it simply wouldn't retry which is fine but for the timeout I can check what the default behavior is if it's negative

Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/remote-source/index.ts]: it would just start sending messages very quickly which is fine it will just throw and error after the retries, that would be there fault at this point

**Comment by innerdvations** [comment]
> well in the in the current behavior, if there is a duplicate message and no response already exists for it, it just gets ignored, we are saving the uuids at the moment we receive the message, so the first message is added to the set, if it's sent again but the first one was still being processed (sent another one too soon) we simply ignore the second message because it exists in the Set already and no response is ready yet. in case a respond was ready we send it. the response also contains the uuid so we know what response corresponds to what message

Ok, sounds good! I just did some manual testing and it looks like pull manages it fine (no errors, no duplicated data from what I can tell), and push gives a `[FATAL] Request timed out` which is fine considering it should be rare and only in cases where it was already having connection problems.

**Review by innerdvations — APPROVED** [review]
LGTM

**Review by christiancp100 — APPROVED** [review]
LGTM 🍝

File: packages/core/data-transfer/src/strapi/providers/utils.ts [hunk 3]
```diff
@@ -18,7 +18,13 @@ interface IDispatchOptions {
 
 type Dispatch<T> = Omit<T, 'transferID' | 'uuid'>;
 
-export const createDispatcher = (ws: WebSocket) => {
+export const createDispatcher = (
+  ws: WebSocket,
+  retryMessageOptions = {
+    retryMessageMaxRetries: 5,
+    retryMessageTimeout: 15000,
+  }
```
Comment (Marc-Roig) [inline packages/core/data-transfer/src/strapi/providers/utils.ts:26]: would it make sense to use an exponential backoff pattern ?
image

15 seconds seems a bit too much if the connection was lost for a split second.

Comment (Marc-Roig) [reply packages/core/data-transfer/src/strapi/providers/utils.ts:26]: not blocking the PR at all 😄 was reading this and wondered if it would be a nice addition for the future

Comment (innerdvations) [reply packages/core/data-transfer/src/strapi/providers/utils.ts:26]: This isn't actually a "retry on failure" it's a "retry if we've been waiting too long" and that's where the 15 seconds comes in. Essentially what is happening here is that we can't detect in every case if a message is actually lost, the best we can do it wait 15 seconds to see if we get a reply and if we don't we try again.

Comment (Marc-Roig) [reply packages/core/data-transfer/src/strapi/providers/utils.ts:26]: That makes sense 💡thank you!

Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/utils.ts:26]: We send very long messages about 1mb so we do expect it to take time to send a single message a 100ms is too quick

**Review by christiancp100 — APPROVED** [review]
LGTM
