### PR TITLE
Fix replace media 

### LINKED ISSUE #7776: Media library breaks when replacing a media
**Describe the bug**

The Media Library has an option called "Replace Media". I wanted to replace one image from there. The first time I clicked on "Replace Media" and select an image. Then I clicked on "Replace Media" again by mistake so I just wanted to close the "choose file" popup. As soon as I close it, the dashboard break and shows "Something went wrong" as you can see on the screenshot below.

**Steps to reproduce the behavior**

1. Go to 'Media Library'
2. Upload one image
3. Click on that image after the upload is done
4. Now click "Replace Media"
5. Select one media from the local disk
6. Again click on "Replace Media"
7. This time do not choose any media and close the select media dialog
8. It will break at this point

**Expected behavior**
It should ignore the "choose media" dialog event and the previously selected image should be there.

**Screenshots**
Annotation 2020-09-07 215821

**Code snippets**
N/A

**System**

- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: 3.1.4
- Database: tested on MongoDB and SQLite
- Operating system: tested on ubuntu and windows

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril.lpz@gmail.com>

#### Description of what you did:

This PR fixes #7776

### CODE REVIEW

File: packages/strapi-plugin-upload/admin/src/utils/createFileToDownloadName.js [hunk 1]
```diff
@@ -1,4 +1,8 @@
-const createFileToDownloadName = ({ file: { ext }, fileInfo: { name } }) => {
+import { get } from 'lodash';
+
+const createFileToDownloadName = ({ file, fileInfo: { name } }) => {
+  const ext = get(file, 'ext', '');
+
   return `${name.replace(ext, '')}${ext}`;
```
Comment (petersg83) [inline packages/strapi-plugin-upload/admin/src/utils/createFileToDownloadName.js:6]: In case the extension is also present in the name (ex: `my.txtfile.txt`), I think this line would not do want expected.
What about:
```
return name.endsWith(ext)
  ? name
  : `${name}${ext}`;
```

**Review by petersg83 — CHANGES_REQUESTED** [review]
Modifications look good to me :) I have a question/remark regarding a related code though

**Review by petersg83 — APPROVED** [review]
LGTM !
