### PR TITLE
[Fix] Unique fields with empty string value

### LINKED ISSUE #11882: [v4] The unique option doesn't work when you empty a field
### Describe the bug

The unique option doesn't work when you empty a field.

### Steps to reproduce the behavior

1. Create an `Profile` content type with a `unique` field, like `instagramUsername`:

    ```json
    "attributes": {
      "name": {
        "type": "string",
        "required": true,
        "unique": true
      },
      "instagramUsername": {
        "type": "string",
        "unique": true
      }
    }
    ```

2. Create new Profile entry with just `name`.
    (I see that now `instagramUsername` it's `null`)

3. Edit the entry, and set `instagramUsername` to `abdonrd`.
    (I see that now `instagramUsername` it's `"abdonrd"`)

4. Edit the entry, and empty the `instagramUsername`.
    **(I see that now the value it's an empty string `""` and not `null`)**
    Maybe it should be `null`?

5. Create another Profile entry with `name` and `instagramUsername`.

6. Edit the entry, and empty the `instagramUsername`.
    ⚠️ `ValidationError. This attribute must be unique`

    Screenshot 2021-12-13 at 13 23 45

    I imagine that the conflict is generated to avoid repeating an empty string.

### Expected behavior

I hope I can save the value without problem.

If I deleted/emptied a field (`instagramUsername`), I hope it doesn't generate a unique conflict.

### System

- Node.js version: v16
- NPM version: v8
- Strapi version: v4
- Database: SQLite
- Operating system: macOS

### PR DESCRIPTION
**Pull request by ronronscelestes**
## Issue

- Go on master branch
- Create a CT with a text, uid and email fields + add `unique field` to advanced settings
- Create, fill and save 2 entries of this CT
- Delete values of those fields on 1 of the entry and save
- Try to delete values of the fields for the 2nd entry
- Save will fail because it compares empty string values as identical

Screenshot 2022-05-13 at 17 40 10

## Fix

Send null when no value for text, uid, number, select and email fields

## Test

Redo previous steps on this branch
It should let the user save multiple empty unique fields

fix #11882

### CODE REVIEW

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js [hunk 1]
```diff
@@ -17,6 +17,12 @@ const cleanData = (retrievedData, currentSchema, componentsSchema) => {
       let cleanedData;
 
       switch (attrType) {
+        case 'uid':
+        case 'email':
+        case 'text':
+        case 'string':
+          cleanedData = value || null;
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js:24]: Could `value` be ever an integer at this point? I'm asking, because it might be safer to use `??` because: `0 || null = null`, but `0 ?? null = 0`.

Could you also create/ extend the tests for `cleanData()` to reflect that change?

Comment (ronronscelestes) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js:24]: Good question, indeed I didn't think about the 0 possibilities. My issue with `??` is that all idea of this fix is to prevent empty strings to be sent to the back-end, but `"" ?? null` would be "" right?
Maybe we should be more specific only preventing empty string then?

Comment (ronronscelestes) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js:24]: I checked, actually if I pass the value `0` we get a string `"0"` that's why it doesn't break 🤔

Comment (soupette) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js:24]: I think we need a reset field instead of this hack, what if the user really wants an empty string?

Comment (ronronscelestes) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js:24]: you mean a user could want empty string as a unique value that can't be shared in 2 entries?

Comment (gu-stav) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js:24]: @soupette @ronronscelestes and I discussed it briefly: what do you think about moving the normalization into https://github.com/strapi/strapi/blob/e58b983b6f22ce237613d93858abf194bf960a9b/packages/core/helper-plugin/lib/src/components/GenericInput/index.js#L337

We are already doing some `null`, `undefined` or `''` normalization here and could do the same for `onChange` handlers on `TextInput`s, if the value is an empty string ...

In the long-term we should clarify, what our notion of empty in the front actually is: right now it is a pretty wild mix of everything ...

**Review by gu-stav — APPROVED** [review]
Thanks for adding these tests 🌻 I think it is not pretty, but it fixes the bug and is aligned with other fixes that exist already.

I'll put a discussion about the empty value (`null`, `undefined` or `''`) of our components on the FE sync agenda. The amount of type casting we need to do here is not funny anymore ...

@soupette in case you have time, your opinion would be appreciated :)

File: packages/core/helper-plugin/lib/src/components/GenericInput/index.js [hunk 2]
```diff
@@ -292,7 +298,13 @@ const GenericInput = ({
           id={name}
           hint={hint}
           name={name}
-          onChange={onChange}
+          onChange={event => {
+            if (event.target.value === '') {
```
Comment (soupette) [inline packages/core/helper-plugin/lib/src/components/GenericInput/index.js:302]: Honestly I don't think it is a good fix here, you are trying to provide a fix for you specific use case in the CM that will impact all the other plugins.

Comment (gu-stav) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js:302]: @soupette What would you suggest? I don't like the fix either, but I don't have a better idea and the file contains some fixes of that type already ...

Comment (soupette) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js:302]: I think we need to implement an `action` on the event propagated by the design system input:

```
onChane={({ target: { type: 'my-type', value: '', action: 'clear'}) => ....
```

React Select does something similar, and then it's up to the developer to deal with the received event.

WDYT?

Comment (gu-stav) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js:302]: Mh, that's an interesting way of looking at it. I'm wondering what this would change in terms of this PR though because I suppose the check would then become

```ls
if (event.target.action === 'clear') {
  // ...
}
```

What do you think of giving this PR a go and starting a discussion on the event in the FE sync? I feel like we need to look at it as a whole, because right now we do have the situation:

- API sends null
- FE converts to undefined or empty string (because the DS can not handle undefined in all cases and null is forbidden by react)
- in case of an empty string we need to send back null

It is a lot of type-casting and the event proposal doesn't really fix it either yet. Your proposal makes the API clearer though and could be a good moment to start discussing a unification of DS component APIs.

Comment (ronronscelestes) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js:302]: @gu-stav I discussed this topic with @soupette during a 1:1 
the proposition is to move this logic to the `handleChange` we can find in the `EditViewDataManagerProvider` mainly because updating a component from the helper-plugin is risky + the CTB needs to make the difference between undefined/null/empty string
it fixed this issue temporarily inside the CM:
- without risking any breaking change for helper-plugin + CTB
- giving us time to bring this conversation during FE sync

I'm ready to push my new commit, WDYT?

Comment (gu-stav) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js:302]: Mh, interesting - didn't know there is another dumpster with fixes. Yeah, I think I'm fine with that. Maybe we should move some of the existing onChange fixes, such as 

https://github.com/strapi/strapi/blob/b6b500b75355f38e0e8401257bd57e48a642149c/packages/core/helper-plugin/lib/src/components/GenericInput/index.js#L254

there too?

Comment (ronronscelestes) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js]: @gu-stav I added select and number empty string value checks inside the `EditViewDataManagerProvider`'s `handleChange` as well!

before possibly merging this fix I would like to validate that `date` type doesn't seem to need this check - I verified and it receives null as initialValue then null onClear action, I removed it - let me know if I missed something @soupette

Comment (soupette) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js]: > Mh, that's an interesting way of looking at it. I'm wondering what this would change in terms of this PR though because I suppose the check would then become
> 
> ```livescript
> if (event.target.action === 'clear') {
>   // ...
> }
> ```
> 
> What do you think of giving this PR a go and starting a discussion on the event in the FE sync? I feel like we need to look at it as a whole, because right now we do have the situation:
> 
> * API sends null
> * FE converts to undefined or empty string (because the DS can not handle undefined in all cases and null is forbidden by react)
> * in case of an empty string we need to send back null
> 
> It is a lot of type-casting and the event proposal doesn't really fix it either yet. Your proposal makes the API clearer though (by hiding the complexity) and could be a good moment to start discussing a unification of DS component APIs.

I won't give this PR a go you are providing a fix in the helper plugin for the content manager without changing the codebase of the CTB or other plugins that are using this component. What you should do instead is providing a fix in the content manager only and not the helper plugin.

Comment (ronronscelestes) [reply packages/core/helper-plugin/lib/src/components/GenericInput/index.js]: hola @soupette I actually removed all the changes from the helper plugin to [implement it directly into the CM ](https://github.com/strapi/strapi/pull/13313/commits/aff13a0d60dbe6969d9c55e1badf0b4540dce684)! that's why I asked for another review from you 😊

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js [hunk 3]
```diff
@@ -233,9 +233,20 @@ const EditViewDataManagerProvider = ({
...
-      // Set the date to null when it's empty
-      if (type === 'date' && value === '') {
+      // Allow to reset text, string, email, uid, select/enum, date
+      if (
+        (type === 'text' ||
+          type === 'string' ||
+          type === 'email' ||
+          type === 'uid' ||
+          type === 'select' ||
+          type === 'select-one') &&
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js:243]:
```suggestion
        (['text', 'string', 'email', 'uid', 'select', 'select-one'].includes(type)) &&
```

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js [hunk 4]
```diff
@@ -233,9 +233,20 @@ const EditViewDataManagerProvider = ({
...
+        value === ''
+      ) {
+        inputValue = null;
+      }
+
+      if (type === 'number' && !value) {
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js:249]: I think this could be part of the previous check, if you would change `&& value === ''` to `&& !value` since `!!'' === false`.

File: packages/core/helper-plugin/lib/src/components/GenericInput/tests/index.test.js [hunk 5]
```diff
@@ -111,13 +111,15 @@ describe('GenericInput', () => {
...
       const spy = jest.fn();
       const { input } = setupNumber({ value: 1, onChange: spy });
 
       fireEvent.change(input, { target: { value: '' } });
 
-      expect(spy).toHaveBeenCalledWith({ target: { name: 'number', type: 'number', value: null } });
+      expect(spy).toHaveBeenCalledWith({
+        target: { name: 'number', type: 'number', value: undefined },
+      });
     });
```
Comment (gu-stav) [inline packages/core/helper-plugin/lib/src/components/GenericInput/tests/index.test.js:123]: I think now that this doesn't test anything regarding the `GenericComponent` anymore, you could remove the whole test, because it would test some design-system internals and should be done there.

**Review by gu-stav — COMMENTED** [review]
That looks much better than the previous attempts - thanks for working on it! ✨ What do you think about adding more tests for each field type, to test if `cleanData` properly resets the value?

File: packages/core/helper-plugin/lib/src/components/GenericInput/tests/index.test.js (hunk 5 above)
Comment (ronronscelestes) [reply packages/core/helper-plugin/lib/src/components/GenericInput/tests/index.test.js:123]: nice catch thanks!

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js (hunk 4 above)
Comment (ronronscelestes) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js:249]: will do!
discovered a bug with the number input though 
if you click the input, doesn't type anything in it, then go using the arrow to change the value this happens:

image

I'll write a card in the DS backlog!

**Comment by ronronscelestes** [comment]
> That looks much better than the previous attempts - thanks for working on it! ✨ What do you think about adding more tests for each field type, to test if `cleanData` properly resets the value?

resetting values doesn't happen in cleanData anymore - I think we decided to move it to `EditViewDataManagerProvider` `handleChange` function since some onChange cleaning/resetting was also done here 🤔

**Review by gu-stav — APPROVED** [review]
Code looks good to me now 🚀 This should propably be tested by @MarionLemaire, so I assign her, before merging.

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js [hunk 6]
```diff
@@ -233,9 +233,13 @@ const EditViewDataManagerProvider = ({
     ({ target: { name, value, type } }, shouldSetInitialValue = false) => {
       let inputValue = value;
 
-      // Allow to reset text, email, uid, select/enum, and number
+      console.log({ type, name });
```
Comment (soupette) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js:236]: Not sure this one is needed...

Comment (ronronscelestes) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js:236]: nice to see you there catching my logs 😁

**Review by gu-stav — APPROVED** [review]

**Review by MarionLemaire — APPROVED** [review]
Tested on Getstarted using Chrome, for short text, long text, number, uid, email fields : OK
