### PR TITLE
Disable primary key requirement on session initialize

### LINKED ISSUE #11723: Can't deploy to MySQL 8 on a Digital Ocean Managed database due to tables without primary keys.
### Table creation is rejected due to the default setting for MySQL not allowing tables without primary keys.

Example:

[2021-11-30 11:30:43.648] error: create table `admin_users_roles_links` (`user_id` int unsigned null, `role_id` int unsigned null) - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
[2021-11-30 11:30:43] Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

Some of the tables affected:

admin_permissions_role_links
admin_users_roles_links
files_related_morphs
up_permissions_role_links
up_users_role_links

### Steps to reproduce the behavior

Deploy vanilla Strapi to Digital Ocean via a docker image used for an App with a MySQL 8 Managed Database.

### Expected behavior

All tables should have primary keys.

### System

- Strapi version: v4
- Database: MySQL 8

### Additional context

Digital Ocean have confirmed they won't relax the rule on primary keys.  They require this for performing database replication.

### PR DESCRIPTION
**Pull request by derrickmehaffy**
fixes #11723

Based on: https://www.digitalocean.com/community/questions/how-to-disable-sql_require_primary_key-in-digital-ocean-manged-database-for-mysql

DigitalOcean forcefully requires primary keys on all tables, in Strapi we don't place primary keys on join tables for relations because they aren't needed. During the database initialization, we do some migration steps and it was during this the error occured. This PR disables this requirement for the session to allow the migration to function and shouldn't be needed later on.

### CODE REVIEW

**Review by Convly — DISMISSED** [review]
LGTM

**Comment by alexandrebodin** [comment]
It is actually breaking some of the mysql tests. To look into :)

**Comment by derrickmehaffy** [comment]
> It is actually breaking some of the mysql tests. To look into :)

I don't think the failing tests relate to the modifications I made, these look like database timeouts, as in the test database is being very slow

**Comment by derrickmehaffy** [comment]
Well on MySQL there is a permissions error

`ER_SPECIFIC_ACCESS_DENIED_ERROR: Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation`

If the permission is missing then nothing we do can solve that, so if we init the test database we need to modify the permissions but if we don't then this solution won't work and we will have to go with adding a primary key to the table.

**Comment by alexandrebodin** [comment]
The github actions are using a mysql docker image I think you can fairly easily add those permissions for the tests. But not sure if user on DO would be able to have those permissions on shared DBs 🤔

**Comment by derrickmehaffy** [comment]
> The github actions are using a mysql docker image I think you can fairly easily add those permissions for the tests. But not sure if user on DO would be able to have those permissions on shared DBs 🤔 

The doadmin user gets full access  to their database afaik,, you share the database server but not the actual database instance.

**Comment by derrickmehaffy** [comment]
> Ok so I think this PR is just missing a try catch so if you don't have the permissions and we don't actually need them we will not break.

done, let me know if this is the best way to handle the catch, tried to mirror what I've seen elsewhere in the codebase.

File: packages/core/database/lib/dialects/mysql/index.js [hunk 1]
```diff
@@ -32,6 +32,14 @@ class MysqlDialect extends Dialect {
     };
   }
 
+  async initialize() {
+    try {
+      await this.db.connection.raw(`set session sql_require_primary_key = 0;`);
+    } catch (err) {
+      console.error({ err });
+    }
```
Comment (alexandrebodin) [inline packages/core/database/lib/dialects/mysql/index.js:40]: The idea here would be to ignore and do an empty catch so we still get the same error later but don't do logs for users that shouldn't see them.

**Review by alexandrebodin — APPROVED** [review]
LGTM 👍
