### PR TITLE
fix: prefill non translatable fields when creating new document locale

### LINKED ISSUE #21850: Strapi 5 ignores "Enable localization for this field" setting
### Describe the bug
Strapi ignores the field  "Enable localization for this field" (considers it true for all fields). I need to input the same value manually in all locales. 

### Steps to reproduce the behavior
Go to Content-Type Builder / Collection types
Create new content type "Category" with 2 fields 
Title - Enable localization for this field: checked
Code - Enable localization for this field: not checked

Go to Content manager
Create new category with English locale. Fill Title and Code values. Save / Publish. 
Press add new locale

### Expected behavior
Code is prefilled from English locale

### Actual behavior
Code is not prefilled from English locale

image
image
image

### PR DESCRIPTION
**Pull request by Adzouz**
### What does it do?

When creating a new locale of a document, the non translatable fields (where "Enable localization for this field" is disabled) are empty but they should be pre-filled because their values are shared between all locales.

BEFORE:

https://github.com/user-attachments/assets/c7b0518d-2c1f-422d-a79f-2ca567598c39

AFTER:

https://github.com/user-attachments/assets/5e03aa12-84fe-45f6-bf8e-9a4f22678aeb

### Why is it needed?

Leaving the fields empty is confusing and the user needs to put them again (or use the "Fill in from another language" feature). It can be a waste of time and the new value entered could overwrite all other locales if different from the original one.

### How to test it?

- Make sure that you have a content type that has Internationalization enabled + have at least one field with "Enable localization for this field" to false
- Go to the content manager and select this content type
- Create a new entry and fill the field with some data
- Save
- Select another locale in the language selector to create a new variation of the document
-> The field you have previously filled should remain with the value you entered instead of being reset

### Related issue(s)/PR(s)

Resolves #21850 #22080 #23600

🚀

### CODE REVIEW

File: packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx [hunk 1]
```diff
@@ -145,6 +147,91 @@ const LocalePickerAction = ({
...
+                  },
+                  {}
+                );
+
+                if (Object.keys(dataToSet).length > 0) {
+                  setValues(dataToSet);
+                }
+              }
+            } catch (error) {
+              console.warn(
```
Comment (mathildeleg) [inline packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx]: I'm guessing you didn't use a NotificationError because if it fails, it's not too bad of a problem if the values aren't set by default right?

File: tests/e2e/tests/i18n/editview.spec.ts [hunk 2]
```diff
@@ -545,6 +545,49 @@ test.describe('Edit view', () => {
       page.getByLabel('Unpublish multiple locales').getByRole('button', { name: 'Unpublish' })
     ).toBeDisabled();
   });
+
+  test.only('As a user I want to see non translatable fields pre-filled when creating a new locale of a document', async ({
```
Comment (mathildeleg) [inline tests/e2e/tests/i18n/editview.spec.ts]: `test('As a user I want to see non translatable fields pre-filled when creating a new locale of a document', async ({`

File: packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx (hunk 1 above)
Comment (Adzouz) [reply packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx]: Yes exactly, that's because it's more a silent notification since if it's not working, it would pretty much fallback on what we currently have: the field not being filled. I'm not sure we want to display an error for that, otherwise the user will think that something went wrong even if they still can edit and publish their document. What's your opinion on this one?

File: tests/e2e/tests/i18n/editview.spec.ts (hunk 2 above)
Comment (Adzouz) [reply tests/e2e/tests/i18n/editview.spec.ts]: Dammit

File: packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx [hunk 3]
```diff
@@ -145,6 +147,91 @@ const LocalePickerAction = ({
...
+    document,
+    schema,
+    setValues,
+    currentDesiredLocale,
+    locales,
+    documentId,
+    getDocument,
+    collectionType,
+    model,
+    meta,
```
Comment (HichamELBSI) [inline packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx]: Wow, that's a lot of dependencies, are you confident about it. I'm not sure to understand everything so I can only trust your confidence. I guess this requires some good testing.

File: packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx (hunk 1 above)
Comment (mathildeleg) [reply packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx]: I agree with you 👍🏻 just wanted to make sure we were on the same page

File: packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx (hunk 3 above)
Comment (Adzouz) [reply packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx]: Yeah I get it 😅 I'm confident about a few dependencies I didn't really had the choice like setValues, getDocument but the others it's because the getDocument needs the collectionType, the model, the documentId and the locale so it's a lot of dependencies I don't really have the choice but to add.
I tried to optimize (with memoization) and chunk it a bit, let me know if it's better.
What it's doing: fetching the source locale to get all non translatable fields to load them in the form (hence the getDocument + setValues).
Let me know if you have a better idea on how to do it 🙏

**Comment by Adzouz** [comment]
After rubberducking this issue, I thought about another approach more stable and without having to do an additional API call. I use the existing availableLocales to autofill the non-translatable fields (only when creating a new locale). It's more efficient and avoid too many side effects.
Let me know what you think!

**Comment by ancashoria** [comment]
Wow, you fixed this! Thank you so much!
