### PR TITLE
Fixes #23986: Conditional field operator reset to "is" when set to "is not".

### LINKED ISSUE #23986: Conditional field - cannot set condition to "is not" with enumeration fields
### Node Version

22.17.0

### NPM/Yarn/PNPM Version

10.9.2

### Strapi Version

5.18.1

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

https://github.com/strapi-support-demo-apps/issue-23986

### Bug Description

When changing the conditional fields' condition from "is" to "is not", it changes back to "is" by itself. 
See below for video demonstration

### Steps to Reproduce

1. Create a component, with an enum field and a boolean field
2. Add a condition to the boolean field like this: if <enumeration-field> is not <enum-value> then Show <boolean-field>
3. Click Finish
4. Go back into the condition and notice it change from "is not" to "is"

### Expected Behavior

I expect the condition to remain as I set it

### Media

https://www.loom.com/share/f0bdeac8f9dd4930b27207859268ad58?sid=492551b1-7b16-4831-a195-690a83fa9169

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by ItsmeAashishKumar**
### What does it do?
Fixed a bug in ConditionForm where the operator (isNot) reverted to is when reopening a condition. Updated convertToJsonLogic and updateCondition to correctly handle operator (is/isNot) and action (show/hide) combinations for JSON Logic output. Ensured convertFromJsonLogic preserves isNot correctly.

Describe the technical changes you did.
 Updated convertToJsonLogic and updateCondition to check both operator (is/isNot) and action (show/hide) to pick the right JSON Logic operator (== or !=).
Example: “is not” + “show” → { visible: { "!=": [...] } }

### Why is it needed?
The bug broke conditions like “if status is not published, then show,” reverting to “is published” on reopen, due to incorrect operator/action mapping. This fix ensures conditions persist as set.

Describe the issue you are solving.
When setting a condition like “if status is not published, then show,” the condition reverted to “is” when reopened.

### Related issue(s)/PR(s)
fixes #23986

### CODE REVIEW

**Comment by butcherZ** [comment]
Hey @ItsmeAashishKumar thank you so much for the fix, I QAed it and it works great 😄 Could you please run `yarn prettier:write` in the root folder so it fixes the indentation issue in the `updateCondition` function? Once this is done, I will approve your PR! Thanks again 🫶

File: packages/core/content-type-builder/admin/src/components/FormModal/attributes/ConditionForm.tsx [hunk 1]
```diff
@@ -129,35 +135,40 @@ export const ConditionForm = ({
...
+          name,
+          value: jsonLogic,
+        },
+      });
     }
-  };
+  } catch {
+    // Optionally, show an error to the user
+    
+  }
```
Comment (butcherZ) [inline packages/core/content-type-builder/admin/src/components/FormModal/attributes/ConditionForm.tsx]: Please run `yarn prettier:write` to fix the format issue here :D

**Review by butcherZ — CHANGES_REQUESTED** [review]

**Comment by ItsmeAashishKumar** [comment]
Hey @butcherZ 
I ran yarn prettier:write on the ConditionForm.tsx file as requested and updated the PR. Other Prettier changes across the repo were discarded to keep this PR clean.
Let me know if you’d like me to format and commit all files instead. Thanks! 🙌

**Review by butcherZ — DISMISSED** [review]

**Comment by butcherZ** [comment]
@ItsmeAashishKumar I have approved your PR, Congratulations on your first PR for Strapi 🎊  I will leave the pleasure of clicking the "squash and merge" button to yourself! I will also see with my colleague that if we can make this fix to this week's release, if not it will be scheduled for next week 😄  Thank you again for your contribution 🍻 !

**Comment by ItsmeAashishKumar** [comment]
@butcherZ  Thank you so much for approving my PR and for your kind words! 🙏
I really enjoyed working on this issue and learned a lot in the process.
I might need a little guidance on future contributions as I get more familiar with the codebase.
 Thanks again for your support! 🚀

**Comment by Boegie19** [comment]
You also have to remove the cls file in the root directory

**Comment by ItsmeAashishKumar** [comment]
@Boegie19 I have removed the cls file .

**Review by butcherZ — APPROVED** [review]
@ItsmeAashishKumar I approved the change, feel free to click the squash and merge button, this branch will be merged to develop and be released next week (30th of July) 😄

**Comment by ItsmeAashishKumar** [comment]
Hi @butcherZ, I don’t have merge permissions on this repo, so I can’t see the "Squash and Merge" button. Could you please merge it when convenient? Thanks again! 🙏

**Comment by butcherZ** [comment]
@ItsmeAashishKumar oh yeah my bad, I forgot about that, no problemI will merge it for you, just need to wait for the CI to pass 😄 Thank you again for your work and patience!
