### PR TITLE
fix: dynamic zone component data

### LINKED ISSUE #16966: Dynamic zone breaks after upgrading from 4.9.2 to 4.11.0
### Required System information

- Node.js version: 16
- NPM version: 6
- Strapi version: 4.11.0
- Database: postgres
- Operating system: ios

### Describe the bug

After upgrading from 4.9.2 to 4.11.0 strapi admin breaks with "Woops! Something went wrong. Please, try again" after trying to use a component in the dynamic zone. 

### Steps to reproduce the behavior

1. In the strapi admin ui, go to any collection type using dynamic zone.
2. Click on any of the components in the dynamic zone to add it
4. See error "Woops! Something went wrong. Please, try again" and the console logs:

```
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Object.entries.reduce (content-manager.4e46c41a.chunk.js:6660:67)
    at Array.reduce (<anonymous>)
    at findAllAndReplace (content-manager.4e46c41a.chunk.js:6651:39)
    at content-manager.4e46c41a.chunk.js:6782:40
    at produce (main.e40cee3e.js:45810:15892)
    at reducer (content-manager.4e46c41a.chunk.js:6728:32)
    at Object.fi [as useReducer] (main.e40cee3e.js:75945:451)
    at exports.useReducer (main.e40cee3e.js:86305:274)
    at EditViewDataManagerProvider (content-manager.4e46c41a.chunk.js:7052:56)
    at Xh (main.e40cee3e.js:75942:137)
```

### Expected behavior

Expected to be able to use components in the zone :) 

### Screenshots

How the UI looks like before click: 

image

How the ui looks when click on any of the components: 

image

### Code snippets

This is one example of the schema for one of the components:

```
{
  "collectionName": "components_landing_pages_big_numbers",
  "info": {
    "displayName": "Big Numbers",
    "description": "",
    "icon": "bold"
  },
  "options": {},
  "attributes": {
    "header": {
      "type": "text",
      "required": false
    },
    "items": {
      "type": "component",
      "repeatable": true,
      "max": 4,
      "min": 2,
      "component": "landing-pages.big-number-item"
    },
    "disclaimer": {
      "type": "text"
    },
    "backgroundColor": {
      "type": "enumeration",
      "enum": [
        "None",
        "Yellow",
        "Alpha"
      ],
      "default": "None"
    }
  }
}
```

Let me know if I can provide any more context, thanks

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Passes every component schema to the context reducer instead of the ones listed for dynamic components

### Why is it needed?

* You can have a component listed in the dynamic zone component choice that contains a component not in that former list leading to a crash.

### Related issue(s)/PR(s)

* resolves #16966

### CODE REVIEW

File: packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js [hunk 1]
```diff
@@ -94,19 +94,11 @@ const DynamicZone = ({ name, labelAction, fieldSchema, metadatas }) => {
...
-      }, {});
-
-      return { ...acc, ...componentObjects };
-    }, {});
-
+    /**
+     * You have to pass _every component_ because the EditViewDataManager is not part of redux
+     * and you could have a dynamic component option that contains a component that is not part
+     * of the former list. Therefore it's schema is inaccessible leading to a crash.
+     */
```
Comment (Marc-Roig) [inline packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js:101]: maybe it's implementation details, but what is a Category in the context of dynamicZones? I am trying to follow what logic was followed to generate dynamicComponentsByCategory before.

Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js:101]: A category is the category of the component, we display all dynamic zone component options grouped by their categories 👍🏼

Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js:101]: realistically when we move the content-manager back to redux this will be a lot cleaner because we can access the schemas in the reducer 🙃

**Review by Marc-Roig — DISMISSED** [review]
