### PR TITLE
Different field types with the same name break CM EditView

### LINKED ISSUE #16048: failed to save dynamic zone with nested fields named the same but different types
### Required System information

- Node.js version: v18
- NPM version: v8
- Strapi version: v4.7.1
- Database: SQLite
- Operating system: Linux Mint 21
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When you have a dynamic zone that contains 2 components:

- Component 1 contains a nested repeatable component called `items`
- Component 2 contains a nested relational field called `items` (in testing only used manyWay relation)

when trying to save the content-type using one or both you will fail to save as the admin is looking for the data response from the relation

Reproduction repo: https://github.com/derrickmehaffy/compo-relation-bug

### Steps to reproduce the behavior

1. Clone reproduction repo locally
2. Go to the `Test` Single Type
3. Try to add any of the components (just 1)
4. Try to add nested compo data (doesn't matter how much)
5. Try to save
6. See error in browser console

### Expected behavior

We either need to prevent users from creating nested fields that contain the same name but different types (repeat compo or relation) or we need to fix the relational population bug

### Screenshots

image

### Code snippets

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* removes `recursivelyFindPathsBasedOnCondition`
* removes `findLeafByPathAndReplace`
* adds `findAllAndReplace`
* refactors `getPopulateForDZ` to use fragments to populate the dynamic zone components

### Why is it needed?

There are two issues here –

* On the FE we weren't passing the index to the relation preperation function in `INIT_FORM` so we (wrongly) assumed that all fields with the relation name in DZs or Repetable Components were relations, this has been changed so we check the type of schema before replacing the value instead.
* On the BE because of how relations & components work (they need to populated) it was confusing which part of the schema wanted to be a `count` in the case of relations vs `populated` in the case of a component, the refactor now uses fragments for better fine grained choosing.

### How to test it?

* automated tests

### Related issue(s)/PR(s)

* resolves #16048

### CODE REVIEW

**Comment by joshuaellis** [comment]
@gu-stav wanted to give you visibility on the approach.

**Comment by joshuaellis** [comment]
Gonna add some more tests around the `path` and `parent` part that are passed to the predicate & replacement functions but this is good for review.

**Comment by joshuaellis** [comment]
Hey @derrickmehaffy, 

This release `0.0.0-f78ba52ea63afa7bd8507d320e458a0939a3f709` when used in your example repo appears to fix the issues you were having, feel free to try it out and let us know if you see any other issues 👍🏼

**Comment by derrickmehaffy** [comment]
Thanks so much @joshuaellis <3

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js [hunk 1]
```diff
@@ -280,68 +218,51 @@ const reducer = (state, action) =>
...
+            return [];
+          }
+        );
+
+        const mergedDataWithPreparedRelations = findAllRelationsAndReplaceWithEmptyArray(
+          data,
+          attributes
+        );
+
+        const findAllDynamicAndRegularComponentsAndReplaceWithTempKey = findAllAndReplace(
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js:238]: Are dynamic components = repeatable components? And are regular components non-repeatable components?

It is very nit-picky, but if so I'd suggest to rename this to

```suggestion
        const findComponentsAndReplaceWithTempKey = findAllAndReplace(
```

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js [hunk 2]
```diff
@@ -1390,6 +1473,7 @@ describe('CONTENT MANAGER | COMPONENTS | EditViewDataManagerProvider | reducer',
               "component": {
                 "__temp_key__": 1,
                 "field1": {
+                  "__temp_key__": 1,
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js:1476]: Should all these fields have the same `__temp_key__`? Could you run into e.g. keying problems because of that?

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findAllAndReplace.js [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+          return acc;
+        }
+
+        if (predicate(value, { path: [...path, key], parent: acc })) {
+          path = [...path, key];
+          acc[key] =
+            typeof replacement === 'function'
+              ? replacement(acc[key], { path, parent: acc })
+              : replacement;
+          path = [];
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findAllAndReplace.js:46]: I find it a bit confusing on why you assign path to empty it later on here and in the following two instances.

What do you think about:

```suggestion
          path = ;
            typeof replacement === 'function'
              ? replacement(acc[key], { path: [...path, key], parent: acc })
              : replacement;
          path = [];
```

I'm wondering if this would allow you to get rid of the global `path` variable entirely?

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js [hunk 4]
```diff
@@ -280,68 +218,51 @@ const reducer = (state, action) =>
          */
         const data = cloneDeep(initialValues);
 
-        /**
-         * relationalFieldPaths won't be an array which is what we're expecting
-         * Therefore we reset these bits of state to the correct data type
-         * which is an array. Hence why we replace those fields.
-         */
-        const mergeDataWithPreparedRelations = relationalFieldPaths
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js:288]: QA will and the tests will probably cover that automatically: where do you handle relations now, which are not part of components? From the code this is not immediately clear to me.

**Review by gu-stav — COMMENTED** [review]
Very nice work. All the comments are quite minor. 👏🏼  This is a very good evolution of the previous helpers.

I'll do a thorough QA now and let you know once it is finished.

**Comment by gu-stav** [comment]
QA:

## Dynamic zones

Following setup: a dynamic-zone contains two components: one 1:1 and one 1:m relation to the same target-content-type (categories) with the same name

The admin API (screenshot) sends a count of 1 for both of them, but the FE neither displays it, not fetches it the relations for the second component. The order of the components doesn't matter - it is always the second that fails.

Screenshot 2023-03-15 at 08 16 18

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js (hunk 4 above)
Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js:288]: `findAllRelationsAndReplaceWithEmptyArray` im not sure what line this is on.

File: packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findAllAndReplace.js (hunk 3 above)
Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findAllAndReplace.js:46]: You need to have the global path because when you dive down one layer (for components / dynamic zones etc) you need that path to be remained although this might be able to be part of the func...

Nice idea, i'll give it a look.

Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findAllAndReplace.js:46]: looks like you were on to something!

**Comment by joshuaellis** [comment]
> The admin API (screenshot) sends a count of 1 for both of them, but the FE neither displays it, not fetches it the relations for the second component. The order of the components doesn't matter - it is always the second that fails.

The API isn't sending me any results it seems... @Marc-Roig might need to look at this...

**Comment by gu-stav** [comment]
@joshuaellis Ok but that means it should be unrelated to this PR and could be tackled as a follow-up to merge this one asap, I guess?

**Comment by Marc-Roig** [comment]
@gu-stav  we also made changes on the backend for dz population. We should be tackling this in this pr imo

**Comment by joshuaellis** [comment]
Actually looking into it a bit more, i think we're not building the correct path inside RelationDataInputManager. the network tab wasn't that clear for me here.

**Comment by joshuaellis** [comment]
> The admin API (screenshot) sends a count of 1 for both of them, but the FE neither displays it, not fetches it the relations for the second component. The order of the components doesn't matter - it is always the second that fails.

@gu-stav Solved this issue, the dynamic zones were all getting the same (incorrect tempkey) i've fixed this and added more to the tests to ensure we can catch this next time.

**Comment by Marc-Roig** [comment]
Was testing this and can not see anything backend related either

**Comment by gu-stav** [comment]
@joshuaellis cool, thanks. I'll test again and let you know once I am finished. Couldn't find anything else so far.

**Review by gu-stav — APPROVED** [review]
Works well for me - great work!

**Review by Convly — APPROVED** [review]
[LGTM](https://github.com/strapi/strapi/pull/16061/files#diff-0dbffbd4cd01b7826ea0a0926c72b04c7f9406134a34fe9b9ee3fa089f57acb0)
