### PR TITLE
fix(pack-up): set NODE_ENV if it's not already set

### LINKED ISSUE #18575: Strapi Color Picker Plugin Causes White Blank Screen on "Custom" Tab Selection
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.2.1
- Strapi version: 4.14.4
- Database: PostgreSQL 16.0
- Operating system: Windows 11 64 bit
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After installing the Strapi Color Picker plugin, selecting the "Custom" tab in the field selector results in a white blank screen.

### Steps to reproduce the behavior

1. Install the Strapi Color Picker plugin.
2. Go to the field selector.
3. Click on the "Custom" tab.
4. See error (white blank screen).

### Expected behavior

The "Custom" tab should display color picker options instead of a white blank screen.

### Screenshots

image

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* pack-up now by default sets `NODE_ENV` to production _unless_ it's set already

### Why is it needed?

* vite doesn't set process.env.NODE_ENV, it does set values on `import.meta.env`, but `react` doesn't look at those 🙃 

### How to test it?

* build the color-picker without this PR and you'll see we're trying to import the dev jsx files
* with this pr we correctly import the non-dev jsx file

### Related issue(s)/PR(s)

* resolves #18575

### CODE REVIEW

File: packages/utils/pack-up/src/node/build.ts [hunk 1]
```diff
@@ -33,6 +33,13 @@ interface BuildWithoutConfigFile extends BuildCLIOptions {
 type BuildOptions = BuildWithConfigFile | BuildWithoutConfigFile;
 
 const build = async (opts: BuildOptions = {}) => {
+  /**
+   * We always want to run in production mode when building and some packages
+   * use NODE_ENV to determin which type of package to import (looking at your react).
```
Comment (jhoward1994) [inline packages/utils/pack-up/src/node/build.ts:38]: "determine" ?

**Review by jhoward1994 — APPROVED** [review]

File: packages/utils/pack-up/src/node/build.ts (hunk 1 above)
Comment (joshuaellis) [reply packages/utils/pack-up/src/node/build.ts:38]: yes 🤓

Comment (joshuaellis) [inline packages/utils/pack-up/src/node/build.ts:38]:
```suggestion
   * use NODE_ENV to determine which type of package to import (looking at your react).
```

**Review by jhoward1994 — APPROVED** [review]

**Comment by pezexd** [comment]
I don't know how make to do that this work, I have deleted node_modules & package-lock.json then npm install and npm run build and don't get any success, plugin color-picker is failing.

**Comment by mighty-phoenix** [comment]
@pezexd +1.
Same for me. Plugin color-picker is failing.
@joshuaellis 
Thanks!

**Comment by derrickmehaffy** [comment]
----->
Look on the right at the milestone, that's the version the PR will be released in, it's not released yet.
