### PR TITLE
fix: blocked users can still login via provider

### LINKED ISSUE #17494: Blocked Users Can Still Login via Provider
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: 4.12.0
- Database: MySql 8.0.31
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When updating a user registered with Google or another provider and setting the "Blocked" value to true on the 'Users' page, the user can still log in using the provider despite being blocked.

### Steps to reproduce the behavior

1. Go to the 'Users' page.
2. Update a user registered with Google (or other provider).
3. Set the 'Blocked' value to true.
4. Save the user.
5. Attempt to log in with the provider using the blocked user's credentials.
6. Notice that the user can still log in despite being blocked.

### Expected behavior

When a user is blocked, they should not be able to log in using any provider.

### Code snippets

https://github.com/strapi/strapi/blob/8aa758396e71ce1d8f8169c132272ffb69877025/packages/plugins/users-permissions/server/controllers/auth.js#L96-L105

### Recommended Solution

The following solution is suggested to fix the issue:

```js
try { 
   const user = await getService('providers').connect(provider, ctx.query); 
  // Fix
   if (user.blocked === true) {
      throw new ApplicationError('Your account is blocked!');
   }
  // Fix End

   return ctx.send({ 
     jwt: getService('jwt').issue({ id: user.id }), 
     user: await sanitizeUser(user, ctx), 
   }); 
 } catch (error) { 
   throw new ApplicationError(error.message); 
 }
```

This fix checks if the user is blocked before allowing the login process to proceed, and if the user is blocked, an error will be thrown, preventing the login with the blocked account.

Please apply this solution to address the bug in the authentication process.

### PR DESCRIPTION
**Pull request by KushalKanungo**
Added the suggested check for blocked users when login via third party providers.

fixes: https://github.com/strapi/strapi/issues/17494

### CODE REVIEW

File: packages/plugins/users-permissions/server/controllers/auth.js [hunk 1]
```diff
@@ -100,6 +100,10 @@ module.exports = {
     try {
       const user = await getService('providers').connect(provider, ctx.query);
 
+      if (user.blocked === true) {
+        throw new ApplicationError('Your account is blocked!');
```
Comment (christiancp100) [inline packages/plugins/users-permissions/server/controllers/auth.js:104]: I think this might be an `UnauthorizedError` instead an `ApplicationError`, wdyt?

File: packages/plugins/users-permissions/server/controllers/auth.js [hunk 2]
```diff
@@ -100,6 +100,10 @@ module.exports = {
...
+      }
```
Comment (innerdvations) [inline packages/plugins/users-permissions/server/controllers/auth.js:105]:
```suggestion
      if (user.blocked) {
        throw new ForbiddenError('Your account has been blocked by an administrator');
      }
```
(and add the import for ForbiddenError at the top)

File: packages/plugins/users-permissions/server/controllers/auth.js (hunk 1 above)
Comment (innerdvations) [reply packages/plugins/users-permissions/server/controllers/auth.js:104]: The user is providing auth, so I think it should be a Forbidden

File: packages/plugins/users-permissions/server/controllers/auth.js (hunk 2 above)
Comment (KushalKanungo) [reply packages/plugins/users-permissions/server/controllers/auth.js]: Thank you @innerdvations , @christiancp100  for suggesting the changes. I have pushed the commit with suggested changes. 
- Changed the error type to **Forbidden**
- Imported it from utils.errors (similar to other imported errors)
- Removed the redundant `user.blocked === true` statement.  

Although I want to ask a question that, will this give any issue if `user.blocked` comes as a truthy value at some case rather than a boolean.

Comment (innerdvations) [reply packages/plugins/users-permissions/server/controllers/auth.js]: I suggested truthy because IMO it's better to err on the side of caution for security things like this -- for example, if by some strange bug in some case `user.blocked = "true"` we'd let them in.

Admittedly we already do it both ways within this same file 🤦

**Review by christiancp100 — APPROVED** [review]
LGTM

**Review by derrickmehaffy — APPROVED** [review]
lgtm
