### PR TITLE
Fix/#4556/null when requiring a component in relation graph ql

### LINKED ISSUE #4556: Querying a relationships group fields returns null in GraphQL
**Describe the bug**
Using graphql, when querying a relationship + a group field inside the relationship the group field returns null.

For example...

```
query group_fields_in_relationship {
  parent(where: { some_prop: "some_value" }) {
    id
    related_content_type {
      group_field {
        title
      }
    }
  }
}
```

`parent.related_content_type.group_field` will be `null`

But, if I query the `related_content_type` directly the `group_field` returns correctly.

**Steps to reproduce the behavior**
1. Create a group field and add it to a content type
2. Relate the content type with a group field in it to another content type
3. Try to query the group field through the content type relationship
4. See the group fielod in the query return `null`

**Expected behavior**
The group field to return what it contains

**System**
- Node.js version: 12.6.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: postgres
- Operating system: macOS mojave

### PR DESCRIPTION
**Pull request by petersg83**
Fix #4556

#### Description of what you did:
- populate with components even if populate option is already existing
- add some tests

### CODE REVIEW

File: packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/Wrapper.js [hunk 1]
```diff
@@ -52,11 +52,7 @@ const Wrapper = styled.tr`
     }
   }
   &.relation-row {
```
Comment (alexandrebodin) [inline packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/Wrapper.js]: Can you just undo the changes to this file as you did make any changes to it :)
