### PR TITLE
Set default locale when using Query Engine function createMany

### LINKED ISSUE #13393: Bulk operations on internationalized content mess up with locales
### Required System information

- Node.js version: 16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.1.11
- Database: SQLite
- Operating system: MacOS

### Describe the bug

When using the Query Engine's `createMany` function, Strapi does not default the locale of the new entries to the default locale of the instance, which means that newly created entries are created in the database but cannot be seen in the admin panel.

This bug also allows users to use the Query Engine to create entities in locales other than those enabled on the Strapi instance.

### Steps to reproduce the behavior

1. Create a controller that runs a `createMany` query on an internationalizable content type, making sure not to specify a `locale` value.
2. Notice how browsing through that content type in the content manager, the new entries are not present.
3. Check your database and notice how the entires have in fact been created even though they are not visible.
4. Repeat (1) but passing in a value for `locale` that represents a locale you have not yet enabled on your instance, like `es` for Spanish or `it` for Italian.
5. Notice how (2) and (3) are still valid in this scenario as well.

### Expected behavior

The Query Engine should default the `locale` value to the instance's default locale or throw an error and not create the entries.

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

Fix #13393

### Why is it needed?

So the function `create` and `createMany` have a consistent behavior of setting the default locale when it is undefined

### How to test it?

1. In the getStarted app, set the boostrap function as :
```js
  async bootstrap({ strapi }) {
    await strapi.db.query('api::country.country').createMany({ data: [{ name: 'I will have a locale' }] });
  },
```
2. See that the created country does have the default locale.
### Related issue(s)/PR(s)

#13393

### CODE REVIEW

**Comment by petersg83** [comment]
Please, check my comment there: https://github.com/strapi/strapi/issues/13393#issuecomment-1422353211 To see if you agree with the logic

File: packages/plugins/i18n/server/bootstrap.js [hunk 1]
```diff
@@ -8,11 +8,17 @@ const registerModelsHooks = () => {
     .map((contentType) => contentType.uid);
 
   if (i18nModelUIDs.length > 0) {
+    // TODO V5 : to remove ?
+    // Should this code exist? It's putting business logic on the query engine
+    // whereas it should maybe stay on the entity service layer ?
```
Comment (Marc-Roig) [inline packages/plugins/i18n/server/bootstrap.js:13]: I do think this code belongs in the i18n plugin. As it is about assigning locales.

Maybe this bit of code could be turned into a service if we see it appropiate, but I do think it should stay in v5.


This is a good way of decoupling logic from core, but  I also think we could:
- document this side effects on the entities. 
- standarize where we apply change effects like this (or extending controllers and services for instance)
 
If we start relying more and more on side effects like this it could become tricky to track whats changing what.

File: packages/plugins/i18n/server/services/localizations.js [hunk 2]
```diff
@@ -11,7 +11,14 @@ const { getService } = require('../utils');
...
+    const defaultLocale = await getDefaultLocale();
+    data.forEach((entry) => {
+      if (isNil(entry.locale)) {
+        entry.locale = defaultLocale;
+      }
+    });
+  } else if (isNil(data.locale)) {
     data.locale = await getDefaultLocale();
   }
 };
```
Comment (Marc-Roig) [inline packages/plugins/i18n/server/services/localizations.js:24]: It's not related to this specific PR, but maybe we could call `assignDefaultLocale` to `assignDefaultLocaleToEntries`, it seems a bit unclear where are we assigning the default locale. wdyt?

File: packages/plugins/i18n/server/services/localizations.js [hunk 3]
```diff
@@ -11,7 +11,14 @@ const { getService } = require('../utils');
 const assignDefaultLocale = async (data) => {
   const { getDefaultLocale } = getService('locales');
 
-  if (isNil(data.locale)) {
+  if (isArray(data) && data.some((entry) => !entry.locale)) {
+    const defaultLocale = await getDefaultLocale();
+    data.forEach((entry) => {
+      if (isNil(entry.locale)) {
+        entry.locale = defaultLocale;
+      }
```
Comment (Marc-Roig) [inline packages/plugins/i18n/server/services/localizations.js:19]: I have a question aboutthe isNil, is there a difference between this and
`entry.locale ??= defaultLocale` or `entry.locale = entry.locale || defaultLocale`

Not that I have a preference, I am curious to know if isNil does more things that I do not know.

Comment (petersg83) [reply packages/plugins/i18n/server/services/localizations.js:19]: Good idea, I'm not used to the new syntax in node. I'll use `??=`! :)

Comment (petersg83) [reply packages/plugins/i18n/server/services/localizations.js:19]: Oh I cannot, it was introduced in NodeJS 15. I'll use `entry.locale = entry.locale || defaultLocale` then

File: packages/plugins/i18n/server/bootstrap.js (hunk 1 above)
Comment (petersg83) [reply packages/plugins/i18n/server/bootstrap.js:13]: Sorry I didn't mean to move the code elsewhere. My question was about just deleting it. I wonder if it's not crossing a boundary to do i18n logic in the database hooks. Adding a default locale is already managed at the entity-service level (with `packages/plugins/i18n/server/services/entity-service-decorator.js`).

File: packages/plugins/i18n/server/services/localizations.js (hunk 2 above)
Comment (petersg83) [reply packages/plugins/i18n/server/services/localizations.js:24]: Yes I'm not against :)

File: packages/plugins/i18n/server/services/localizations.js (hunk 3 above)
Comment (Marc-Roig) [reply packages/plugins/i18n/server/services/localizations.js]: ooh, didn't know about that, such as shame! It's a nice operator

**Review by Marc-Roig — APPROVED** [review]
LGTM 👏
