### PR TITLE
fix: reordering dynamic zones messes up indexes during validation

### LINKED ISSUE #24186: Nested repeatable reorder + delete inside Dynamic Zone swaps content between items
### Node Version

22.18.0

### NPM/Yarn/PNPM Version

yarn version v1.22.22

### Strapi Version

5.22.0

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Javascript

### Reproduction URL

_No response_

### Bug Description

When deleting items from a nested repeatable field (columns) inside a component within a Dynamic Zone — and causing the remaining items to shift position — the Strapi Admin UI generates an incorrect payload.

The remaining item’s id is preserved, but its nested content (heading, paragraph, etc.) is replaced with the data from the item that previously occupied its new position, rather than retaining its own data. This “implicit reorder” happens automatically as a result of deletions.

This bug is probably entirely on the Admin UI side — the incorrect data is already present in the payload before it is sent to the API. The backend simply persists what it receives.

**Video:**

https://github.com/user-attachments/assets/ba5de1c2-3bc6-43c0-b395-d8d7e69330e3

**Example of actual PUT request payload**

`{
  "structure": [
    {
      "__component": "section.row",
      "id": 1818,
      "customId": null,
      "backgroundColor": {
        "connect": [],
        "disconnect": []
      },
      "borderRadius": null,
      "paddingTop": null,
      "paddingBottom": null,
      "paddingLeft": null,
      "paddingRight": null,
      "ariaLabel": "Dynamic zone row",
      "alignColumnsVertically": null,
      "columns": [
        {
          "id": 4713,
          "widthPercentage": null,
          "backgroundColor": {
            "connect": [],
            "disconnect": []
          },
          "borderRadius": null,
          "paddingTop": null,
          "alignContentHorizontally": null,
          "alignContentVertically": null,
          "isHiddenForDesktop": false,
          "isHiddenForMobile": false,
          "heading": {
            "id": 3052,
            "fontWeight": null,
            "customId": null,
            "value": "Heading Test",
            "visuallyHidden": null,
            "level": "H2",
            "colorSelectedText": {
              "connect": [],
              "disconnect": []
            },
            "size": null,
            "color": {
              "connect": [],
              "disconnect": []
            },
            "align": "left"
          },
          "list": null,
          "paragraph": {
            "id": 2383,
            "customId": null,
            "content": "Paragraph",
            "alignContent": null,
            "color": {
              "connect": [],
              "disconnect": []
            }
          },
          "buttons": [
            {
              "id": 1449,
              "customId": null,
              "variant": "primary",
              "label": "Test Button",
              "route": null,
              "openInNewTab": false,
              "routeUserLogged": null,
              "color": {
                "connect": [],
                "disconnect": []
              },
              "hoverColor": {
                "connect": [],
                "disconnect": []
              },
              "iconLeft": {
                "connect": [],
                "disconnect": []
              },
              "iconRight": {
                "connect": [],
                "disconnect": []
              },
              "routeParams": null
            }
          ],
          "buttonsVerticalAlign": null,
          "image": null,
          "imageBottom": null,
          "icon": {
            "connect": [],
            "disconnect": []
          },
          "gapDesktopImage": null,
          "gapDesktopIcon": null,
          "badge": null,
          "video": null,
          "orderMobile": null,
          "gapMobileImage": null,
          "gapMobileIcon": null,
          "paddingBottom": null,
          "paddingLeft": null,
          "paddingRight": null,
          "blankSpaceDesktopImage": null,
          "blankSpaceMobileImage": null,
          "name": "column3 - button - test",
          "iconColor": {
            "connect": [],
            "disconnect": []
          }
        }
      ]
    }
  ],
  "name": "page-31",
  "route": "/nested-components-problem",
  "footer": {
    "connect": [],
    "disconnect": []
  },
  "headerNext": {
    "connect": [],
    "disconnect": []
  },
  "metaDataTitle": null,
  "metaDataDescription": null,
  "metaDataKeywords": null,
  "maxWidth": null,
  "createdAt": null,
  "updatedAt": null,
  "createdBy": null,
  "updatedBy": null,
  "documentId": "f2oeraoogdwrhbfifjxvr947"
}`

**UI mismatch**
Based on the Admin UI, the remaining column (column3 - button - test) does not have a heading or paragraph — these fields are visibly empty before saving.

However, the payload built by the Admin UI for the PUT request incorrectly includes a heading and paragraph object taken from another (deleted) column. 

**Additional notes**
I tested this exact same content structure and workflow in Strapi v4.9.2, and it works as expected there — the payload correctly reflects the Admin UI state after deleting nested items.

### Steps to Reproduce

	1.	Create a page with a Dynamic Zone field (e.g., structure) that contains a section.row component.
	2.	In the section.row component, add at least 3 columns in its columns (nested repeatable) field.
	•	Give the first two columns some content in heading and/or paragraph.
	•	Leave the third column without a heading or paragraph (only other content, e.g., a button).
	3.	Save the page.
	4.	Edit the page again.
	5.	Delete the first two columns in the same edit session. (reorder has occurred)
	6.	Save the page.
	7.	Inspect the PUT request payload sent from the Admin UI to the backend.

### Expected Behavior

Deleting one or more items in a nested repeatable (e.g., columns inside section.row) must:
	1.	remove only the selected items,
	2.	keep the remaining items’ identity and content intact, and
	3.	(if positions shift) only change their array order, not their nested data.

And the payload of PUT request should be something like this:

`{
  "structure": [
    {
      "__component": "section.row",
      "id": 1818,
      "customId": null,
      "backgroundColor": {
        "connect": [],
        "disconnect": []
      },
      "borderRadius": null,
      "paddingTop": null,
      "paddingBottom": null,
      "paddingLeft": null,
      "paddingRight": null,
      "ariaLabel": "Dynamic zone row",
      "alignColumnsVertically": null,
      "columns": [
        {
          "id": 4713,
          "widthPercentage": null,
          "backgroundColor": {
            "connect": [],
            "disconnect": []
          },
          "borderRadius": null,
          "paddingTop": null,
          "alignContentHorizontally": null,
          "alignContentVertically": null,
          "isHiddenForDesktop": false,
          "isHiddenForMobile": false,
          "heading": null, // HERE: Without data
          "list": null,
          "paragraph": null, // HERE: Without data
          "buttons": [
            {
              "id": 1449,
              "customId": null,
              "variant": "primary",
              "label": "Test Button",
              "route": null,
              "openInNewTab": false,
              "routeUserLogged": null,
              "color": {
                "connect": [],
                "disconnect": []
              },
              "hoverColor": {
                "connect": [],
                "disconnect": []
              },
              "iconLeft": {
                "connect": [],
                "disconnect": []
              },
              "iconRight": {
                "connect": [],
                "disconnect": []
              },
              "routeParams": null
            }
          ],
          "buttonsVerticalAlign": null,
          "image": null,
          "imageBottom": null,
          "icon": {
            "connect": [],
            "disconnect": []
          },
          "gapDesktopImage": null,
          "gapDesktopIcon": null,
          "badge": null,
          "video": null,
          "orderMobile": null,
          "gapMobileImage": null,
          "gapMobileIcon": null,
          "paddingBottom": null,
          "paddingLeft": null,
          "paddingRight": null,
          "blankSpaceDesktopImage": null,
          "blankSpaceMobileImage": null,
          "name": "column3 - button - test",
          "iconColor": {
            "connect": [],
            "disconnect": []
          }
        }
      ]
    }
  ],
  "name": "page-31",
  "route": "/nested-components-problem",
  "footer": {
    "connect": [],
    "disconnect": []
  },
  "headerNext": {
    "connect": [],
    "disconnect": []
  },
  "metaDataTitle": null,
  "metaDataDescription": null,
  "metaDataKeywords": null,
  "maxWidth": null,
  "createdAt": null,
  "updatedAt": null,
  "createdBy": null,
  "updatedBy": null,
  "documentId": "f2oeraoogdwrhbfifjxvr947"
}`

### Logs

```shell

```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

**Related issues**
- [#23909](https://github.com/strapi/strapi/issues/23909)

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by Adzouz**
### What does it do?

Reordering dynamic zones messes up the data because of an index change and mix the content between the swapped items.
It's happening during the form validation where we use indexes to fetch the initialValue.
See the following video to show the issue:

https://github.com/user-attachments/assets/aa2ebda8-d71e-400e-aee9-34c499e02ed7

### Why is it needed?

It's not saving the actual state of the form and messes up with the data, it could lead to pretty nasty behaviours and loss of data.

### How to test it?

Since the issue is pretty hard to reproduce, see the details in the ticket below.
Reordering dynamic zones will not be enough. The dynamic zone should have repeatable components as children.
For the test, create a first row with a child content (fill some data) + create a new one without anything in it, then swap the two items and save.
You can also see in the payload of the PUT request that the data is incorrect.

### Related issue(s)/PR(s)

Resolves #24186

🚀

### CODE REVIEW

File: packages/core/content-manager/admin/src/pages/EditView/utils/data.ts [hunk 1]
```diff
@@ -302,18 +312,29 @@ const handleInvisibleAttributes = (
         continue;
       }
 
-      result[attrName] = currentValue.map((dzItem, index) => {
+      result[attrName] = currentValue.map((dzItem) => {
         const compUID = dzItem?.__component;
         const compSchema = components[compUID];
 
+        // Find the initial value for this component using __temp_key__ instead of index
```
Comment (hood) [inline packages/core/content-manager/admin/src/pages/EditView/utils/data.ts]: Since this is repeated twice, wouldn’t it make sense to extract it into a helper fn?

File: packages/core/content-manager/admin/src/pages/EditView/utils/data.ts [hunk 2]
```diff
@@ -219,6 +219,25 @@ type HandleOptions = {
 
 type RemovedFieldPath = string;
 
+/**
+ * @internal
+ * @description Finds the initial value for a component or dynamic zone item (based on its __temp_key__ and not its index).
```
Comment (markkaylor) [inline packages/core/content-manager/admin/src/pages/EditView/utils/data.ts:224]: I believe the `__temp_key__` is used for drag and drop and will change when you move an item. Will that have an impact?

Comment (Adzouz) [reply packages/core/content-manager/admin/src/pages/EditView/utils/data.ts:224]: The method prepareTempKeys is adding `__temp_key__` to all items before their generation to be able to use them for the drag and drop so even if you don't move the items, those keys will be there

Comment (markkaylor) [reply packages/core/content-manager/admin/src/pages/EditView/utils/data.ts:224]: and if you do move the items everything still works as expected?

Comment (Adzouz) [reply packages/core/content-manager/admin/src/pages/EditView/utils/data.ts:224]: Yes actually that was this case that was broken since it was getting the old initialValues from the previous indexes, if you were moving items it messed up the value. For example you already have an item and you create a new one, you move it to the first position, then the index that used to be 0 (the first one) will still contain the value of the row that was there before and so it will copy its content to the row you just created and moved.
[A] => create empty [B] => move [B] before [A] => [B][A] but index 0 still contains values from A and since B is empty it will take the initialValue instead so if you save it will result in [A][A]
