### PR TITLE
[@strapi/database]: Add missing WhereParams attributes to the type definition 

### LINKED ISSUE #13287: [4.2.0-beta.2] Type definition for WhereParams in query(...).findMany and other query functions is missing attributes
## Bug report
The `WhereParams` type in [`@strapi/database`](https://github.com/strapi/strapi/blob/master/packages/core/database/lib/index.d.ts) is not complete. It only has support for `$and`, `$or` and `$not`, so most of the functions described in the [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/filtering.html#lt) are missing.

### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.2.0-beta.2
- Database: postgres
- Operating system: Ubuntu-20.04

### Describe the bug

Incomplete type definition as described above.

### Steps to reproduce the behavior

1. Try using the `where` attribute in `strapi.query('UID').findMany({ where: { ... } })`
2. Only the basic and, or and not operations are available

### Expected behavior

The type should have all the attributes as described in the docs

### PR DESCRIPTION
**Pull request by fingeg**
Fixes #13287 

As described in the mentioned issue. Most of the parameters listed in the [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/filtering.html#logical-operators) are missing. Only the and, or and not was added so far. 

This PR adds all missing attributes so that the typing for the WhereParams is correct.

### What does it do?

It adds the filter parameters `$eq`, `$ne`, `$in`, and all others while supporting the nested structure.

### Why is it needed?

As of now the typescript complirer throws an error on the where clause. Example:
```ts
const data = await strapi.query('api::bber-post.bber-post').findMany({
            where: {
                $and: [
                    { date: { $gte: '2019-01-01' } },
                    { date: { $lt: '2020-01-01' } }
                ]
            }
        });
```
this was not possible, because `$gte` and `$lt` where both within the missing attributes.

### How to test it?
Use the code example from above and try out valid queries. Now the types will be correct.

### Related issue(s)/PR(s)

#13287

### CODE REVIEW

File: packages/core/database/lib/index.d.ts [hunk 1]
```diff
@@ -2,16 +2,37 @@ import { LifecycleProvider } from './lifecycles';
...
+  $endsWith?: T[K];
+  $null?: boolean;
+  $notNull?: boolean;
+  $not?: WhereParams<T> | AttributeOperators<T, K>;
+}
 
-type WhereParams<T> = {
-  [K in keyof T]?: T[K];
+export type WhereParams<T> = {
+  [K in keyof T]?: T[K] | T[K][] | AttributeOperators<T, K>;
```
Comment (Convly) [inline packages/core/database/lib/index.d.ts:33]: I'm not sure to understand the need for `T[K][]` here, could you explain what is its purpose?

**Review by Convly — COMMENTED** [review]
Thanks for opening this PR, only one question!

File: packages/core/database/lib/index.d.ts (hunk 1 above)
Comment (fingeg) [reply packages/core/database/lib/index.d.ts:33]: It's because the [`$in`](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/filtering.html#in) attribute can be omitted. 
For example, if the data type is a string for a certain attribute (called position in this case):
```json
{
 "where": {
   "position": ["manager", "intern"]
 }
}
```
this would be correct and converted to an `$in` attribute. Therefore the type `T[K][]` has to be supported.

**Comment by fingeg** [comment]
The only thing I noticed that's still not supported even with the updated types is nested where clauses that filter on relations.
Also not sure how that should be added. 

In my application I have a usecase like this:
```ts
type ResearchCollection = {
    id: number;
    title: string;
    slug: string;
    date: string;
    created_at: string;
    updated_at: string;
    published_at: string;
    created_by_id: string;
    updated_by_id: string;
    categories:  {
        id: number;
        category: string;
    }[];
    communities: {
        id: number;
        community: string;
    }[];
}
```

now using this type definition for one of the collection by overriding the AllTypes in `global.d.ts`: 
```ts
interface AllTypes {
        'api::research.research': ResearchCollection;
}
```

If now I want to write a where clause that filters on the collection `categories`, the correct way would be:
```ts
 {
        where: {
            categories: {
                id: SOME_ID
            }
        }
}
```
which still throws a type error as of now.

Any ideas how that should be handled?

File: packages/core/database/lib/index.d.ts (hunk 1 above)
Comment (Convly) [reply packages/core/database/lib/index.d.ts:33]: Make sense, thanks :slightly_smiling_face:

**Comment by fingeg** [comment]
> Hey, concerning your last point about nested where clauses:
> 
> I'm currently writing the first version of the typings for the content types. Once we'll have that, we'll be able to refactor typings for the entity service & such tools. I think we can wait a bit for them before diving into early solutions. What do you think?

Yeah, we can wait a bit.
