### PR TITLE
fix: adding component to dynamic zone overwrites data

### LINKED ISSUE #22399: Dynamic zone not inserting items correctly when using "Add component below/above" button
### Required System information

- Node.js version: 22.12.0
- NPM version: 10.9.0
- Strapi version: 5.5.1
- Database: MySql
- Operating system: MacOs
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When adding new items to a dynamic zone list, clicking 'Add Component Below' replaces the item below the selected element instead of inserting a new item underneath it as expected. Similarly, clicking 'Add Component Above' replaces the current item with the new one, rather than adding it above the selected element.

### Steps to reproduce the behavior

1. Create components to add to the dynamicZone list
2. Create a collection type with a dynamicZone attribute
3. Add those components in the dynamicZone.
4. Create a new item on the new collection.
5. Upon creation, add components to the dynamicZone
6. Try to add components above or below on that dynamicZone list using the buttons provided by the admin panel (3 dots)
7. (To reproduce the issue, the component you are referencing to insert a new item above or below should already have items below and above)

### Expected behavior

- New components added via "Add component above" should be inserted **above** the referenced component where the action was triggered.
- New components added via "Add component below" should be inserted **below** the referenced component where the action was triggered.

### Screenshots

https://github.com/user-attachments/assets/ff49eec5-54c6-4b88-89b7-69ba00cb541e

### Code snippets

If applicable, add code samples to help explain your problem.

### PR DESCRIPTION
**Pull request by remidej**
### What does it do?

- Fixes #22399. I do the fix by not relying on setIn anymore, because it's designed to overwrite content at the index it's given. I use toSpliced instead (the FP version of splice) which just inserts at the the given position
- Adds new e2e test case to catch the issue
- Fixes the alignment of the "more" action button on components

### Why is it needed?

To avoid accidental data loss

### How to test it?

Create content in dynamic zones, add components to the top, to the bottom, in the middle, maybe delete and recreate some.

Also do sanity check changing review workflows stages, because it seems to use the same addFieldRow util.

### CODE REVIEW

File: packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx [hunk 1]
```diff
@@ -149,7 +149,7 @@ const DynamicComponent = ({
         <Drag />
       </IconButton>
       <Menu.Root>
-        <Menu.Trigger size="S" endIcon={null} paddingLeft={2} paddingRight={2}>
+        <Menu.Trigger size="S" endIcon={null} paddingTop="4px" paddingLeft="7px" paddingRight="7px">
```
Comment (markkaylor) [inline packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx:152]: Could you explain why we are no longer using theme values?

**Review by markkaylor — COMMENTED** [review]
The code looks good to me but I won't have time to do the QA today

**Comment by remidej** [comment]
@markkaylor looks like I have to investigate the failing tests before it's ready for QA

File: packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx (hunk 1 above)
Comment (remidej) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx:152]: 4px can just be 1, I updated that 👍

for the 7px, it's the padding given to the siblings via IconButton, not sure why (@lucasboilly do you know?). So I'm setting 7px myself so the sizes and gaps match. It's also done [there](https://github.com/strapi/strapi/blob/52ef733c58d68d1fbeb03775edcde7dc1ebd490b/packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx#L282-L284)

screenshot 2025-01-20 at 10 24 06@2x

Comment (lucasboilly) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx]: @remidej the paddings should be inherited from `size`, I don't know why we need to add styles on top of it. Maybe it comes from the `Accordion` component in the DS? And what happens if you only keep the `size` property?

Comment (remidej) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx]: screenshot 2025-01-20 at 10 49 53@2x
it gives it a huge padding

Comment (lucasboilly) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx]: @remidej ok, only for the last one from what I see? 

It seems specific styles were added to it somewhere.

Comment (remidej) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx]: The first 2 are IconButtons. The last one is a Menu.Trigger

Comment (lucasboilly) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx]: Can't we nest an `IconButton` in the `Menu.Trigger`? That's what we do in the nav, a menu is displayed when clicking on the `Avatar` and the `Menu.Trigger` has `padding: 0`.

If it's not possible let's just use your workaround. What's important here is to fix the DZ bug.

Comment (remidej) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx]: That works! I just had to give tag="span" to the icon button, otherwise the nested buttons messed with the accessibility

File: tests/e2e/tests/content-manager/editview.spec.ts [hunk 2]
```diff
@@ -678,5 +678,47 @@ test.describe('Edit View', () => {
...
+        .filter({ has: page.getByRole('heading') })
+        .all();
+      expect(components).toHaveLength(2);
+      expect(components[0]).toHaveText(/product carousel/i);
+      expect(components[1]).toHaveText(/content and image/i);
+
+      // Add components add specific locations:
+      // - very last position
+      await components[1].getByRole('button', { name: /more actions/i }).click();
+      await page.getByRole('menuitem', { name: /add component below/i }).dispatchEvent('click');
```
Comment (remidej) [inline tests/e2e/tests/content-manager/editview.spec.ts:700]: I hate that I have to do those dispatchEvent, but a normal click just would not pass in the CI, even though it always passed locally. See [this section](https://playwright.dev/docs/input#forcing-the-click) of the Playwright docs (force: true did not work either in the CI 🤷)

**Review by Marc-Roig — APPROVED** [review]

**Comment by markkaylor** [comment]
Hey just tested this but I have a couple issues:
- Components are always added below
- If there is only one component already and I try to add above I get an error


https://github.com/user-attachments/assets/9040ca07-7827-4285-8e2d-e0f1b02c39fb

File: tests/e2e/tests/content-manager/editview.spec.ts [hunk 3]
```diff
@@ -678,5 +678,47 @@ test.describe('Edit View', () => {
...
+      // There should be a dynamic zone with two components
+      const components = await page
+        .getByRole('listitem')
+        .filter({ has: page.getByRole('heading') })
+        .all();
+      expect(components).toHaveLength(2);
+      expect(components[0]).toHaveText(/product carousel/i);
+      expect(components[1]).toHaveText(/content and image/i);
+
+      // Add components add specific locations:
```
Comment (markkaylor) [inline tests/e2e/tests/content-manager/editview.spec.ts:697]:
```suggestion
      // Add components at specific locations:
```

**Comment by remidej** [comment]
@markkaylor up until the crash isn't the order what you're expecting?

**Comment by markkaylor** [comment]
> @markkaylor up until the crash isn't the order what you're expecting?

oh yeah you're right it looks like it is! My bad

**Review by markkaylor — APPROVED** [review]
Nice quick fix!
