### PR TITLE
Fix transfer DZ and repeatable components

### LINKED ISSUE #20394: DTS Import Unique Constraint Failed
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-beta.8
- Node/Yarn Version: npm/10.2.4 node/v20.11.1 darwin arm64 workspaces/false
- Edition: Community
- Database: sqlite
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Get  `UNIQUE constraint failed` error when doing a DTS import on SQlite Database.

### Steps to reproduce the behavior

1. Run `strapi import`

https://github.com/strapi/strapi/assets/6153188/ee200c62-fccd-4be1-bdd5-010241f2486f

### Expected behavior

Should not fail with `Unique constrain` error.

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

filters out links related to components so we don't export them

### Why is it needed?

- components and dz are already populated at the entity stage 
- we face a unique constraint error otherwise by attempting to insert duplicate ids

### How to test it?

- export a strapi app with repeatable components and dz data it should work if you try to import it back

fix #20394

### CODE REVIEW

File: packages/core/data-transfer/src/strapi/queries/link.ts [hunk 1]
```diff
@@ -338,7 +338,16 @@ const filterValidRelationalAttributes = (attributes: Record<string, any>) => {
...
   const isComponentLike = (attribute: any) => {
-    return attribute.component || attribute.components;
+    return (
+      /**
+       * probably can remove attribute.component & attribute.components
+       * to be checked
+       *  */
+      attribute.component ||
+      attribute.components ||
+      attribute.joinTable?.name.includes('components') ||
```
Comment (Convly) [inline packages/core/data-transfer/src/strapi/queries/link.ts:348]: How is that possible to have a relation to components/cmps that is not a component/dynamic zone?

What is the shape of the attribute you get here?

Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/queries/link.ts:348]: it's not different, I just think the object we are receiving doesn't contain this anymore attribute.component  or
      attribute.components

Comment (Convly) [reply packages/core/data-transfer/src/strapi/queries/link.ts:348]: I see, could you make it so that we're checking the suffix instead of a loose `includes`? This should prevent having false positives.

Also, you can indeed remove the previous check.

Comment (innerdvations) [reply packages/core/data-transfer/src/strapi/queries/link.ts:348]: Just curious what causes this bug on v5 but not on v4. Are we just covering up another issue?

Comment (innerdvations) [reply packages/core/data-transfer/src/strapi/queries/link.ts:348]: Basically: can you see if this issue exists or not in v4?

If the issue also exists in v4, this fix seems ok (but will also need to be merged in v4 as well).

If this issue doesn't exist in v4, it means that something unexpected has changed in the objects sent, and it could be an underlying problem we need to look into.

Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/queries/link.ts]: it's only a v5 issue, the v4 object contains the component/components attribute, it seems it's been removed in v5
at the same time it doesn't look like it's been used anywhere else expect here previously

**Comment by innerdvations** [comment]
Could you add a unit test for `filterValidRelationalAttributes` that takes attributes and filters them correctly?

**Review by Convly — COMMENTED** [review]
Given the following structure

`CT1 > (comp) CompA > (rel) CT2`

Would `CompA > CT2` link be preserved with this solution?

**Comment by Bassel17** [comment]
> Given the following structure
> 
> `CT1 > (comp) CompA > (rel) CT2`
> 
> Would `CompA > CT2` link be preserved with this solution?

it works, the links are preserved, this only changes what we are checking against "table name" but it still the same behavior as before, we are ignoring the same links we used to ignore

**Review by Convly — APPROVED** [review]

**Review by Convly — CHANGES_REQUESTED** [review]
Looks like some tests (including lint) are failing

**Comment by Bassel17** [comment]
> Looks like some tests (including lint) are failing

indeed seems i forgot to commit one of the files

**Review by Convly — APPROVED** [review]
LGTM

**Review by innerdvations — APPROVED** [review]
Looks great now, thanks!
