### PR TITLE
fix(security-middleware): fix config merging with defaults

### LINKED ISSUE #19589: Custom CSP rules in security middleware are ignored
### Required System information

- Node.js version: v20
- Yarn version: 3.1.1
- Strapi version: v4.20.1
- Database: Postgres
- Operating system: Linux 
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Custom Content Security Policy directives configured in security middleware are ignored for '/admin' path. 

### Steps to reproduce the behavior

1. Go to `config/middleware.ts`, and add custom `script-src` rule for CSP, example:
```js
// config/middleware.ts
export default [
  'strapi::logger',
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'script-src': ["'self'", 'https://cdn.jsdelivr.net', 'https://unpkg.com'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  ...
];
```
3. Request the `/admin` from Strapi server, and verify the CSP header includes the custom rules configured above :x:
```sh
curl -v https://localhost:1337/admin 2>&1 | grep content-security-policy
```

### Expected behavior

The CSP header should include the custom rules I configured in security middleware.

### Additional context

This bug was introduced here https://github.com/strapi/strapi/pull/18697/files#r1440289055.  `lodash/merge` was used to merge CSP policies, and it has an unexpected behavior with arrays https://github.com/lodash/lodash/issues/5384. The fix replaces `merge` with `mergeWith` with custom handler for array values.

On the side, `unsafe-inline` is unsafe and should preferably be enabled only in DEV mode. This hack seems related to the work on vite (having vite would be great :rocket:).

### PR DESCRIPTION
**Pull request by med8bra**
### What does it do?

Fixes merging logic in security middleware configuration.

### Why is it needed?

Currently, security middleware ignores user custom CSP rules for the directives `script-src/connect-src`, which blocks loading any custom scripts.

### How to test it?

1. Set custom script-src CSP rules in security middleware configuration `config/middleware`. Example:

```js
// config/middleware.ts
export default [
  'strapi::logger',
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'script-src': ["'self'", 'https://cdn.jsdelivr.net', 'https://unpkg.com'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  ...
];
```

2. Start and request admin page from strapi server, and verify that custom CSP rules are respected.

```sh
curl -v https://localhost:1337/admin 2>&1 | grep content-security-policy
```

### Related issue(s)/PR(s)

This fixes #19589.

### CODE REVIEW

**Comment by joshuaellis** [comment]
Please don't ping members of the team for a review. We have many PRs waiting for review 😊

File: packages/core/strapi/src/middlewares/security.ts [hunk 1]
```diff
@@ -29,6 +29,14 @@ const defaults: Config = {
   },
 };
 
+const mergeConfig = (existingConfig: Config, newConfig: Config) => {
```
Comment (alexandrebodin) [inline packages/core/strapi/src/middlewares/security.ts:32]: This kind of merging prevents overwritting completly and should be avoided. 

You can inverse the merge order so that user config will override the default one when provided below

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/core/strapi/src/middlewares/security.ts (hunk 1 above)
Comment (med8bra) [reply packages/core/strapi/src/middlewares/security.ts:32]: @alexandrebodin mergeConfig is only used to update existing user config with extra rules, so it won't overwrite user config, but extend it (set field if missing, and concat array if existing).

Below `helmetConfig` is computed from user `config` and defaults, and won't be affected by this merge strategy.
```
let helmetConfig: Config = defaultsDeep(defaults, config);
```

Please let me know if I'm missing a case, we can have it as test

**Review by alexandrebodin — APPROVED** [review]

**Comment by alexandrebodin** [comment]
@med8bra Thank you for your contribution 💯
