### PR TITLE
Fix decimal on pg and mysql

### LINKED ISSUE #1273: Decimal fields are stored as string in DB
**Informations**
- **Node.js version**: v9.10
- **npm version**: v6.0.1
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: Postgres
- **Operating system**: Mac OS

**What is the current behavior?**
Decimal data is stored as string in the database.

**Steps to reproduce the problem**
- Create a content type with a decimal field
- Go to the `content-manager` and create an entry
- The admin send the data as with the correct format (number)

**What is the expected behavior?**
The data should be stored as numeric type.

I believe this issue as already been referenced but since it's working for integer and float and not decimal I'm opening a new issue.

### PR DESCRIPTION
**Pull request by lauriejim**
My PR is a: 🐛 Bug fix

Main update on the: Framework

Fix #1273 issue, decimal are received as string on pg and mysql decimal are stored as integer.

### CODE REVIEW

File: packages/strapi-bookshelf/lib/index.js [hunk 1]
```diff
@@ -361,7 +361,7 @@ module.exports = function(strapi) {
                             type = definition.client === 'pg' ? 'double precision' : 'double';
                             break;
                           case 'decimal':
-                            type = 'decimal';
```
Comment (derrickmehaffy) [inline packages/strapi-bookshelf/lib/index.js]: I think we should look at making this configurable in the adminUI and the config files if possible. 

Using this I believe the accuracy is 10 total digits with 2 being after the decimal point so something like:
`99999999.99`

File: packages/strapi-bookshelf/lib/index.js [hunk 2]
```diff
@@ -361,7 +361,7 @@ module.exports = function(strapi) {
...
+                            type = 'decimal(10,2)';
```
Comment (derrickmehaffy) [inline packages/strapi-bookshelf/lib/index.js]: I think we should look at making this configurable in the adminUI and the config files if possible. 

Using this I believe the accuracy is 10 total digits with 2 being after the decimal point so something like:
`99999999.99`

Comment (lauriejim) [reply packages/strapi-bookshelf/lib/index.js]: @derrickmehaffy yes it's a good idea ! But in an other PR. Can you create an issue (feature request) with detail of this options. Thank you !

The topic of this one is just to make it work ;)
