### PR TITLE
Fix deep filtering for manyWay

### LINKED ISSUE #4487: Filtering data manyWay cause an 500 internal error with SQLite
Hello,
I think i found some bug in deep filtering data with relations. 

I have freshly installed new version of strapi cms on my computer and i create two new Content Types in it. In that case it will be Restaurants (width field name and description) and Tags (with field name). And now in Restaurants i create relations with Tags just like on image below
relations

I put some random data and when i go to `/restaurants` endpoint i see something like this:
relations_example

Everything looks god until i try to filter restaurants by tag name and go to `/restaurants?tags.name=food`. Filtering data resturn a `500 internal server error` and in console i have:
relations_console

When i try change relations type to other everyting is fine, but with that last one i have always same error. Is it a bug? or it is my mistake?

**System**
- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: Strapi v3.0.0-beta.17.5
- Database: SQLite
- Operating system: Windows 10 / Ubuntu Digital Ocean

### PR DESCRIPTION
**Pull request by petersg83**
fix #4487 

#### Description of what you did:
- Change how joins are made for manyWay in buildQuery
- Add test of deep filtering for manyWay

### CODE REVIEW

File: packages/strapi-connector-bookshelf/lib/buildQuery.js [hunk 1]
```diff
@@ -84,38 +84,52 @@ const buildJoinsAndFilter = (qb, model, whereClauses) => {
...
-        : `${originInfo.alias}.${assoc.alias}`;
-
-    qb.leftJoin(
-      `${destinationInfo.model.databaseName}.${destinationInfo.model.collectionName} AS ${destinationInfo.alias}`,
-      externalKey,
-      internalKey
-    );
+      qb.leftJoin(
+        `${originInfo.model.databaseName}.${assoc.tableCollectionName} AS ${joinTableAlias}`,
+        `${joinTableAlias}.${singular(originInfo.alias)}_id`,
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/buildQuery.js]: Two comments here:

- Test with a manyWay pointing to the same model ;) 
- As it is the only change can you refactor the code a bit to avoid repetition :)

Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/buildQuery.js]: Ah oui bien vu le `related` 😏

**Comment by petersg83** [comment]
I updated the PR.
I couldn't think of a way to refactor the code to avoid repetition without losing readability. Do you have a suggestion?

**Comment by alexandrebodin** [comment]
You should start buy splitting the join columns into variables with understadable names and see how you can factor those :)

File: packages/strapi-connector-bookshelf/lib/buildQuery.js [hunk 2]
```diff
@@ -79,43 +79,50 @@ const buildJoinsAndFilter = (qb, model, whereClauses) => {
    * @param {Object} destinationInfo - destination with which we are making a join
    */
   const buildJoin = (qb, assoc, originInfo, destinationInfo) => {
-    if (assoc.nature === 'manyToMany') {
+    if (['manyToMany', 'manyWay'].includes(assoc.nature)) {
       const joinTableAlias = generateAlias(assoc.tableCollectionName);
 
+      let originColumnNameInJoinTable = `${joinTableAlias}.`;
+      if (assoc.nature === 'manyToMany') {
+        originColumnNameInJoinTable += `${singular(
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/buildQuery.js]: I would avoid the concatenation here and leave the joinTableAlias in the templateString.
