### PR TITLE
[Data transfer] Filesystem agnostic loading of Strapi data files

### LINKED ISSUE #15616: Fatal error on import: Invalid schema changes detected during integrity checks
### System information
- Node.js version: 16.19.0
- NPM version: 9.3.1
- Strapi version: 4.6.0
- Database: SQLite
- Operating system: Windows 11 Home, 22H2 22621.1194

### Describe the bug
When trying to use the new import future of Strapi 4.6.0 I get the error below. This is with barebone Strapi, and with a single content type and a few records, nothing else and no plugins.

```
error: [FATAL] Invalid schema changes detected during integrity checks (using the strict strategy). Please find a summary of the changes below:
- admin::permission:
  - Removed ""
- admin::user:
  - Removed ""
- admin::role:
  - Removed ""
- admin::api-token:
  - Removed ""
- admin::api-token-permission:
  - Removed ""
- api::test.test:
  - Removed ""
- plugin::upload.file:
  - Removed ""
- plugin::upload.folder:
  - Removed ""
- plugin::users-permissions.permission:
  - Removed ""
- plugin::users-permissions.role:
  - Removed ""
- plugin::users-permissions.user:
  - Removed ""
- plugin::i18n.locale:
  - Removed ""
```

### Steps to reproduce the behavior

1. Install a new instance of the latest Strapi version.
2. Make a simple content type and some records.
3. Export the data with `npm run strapi export -- --file test --no-encrypt`.
4. Add a few records.
5. Import the old data with `npm run strapi import -- -f test.tar.gz`.

### Expected behavior
The data should be successfully imported.

### Additional context
I have the issue with Yarn also, and I have tried to import the data to an empty and new Strapi instance, but I have the same issue. I have also experienced the issue with a PostgreSQL database.

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

1. Improve error handling when schema or metadata cannot be loaded from a Strapi data file
2. Fix loading of Strapi data files that were generated on win32 systems
3. Strapi data files now always export with (internal) paths using posix format
4. Allows us to have jsonl directory paths deeper than one in our export

### Why is it needed?

1. When schema failed to load, it was incorrectly being reported as a schema validation error for every property on the schema
2. Exports that were generated on win32 had internal tar paths using backslash (\\) instead of forward slash (/) and could not be loaded
3. We want our generated tar files to be as consistent as possible between platforms, and it's better if we can know that our export files always use posix paths internally to reduce complexity in the future
4. it was a limitation we had previously that is no longer necessary with the new implementation

### How to test it?

Generate all four possible Strapi data files with a `yarn strapi export`:

- win32 with this PR
- win32 without this PR
- posix with this PR
- posix without this PR

Then test **importing all four of those files** on the same combinations:

- win32 with this PR 
- win32 without this PR
- posix with this PR
- posix without this PR

For each one:

- Ensure all assets are transferred and not just reported as successful with zero transfers
- Ensure all assets are transferred with the correct path and filename (ie, not with filenames that includes a path with slashes)
- Ensure all other data is transferred

### Known limitations

There are still some limitations that we can improve at a later time.

- if the importer does not read the assets path properly, it reports zero files transferred successfully rather than displaying an error for being unable to transfer any files. We need to add a sanity check in metadata about number of records for each stage (including entities, links, etc) so that we can detect when a different number of entities or assets are transferred than expected
- if a posix systems includes files in the assets directory that includes special characters not permitted on win32 (only possibly with manually placed files; strapi media library normalizes filenames to not include special characters) they will not unpack properly on win32; there is no solution for this, but it should be documented and we should check that it works with the check mentioned in the previous line

### Related issue(s)/PR(s)

Fixes #15616

Two community PRs were opened at roughly the same time to fix the issue, but only solved the issue for win32->win32 and did not solve the issue for win32->posix. I also needed to go a few steps further and improve the way we export the files to begin with, improved error handling, and cleaned up the inconsistent way we were comparing paths. Will add them as co-authors in a commit before publishing this PR :)

https://github.com/strapi/strapi/pull/16211
https://github.com/strapi/strapi/pull/16212

### CODE REVIEW

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 1]
```diff
@@ -45,6 +45,34 @@ export const createLocalFileSourceProvider = (options: ILocalFileSourceProviderO
...
+ * support manually-created tar files coming from Windows systems (ie, if a user creates a
+ * backup file with a windows tar tool rather than using the `export` command)
+ *
+ * Because of this, export/import files may never contain files with a forward slash in the name, even escaped
+ * */
+
+// Check if the directory of a given filePath (which can be either posix or win32) resolves to the same as the given posix-format path posixDirName
+const isDirPathEquivalent = (posixDirName: string, filePath: string) => {
+  // if win32 convert to posix, then get dirname
+  const normalizedDir = path.posix.dirname(filePath.split(path.win32.sep).join(path.posix.sep));
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:62]: What about paths that include escape characters (e.g. `My File's Name` > `My\ File\'s\ Name`)? Won't this break the logic here?

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 2]
```diff
@@ -45,6 +45,34 @@ export const createLocalFileSourceProvider = (options: ILocalFileSourceProviderO
...
+
+  return posixDirName === normalizedDir;
+};
+
+// Check if two file paths that can be either in posix or win32 format resolves to the same file
+const isFilePathEquivalent = (fileA: string, fileB: string) => {
+  // Check if paths appear to be win32 or posix, and if win32 convert to posix
+  const normalizedPathA = fileA.split(path.win32.sep).join(path.posix.sep);
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:70]: Same as the comment above for the directories

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 3]
```diff
@@ -81,18 +111,28 @@ class LocalFileSourceProvider implements ISourceProvider {
...
+      throw new ProviderInitializationError('Could not load metadata from Strapi data file.');
+    }
   }
 
-  getMetadata() {
-    // TODO: need to read the file & extract the metadata json file
-    // => we might also need to read the schema.jsonl files & implements a custom stream-check
+  async getMetadata() {
+    if (this.#metadata) {
+      return this.#metadata;
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:122]: Could you describe what edge-case we're handling there?

Comment (Convly) [reply packages/core/data-transfer/src/file/providers/source/index.ts:122]: After reading the code, I assume it's made to cache the jsonl read operation?

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 1 above)
Comment (christiancp100) [reply packages/core/data-transfer/src/file/providers/source/index.ts:62]: Screenshot 2023-04-17 at 09 43 16

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 3 above)
Comment (innerdvations) [reply packages/core/data-transfer/src/file/providers/source/index.ts:122]: Yeah, we're reading metadata three times so this way it's caching it. I'll restructure it into different loading/retreiving methods)

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 1 above)
Comment (innerdvations) [reply packages/core/data-transfer/src/file/providers/source/index.ts:62]: I'll test for those cases of paths with escaped characters, and can also add a comment about the expected filePath requirements, since it's just for the internal tar path usage.

Because it's just for that purpose, and we never generated tars with absolute paths on windows (as far as I know, I'll check though), there shouldn't be any worries about the drive prefix.

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 3 above)
Comment (Convly) [reply packages/core/data-transfer/src/file/providers/source/index.ts:122]: Alright make sense, might be worth adding a small comment to explain the benefit :slightly_smiling_face:

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 4]
```diff
@@ -81,18 +83,33 @@ class LocalFileSourceProvider implements ISourceProvider {
...
   }
 
-  getMetadata() {
-    // TODO: need to read the file & extract the metadata json file
-    // => we might also need to read the schema.jsonl files & implements a custom stream-check
+  async #loadMetadata() {
     const backupStream = this.#getBackupStream();
-    return this.#parseJSONFile<IMetadata>(backupStream, METADATA_FILE_PATH);
+    this.#metadata = await this.#parseJSONFile<IMetadata>(backupStream, METADATA_FILE_PATH);
+    return this.#metadata;
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:95]: Does it make sense to return the value from a "loader" function?

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 5]
```diff
@@ -81,18 +83,33 @@ class LocalFileSourceProvider implements ISourceProvider {
...
+  }
+
+  async getMetadata() {
+    if (this.#metadata) {
+      await this.#loadMetadata();
+    }
+
+    return this.#metadata || null;
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:103]: We could use ?? instead of ||

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 6]
```diff
@@ -121,20 +138,21 @@ class LocalFileSourceProvider implements ISourceProvider {
...
         new tar.Parse({
+          // find only files in the assets/uploads folder
           filter(filePath, entry) {
             if (entry.type !== 'File') {
               return false;
             }
-
-            const parts = filePath.split('/');
-            return parts[0] === 'assets' && parts[1] === 'uploads';
+            return isFilePathInDirname('assets/uploads', filePath);
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:146]: Shouldn't we rely on path.posix.join(assets, uploads) instead of a regular string? I know it won't make a real difference here, it's more about consistency

Comment (innerdvations) [reply packages/core/data-transfer/src/file/providers/source/index.ts:146]: I think this is fine, the function requires a posix path and we are providing one. And we use paths like that in many places throughout the codebase. I'm more trusting of this string that I know exactly what it is rather than trusting posix.join not to change it to something like './assets/uploads' or 'assets/uploads/' without me knowing for sure (even though those cases would be fine as seen in the tests).

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 4 above)
Comment (innerdvations) [reply packages/core/data-transfer/src/file/providers/source/index.ts:95]: I don't think it hurts, but I can also remove it to ensure we always use getMetadata when it's needed.

**Review by christiancp100 — APPROVED** [review]
