### PR TITLE
fix: Reverse proxy config 

### LINKED ISSUE #21184: Install Strapi v5 in Sub-Path on Server not working
### Required System information

- Node.js version: v18
- Strapi version: 5.0.0-rc.17
- Database: postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Installing Strapi in a Sub-Path on a Server (f.e. https://rooturl.tld/backend) seems nearly unpossible. In a fresh install with server config url: https://rooturl.tld/backend/ and admin config admin-url: /admin (at build-time and runtime) the admin page generally loads (http 200) in /backend/admin, but the resources are loaded from the root path (https://rooturl.tld/strapi-BA4UeQmR.js). This leads to 404 and a blank page.

### Steps to reproduce the behavior

1. Build Strapi with ENV URL=https:/rooturl.tld/backend/, ENV ADMIN_URL=/admin
2. Run Container
3. Admin Page is blank because js resources could not be loaded

### Expected behavior

The resources should not ignore server-paths.

### Code snippets

We are running strapi in a kubernetes cluster and have a rewrite in our virtual service:
```
- name: "backend-routes"
    match:
    - uri:
        prefix: "/backend/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: strapi-backend
        port:
          number: 1337
```

We already tried nearly all permutations in rewriting, ENV URL/ADMIN URL setting (like ADMIN_URL=/backend/admin) etc., but the initial javascript is always requested from the root url.

### PR DESCRIPTION
**Pull request by alexandrebodin**
### What does it do?

Fixes reverse proxy compatibility without involved prefixing strapi routes. Make it iso with v4 behavior

Alternative to https://github.com/strapi/strapi/pull/21507
fixes #21184

### CODE REVIEW

**Review by Convly — COMMENTED** [review]
Dumping the raw output of my local test, haven't tested to use a reverse proxy yet, I wanted to make sure the rest is working fine and do some first testing from the train.

```json
[
   {
      "serverUrl":"",
      "serverAbsoluteUrl":"http://localhost:1337",
      "adminUrl":"/admin",
      "adminAbsoluteUrl":"http://localhost:1337/admin",
      "adminPath":"/admin",
      "adminBaseName":"/admin",
      "serverPath":"/",
      "note": "Working fine"
   },
   {
      "serverUrl":"",
      "serverAbsoluteUrl":"http://localhost:1337",
      "adminUrl":"/dashboard",
      "adminAbsoluteUrl":"http://localhost:1337/dashboard",
      "adminPath":"/dashboard",
      "adminBaseName":"/dashboard",
      "serverPath":"/",
      "note": "Working fine"
   },
   {
      "serverUrl":"",
      "serverAbsoluteUrl":"http://localhost:1337",
      "adminUrl":"http://localhost:1337/dashboard",
      "adminAbsoluteUrl":"http://localhost:1337/dashboard",
      "adminPath":"http://localhost:1337/dashboard",
      "adminBaseName":"/dashboard",
      "serverPath":"/",
      "note": "Working fine"
   },
   {
      "serverUrl":"http://localhost:1337/cms",
      "serverAbsoluteUrl":"http://localhost:1337/cms",
      "adminUrl":"http://localhost:1337/cms/admin",
      "adminAbsoluteUrl":"http://localhost:1337/cms/admin",
      "adminPath":"/admin",
      "adminBaseName":"/cms/admin",
      "serverPath":"/cms",
      "note":"localhost:1337/admin don't return 404, but only a blank page (network requests are fine), (vite vs requests issue?), both /api and /cms/api works"
   },
   {
      "serverUrl":"http://localhost:1337/cms",
      "serverAbsoluteUrl":"http://localhost:1337/cms",
      "adminUrl":"http://localhost:1337/cms/dashboard",
      "adminAbsoluteUrl":"http://localhost:1337/cms/dashboard",
      "adminPath":"/dashboard",
      "adminBaseName":"/cms/dashboard",
      "serverPath":"/cms",
      "note":"same as above"
   },
   {
      "serverUrl":"/cms",
      "serverAbsoluteUrl":"http://localhost:1337/cms",
      "adminUrl":"/cms/dashboard",
      "adminAbsoluteUrl":"http://localhost:1337/cms/cms/dashboard",
      "adminPath":"/dashboard",
      "adminBaseName":"/cms/cms/dashboard",
      "serverPath":"/cms",
      "note":"/cms/cms/dashboard ??? (doesn't even load using this url, and vite fails on /cms/dashboard but tries to load anyway)"
   },
   {
      "serverUrl":"/cms",
      "serverAbsoluteUrl":"http://localhost:1337/cms",
      "adminUrl":"/cms/cms/dashboard",
      "adminAbsoluteUrl":"http://localhost:1337/cms/cms/cms/dashboard",
      "adminPath":"/cms/dashboard",
      "adminBaseName":"/cms/cms/cms/dashboard",
      "serverPath":"/cms",
      "note":"doesn't detect well common subpaths"
   },
   {
      "serverUrl":"/cms/server",
      "serverAbsoluteUrl":"http://localhost:1337/cms/server",
      "adminUrl":"/cms/server/cms/dashboard",
      "adminAbsoluteUrl":"http://localhost:1337/cms/server/cms/server/cms/dashboard",
      "adminPath":"/cms/dashboard",
      "adminBaseName":"/cms/server/cms/server/cms/dashboard",
      "serverPath":"/cms/server",
      "note":"wtf"
   }
]
```

**Comment by wladyslawczyzewski** [comment]
hey @Convly, I think the issues you get with the paths are due to mutation of config object and generating the paths on mutated config instead of using the config before mutation - see the change from the original PR to fix this issue https://github.com/strapi/strapi/pull/21507/files#diff-39132cb22fba5c04fba6f5fe28ee2a991f962c84eefc1dffdee2618cb7091ac1

**Comment by Convly** [comment]
> hey @Convly, I think the issues you get with the paths are due to mutation of config object and generating the paths on mutated config instead of using the config before mutation - see the change from the original PR to fix this issue [#21507 (files)](https://github.com/strapi/strapi/pull/21507/files#diff-39132cb22fba5c04fba6f5fe28ee2a991f962c84eefc1dffdee2618cb7091ac1)
> 
> should I continue investigation with my original PR to reduce the number of changes or you prefer to go forward with these changes?

Hey, sorry for the late response, I was out of office for the past 2 weeks.

I'm gonna meet with Alexandre today to talk more about our options and where we want to go, so that we can move forward on this topic.

I'll keep you updated

File: packages/core/strapi/src/node/create-build-context.ts [hunk 1]
```diff
@@ -79,15 +80,25 @@ const createBuildContext = async <TOptions extends BaseOptions>({
     });
 
   const serverUrl = strapiInstance.config.get<string>('server.url');
-  const adminPath = strapiInstance.config.get<string>('admin.path');
+  const serverAbsoluteUrl = strapiInstance.config.get<string>('server.absoluteUrl');
+  const adminUrl = strapiInstance.config.get<string>('admin.url');
+  const adminAbsoluteUrl = strapiInstance.config.get<string>('admin.absoluteUrl');
+
+  const sameOrigin = new URL(adminAbsoluteUrl).origin === new URL(serverAbsoluteUrl).origin;
```
Comment (Convly) [inline packages/core/strapi/src/node/create-build-context.ts:87]: Maybe consider adding a quick explanation of what we're testing.

e.g.

```typescript
// Check if both the server and admin URLs share the same origin
// Example: Comparing origins 'http://localhost:1337/admin' and 'http://localhost:1337/cms' will return true
```

File: packages/core/strapi/src/node/create-build-context.ts [hunk 2]
```diff
@@ -79,15 +80,25 @@ const createBuildContext = async <TOptions extends BaseOptions>({
...
+
+  const adminPublicPath = new URL(adminAbsoluteUrl).pathname;
+
+  const adminPath = sameOrigin
+    ? strings.getCommonPath(serverUrl, adminUrl)
```
Comment (Convly) [inline packages/core/strapi/src/node/create-build-context.ts:92]: If both path share the same origin, shouldn't we take what's after the common path in the admin URL? Here it'll return the common origin and/or path (or am I missing something?)

File: packages/core/strapi/src/node/create-build-context.ts [hunk 3]
```diff
@@ -79,15 +80,25 @@ const createBuildContext = async <TOptions extends BaseOptions>({
...
+    : new URL(adminUrl).pathname;
 
   const appDir = strapiInstance.dirs.app.root;
 
   await loadEnv(cwd);
 
   const env = getStrapiAdminEnvVars({
-    ADMIN_PATH: adminPath,
-    STRAPI_ADMIN_BACKEND_URL: serverUrl,
+    ADMIN_PATH: adminPublicPath,
```
Comment (Convly) [inline packages/core/strapi/src/node/create-build-context.ts:100]: Just to be sure, why are we using adminPublicPath instead of the computed adminPath here ?

Comment (Convly) [reply packages/core/strapi/src/node/create-build-context.ts:100]: (might be worth adding a comment to explain the reasoning anyway)

File: packages/core/strapi/src/node/vite/config.ts [hunk 4]
```diff
@@ -85,6 +85,7 @@ const resolveDevelopmentConfig = async (ctx: BuildContext): Promise<InlineConfig
       },
     },
     server: {
+      cors: false,
```
Comment (Convly) [inline packages/core/strapi/src/node/vite/config.ts:88]: Is it needed for this PR? Does serving from different paths causes cors issues?

Comment (alexandrebodin) [reply packages/core/strapi/src/node/vite/config.ts:88]: It was causing some issues in the past, and I figure it doesn't make sense to have that conflict with our own cors middleware basically. I don't see where there would be an issue considering it's only in dev mode

File: packages/core/strapi/src/node/create-build-context.ts (hunk 3 above)
Comment (alexandrebodin) [reply packages/core/strapi/src/node/create-build-context.ts:100]: it's going to be the url used in on the browser side so you need to have the full path including the potential proxied parts

**Review by Convly — APPROVED** [review]
LGTM, tested with the different usecases and works well. The PR makes the behavior ISO with v4

**Comment by innerdvations** [comment]
Do we need to document these as new config options?

**Comment by Convly** [comment]
> Do we need to document these as new config options?

We're making sure everything is ISO with v4, nothing new or undocumented should have been added :thinking:

**Review by Convly — CHANGES_REQUESTED** [review]
Code LGTM

Can you fix the failing tasks (lint, ...) ?

**Review by Convly — APPROVED** [review]

File: packages/core/strapi/src/node/create-build-context.ts (hunk 1 above)
Comment (ashisherc) [reply packages/core/strapi/src/node/create-build-context.ts:86]: this doesnt seem to work, if the admin config URL is set to `/` and the server URL is set to a backend URL. this still results in true and hence admin panel is built with relative path. essentially deployment on different server doesn't work.

It will be good to utilise the serverAdminPanel config option itself to determine the backend URL.

**Comment by raphaelbadawi** [comment]
I may be missing something but upgrading Strapi to 5.5.1 (which should include this PR), putting back the rewrite rule which actually worked in Strapi 4 and the "url" conf in server.ts pointing to the absolute URL including the subpath, this which worked perfectly in Strapi 4, the exact same configuration and proxying, still doesn't work at all with Strapi 5.5.1 since assets are still loaded from the root domain.
