### PR TITLE
Fixes #12896

### LINKED ISSUE #12896: [4.2 beta] - Can't overwrite the theme colors
### Describe the bug

When using the `4.2.0-beta.0` with typescript I can't seem to overwrite the theme in the `src/admin/app.js` file.

### Steps to reproduce the behavior

1. `npx create-strapi-app@beta test-app-beta --ts` use quickstart method
2. `cd test-app-beta`
3. `yarn add strapi-code-themes`
4. Create file `src/admin/app.js` or `src/admin/app.ts` doesn't really matter.
5. Fill the file with this contents:

```
import { shadesOfPurple } from 'strapi-code-themes';

export default {
  config: {
    theme: {
      colors: shadesOfPurple,
    },
  },
};
```

### Expected behavior

Expected the theme to be overwritten with the colors from `strapi-code-themes`.

### System

- Node.js version: v14.19.0
- Strapi version: 4.2.0-beta.0
- Database: sqlite
- Operating system: Mac OS (M1)

### Additional context

When I do an non-typescript install of the beta this issue does not happen and the theme can be overwritten.

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril@strapi.io>

### What does it do?

It allows to use either a `app.ts` or an `app.tsx` file extension to customise the admin panel.

### Why is it needed?

To be able to customise the admin panel

### How to test it?

1. Replace the app.example.tsx file by an app.tsx. one and make some customisations.
2. The customisations should appear in the admin while running the dev mode (`yarn develop --watch-admin`)

### Related issue(s)/PR(s)

Fixes #12896

### CODE REVIEW

File: packages/core/admin/utils/get-custom-app-config-file.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ */
+const getCustomAppConfigFile = async (dir, useTypeScript) => {
+  const adminSrcPath = join(dir, 'src', 'admin');
+  const files = await fse.readdir(adminSrcPath);
+
+  if (useTypeScript) {
+    return files.find(file => file.match(/app.tsx?$/));
+  }
+
+  return files.find(file => file.match(/app.jsx?$/));
```
Comment (gu-stav) [inline packages/core/admin/utils/get-custom-app-config-file.js:20]: What do you think about normalizing first and therefore shortening this?

```suggestion
  const appRegex = new RegExp(`app.${useTypeScript ? 't' : 'j'}sx?$`)

  return files.find(file => file.match(appRegex));
```

Also: I think it's not mandatory, but I'd love to see a test for this file.

File: packages/core/admin/utils/should-build-admin.js [hunk 2]
```diff
@@ -31,11 +32,11 @@ const hasNonDefaultPlugins = plugins => {
...
 const hasCustomAdminCode = async (dir, useTypeScript) => {
   const customAdminPath = path.join(dir, 'src', 'admin');
-  const customAdminConfigFileExtension = useTypeScript ? 'app.tsx' : 'app.js';
-  const customAdminConfigFile = path.join(customAdminPath, customAdminConfigFileExtension);
+
+  const customAdminAppConfigFile = await getCustomAppConfigFile(dir, useTypeScript);
   const customAdminWebpackFile = path.join(customAdminPath, 'webpack.config.js');
 
-  const hasCustomConfigFile = await fs.pathExists(customAdminConfigFile);
+  const hasCustomConfigFile = customAdminAppConfigFile !== undefined;
```
Comment (gu-stav) [inline packages/core/admin/utils/should-build-admin.js:39]: I think this could be reduced to:

```suggestion
  const hasCustomConfigFile = !!customAdminAppConfigFile;
```

File: packages/core/admin/utils/create-cache-dir.js [hunk 3]
```diff
@@ -82,26 +83,26 @@ async function createCacheDir({ appDir, plugins, useTypeScript }) {
...
-  const customAdminConfigJSFilePath = path.join(appDir, 'src', 'admin', 'app.js');
-  const customAdminConfigTSXFilePath = path.join(appDir, 'src', 'admin', 'app.tsx');
-  const customAdminConfigFilePath = useTypeScript
-    ? customAdminConfigTSXFilePath
-    : customAdminConfigJSFilePath;
+  // Retrieve the custom config file extension
+  const customAdminAppConfigFile = await getCustomAppConfigFile(appDir, useTypeScript);
 
-  if (fs.existsSync(customAdminConfigFilePath)) {
+  if (customAdminAppConfigFile !== undefined) {
```
Comment (gu-stav) [inline packages/core/admin/utils/create-cache-dir.js:89]: I think this could be reduced to, because `.find` either returns a truthy or undefined value. Nothing else. I feel that explicit testing for `undefined` creates the impression there could be another falsy value.

```suggestion
  if (customAdminAppConfigFile) {
```

**Review by HichamELBSI — COMMENTED** [review]
Good job. Not sure that my comment ⬇️  is relevant. It's just that by seeing the test file, it's not easy to understand that the second parameter of `getCustomAppConfigFile` is used to define if TypeScript is used or not. It's up to you to decide if you want to update it or not 😅

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
👍🏽
