### PR TITLE
Fix not working deleteUsersPermissionsUser and mutations related to role 

### LINKED ISSUE #12349: Mutation deleteUsersPermissionsUser always forbidden
### Describe the bug

The mutation `deleteUsersPermissionsUser` is always forbidden. The admin UI allows you to only grant permissions for the `destroy` action, but that is not the permission being checked for the mutation (that is the `delete` action; See `Additional Context` below).

### Steps to reproduce the behavior

1. Assign User `destroy` permission
2. Execute `deleteUsersPermissionsUser` mutation
3. See it failing with `FORBIDDEN`

### Expected behavior

The UI should allow you to set the `delete` action permissions. In that case, the mutation would work.

### Code snippets

```graphql
mutation deleteProfile($id: ID!) {
  deleteUsersPermissionsUser(id: $id) {
    __typename
  }
}
```

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.6
- Database: SQLite
- Operating system: macOS

### Additional context

Changing the permission in the DB from `plugin::users-permissions.user.destroy` to `plugin::users-permissions.user.delete` has the desired effect. The mutation succeeds.

### PR DESCRIPTION
**Pull request by iicdii**
### What does it do?

1. Fix `deleteUsersPermissionsUser` mutation not working.
2. Fix `createUsersPermissionsRole`, `updateUsersPermissionsRole`, `deleteUsersPermissionsRole` mutation not working.

### Why is it needed?

In order to fix the bug that you cannot execute mutations unless you are admin.

### How to test it?

1. Create User entry - suppose its id is `1`
2. Enable to `destory` permission to `Authenticated` role

role

3. Execute Login mutation and get jwt token
```gql
mutation Login($input: UsersPermissionsLoginInput!) {
  login(input: $input) {
    jwt
    user {
      id
      username
    }
  }
}

{
  "input": {
    "identifier": "username",
    "password": "password"
  }
}
```

4. Execute mutation with HTTP header
```gql
mutation deleteProfile($id: ID!) {
  deleteUsersPermissionsUser(id: $id) {
    data {
      id
      attributes {
        username
      }
    }
  }
}

{
  "id": "1"
}
```

```json
{
  "Authorization": "Bearer <input jwt token>"
}
```

5. Same goes with `createUsersPermissionsRole`, `updateUsersPermissionsRole`, `deleteUsersPermissionsRole` mutation.

### Related issue(s)/PR(s)

Closes #12349

### CODE REVIEW

**Comment by bublinec** [comment]
Hey could we please merge this one?

File: packages/plugins/users-permissions/server/graphql/mutations/crud/user/update-user.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ module.exports = ({ nexus, strapi }) => {
       data: nonNull(userInputName),
     },
 
-    description: 'Update an existing user',
+    description: 'Delete an existing user',
```
Comment (alexandrebodin) [inline packages/plugins/users-permissions/server/graphql/mutations/crud/user/update-user.js:28]: I think you renamed the wrong description you are in the update-user.js file instead of the delete-user.js file :)

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/plugins/users-permissions/server/graphql/mutations/crud/user/update-user.js (hunk 1 above)
Comment (iicdii) [reply packages/plugins/users-permissions/server/graphql/mutations/crud/user/update-user.js]: Thanks :) Fixed

**Review by Convly — APPROVED** [review]

**Review by alexandrebodin — APPROVED** [review]

**Comment by Convly** [comment]
Good for me, I'll make a last test tomorrow and will merge if everything is still working great :slightly_smiling_face:

**Comment by Convly** [comment]
Hey @iicdii, could you try to amend/force push in order to force the tests to be re-run? It looks like they're stuck somehow.

Thanks!
