### PR TITLE
fix(openapi): correctly merge plugin router prefix with route paths

### LINKED ISSUE #25591: openapi generator messes up `upload` paths.
### Node Version

22.20.0

### NPM/Yarn/PNPM Version

10.9.3

### Strapi Version

develop branch

### Operating System

Linux (Debian/Ubuntu)

### Database

SQLite

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Bug Description

`strapi openapi generate` does not extract the right upload url's:

```JSON
{
  "openapi": "3.1.0",
  "x-powered-by": "strapi",
  "x-strapi-version": "5.37.1",
  "info": {
    "title": "kitchensink-ts",
    "description": "API documentation for kitchensink-ts v0.0.0",
    "version": "0.0.0"
  },
  "paths": {
    [...]
    "/": {  <=============== This is wrong.
       [...]
    },
```

The path is missing the `/upload` part..
This happens to all upload urls.

### Steps to Reproduce

- open the kitchensing example
- generate openapi specs
- wonder

### Expected Behavior

The paths are generated correctly.

### Logs

```shell

```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by Akash504-ai**
### What does it do?

Fixes an issue in the OpenAPI generator where plugin route prefixes were not merged with their route paths.

`PluginRoutesProvider` was returning `router.routes` directly and ignoring `router.prefix`, causing prefixed plugin routes (e.g. upload) to be generated under `/` instead of their actual base path.

This change merges `router.prefix` with `route.path` and normalizes the resulting path to prevent duplicate or trailing slashes.

---

### Why is it needed?

When running: strapi openapi generate

Upload plugin routes were generated like:

```json
"/": {
  "operationId": "upload/post"
}
```
Instead of:
```json
"/upload": {
  "operationId": "upload/post"
}
```
This resulted in incorrect OpenAPI specifications for plugin routes.

### How to test it?

1. Checkout `develop`
2. Run yarn `build`
3. Navigate to `examples/kitchensink-ts`
4. Run `yarn develop`
5. Run `yarn strapi openapi generate`
6. Open `specification.json`

Before fix:
```json
"/": { "operationId": "upload/post" }
```
After fix:
```json
"/upload": { "operationId": "upload/post/upload" }
"/upload/files"
"/upload/files/:id"
```

### Related issue(s)/PR(s)

Fixes #25591

### CODE REVIEW

**Comment by nclsndr** [comment]
Thank your for raising this PR @Akash504-ai!
I'm making a pre-check on the feature design with the team. I'll then get back here for the code review.

File: packages/core/openapi/src/routes/providers/plugin.ts [hunk 1]
```diff
@@ -30,10 +30,20 @@ export class PluginRoutesProvider extends AbstractRoutesProvider {
       const { routes } = plugin;
 
       return Array.isArray(routes)
-        ? // If it is a simple Route[], return as is
-          routes
-        : // Else, extract and flatten every route from each router
-          Object.values(routes).flatMap((router) => router.routes);
+        ? routes
+        : Object.values(routes).flatMap((router: any) => {
```
Comment (jhoward1994) [inline packages/core/openapi/src/routes/providers/plugin.ts]: Could we use the type "router: Core.Router" here?

(import type { Core } from '@strapi/types';)

File: packages/core/openapi/src/routes/providers/plugin.ts [hunk 2]
```diff
@@ -30,10 +30,20 @@ export class PluginRoutesProvider extends AbstractRoutesProvider {
...
+            const prefix = router.prefix ?? '';
```
Comment (jhoward1994) [inline packages/core/openapi/src/routes/providers/plugin.ts]: I think this might have to be something like this 

```
  const hasOwnPrefix =
    route.config != null &&
    Object.prototype.hasOwnProperty.call(route.config, 'prefix');
  const effectivePrefix = hasOwnPrefix
    ? (route.config.prefix ?? '')
    : (router.prefix ?? '');
```

Otherwise the changes would generate incorrect OpenAPI paths for e.g. `packages/plugins/users-permissions/server/routes/content-api/auth.js` as they have route level prefixes defined at `config.prefix` ?

File: packages/core/openapi/src/routes/providers/plugin.ts (hunk 1 above)
Comment (Akash504-ai) [reply packages/core/openapi/src/routes/providers/plugin.ts]: I'll update the type to router: Core.Router instead of any and push the change.

File: packages/core/openapi/src/routes/providers/plugin.ts (hunk 2 above)
Comment (Akash504-ai) [reply packages/core/openapi/src/routes/providers/plugin.ts]: I'll update the implementation to respect route-level prefixes before falling back to router.prefix and push the change shortly.

**Comment by Akash504-ai** [comment]
Hi! @jhoward1994  I have pushed the requested changes. 
The router type now uses Core.Router and the implementation respects route-level config.prefix before falling back to router.prefix. I also verified the build locally. Please let me know if any further adjustments are needed.

**Comment by jhoward1994** [comment]
Thanks @Akash504-ai !

One more thing, would you be able to add this code to `packages/core/openapi/__tests__/routes/plugins-route-provider.test.ts` starting at L20

This will make sure we have unit tests that cover this new behaviour 

```
    it('should prepend router prefix to route paths', () => {
      const strapiMock = {
        plugins: {
          upload: {
            routes: {
              'content-api': {
                type: 'content-api',
                prefix: '/upload',
                routes: [
                  {
                    method: 'GET',
                    path: '/',
                    handler: 'controller.find',
                    info: { type: 'content-api' },
                  },
                  {
                    method: 'GET',
                    path: '/files/:id',
                    handler: 'controller.findOne',
                    info: { type: 'content-api' },
                  },
                ],
              },
            },
          },
        },
      } as unknown as Core.Strapi;

      const provider = new PluginRoutesProvider(strapiMock);
      const { routes } = provider;

      expect(routes).toHaveLength(2);
      expect(routes[0].path).toBe('/upload');
      expect(routes[1].path).toBe('/upload/files/:id');
    });

    it('should use route config.prefix instead of router prefix when present', () => {
      const strapiMock = {
        plugins: {
          'users-permissions': {
            routes: {
              'content-api': {
                type: 'content-api',
                prefix: '/users-permissions',
                routes: [
                  {
                    method: 'POST',
                    path: '/auth/local',
                    handler: 'auth.callback',
                    info: { type: 'content-api' },
                    config: { prefix: '' },
                  },
                  {
                    method: 'GET',
                    path: '/users/me',
                    handler: 'user.me',
                    info: { type: 'content-api' },
                    config: { prefix: '' },
                  },
                ],
              },
            },
          },
        },
      } as unknown as Core.Strapi;

      const provider = new PluginRoutesProvider(strapiMock);
      const { routes } = provider;

      expect(routes).toHaveLength(2);
      // These routes have config.prefix = '', so they bypass the router prefix
      expect(routes[0].path).toBe('/auth/local');
      expect(routes[1].path).toBe('/users/me');
    });

    it('should handle mix of routes with and without config.prefix', () => {
      const strapiMock = {
        plugins: {
          'users-permissions': {
            routes: {
              'content-api': {
                type: 'content-api',
                prefix: '/users-permissions',
                routes: [
                  {
                    method: 'POST',
                    path: '/auth/local',
                    handler: 'auth.callback',
                    info: { type: 'content-api' },
                    config: { prefix: '' },
                  },
                  {
                    method: 'GET',
                    path: '/roles',
                    handler: 'role.find',
                    info: { type: 'content-api' },
                  },
                ],
              },
            },
          },
        },
      } as unknown as Core.Strapi;

      const provider = new PluginRoutesProvider(strapiMock);
      const { routes } = provider;

      expect(routes).toHaveLength(2);
      // config.prefix = '' bypasses router prefix
      expect(routes[0].path).toBe('/auth/local');
      // No config.prefix, uses router prefix
      expect(routes[1].path).toBe('/users-permissions/roles');
    });

    it('should handle routes with no router prefix', () => {
      const strapiMock = {
        plugins: {
          test: {
            routes: {
              'content-api': {
                type: 'content-api',
                routes: [
                  {
                    method: 'GET',
                    path: '/items',
                    handler: 'controller.find',
                    info: { type: 'content-api' },
                  },
                ],
              },
            },
          },
        },
      } as unknown as Core.Strapi;

      const provider = new PluginRoutesProvider(strapiMock);
      const { routes } = provider;

      expect(routes).toHaveLength(1);
      expect(routes[0].path).toBe('/items');
    });

```

**Comment by Akash504-ai** [comment]
@jhoward1994  I have added the unit tests for the plugin route prefix behavior and route-level prefix overrides. I also ran the tests locally to ensure everything passes. Please let me know if any adjustments are needed.

**Comment by nclsndr** [comment]
thank your for your help @Akash504-ai!

**Comment by Akash504-ai** [comment]
You're welcome @nclsndr! Happy to help
