### PR TITLE
Fix InputDate not working

### LINKED ISSUE #1960: "hour" field in DatePicker of content manager decrease by 7
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: postgres v10.5
- **Operating system**: macOS High Sierra

**What is the current behavior?**
When using content-manager to Edit/Add entries with fields of `date` type, either up or down arrow of the `hour` will cause the value `hour` to decrease by 7 on releasing mouse button.

**Steps to reproduce the problem**
Add a Content Type with a field of type `date`. Then edit or add entries in Content Manager

**What is the expected behavior?**
Function normally as a time picker should.

**Suggested solutions**

### PR DESCRIPTION
**Pull request by soupette**
**My PR is a:**
- [ ] 💥 Breaking change
- [X] 🐛 Bug fix #1960 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

**Manual testing done on the follow databases:**
- [ ] Not applicable
- [X] MongoDB
- [ ] MySQL
- [ ] Postgres

**Description:**
This PR fixes the hour field that was very buggy.

### CODE REVIEW

File: packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js [hunk 1]
```diff
@@ -88,8 +89,18 @@ export function* submit() {
...
-      const cleanedData = attrType === 'json' ? record[current] : cleanData(record[current], 'value', 'id');
-
+      let cleanedData;
+
+      switch (attrType) {
+        case 'json':
+          cleanedData = record[current];
+          break;
+        case 'date':
+          cleanedData = moment(record[current]).format();
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js]: I haven't specified any format here and I don't know if I should specify one...
@lauriejim @Aurelsicoko do you confirm that it matches what the back-end is expecting?

Comment (derrickmehaffy) [reply packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js]: In terms of bookshelf at least with MySQL, the format *has* to be in `YYYY-MM-DD HH:MM:SS` or the knex create/update query will fail.

Comment (soupette) [reply packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js]: @derrickmehaffy This PR fixes the time and date picker that were unusable in the front-end.
I have tested it with mongo and I know that it works.

Regarding bookshelf I think that it should be the back-end that should take care of formatting the received date instead of the front-end that way users won't have to duplicate the admin logic in their client app.

**cc/** @lauriejim

**Comment by fabricioanciaes** [comment]
Super excited for this! thanks for putting the work

**Comment by aaronweatherall** [comment]
Any update on this? We're trying to build an event system and strapi is literally unusable without the datepicker.

**Comment by fabricioanciaes** [comment]
I'm on strapi 3.0.0-alpha.22 and the issue still persists
footage of it happening: 

#2659 is supposed to fix this, right? Maybe its something on my end.

**Comment by lauriejim** [comment]
Thank you @fabricioanciaes !

Can you open a new issue please. Not completely the same issue and you GIF is really clear.
