### PR TITLE
Fix RBAC upload permissions

### LINKED ISSUE #10452: Default RBAC policies for Upload plugin not functioning properly
### Describe the bug

When apply the "default" RBAC conditions to the assets section of the upload plugin on a role that is not "super admin". Users can upload new assets but cannot update them nor delete their own assets (or in the case if the "same role as creator" is selected, then another user of the same role).

### Steps to reproduce the behavior

1. Spin up a new project (EE License required)
2. Create a new admin user with the default editor role
3. Modify the upload plugin settings and apply the "default" condition group on update, download, and copy link
4. Try as the new editor user to upload, modify, download, and delete an image.
4. See error "Forbidden"

### Expected behavior

With those conditionals, a user (or role) who uploaded an image should have full control over that image.

### Screenshots

image

### Code snippets

N/A

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: 3.6.3
- Database: SQLite
- Operating system: Linux Mint 20.1 (Ubuntu 20.04.1)

### Additional context

Internal TID 278

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Fix an issue where setting permissions with conditions on the assets for the upload plugin can break the permissions checks.
In a [previous PR](https://github.com/strapi/strapi/pull/10370/files#diff-ce5847e2721e68f1c2682b5812248461031c101c4bf74ed7abcbd6a8cd5b47d1R194), the auto-populate for the fetch has been removed, which caused the `created_by` attribute to be raw instead of populated, hence causing an issue when fetching the associated role.

As a fix, we simply use the raw identifier (from the `created_by` field) instead of trying to access the `id` property inside.

Another idea would've been to fetch directly the whole user based on the `created_by` id, but it would mean fetching also unwanted properties for the user, such as password & co. 

### Why is it needed?

Upload plugin's assets permissions are not working as they should.

### How to test it?

See: https://github.com/strapi/strapi/issues/10452 ("_Steps to reproduce this issue_")

### Related issue(s)/PR(s)

introduced by #10370 
fix #10452

### CODE REVIEW

File: packages/strapi-plugin-upload/controllers/upload/admin.js [hunk 1]
```diff
@@ -199,10 +199,9 @@ const findEntityAndCheckPermissions = async (ability, action, model, id) => {
 
   const pm = strapi.admin.services.permission.createPermissionsManager({ ability, action, model });
 
-  const roles = _.has(file, 'created_by.id')
-    ? await strapi.query('role', 'admin').find({ 'users.id': file[CREATED_BY_ATTRIBUTE].id }, [])
-    : [];
-  const fileWithRoles = _.set(_.cloneDeep(file), 'created_by.roles', roles);
+  const roles = await strapi.admin.services.role.find({ 'users.id': file[CREATED_BY_ATTRIBUTE] });
+
+  const fileWithRoles = _.set(_.cloneDeep(file), 'created_by.roles', roles || []);
```
Comment (alexandrebodin) [inline packages/strapi-plugin-upload/controllers/upload/admin.js:204]: we actually need the created_by.id too for the isOwner condition. so you need to find the user with the roles instead of just the roles

File: packages/strapi-plugin-upload/controllers/upload/admin.js [hunk 2]
```diff
@@ -199,10 +199,9 @@ const findEntityAndCheckPermissions = async (ability, action, model, id) => {
 
   const pm = strapi.admin.services.permission.createPermissionsManager({ ability, action, model });
 
-  const roles = _.has(file, 'created_by.id')
-    ? await strapi.query('role', 'admin').find({ 'users.id': file[CREATED_BY_ATTRIBUTE].id }, [])
-    : [];
-  const fileWithRoles = _.set(_.cloneDeep(file), 'created_by.roles', roles);
+  const author = await strapi.admin.services.user.findOne({ id: file[CREATED_BY_ATTRIBUTE] });
```
Comment (alexandrebodin) [inline packages/strapi-plugin-upload/controllers/upload/admin.js:202]: you can populate only the roles in the findOne

Comment (Convly) [reply packages/strapi-plugin-upload/controllers/upload/admin.js:202]: Yes, I thought that since we already need the roles, maybe users will find other information useful. I can keep only the roles for the moment though

**Review by alexandrebodin — APPROVED** [review]
