### PR TITLE
Upload path can be absolute

### LINKED ISSUE #7257: Not possible to use an absolute directory as public path
**Describe the bug**

Hey there, thank you for strapi, it's awesome!

After updating from beta to the latest stable (3.1.2) it seems that using absolute paths as the public directory breaks file uploads (which used to work before) :confused:

**Steps to reproduce the behavior**

1. Go to 'config/middleware.js'
2. Edit option 'settings.public' as described here https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations
3. Enter an `/absolute/path`
4. Upload a file
5. See error message

   error Error: ENOENT: no such file or directory, open '/path/to/strapi/absolute/path/uploads/<filename>'

**Expected behavior**

File upload should work

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.1.2
- Database: MySQL
- Operating system:

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

### PR DESCRIPTION
**Pull request by petersg83**
fix #7257

### CODE REVIEW

File: packages/strapi-plugin-upload/middlewares/upload/index.js [hunk 1]
```diff
@@ -1,15 +1,18 @@
...
+const { join, isAbsolute } = require('path');
 const range = require('koa-range');
 const koaStatic = require('koa-static');
 
 module.exports = strapi => ({
   initialize() {
-    const staticDir = join(
-      strapi.dir,
-      strapi.config.middleware.settings.public.path || strapi.config.paths.static
+    const configPublicPath = strapi.config.get(
```
Comment (alexandrebodin) [inline packages/strapi-plugin-upload/middlewares/upload/index.js:9]: Why not replace join by a resolve ?

File: packages/strapi-plugin-upload/middlewares/upload/index.js [hunk 2]
```diff
@@ -1,15 +1,16 @@
...
+      'middleware.settings.public.path',
+      strapi.config.paths.static
     );
+    const staticDir = resolve(configPublicPath);
```
Comment (alexandrebodin) [inline packages/strapi-plugin-upload/middlewares/upload/index.js:13]: you need to call resolve(strapi.dir, publicPath) or this will not work with relative path
