### PR TITLE
Fix/graphql playground

### LINKED ISSUE #12289: GraphQL Playground does not work without `users-permission` plugin
After uninstalling the `users-permission` plugin the GraphQL playground breaks down and is not accessible.

* Visiting http://localhost:1337/graphql/ gives 401 response saying:

```
{"data":null,"error":{"status":401,"name":"UnauthorizedError","message":"Missing or invalid credentials","details":{}}}
```

* Using API key in headers and visiting the same URL ends up in 400 response saying:

```
GET query missing.
```

### Steps to reproduce the behavior

1. Install strapi using `create-strapi-app`
2. Install `graphql` plugin
3. Uninstall `users-permissions`
4. Access `http://localhost:1337/graphql`

### System

- Node.js version: v14.17.6
- Strapi version: 4.0.5
- Operating system: macOS

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- Makes "/graphql" route authorized incase there is no token for the api token authentication strategy

### Why is it needed?

- When user-permissions plugin is uninstalled, users can't access the graphql playground
- the api token authentication strategy considers the /graphql route Unauthorized by default and with the absence of user-permissions plugin, api token is the default

### How to test it?

- Install graphql plugin
- Uninstall users-permissions
- Access http://localhost:1337/graphql and  you should have access to it

### Related issue(s)/PR(s)

fix #12289

### CODE REVIEW

File: packages/plugins/graphql/server/bootstrap.js [hunk 1]
```diff
@@ -110,6 +110,7 @@ module.exports = async ({ strapi }) => {
             },
           };
 
+          if (ctx.request.method === 'GET') return next();
```
Comment (innerdvations) [inline packages/plugins/graphql/server/bootstrap.js:113]:
```suggestion
          // allow graphql playground to load without authentication
          if (ctx.request.method === 'GET') return next();
          
```

Comment (innerdvations) [reply packages/plugins/graphql/server/bootstrap.js:113]: just so we don't forget why we're doing this

**Review by innerdvations — APPROVED** [review]
