### PR TITLE
Fix date field

### LINKED ISSUE #12630: GraphQL shadow mutation throws an error "Invalid date"
### Describe the bug
GraphQL throws an error "Invalid date" even though the exact date value is entered.
error

### Steps to reproduce the behavior

I tested with `strapi/examples/getstarted` example.

1. Go to http://localhost:1337/graphql
2. Execute mutation
```gql
mutation CreateCategory($data: CategoryInput!) {
  createCategory(data: $data) {
    data {
      attributes {
        date
        datetime
      }
    }
  }
}

{
  "data": {
    "date": "2022-01-01"
  }
}
```

### Expected behavior

Mutation should create an entry

### System

- Node.js version: 14.17.1
- NPM version: 8.4.1
- Strapi version: 4.1.0
- Database: SQLite, mySQL
- Operating system: MacOS M1 silicon

### Additional context

If the field is `DateTime` format, entering ISO String (ex: `'2022-02-23T07:01:06.869Z'`) creates an entry without validation error. Only `Date` format has a validation issue.

### PR DESCRIPTION
**Pull request by petersg83**
fix #12630

### CODE REVIEW

File: packages/plugins/graphql/server/services/internals/scalars/date.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+'use strict';
+
+const { GraphQLDate } = require('graphql-iso-date/dist');
+
+const parseAndCast = parseFn => (...args) => {
+  const parsedValue = parseFn(...args);
+
+  if (parsedValue instanceof Date) {
+    return parsedValue.toISOString().split('T')[0];
```
Comment (petersg83) [inline packages/plugins/graphql/server/services/internals/scalars/date.js:9]: After all I didn't use `formatISO` from `date-fns` as `formatISO` was taking the local timezone into account whereas `parsedValue` was not created using the local timezone (`parsedValue.toISOString()` always has hours and minutes set to 0). When using a timezone in america, the date was one day prior to the real one.

**Review by gu-stav — APPROVED** [review]
Well done & very nice tests 🌻

**Review by MarionLemaire — APPROVED** [review]
Tested on fix/date-graphql branch using Getstarted on Chrome and Visual Studio : OK.
