### PR TITLE
Fix entity-service types for relations' input

### LINKED ISSUE #18106: Set, Connect, Disconnect relations with EntityService (TypeScript) not possible
### Required System information

- Node.js version: 18.15.0
- NPM version: 9.8.0
- Strapi version: 4.13.6
- Database: MySQL
- Operating system: WSL2 (Windows 11) Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

With the new typescript definitions it is not possible to use connect, disconnect and set for relations with the EntityService.
It always expects an ID.

### Steps to reproduce the behavior
```
await strapi.entityService.update('api::core.subject', subjectResult[0].id, {
          data: {
            studies: {
              connect: [studiesInfo.study.id],
            },
          },
        });
```
Error: `Type '{ connect: (number | `${number}`)[]; }' is not assignable to type 'ID[]'.
  Object literal may only specify known properties, and 'connect' does not exist in type 'ID[]'.`

### Expected behavior

Working objects beside plain IDs

### LINKED ISSUE #18317: Upgrade from 4.13 to 4.14, in typescript, fundamentally changed and breaks core features of data management
I have a big backend running on strapi. Was running fine on 4.13, in typescript. Upgrading to 4.14 creates a ton of errors because of the types.

I am working with interfaces that look like this:
```
export interface IBatchBase {
  id?: number;

  type: BatchType;

  batchNumber?: string;
  material: IMaterial;
  openedAt: string;
  closedAt?: string;
  openedBy?: IUser;
  closedBy?: IUser;

  batchLines: IBatchLine[];
  flags?: IFlag[];
}

export interface IBatchRework extends IBatchBase {
  type: BatchType.rework;
  reasonForMovement?: IReasonForMovement;
}
```
Those interfaces were compatible with the strapi api and I could find items or create and update items. But moving to 4.13, my types are incompatible with the types expected by strapi. I have a lot of errors like:
```
 error TS2339: Property 'material' does not exist on type 'GetValues<"api::batch.batch", GetNonPopulatableKeys<"api::batch.batch">>'.

548     if (batch.material.pkgType !== PkgType.SS) {
```
```
error TS2339: Property 'flags' does not exist on type 'GetValues<"api::batch.batch", GetNonPopulatableKeys<"api::batch.batch">>'.

490         batch.flags.push(flag);
```
```
error TS2322: Type '{ type?: BatchType.rework; reasonForMovement?: IReasonForMovement; id?: number; batchNumber?: string; material?: IMaterial; openedAt?: string; closedAt?: string; openedBy?: IUser; closedBy?: IUser; batchLines?: IBatchLine[]; flags?: IFlag[]; }' is not assignable to type 'Input<"api::batch.batch">'.
  Type '{ type?: BatchType.rework; reasonForMovement?: IReasonForMovement; id?: number; batchNumber?: string; material?: IMaterial; openedAt?: string; closedAt?: string; openedBy?: IUser; closedBy?: IUser; batchLines?: IBatchLine[]; flags?: IFlag[]; }' is not assignable to type 'OmitRelationWithoutTarget<"api::batch.batch", { material?: ID; type?: "regular" | "rework"; comment?: string; createdAt?: DateTimeValue; updatedAt?: DateTimeValue; createdBy?: ID; ... 11 more ...; flags?: ID[]; } & {}>'.
    Types of property 'material' are incompatible.
      Type 'IMaterial' is not assignable to type 'ID'.

444         data: {

const ret = await strapi.entityService
      .create("api::batch.batch", {
        data: {
          ...batch,
        },
        populate: strapi.service("api::batch.batch").getFullPopulateObject(),
      })
      .catch(console.error);
``` 
It seems Strapi was returning full hierarchy of objects, now it is just returning ids of linked objects.

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

- Add support for relation reordering APIs (only for x(to)Many relations)
	- set
	- connect (including positional arguments `before`, `after`, `start` and `end`)
	- disconnect
- Add support for both shorthand and longhand notations (`ID | { id: ID }`) for all relations

### Why is it needed?

Fix broken types introduced by the Entity-Service x TypeScript PR

### How to test it?

In a Strapi project with types, write a create or update query and mutate relation properties.
- For `x(to)Many` relations, it should propose both the reordering APIs (`set`, `connect` and `disconnect`) and an array of either `ID`s or `{ id: Id }`
- For `x(to)One` relations, it should propose either `ID` or `{ id: ID }`

### Examples

Note: Using the `admin::role` generated type for this example

image

```ts
const { update } = strapi.entityService;
const uid = 'admin::user' as const;

// xMany (valid)
await update(uid, 1, { data: { roles: null } });
await update(uid, 1, { data: { roles: [] } });
await update(uid, 1, { data: { roles: [2, '3'] } });
await update(uid, 1, { data: { roles: [{ id: 2 }, { id: '3' }] } });
await update(uid, 1, { data: { roles: { set: null } } });
await update(uid, 1, { data: { roles: { set: [] } } });
await update(uid, 1, { data: { roles: { set: [2, 3] } } });
await update(uid, 1, { data: { roles: { set: [{ id: 2 }, { id: 3 }] } } });
await update(uid, 1, { data: { roles: { connect: [1, 2] } } });
await update(uid, 1, { data: { roles: { connect: [{ id: 1 }, { id: 2 }] } } });
await update(uid, 1, { data: { roles: { disconnect: [1, 2] } } });
await update(uid, 1, { data: { roles: { disconnect: [{ id: 1 }, { id: 2 }] } } });
await update(uid, 1, {
  data: { roles: { connect: [1, 2], disconnect: [{ id: 1 }, { id: 2 }] } },
});
// xMany (errors)
await update(uid, 1, { data: { roles: 2 } }); // not assignable to number
await update(uid, 1, { data: { roles: [2, { id: 2 }] } }); // number not assignable to { id: ID }

// xOne (valid)
await update(uid, 1, { data: { createdBy: null } });
await update(uid, 1, { data: { createdBy: 1 } });
await update(uid, 1, { data: { createdBy: '2' } });
// xOne (errors)
await update(uid, 1, { data: { createdBy: {} } }); // not assignable to {}
await update(uid, 1, { data: { createdBy: [] } }); // not assignable to []
```

### Related issue(s)/PR(s)

fix #18106
fix #18317

### CODE REVIEW

**Comment by Convly** [comment]
Experimental release available: `0.0.0-experimental.e9c8c97196ede5f344f1b92e43eb52c88c0c2b55`

**Comment by Convly** [comment]
Missing some properties, I'm gonna put this in draft & finalize it

**Comment by Convly** [comment]
Alright, this should be it now. Switching back to ready for review & releasing a new experimental

**Comment by Convly** [comment]
New experimental available: `0.0.0-experimental.af0176cf2e8b90e8550f1099a5ad7509a737dd1d`

File: packages/core/types/src/modules/entity-service/params/attributes/mocks.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import type { Attribute } from '../../../../types';
```
Comment (Marc-Roig) [inline packages/core/types/src/modules/entity-service/params/attributes/mocks.ts:1]: Minor thing, maybe it's me not used to using "mocks" in this case, is it mocking types?
I rather see them as primitives, but unsure if they are used for something else

Comment (Convly) [reply packages/core/types/src/modules/entity-service/params/attributes/mocks.ts:1]: Thanks for pointing that out, I wasn't sure about the naming.

We're "overriding" types' value for the original values.

e.g. boolean is not just boolean anymore, it's boolean | 1 | 0 | '1' | '0' | 'false' | 'true', etc...

Hence the "literal value mocks" (or overrides?)

Do you have a better naming idea by any chance?

Comment (Marc-Roig) [reply packages/core/types/src/modules/entity-service/params/attributes/mocks.ts:1]: Ah 💡 I see, then `mock`makes sense in this case! thank you

**Review by Marc-Roig — APPROVED** [review]

File: packages/core/types/src/modules/entity-service/params/attributes/mocks.ts (hunk 1 above)
Comment (innerdvations) [reply packages/core/types/src/modules/entity-service/params/attributes/mocks.ts:1]: I also found mocks to be confusing. It's more like API contract values, right? Or maybe just going with "literals" makes more sense than "mocks"?

Comment (Convly) [reply packages/core/types/src/modules/entity-service/params/attributes/mocks.ts:1]: I can switch to literals to avoid confusion

Comment (Convly) [reply packages/core/types/src/modules/entity-service/params/attributes/mocks.ts]: done in [01b5382](https://github.com/strapi/strapi/pull/19011/commits/01b53828d62ea4bb360aafdade04be9b8617fb16)

File: packages/core/types/src/modules/entity-service/params/attributes/index.ts [hunk 2]
```diff
@@ -49,23 +23,23 @@ export type ScalarValues = GetValue<
...
+  // | Attribute.Password
 >;
 
 /**
  * Attribute.GetValues override with extended values
  */
 export type GetValues<TSchemaUID extends Common.UID.Schema> = {
   id?: ID;
-} & OmitRelationWithoutTarget<
+} & OmitRelationsWithoutTarget<
```
Comment (innerdvations) [inline packages/core/types/src/modules/entity-service/params/attributes/index.ts:42]: I'm wondering if renaming OmitRelationsWithoutTarget (as well as moving the export path of it, along with ID and literals) would be considered a breaking change, since we do export it in @strapi/strapi, even though it's not documented.

Could we get around that by also continuing to export them the same way from this file, with a note to remove the dual-export in v5?

Comment (Convly) [reply packages/core/types/src/modules/entity-service/params/attributes/index.ts:42]: Root namespaces are unchanged, which I think should be the way the "types breaking changes" should be looked at.

We should advise people to use root-level namespace imports (`@strapi/strapi`) instead of deep ones (`@strapi/strapi/core/entity-service/...`), which -in my opinion- correspond to the public type API

Hence, since the splitting offers more readability from a maintainer perspective (at least I believe so), I would keep it personally like this. What do you think?

**Comment by Convly** [comment]
@Marc-Roig / @innerdvations Just a head's up but I assume there will be some things to accommodate when porting this change to V5 since you've been re-using portions of the ES types for the DS?

File: packages/core/types/src/modules/entity-service/params/attributes/index.ts (hunk 2 above)
Comment (innerdvations) [reply packages/core/types/src/modules/entity-service/params/attributes/index.ts:42]: Ok, I agree, I think as long as we keep the namespaces the same people shouldn't be using the deep references.

**Review by innerdvations — APPROVED** [review]
