### PR TITLE
fix(admin): handle windows paths in plugins.js

### LINKED ISSUE #18070: @strapi/plugin-color-picker not working when upgrading to 4.13.6
## Bug report

Color picker no longer works with strapi version 4.13.6

### Required System information

Environment: development
OS: win32-x64
Strapi Version: 4.13.6
Node/Yarn Version: yarn/1.22.19 npm/? node/v16.15.1 win32 x64
Edition: Community
Database: sqlite

### Describe the bug

After upgrading to 4.13.6 color picker is not showing up when adding custom fields.
Plugin is visible in plugins list.

If I try to edit collection type with color-picker (in component) I get:
```
index.js:33 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'default')
    at index.js:33:48
    at Array.forEach (<anonymous>)
    at m (index.js:32:12)
(anonymous) @ index.js:33
m @ index.js:32
await in m (async)
(anonymous) @ index.js:53
da @ react-dom.production.min.js:244
ac @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
L @ scheduler.production.min.js:13
ye @ scheduler.production.min.js:14
```

And if I try to edit component type:
```
react-dom.production.min.js:189 TypeError: Cannot destructure property 'icon' of 'At.get(...)' as it is undefined.
    at je (index.js:71:13)
    at Rs (react-dom.production.min.js:167:137)
    at Ye (react-dom.production.min.js:290:337)
    at tf (react-dom.production.min.js:280:389)
    at Af (react-dom.production.min.js:280:320)
    at jc (react-dom.production.min.js:280:180)
    at Ad (react-dom.production.min.js:271:88)
    at qd (react-dom.production.min.js:268:429)
    at L (scheduler.production.min.js:13:203)
    at MessagePort.ye (scheduler.production.min.js:14:128)
Kr @ react-dom.production.min.js:189
Pc.b.callback @ react-dom.production.min.js:189
Bl @ react-dom.production.min.js:144
Bc @ react-dom.production.min.js:262
yd @ react-dom.production.min.js:260
vd @ react-dom.production.min.js:259
Tf @ react-dom.production.min.js:283
sc @ react-dom.production.min.js:281
qd @ react-dom.production.min.js:269
L @ scheduler.production.min.js:13
ye @ scheduler.production.min.js:14
```

### Steps to reproduce the behavior

Try to add or edit types with color picker
Try to add or edit data with color picker

### Expected behavior

Color picker should be available when adding new fields.
Color picker should work when editing data.

### Additional context

Strapi 4.13.5 works fine.

### PR DESCRIPTION
**Pull request by jramstedt**
### What does it do?

Fixes plugin module paths on windows systems.

### Why is it needed?

Windows operating system uses \ as path separator. It is also escaped by \ making pathToPlugin something like `@strapi\\plugin-color-picker`

Using that path in module resolution fails when plugin is using "exports" package entry points in package.json.
"exports" entry points use posix style / separator.

Currently @strapi/plugin-color-picker doesn't work on Windows because it changed from using "strapi-admin.js" file to using exports entry points in package.json in 4.13.6.

See issue #18070 

### How to test it?

```
yarn create strapi-app colorpickertest --quickstart --ts --no-run
cd colorpickertest
yarn add @strapi/plugin-color-picker
yarn build
yarn develop
```

On Windows (without fix) .cache/admin/src/plugins.js won't have the plugins that use "exports" entry points in their package.json

### Related issue(s)/PR(s)

* resolves #18070

### CODE REVIEW

**Comment by joshuaellis** [comment]
Can you fill out the PR template correctly please – ensuring you describe the issue you found & your solution as well as how you came to it. Linking to an issue is not enough for "Why is needed" or "How to test it"

**Comment by jramstedt** [comment]
> Can you fill out the PR template correctly please – ensuring you describe the issue you found & your solution as well as how you came to it. Linking to an issue is not enough for "Why is needed" or "How to test it"

ok

File: packages/core/admin/utils/plugins.js [hunk 1]
```diff
@@ -112,7 +112,16 @@ const filterPluginsByAdminEntry = (plugin) => {
     );
 
     if (!isLocalPluginWithLegacyAdminFile) {
-      const isModuleWithFE = require.resolve(`${plugin.pathToPlugin}/strapi-admin`);
+      let packageName = plugin.info.packageName
```
Comment (joshuaellis) [inline packages/core/admin/utils/plugins.js:115]: Why have you chosen this as the primary way? My concern is this won't work with plugins local to a user's strapi-application?

**Review by joshuaellis — CHANGES_REQUESTED** [review]

File: packages/core/admin/utils/plugins.js (hunk 1 above)
Comment (jramstedt) [reply packages/core/admin/utils/plugins.js]: I pushed a new variation that only fixes the paths on windows.

**Review by joshuaellis — APPROVED** [review]
