### PR TITLE
Fix query when filtering and sorting on a relational field

### LINKED ISSUE #8931: [3.4.0] Invalid SQL generated for sorting relationship on filtered list view
### Describe the bug

Getting "An error occurred during models config fetch" when trying to sort a relationship column on a filtered list view. 
It appears an invalid Postgres SQL statement is being generated for this specific use case. 

### Steps to reproduce the behavior
1, Have postgres database connector setup on strapi 3.4.0 
2. Setup collection type with any relationship
3. Setup a list view to display that relationship
4. Should be able to sort that relationship fine
5. Now do a filter or search on that list view
6. Again try to sort the list, you will receive an error

### Expected behavior

Should just sort the filtered list

### Screenshots

Error received in list view: 
image

Filter applied, and relationship sorted:
image

Error from backend:
image

### SQL snippets (error description)

Invalid Postgres raw SQL generated:
```
'select distinct "test_results".* from "test_results" left join "dbname"."public"."products" as "products_1" on "products_1"."id" = "test_results"."soil" where "test_results"."Score" = ? order by "products_1"."Name" desc limit ?'
```

### Reason for error: ###
The ORDER BY clause can only be applied after the DISTINCT has been applied. Since only the fields in the SELECT statement are taken into consideration for the DISTINCT operations, those are the only fields may be used in the ORDER BY.

In the above SQL statement, products_1.Name is not available to "order by" because it was never selected in the select statement. 

### System

- Node.js version: 14.15.2
- NPM version: 6.14.9
- Strapi version: 3.4.0
- Database: Postgres
- Operating system: Linux/Heroku

### Additional context

It's appears this is valid syntax for SQLite, but Postgres can be more strict about this.

### PR DESCRIPTION
**Pull request by petersg83**
fix #8931

### CODE REVIEW

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/strapi-connector-bookshelf/lib/buildQuery.js [hunk 1]
```diff
@@ -21,8 +21,18 @@ const buildQuery = ({ model, filters }) => qb => {
   const joinsTree = buildJoinsAndFilter(qb, model, filters);
 
   if (_.has(filters, 'sort')) {
-    const clauses = filters.sort.map(buildSortClauseFromTree(joinsTree));
-    qb.orderBy(reject(isEmpty, clauses));
+    const clauses = filters.sort.map(buildSortClauseFromTree(joinsTree)).filter(c => !isEmpty(c));
+    const aliasedClauses = clauses.map(c => ({
+      order: c.order,
+      column: c.column.includes('.') ? c.tmpColumnName : c.column,
```
[the remark this answers is not in the document]
Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/buildQuery.js]: I did it but still need to filter somewhere to avoid renaming the columns of the main table, otherwise those columns would be duplicated and be present in the query result

File: packages/strapi-connector-bookshelf/lib/buildQuery.js [hunk 2]
```diff
@@ -14,15 +14,23 @@ const BOOLEAN_OPERATORS = ['or'];
...
 
-  const joinsTree = buildJoinsAndFilter(qb, model, filters);
-
   if (_.has(filters, 'sort')) {
-    const clauses = filters.sort.map(buildSortClauseFromTree(joinsTree));
-    qb.orderBy(reject(isEmpty, clauses));
+    const clauses = filters.sort.map(buildSortClauseFromTree(joinsTree)).filter(c => !isEmpty(c));
+    const orderBy = clauses.map(({ order, alias }) => ({ order, column: alias }));
+    const orderColumns = clauses
+      .filter(({ alias, column }) => alias !== column) // avoid renaming columns of the main table
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/buildQuery.js:27]: I don't understand why you need this ? if the alias equal the column then you are not renaming anything anyway ?

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 3]
```diff
@@ -599,22 +599,31 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
+              delete entry.attributes[key];
+              return;
+            }
             const attr = definition.attributes[key] || {};
             entry.attributes[key] = formatValue(attr, entry.attributes[key]);
           });
         }
 
+        this.on('fetching fetching:collection', (instance, attrs, options) => {
+          if (Array.isArray(instance.models)) {
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:615]: Why are you calling formatEntry before the fetch ?

I think the formatEntry should be only called on the `fetched fetched:collection`

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/strapi-connector-bookshelf/lib/buildQuery.js (hunk 2 above)
Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/buildQuery.js:27]: Not really, if the column is in the main table, than it would be named to "mainTableName.columnName" and would be a duplicated of the column. We would find this column in the query results (it breaks some tests without this line)

File: packages/strapi-connector-bookshelf/lib/mount-models.js (hunk 3 above)
Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/mount-models.js:615]: Yes, it's an error

**Review by alexandrebodin — COMMENTED** [review]
LGTM, just need to update the test to match the test refacto we just merged ;)

File: packages/strapi-plugin-content-manager/tests/api/basic-count-relations.test.e2e.js [hunk 4]
```diff
@@ -1,171 +0,0 @@
-'use strict';
```
Comment (alexandrebodin) [inline packages/strapi-plugin-content-manager/tests/api/basic-count-relations.test.e2e.js:1]: Is it just a file rename ?

Comment (petersg83) [reply packages/strapi-plugin-content-manager/tests/api/basic-count-relations.test.e2e.js:1]: yes :)

**Review by alexandrebodin — APPROVED** [review]
LGTM, good job on the fix & adding tests
