### PR TITLE
Fix Initializer invalid assignment of current prop

### LINKED ISSUE #14446: Typescript plugin generation problem
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.1.2
- Strapi version: 4.3.8
- Database: sqlite
- Operating system: osx 12.5

### Describe the bug

When Typescript Plugin generated with `npm run strapi generate` the generated code contains two error in `src/plugins/plugin-name/admin/src/components/Initializer/index.tsx`

1. `Cannot assign to 'current' because it is a read-only property.ts(2540)`
2. `Cannot invoke an object which is possibly 'null'.ts(2721)`

I found this article about the problem but I can't solve it:
https://claritydev.net/blog/typescript-typing-react-useref-hook/

### Steps to reproduce the behavior

1. generate code with `npm run strapi generate`
2. choose 'Plugin'
3. Type plugin name
4. choose 'TypeScript'
5. Wait for code generation
6. Type 'npm run build'
7. check `src/plugins/plugin-name/admin/src/components/Initializer/index.tsx`

### Expected behavior

Code generated without Typescript error.

### Screenshots

Képernyőfotó 2022-09-19 - 18 05 39

### Code snippets

```
const Initializer: React.FC<InitializerProps> = ({ setPlugin }) => {
  const ref = useRef<(id: string) => void | null>(null);
  ref.current = setPlugin;

  useEffect(() => {
    ref.current(pluginId);
  }, []);

  return null;
};
```

### PR DESCRIPTION
**Pull request by iagocalazans**
### What does it do?

Fixes two TS errors while trying to build into --watch-admin mode right after create a new plugin using `strapi generate`.

### Why is it needed?

On building with TS it throws the following errors: 
- TS2540: Cannot assign to 'current' because it is a read-only property.
- TS2721: Cannot invoke an object which is possibly 'null'.

### How to test it?

Create a new plugin using `strapi generate` for TS re-build all the project and then try to run with `yarn develop --watch-admin`.

### Related issue(s)/PR(s)

Fix #14446

### CODE REVIEW

File: packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx [hunk 1]
```diff
@@ -12,8 +12,7 @@ type InitializerProps = {
 };
 
 const Initializer: React.FC<InitializerProps> = ({ setPlugin }) => {
```
Comment (joshuaellis) [inline packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx:14]:
```suggestion
const Initializer = ({ setPlugin }: InitializerProps) => {
```

Comment (joshuaellis) [reply packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx:14]: This component shouldn't allow `children`.

File: packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx [hunk 2]
```diff
@@ -12,8 +12,7 @@ type InitializerProps = {
...
-  const ref = useRef<(id: string) => void | null>(null);
-  ref.current = setPlugin;
+  const ref = useRef<(id: string) => void | null>(setPlugin);
```
Comment (joshuaellis) [inline packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx:15]:
```suggestion
  const ref = useRef(setPlugin);
```

I think this doesn't need typing because it won't even be `null` now we're setting it here. The type should therefore be inferred correctly.

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Thanks for the contribution! See comments inline 😄

File: packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx (hunk 2 above)
Comment (iagocalazans) [reply packages/generators/generators/lib/files/ts/plugin/admin/src/components/Initializer/index.tsx]: Thats true! 😄

**Review by joshuaellis — APPROVED** [review]
