### PR TITLE
Save dimensions for svg and gif images

### LINKED ISSUE #12823: SVG width and height missing
### SVG width and height missing when uploading

Strapi used to get width and height of uploaded svg, now it doesn't do it anymore.

### Steps to reproduce the behavior

1. Upload an svg
2. Check its dimensions
3. It's empty

### Expected behavior

Strapi should output width and height of svg
### System

- Node.js version: v14.19.0
- NPM version: 8.5.2
- Strapi version: v4.1.3
- Database: Postgre
- Operating system: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

Fix #12823 (`svg` and `gif` dimensions were not displayed)

### Why is it needed?

To display `svg` and `gif` dimensions

### How to test it?

Upload an `svg` and a gif `image` and see the dimensions displayed

### Related issue(s)/PR(s)

#12823

### CODE REVIEW

**Comment by petersg83** [comment]
Wait for QA approval before merging

File: packages/core/upload/server/services/image-manipulation.js [hunk 1]
```diff
@@ -172,7 +185,8 @@ const isSupportedImage = async file => {
 };
 
 module.exports = () => ({
-  isSupportedImage,
+  isOptimizableImage,
```
Comment (gu-stav) [inline packages/core/upload/server/services/image-manipulation.js:188]: I have seen users using this: to not break their use-cases should we keep `isSupportedImage()` and render a deprecation warning until v5?

File: packages/core/upload/server/services/upload.js [hunk 2]
```diff
@@ -162,27 +162,30 @@ module.exports = ({ strapi }) => ({
...
     await getService('provider').upload(fileData);
 
-    if (await isSupportedImage(fileData)) {
-      const thumbnailFile = await generateThumbnail(fileData);
-      if (thumbnailFile) {
-        await getService('provider').upload(thumbnailFile);
-        _.set(fileData, 'formats.thumbnail', thumbnailFile);
-      }
+    if (await isImage(fileData)) {
+      if (await isOptimizableImage(fileData)) {
```
Comment (gu-stav) [inline packages/core/upload/server/services/upload.js:171]: I think you could write it like:

```suggestion
    if (await isImage(fileData) && await isOptimizableImage(fileData)) {
```

if the first check will be falsy, the second won't be executed.

**Review by gu-stav — APPROVED** [review]
