### PR TITLE
fix(admin): restore current password input on profile page

### LINKED ISSUE #18678: Can't save profile page changes
### Required System information

- Node.js version: v18.18.2
- NPM version: 9.8.1
- Strapi version: 4.15.1
- Database: Postgres 12
- Operating system: node:18-alpine
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I try and change the interface mode to `Light Mode` it says `Warning: an error occured`

### Steps to reproduce the behavior

1. Go to 'User Profile'
2. Try to switch to 'Light Mode' from theme settings.
3. No change is observed, and the interface remains in 'Dark Mode'.
4. No error message is displayed in the UI.

### Expected behavior

I expect the interface to switch to light mode when I select the option in the user profile settings.

### Screenshots

image

image

### Code snippets

```
[strapi] [2023-11-06 08:22:18] ValidationError: 5 errors occurred
[strapi] [2023-11-06 08:22:18]     at handleYupError (/opt/node_modules/@strapi/admin/node_modules/@strapi/utils/dist/index.js:408:9)
[strapi] [2023-11-06 08:22:18]     at /opt/node_modules/@strapi/admin/node_modules/@strapi/utils/dist/index.js:418:7
[strapi] [2023-11-06 08:22:18]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[strapi] [2023-11-06 08:22:18]     at async Object.updateMe (/opt/node_modules/@strapi/admin/server/controllers/authenticated-user.js:18:5)
[strapi] [2023-11-06 08:22:18]     at async returnBodyMiddleware (/opt/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
[strapi] [2023-11-06 08:22:18]     at async policiesMiddleware (/opt/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
[strapi] [2023-11-06 08:22:18]     at async /opt/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
[strapi] [2023-11-06 08:22:18]     at async /opt/node_modules/@strapi/strapi/dist/middlewares/body.js:45:9
[strapi] [2023-11-06 08:22:18]     at async /opt/node_modules/@strapi/strapi/dist/middlewares/logger.js:6:5
[strapi] [2023-11-06 08:22:18]     at async /opt/node_modules/@strapi/strapi/dist/middlewares/powered-by.js:9:5
```

### PR DESCRIPTION
**Pull request by remidej**
### What does it do?

Changes on the profile page:

- restores the current password input, as it it needed by the backend to change password
- avoids passing an empty password string if the user didn't touch the password input. This is what prevented users from saving

### Why is it needed?

To allow users to save their changes on the profile page.

### How to test it?

Go to the profile page, make changes (both with and without password changes), then try to save.

### Related issue(s)/PR(s)

fixes #18678

### CODE REVIEW

File: packages/core/admin/admin/src/pages/ProfilePage.tsx [hunk 1]
```diff
@@ -132,6 +132,11 @@ const ProfilePage = () => {
   >(
     async (body) => {
       const { confirmPassword: _confirmPassword, currentTheme, ...dataToSend } = body;
+
+      if (dataToSend.password === '') {
+        delete dataToSend.password;
+      }
```
Comment (joshuaellis) [inline packages/core/admin/admin/src/pages/ProfilePage.tsx:138]: Can you explain why this is necessary as a code comment? Not knowing this is exactly how we got into this situation 😭

**Comment by remidej** [comment]
>So a user needs to pass their current password to change their password?

@joshuaellis yes it is, because it's different from the password recovery feature which works via an email

**Comment by joshuaellis** [comment]
Do you think we could get the types to represent this? i.e if password is present in the object then current password is not optional... just wondering more solutions to tighten this up for the future.

**Review by joshuaellis — APPROVED** [review]
