### PR TITLE
Set operationId

### LINKED ISSUE #12489: [documentation-plugin]: Warnings in OpenAPI specs: missing operationId
### Describe the bug

The documentation plugin generates JSON files that produce warnings in other tools like openapi-generator. This can only be circumvented by disabling the validation step of openapi-generator.
The precise problem described in this issue is, that all operations are missing an `operationId` which leads to the openapi-generator generating default operationIds that don't look nice.

### Expected behavior

The JSON file(s) generated by the documentation plugin should not provoke warnings in other OpenAPI tools. The plugin should include an `operationId` for all operations.

### System

- Node.js version: v16.13.2
- NPM version: 7.19.0
- Strapi version: 4.0.5
- Database: PostgreSQL and SQLite
- Operating system: Windows 8.1 Pro and Docker

### PR DESCRIPTION
**Pull request by DennisHartrampf**
fix #12489

### What does it do?

This solves #12489 by generating operationIds consisting of the HTTP verb and the route.

### How to test it?

Start the example getstarted project and look at the generated file **examples/getstarted/src/extensions/documentation/documentation/2.0.0/full_documentation.json**. All operations should now contain a `operationId` field.

### Related issue(s)/PR(s)

#12489
Should be merged after #12488 to avoid confusion or merge conflicts.

### CODE REVIEW

File: packages/plugins/documentation/server/utils/builders/build-api-endpoint-path.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ const getPaths = ({ routeInfo, attributes, tag }) => {
       responses,
       tags: [_.upperFirst(tag)],
       parameters: [],
-      requestBody: {},
+      operationId: `${methodVerb}${_.upperFirst(routePath)}`,
```
Comment (markkaylor) [inline packages/plugins/documentation/server/utils/builders/build-api-endpoint-path.js:100]: I'm not sure the `upperFirst` is working since the first character in the string is a `/`, but I'm wondering if it is necessary anyway? Couldn't we just leave the route path as it is?

**Review by markkaylor — CHANGES_REQUESTED** [review]

File: packages/plugins/documentation/server/utils/builders/build-api-endpoint-path.js (hunk 1 above)
Comment (DennisHartrampf) [reply packages/plugins/documentation/server/utils/builders/build-api-endpoint-path.js]: You're right, the `upperFirst` doesn't change the `routPath` at all. I removed it.
Thanks for your feedback.

**Review by markkaylor — APPROVED** [review]
Looks good to me! thanks @DennisHartrampf
