### PR TITLE
[V4] Fix sso existing user query

### LINKED ISSUE #11652: v4 SSO Error: Undefined attribute level operator email
### Describe the bug

After lifting and shifting the SSO configuration from `./config/server.js` in v3, to `./config/admin.js` for v4, when the `done` function is called as part of the `createStrategy` factory, I get the following error:

```
[2021-11-22 08:13:09.694] error: Undefined attribute level operator email
Error: Undefined attribute level operator email
    at processAttributeWhere (/beta/node_modules/@strapi/database/lib/query/helpers/where.js:82:13)
    at processWhere (/beta/node_modules/@strapi/database/lib/query/helpers/where.js:176:36)
    at /beta/node_modules/@strapi/database/lib/query/helpers/where.js:104:29
    at Array.map (<anonymous>)
    at Object.processWhere (/beta/node_modules/@strapi/database/lib/query/helpers/where.js:104:18)
    at Object.processState (/beta/node_modules/@strapi/database/lib/query/query-builder.js:234:29)
    at Object.getKnexQuery (/beta/node_modules/@strapi/database/lib/query/query-builder.js:271:12)
    at Object.execute (/beta/node_modules/@strapi/database/lib/query/query-builder.js:352:25)
    at Object.findOne (/beta/node_modules/@strapi/database/lib/entity-manager.js:121:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.findOne (/beta/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
    at async /beta/node_modules/@strapi/admin/ee/server/controllers/authentication/middlewares.js:30:18
```

### Steps to reproduce the behavior

1. Make sure that the auto registration is turned on in settings (I have set the default role to author)
1. In `./config/admin.js` set up your provider (I use `passport-oauth2` and an internal SSO provider)
1. You should see the login option in the admin panel
1. Click on the SSO option and login via your provider
1. When the verify function gets called, you'll see the error

### Expected behavior

I expect that I would see login success

### System

- Node.js version: 16.5.0
- NPM version: 7.20.3
- Strapi version: 4.0.0-beta.14
- Database: SQLite
- Operating system: MacOS

Also, I notice that in the docs it has the following structure for `./config/admin`:

```js
// ./config/admin.js
module.exports = ({ env }) => ({
    // ...
    admin: {
        // ...
        auth: {
```

This structure actually makes it so the SSO provider doesn't show in the admin panel. I was able to get it to at least show up by removing the outer `admin` object from this file

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

It adds a findUserByEmail method in the admin user service & use it from the admin authentication middleware

### Why is it needed?

The admin authentication middleware was using the old findOne syntax to check for an existing user (by mail). This caused the app to crash when trying to log in using SSO.

### Related issue(s)/PR(s)

Should fix #11652

### CODE REVIEW

File: packages/core/admin/server/services/user.js [hunk 1]
```diff
@@ -180,6 +180,19 @@ const findOne = async (id, populate = ['roles']) => {
   return strapi.entityService.findOne('admin::user', id, { populate });
 };
 
+/**
+ * Find one user by its email
+ * @param {string} id  email
+ * @param {string || string[] || object} populate
+ * @returns
+ */
+const findOneByEmail = async (email, populate = []) => {
```
Comment (alexandrebodin) [inline packages/core/admin/server/services/user.js:189]: shouldn't this call the findOne function defined above ? Do we need to populate the roles or something like that ?

Comment (Convly) [reply packages/core/admin/server/services/user.js:189]: The findOne above uses the `entityService.findOne` which can only find by ID, which isn't what we want here

Comment (Convly) [reply packages/core/admin/server/services/user.js:189]: The findOne above uses the `entityService.findOne` method which requires an ID (that we don't have)

Comment (alexandrebodin) [reply packages/core/admin/server/services/user.js:189]: Should you be using the entityService at least then ?

Comment (Convly) [reply packages/core/admin/server/services/user.js:189]: I would then have to use smth like `first(await findMany())`. Since we're using s`trapi.query() `in other methods of the service, I assumed it was cleaner to use it here too, wdyt?

Comment (alexandrebodin) [reply packages/core/admin/server/services/user.js:189]: I think it's alright for now 👍

**Review by alexandrebodin — APPROVED** [review]
