### PR TITLE
Escape MongoDB password 

### LINKED ISSUE #2441: "Special" characters in Mongo passwords are not being escaped
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0@alpha.16
- **Database**: CosmosDB (mongo)
- **Operating system**:  WSL

**What is the current behavior?**
```
strapi start
[2018-12-06T15:36:08.487Z] debug ⛔️ Server wasn't able to start properly.
[2018-12-06T15:36:08.489Z] error Unescaped slash in userinfo section
```

**Steps to reproduce the problem**
Use a mongo password that includes special characters, such as / or =

**What is the expected behavior?**
Special characters should be escaped or URL encoded

**Suggested solutions**
Editing [strapi-hook-mongoose #85](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js#L85) to URL encode the password string, appears to resolve the issue.

```
await instance.connect(uri || `mongodb${isSrv ? '+srv' : ''}://${username}:${encodeURIComponent(password)}@${host}${ !isSrv ? ':' + port : '' }/`, connectOptions); ```

### PR DESCRIPTION
**Pull request by JelmerV-WFC**
#### Description of what you did:
uriEncode MongoDB password if using srv uri (fix #2441)
 
#### My PR is a:

- [ ] 💥 Breaking change
- [X] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [x] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [X] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

File: packages/strapi-hook-mongoose/lib/index.js [hunk 1]
```diff
@@ -93,7 +93,7 @@ module.exports = function(strapi) {
            * https://github.com/Automattic/mongoose/issues/6881 */
           await instance.connect(
             uri ||
-              `mongodb${isSrv ? '+srv' : ''}://${username}:${password}@${host}${
+              `mongodb${isSrv ? '+srv' : ''}://${username}:${isSrv ? encodeURIComponent(password) : password}@${host}${
```
Comment (alexandrebodin) [inline packages/strapi-hook-mongoose/lib/index.js]: You can encode the password when not using srv too. this issue exists in both cases right now
