### PR TITLE
Fix file extensions not always detected with cloudinary

### LINKED ISSUE #8462: Files uploaded to cloudinary lose their extension
Hi! 

I am using strapi as CMS for gatsby and I find both really cool. Thank you for making available such awesome technologies.

### Describe the bug

I stumbled into this issue though, and I don't know if I did something wrong or it's something already known:
I am uploading svg's as images for some posts, and 
1. They don't show as preview in strapi (i found this [https://github.com/strapi/strapi/issues/5788](https://github.com/strapi/strapi/issues/5788) but I don't really see the solution)
2. They don't get fetched correctly from gatsby (they get fetched without the .svg extension and they are not recognized as images)

### Steps to reproduce the behavior

1. Upload an svg in the media library in strapi 
2. Check the media library => no preview
3. Query the image with graphql in gatsby (using publicURL and not gatsbyImageSharp) => the file will arrive in the `/static` folder of gatsby, but without an extension => is not recognized as image (about that I am sure, because I manually changed the extension of the file in the static folder and I concatenated the publicURL with .svg in the img element I am trying to access it, and then it worked)

### Expected behavior

1. I see the preview images correctly in strapi
2. I receive the images WITH the svg extension from strapi in gatsby 

### Screenshots

strapi-media-library
no-svg-ext
)

### Code snippets
Code that doesn't import the image correctly (cardImg is the queried variable name for my image): 
```
<CardImage
          src={cardImg.publicURL}
          alt={`${cardTitle} word cloud`}
        />
```
Result: 
card-no-svg-ext

If I add the svg extension manually, like so:
manually-added-svg-ext
and use the following code: 
```
<CardImage 
        src={`${cardImg.publicURL}.svg`} 
        alt={`${cardTitle} word cloud`} 
/>
```
then it works:
card-manually-added-svg-ext

### System

- Node.js version: v12.18.3
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: mongoDB (Atlas)
- Operating system: Windows10

### PR DESCRIPTION
**Pull request by petersg83**
fix #8462

### CODE REVIEW

File: packages/strapi-provider-upload-cloudinary/lib/index.js [hunk 1]
```diff
@@ -16,8 +16,17 @@ module.exports = {
     return {
       upload(file, customConfig = {}) {
         return new Promise((resolve, reject) => {
+          const config = {
+            resource_type: 'auto',
+            public_id: file.hash,
+          };
+
+          if (file.ext) {
+            config.format = file.ext.replace(/^\./, ''); // remove leading dot
```
Comment (alexandrebodin) [inline packages/strapi-provider-upload-cloudinary/lib/index.js:25]: Looks like this is documented to be a field to specify conversion on cloudinary. I feel like this is going to do some processing we might avoid in most cases 🤔

File: packages/strapi-provider-upload-cloudinary/lib/index.js [hunk 2]
```diff
@@ -16,8 +16,14 @@ module.exports = {
     return {
       upload(file, customConfig = {}) {
         return new Promise((resolve, reject) => {
+          const config = {
+            resource_type: 'auto',
+            public_id: file.hash,
+            filename: `${file.hash}${file.ext}`,
```
Comment (alexandrebodin) [inline packages/strapi-provider-upload-cloudinary/lib/index.js:22]: what happens in case there is no extension on the file ? looks like we are gonna get sth like 'fileundefined'

Comment (petersg83) [reply packages/strapi-provider-upload-cloudinary/lib/index.js:22]: That's true, I'll change that

**Review by alexandrebodin — APPROVED** [review]
