### PR TITLE
Fix relation search

### LINKED ISSUE #9137: Request limit of a relation is fixed to 20 in Strapi Admin
### Describe the bug

I can't display more than 20 items of a relation in Strapi Admin.
The request contains  __limit=20_ and I want to know how to remove it.

### Steps to reproduce the behavior

1. Create a Collection Type Agences
2. Add more than 20 agences
2. Create a component with that collection inside
3. Create another Collection Type with a Dynamic Zone containing that component
4. Create an entry and try to add all available agences
5. See the dropdown is limited to 20

### Expected behavior

Display all the data in the relation's dropdown (more than 20).

### System

- Strapi Version: 3.4.2
- Operating System: Debian
- Database: MySQL
- Node Version: 12.18.2
- NPM Version: 6.14.6

### Additional context
Hi,

I have trouble to display more than 20 items of a relation in Strapi Admin.
We were on version 3.2.5 while we discovered what I will explain, and we’ve migrate to the latest version but it doesn’t change.
I guess there is something I missed so i need help to fix it.

So when I move to the content manager and add some Agences, I’m limited to 20 while I have more agences stored in database
This is because the request limit is fixed to 20

`http://localhost:1337/content-manager/relations/application::page.page/agences?_limit=20&_start=0&_component=pages.carte-interactive`

link

**I want to know how to change the limit value or remove it from the request.**

Thanks for your help 

[Link to my Strapi Forum post](https://forum.strapi.io/t/request-limit-is-fixed-to-20-in-strapi-admin/2169)

### PR DESCRIPTION
**Pull request by petersg83**
fix #9137

### CODE REVIEW

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Can you update the open api spec of the content manager :)

File: packages/strapi-plugin-content-manager/controllers/relations.js [hunk 1]
```diff
@@ -31,6 +32,11 @@ module.exports = {
       return ctx.notFound('target.notFound');
     }
 
+    if (idsToOmit && Array.isArray(idsToOmit)) {
+      query._where = query._where || {};
+      query._where.id_nin = concat(query._where.id_nin || [], idsToOmit.map(String));
```
Comment (alexandrebodin) [inline packages/strapi-plugin-content-manager/controllers/relations.js:37]: do we really need th cast to string here ?

**Review by alexandrebodin — COMMENTED** [review]
LGTM, an open question left

File: packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js [hunk 2]
```diff
@@ -79,14 +79,22 @@ function SelectWrapper({
...
+
+      const params = { _limit: state._limit, ...defaultParams };
 
       if (state._contains) {
         params[containsKey] = state._contains;
       }
 
       try {
-        const data = await request(endPoint, { method: 'GET', params, signal });
+        const idsToOmit = value ? value.map(val => val.id) : [];
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js:91]: This won't work in case of oneToOne relations, can you make the following update:

```
 const idsToOmit = useMemo(() => {
    if (!value) {
      return [];
    }

    if (isSingle) {
      return [value];
    }

    return value.map(val => val.id);
  }, [isSingle, value]);
```

File: packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js [hunk 3]
```diff
@@ -108,30 +116,31 @@ function SelectWrapper({
...
-      mainField.name,
+      isFieldAllowed,
       state._limit,
-      state._start,
       state._contains,
+      defaultParams,
+      containsKey,
+      endPoint,
+      mainField.name,
+      value,
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js:128]: With the comment from above you'll need to change this to `idsToOmit`

File: packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js [hunk 4]
```diff
@@ -145,8 +154,25 @@ function SelectWrapper({
...
   };
 
-  const onMenuScrollToBottom = () => {
-    setState(prevState => ({ ...prevState, _start: prevState._start + 20 }));
+  const handleMenuScrollToBottom = () => {
+    setState(prevState => ({ ...prevState, _limit: prevState._limit + 20 }));
+  };
+
+  const handleMenuClose = () => {
+    setState(prevState => ({ ...prevState, _contains: '' }));
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js:162]: I think that we might need to reset the pagination to `0` since the idsToOmit might change I think that we should return to the initial state. What do you think?

File: packages/strapi-plugin-content-manager/controllers/relations.js (hunk 1 above)
Comment (petersg83) [reply packages/strapi-plugin-content-manager/controllers/relations.js:37]: not anymore

**Review by soupette — CHANGES_REQUESTED** [review]

**Review by soupette — APPROVED** [review]
LGTM for the front-end part.

Nice job!

**Review by alexandrebodin — APPROVED** [review]
LGTM ! 💯  great improvement
