### PR TITLE
Fix custom mutation returning null and not executing policies

### LINKED ISSUE #1887: The policies are not executed in my GraphQL custom schema
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: mongo:4.0.1
- **Operating system**: OSX 10.13.6

**What is the current behavior?**
The policies are not executed in my graphql custom schema

**Steps to reproduce the problem**
This is my schema.graphql into api/contacts/config/
```js
module.exports = {
  definition: `
    type Contacts {
      count: Int!
      rows: [Contact]!
    }
  `,
  query: `
    _contacts(sort: String, limit: Int, start: Int, where: JSON): Contacts
  `,
  resolver: {
    Query: {
      _contacts: {
        description: `Contacts`,
        policy: ['plugins.users-permissions.isAuthenticated'],  // <-------
        resolver: async (obj, options, ctx) => {
          let params = {
            _limit: options.limit ? options.limit : 10,
            _sort: options.sort ? options.sort : '',
            _start: options.start ? options.start : 0
          }

          if ( options.where ) {
            params = Object.assign(params, { ...options.where })
          }

          const rows = await strapi.services.contact.fetchAll(params);
          const count = await strapi.services.contact.count(params);
          return { count, rows };
        }
      }
    }
  }
};
```

**What is the expected behavior?**
The policy executed

**Suggested solutions**

### PR DESCRIPTION
**Pull request by JelmerV-WFC**
**Description:**

**The fix address the following issues:**

Custom mutation resolvers defined as string will return null
Policies defined for custom resolvers won't execute

**Steps to reproduce:**

1. In schema.graphql add a custom resolver:
```
resolver: {
    Mutation: {
      upsertPost: {
        policies: ['global.isLoggedIn'],
        resolver: 'Post.createOrUpdate'
      }
    }
  }
```
2. Add the controller action returning a sample data according to your schema
3. `strapi generate:policy isLoggedIn`
4. Execute the mutation

**My PR is a:**

- [ ] 💥 Breaking change
- [X] 🐛 Bug fix #1887 #2766
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

**Main update on the:**

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

**Manual testing done on the following databases:**

- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [x] Postgres
- [x] SQLite

### CODE REVIEW

**Comment by WeFlyCheap** [comment]
@alexandrebodin like this?

**Comment by derrickmehaffy** [comment]
Failing Travis tests:

```
 FAIL   Setup  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js (6.659s)
  Test Graphql API End to End
    Test CRUD
      ✕ Create Post { name: 'post 1', bigint: 1316130638171, nullable: 'value' } (24ms)
      ✕ Create Post { name: 'post 2', bigint: 1416130639261, nullable: null } (8ms)
      ✕ List posts (7ms)
      ✕ List posts with limit (6ms)
      ✕ List posts with sort (14ms)
      ✕ List posts with start (7ms)
      ✕ List posts with where clause { name: 'post 1', bigint: 1316130638171 } (7ms)
      ✕ List posts with where clause { name_eq: 'post 1', bigint_eq: 1316130638171 } (6ms)
      ✕ List posts with where clause { name_ne: 'post 1', bigint_ne: 1316130638171 } (7ms)
      ✕ List posts with where clause { name_contains: 'Post' } (6ms)
      ✕ List posts with where clause { name_contains: 'Post 1' } (7ms)
      ✕ List posts with where clause { name_containss: 'post' } (7ms)
      ✕ List posts with where clause { name_ncontainss: 'post 1' } (6ms)
      ✕ List posts with where clause { name_in: [ 'post 1', 'post 2', 'post 3', [length]: 3 ] } (7ms)
      ✕ List posts with where clause { name_nin: [ 'post 2', [length]: 1 ] } (7ms)
      ✕ List posts with where clause { nullable_null: true } (7ms)
      ✕ List posts with where clause { nullable_null: false } (7ms)
      ✕ Get One Post (1ms)
      ✕ Update Post
      ✓ Delete Posts (1ms)
```

**Comment by WeFlyCheap** [comment]
> Failing Travis tests:
> 
> ```
>  FAIL   Setup  packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js (6.659s)
>   Test Graphql API End to End
>     Test CRUD
>       ✕ Create Post { name: 'post 1', bigint: 1316130638171, nullable: 'value' } (24ms)
>       ✕ Create Post { name: 'post 2', bigint: 1416130639261, nullable: null } (8ms)
>       ✕ List posts (7ms)
>       ✕ List posts with limit (6ms)
>       ✕ List posts with sort (14ms)
>       ✕ List posts with start (7ms)
>       ✕ List posts with where clause { name: 'post 1', bigint: 1316130638171 } (7ms)
>       ✕ List posts with where clause { name_eq: 'post 1', bigint_eq: 1316130638171 } (6ms)
>       ✕ List posts with where clause { name_ne: 'post 1', bigint_ne: 1316130638171 } (7ms)
>       ✕ List posts with where clause { name_contains: 'Post' } (6ms)
>       ✕ List posts with where clause { name_contains: 'Post 1' } (7ms)
>       ✕ List posts with where clause { name_containss: 'post' } (7ms)
>       ✕ List posts with where clause { name_ncontainss: 'post 1' } (6ms)
>       ✕ List posts with where clause { name_in: [ 'post 1', 'post 2', 'post 3', [length]: 3 ] } (7ms)
>       ✕ List posts with where clause { name_nin: [ 'post 2', [length]: 1 ] } (7ms)
>       ✕ List posts with where clause { nullable_null: true } (7ms)
>       ✕ List posts with where clause { nullable_null: false } (7ms)
>       ✕ Get One Post (1ms)
>       ✕ Update Post
>       ✓ Delete Posts (1ms)
> ```

That's weird. Will check.

**Comment by WeFlyCheap** [comment]
@derrickmehaffy locally this test is passing 100% on all the e2e test suites. The previous commit is also passing and there is no change in data since then.
image 
image

**Comment by WeFlyCheap** [comment]
@derrickmehaffy now it's passing on mysql and failing on SQLite with the same code. Weird stuff. Any idea? Can it be related to: https://www.traviscistatus.com?

**Comment by derrickmehaffy** [comment]
@WeFlyCheap that is possible yeah:

```
Error while installing dependencies:
(node:7316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error An unexpected error occurred: "https://registry.yarnpkg.com/lodash: ETIMEDOUT".
{ Error: Command failed: /bin/sh -c node /home/travis/build/strapi/strapi/packages/strapi/bin/strapi.js new testApp --dbclient=sqlite --dbfile=./tmp/data.db
    at makeError (/home/travis/build/strapi/strapi/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/travis/build/strapi/strapi/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   '/bin/sh -c node /home/travis/build/strapi/strapi/packages/strapi/bin/strapi.js new testApp --dbclient=sqlite --dbfile=./tmp/data.db',
  timedOut: false,
  killed: false }
error Command failed with exit code 1.
The command "yarn run -s test:generate-app -- $DB_STRING" exited with 1.
```

**Comment by WeFlyCheap** [comment]
> @WeFlyCheap that is possible yeah:
> 
> ```
> Error while installing dependencies:
> (node:7316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> error An unexpected error occurred: "https://registry.yarnpkg.com/lodash: ETIMEDOUT".
> { Error: Command failed: /bin/sh -c node /home/travis/build/strapi/strapi/packages/strapi/bin/strapi.js new testApp --dbclient=sqlite --dbfile=./tmp/data.db
>     at makeError (/home/travis/build/strapi/strapi/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/home/travis/build/strapi/strapi/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 1,
>   stdout: null,
>   stderr: null,
>   failed: true,
>   signal: null,
>   cmd:
>    '/bin/sh -c node /home/travis/build/strapi/strapi/packages/strapi/bin/strapi.js new testApp --dbclient=sqlite --dbfile=./tmp/data.db',
>   timedOut: false,
>   killed: false }
> error Command failed with exit code 1.
> The command "yarn run -s test:generate-app -- $DB_STRING" exited with 1.
> ```

Okay, what to do now? Wait till the issues are fixed at the side of Travis?

**Comment by derrickmehaffy** [comment]
Yup for now unless @alexandrebodin wants to approve it as is

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ module.exports = {
           : {};
 
         // Retrieve the controller's action to be executed.
-        const [name, action] = handler.split('.');
+        [name, action] = handler.split('.');
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: Can you please avoid mutating the name and action variables.

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 2]
```diff
@@ -129,7 +129,7 @@ module.exports = {
     // Force policies of another action on a custom resolver.
     if (_.isString(resolverOf) && !_.isEmpty(resolverOf)) {
       // Retrieve the controller's action to be executed.
-      const [name, action] = resolverOf.split('.');
+      [name, action] = resolverOf.split('.');
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: same here

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 3]
```diff
@@ -195,11 +195,15 @@ module.exports = {
 
       // Resolver can be a function. Be also a native resolver or a controller's action.
       if (_.isFunction(resolver)) {
+        name = _.toLower(name);
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: you can call this normalizedName for ex so we do not mutate the variable

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 4]
```diff
@@ -195,11 +195,15 @@ module.exports = {
...
+
         context.params = Query.convertToParams(
           options.input.where || {},
-          (plugin ? strapi.plugins[plugin].models[name] : strapi.models[name])
-            .primaryKey
+          action &&
+            (plugin ? strapi.plugins[plugin].models[name] : strapi.models[name])
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: to hard to read. can you create a variable before the function call please

File: packages/strapi-plugin-graphql/services/Mutation.js (hunk 1 above)
Comment (WeFlyCheap) [reply packages/strapi-plugin-graphql/services/Mutation.js]: But in case of a custom mutation the correct 'name' and 'action' are not available until this point I think. And I need that 'name' and 'action' outside that statement. What's the best way to achieve that?

Comment (alexandrebodin) [reply packages/strapi-plugin-graphql/services/Mutation.js]: I would split the code in smaller functions so you can just have `if (action) createActionMutation` else `createCustomMutation`

Comment (WeFlyCheap) [reply packages/strapi-plugin-graphql/services/Mutation.js]: At what place inside the Mutation.js do I need to create this? I don't have it clear for myself how you want to do it. Can you maybe give me an example or something?

Comment (alexandrebodin) [reply packages/strapi-plugin-graphql/services/Mutation.js]: I basically just want you to do `const [controllerName, ctrollerAction] = handler.split('.')` :)

Comment (WeFlyCheap) [reply packages/strapi-plugin-graphql/services/Mutation.js]: I found another way that works. Will push in a minute. Let me know what you think :)

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 5]
```diff
@@ -23,7 +23,7 @@ module.exports = {
     // Extract custom resolver or type description.
     const { resolver: handler = {} } = _schema;
 
-    const queryName = `${action}${_.capitalize(name)}`;
+    const queryName = action ? `${action}${_.capitalize(name)}` : `${name}`;
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: I think you don't need to do this check anymore as you always pass an action :)

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 6]
```diff
@@ -195,27 +195,37 @@ module.exports = {
 
       // Resolver can be a function. Be also a native resolver or a controller's action.
       if (_.isFunction(resolver)) {
+        const normalizedName = _.toLower(name);
+        const primaryKey =
+          action &&
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: same here :)

Just for me, can you just do a simple if statement for this to avoid ternary plus property acces on the same line :) 
```js
let primaryKey;
if (plugin) {
  primaryKey = ...
} else {
   primaryKey = 
}
```

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 7]
```diff
@@ -195,27 +195,39 @@ module.exports = {
...
+              [pluralize.singular(normalizedName)]: ctx.body,
             };
           }
 
           const body = values && values.toJSON ? values.toJSON() : values;
 
-          return {
-            [pluralize.singular(name)]: body,
-          };
+          return action
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: action will always be set here I think ? this might be a problem for you no ?

Comment (JelmerV-WFC) [reply packages/strapi-plugin-graphql/services/Mutation.js]: You're right, missed that. I don't think it will be an issue.

**Comment by alexandrebodin** [comment]
Thank you for this, I'll be trying it out before this week so we can get it merged soon

**Comment by JelmerV-WFC** [comment]
> Thank you for this, I'll be trying it out before this week so we can get it merged soon

No problem at all! It's great to contribute on the strapi project itself, it gives me a better understanding of how things work in general.

File: packages/strapi-plugin-graphql/services/Schema.js [hunk 8]
```diff
@@ -205,14 +205,18 @@ const schemaBuilder = {
...
-            case 'Mutation':
+            case 'Mutation': {
               // TODO: Verify this...
+              const [name, action] = acc[type][resolver].split('.');
+
               acc[type][resolver] = Mutation.composeMutationResolver(
                 strapi.plugins.graphql.config._schema.graphql,
                 plugin,
-                resolver
+                name,
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Schema.js]: Make sure to send the name lowercased or it will not find the controller if the user wrote it with an uppercase

Comment (JelmerV-WFC) [reply packages/strapi-plugin-graphql/services/Schema.js]: Give me one sec ;-)

**Comment by alexandrebodin** [comment]
Ok I'v tried using it but it is not working. there are quite a few issues it is using options.input which just doesn't exist and the return value is put un a sub key with the name which forces. 

I think we need to rethink this tbh. 

Have you been able to make this work ?

**Comment by JelmerV-WFC** [comment]
> Ok I'v tried using it but it is not working. there are quite a few issues it is using options.input which just doesn't exist and the return value is put un a sub key with the name which forces.
> 
> I think we need to rethink this tbh.
> 
> Have you been able to make this work ?

It looks like it works at my end. What do you mean by options.input doesn't exist? It contains my data when I try. For example when I run the following GraphQL mutation:

```
mutation {
  updateOrCreateDeal(
    input: { where: { id: "5d3eaebcbef468692003c51f" }, data: {} }
  ) {
    deal {
     	title,
      _id
    }
  }
}
```

options.input contains:

```
[Object: null prototype] {
     where: [Object: null prototype] { id: '5d3eaebcbef468692003c51f' },
     data: [Object: null prototype] {} }
```

Can you tell me what it is that is not working at your side?

**Comment by alexandrebodin** [comment]
Ok now what if I want a mutation without an input ? and I want to return a custom Type without it being in a sub field ? example:

```js
module.exports = {
  definition: `
    type SomeType {
      value: String
    }
  `,
  mutation: `
    myCustomMutation: SomeType
  `,
  resolver: {
    Mutation: {
      myCustomMutation: {
        resolver: 'SomeController.customAction',
      },
    },
  },
};

```

The current code breaks with errors for this

**Comment by JelmerV-WFC** [comment]
> ```js
> myCustomMutation
> ```

Fair point. Going to rethink it. Thanks for this headsup!

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 9]
```diff
@@ -195,27 +195,49 @@ module.exports = {
...
+            primaryKey
+          );
+        } else {
+          context.params = {};
+        }
+
+        if (options.input && options.input.data) {
+          context.request.body = options.input.data || {};
+        } else {
+          context.request.body = {};
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/Mutation.js]: shouldn't we just pass all the options as body in case the user declare a mutation with custom arguments ?

Comment (JelmerV-WFC) [reply packages/strapi-plugin-graphql/services/Mutation.js]: Do you mean
`context.request.body = options.input.data;`
Instead of
`context.request.body = options.input.data || {};`
?

Comment (alexandrebodin) [reply packages/strapi-plugin-graphql/services/Mutation.js]: nop I mean 
```js
if (options.input && options.input.data) {
     context.request.body = options.input.data || {};
} else {
     context.request.body = options; // here you can pass the grahpql arguments as body to the controller
}
```

Comment (JelmerV-WFC) [reply packages/strapi-plugin-graphql/services/Mutation.js]: Ah yeah. Will do that.

File: packages/strapi-plugin-graphql/services/Mutation.js [hunk 10]
```diff
@@ -195,27 +195,49 @@ module.exports = {
...
-        );
-        context.request.body = options.input.data || {};
+        const normalizedName = _.toLower(name);
+
+        let primaryKey;
+
+        if (plugin) {
+          primaryKey = strapi.plugins[plugin].models[normalizedName].primaryKey;
+        } else {
+          primaryKey = strapi.models[normalizedName].primaryKey;
```
Comment (ndazaiy) [inline packages/strapi-plugin-graphql/services/Mutation.js]: This will cause an error when the controller doesn't have a model with its name.

File: packages/strapi-plugin-graphql/services/Schema.js [hunk 11]
```diff
@@ -205,14 +205,19 @@ const schemaBuilder = {
             : {};
 
           switch (type) {
-            case 'Mutation':
+            case 'Mutation': {
               // TODO: Verify this...
+              const [name, action] = acc[type][resolver].split('.');
```
Comment (donmasakayan) [inline packages/strapi-plugin-graphql/services/Schema.js]: While this works for Mutation definitions such as
```
Mutation: {
    customMutation: {
        resolver: "Post.customMutation"
    }
}
```

This breaks when resolvers are objects (i.e. referencing an action within a plugin) such as...
```
Mutation: {
    customMutation: {
        resolver: {
            plugin: "my-plugin"
            handler: "Post.customMutation"
        }
    }
}
```

Admittedly, I'm not sure if it originally worked to begin with.
