### PR TITLE
Fix incorrect openapi type for datetime, date and password

### LINKED ISSUE #7149: Incorrect datetime type generated in the Documentation plugin
**Description**
When generating swagger documentation using strapi-plugin-documentation, we see that for data type "Datetime" swagger documentation generated is also "datetime". This instead according to [OpenAPI](https://swagger.io/specification/#oas-document) standards should be "date-time"

**Steps to reproduce the behavior**

1. Using content-type buider create new data type with a datetime field
2. Build strapi with  strapi-plugin-documentation configured

**Expected behavior**
Should generate swagger documentation with `date-time`

**Screenshots**
image
image

**System**

- Strapi version: 3.0.0
- strapi-plugin-documentation version: 3.0.0

### PR DESCRIPTION
**Pull request by henrych4**
Signed-off-by: henrych4 <singyinhenry@gmail.com>

#### Description of what you did:
Reopen #7623 and update with respect to the comments to fix #7149

### CODE REVIEW

File: packages/strapi-plugin-documentation/services/Documentation.js [hunk 1]
```diff
@@ -619,6 +619,18 @@ module.exports = {
...
+            type: 'string',
+            format: this.getFormat(type),
+            description,
+            default: defaultValue,
+            minimum,
+            maxmimun,
+            maxLength,
+            minLength,
+            enum: enumeration,
+          };
```
Comment (petersg83) [inline packages/strapi-plugin-documentation/services/Documentation.js:633]: I would suggest to just modify the `else` block.
Something like:
```
        } else {
          acc.properties[current] = {
            type,
            format: getFormat(attribute.type),
            description,
            default: defaultValue,
            minimum,
            maxmimun,
            maxLength,
            minLength,
            enum: enumeration,
          };
        }
```

(In your code the value of `type` is `'string'` for date and password, so it would not work for those two. The right variable to use would be `attribute.type`.)

(I think we need to modify the function `getType` so it handles `datetime`)

File: packages/strapi-plugin-documentation/services/Documentation.js [hunk 2]
```diff
@@ -1473,6 +1483,20 @@ module.exports = {
...
+   * @returns {String}
+   */
+  getFormat: type => {
+    switch (type) {
+      case 'datetime':
+        return 'date-time';
+      default:
+        return type;
+    }
+  },
```
Comment (petersg83) [inline packages/strapi-plugin-documentation/services/Documentation.js:1498]: Can you make the handling of `date` and `password` explicit please? And make the default value `undefined` as the function would be wrong for other types.

Something like:
```
  getFormat: type => {
    switch (type) {
      case 'date':
        return 'date';
      case 'datetime':
        return 'date-time';
      case 'password':
        return 'password';
      default:
        return undefined;
    }
  },
```

**Review by petersg83 — CHANGES_REQUESTED** [review]
Thanks for you contribution ! I have some remarks :)

File: packages/strapi-plugin-documentation/services/Documentation.js (hunk 1 above)
Comment (henrych4) [reply packages/strapi-plugin-documentation/services/Documentation.js]: Updated. Thanks for the comment, the code looks much better now.

File: packages/strapi-plugin-documentation/services/Documentation.js [hunk 3]
```diff
@@ -1451,11 +1452,9 @@ module.exports = {
       case 'string':
       case 'byte':
       case 'binary':
-      case 'password':
       case 'email':
       case 'text':
       case 'enumeration':
-      case 'date':
```
Comment (petersg83) [inline packages/strapi-plugin-documentation/services/Documentation.js:1458]: No need to remove password and date. Just to add `datetime` here :)

**Review by petersg83 — CHANGES_REQUESTED** [review]

File: packages/strapi-plugin-documentation/services/Documentation.js (hunk 3 above)
Comment (petersg83) [reply packages/strapi-plugin-documentation/services/Documentation.js]: @henrych4 You forgot to add `datetime` :)

**Review by petersg83 — CHANGES_REQUESTED** [review]
Thank you ! I tested it, it works well :)
While testing I saw that the type `time` was not handled neither in `getType`. Can you just add `case 'time:'` at the same place as `case 'datetime'` please ? :) No need to update `getFormat` as doesn't this it has an official format.

**Review by petersg83 — APPROVED** [review]
Thank you, nice addition ! :)
