### PR TITLE
fix(documentation): use correct localization schema

### LINKED ISSUE #18577: Documentation plugin generates incorrect localization field
### Required System information

- Node.js version: v18.18.2
- NPM version: npm 9.4.0
- Strapi version: 4.15.0
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: typescript

### Describe the bug

The `full_documentation.json` file contains the localizations field on the responses.
However, json doesn't match the actual api response.

```jsonc
          "localizations": {
            "type": "object",
            "properties": {
              "data": {
                "type": "array",
                "items": {
                  // This links to the Article type below, which is incorrect.
                  // Instead, the api returns a property `attributes`, which then contains the linked Article
                  "$ref": "#/components/schemas/Article"
                }
              }
            }
          },
...
      "Article": {
        "type": "object",
        "required": [
          "slug",
          "header_image",
          "created"
        ],
        "properties": {
          "slug": {
            "type": "string"
          },
          // other properties
          ...
      }
```
### Steps to reproduce the behavior

I can provide a MCVE if required, but I think the issue is clear from the description above.

1. `npm run develop`
2. json files are generated automatically

### Expected behavior

json file should match the api response, since otherwise the types generated via [openapi-typescript](https://www.npmjs.com/package/openapi-typescript) are incorrect.

### Screenshots

Postman response:

CleanShot 2023-10-26 at 00 30 20@2x

### Other context

1. This started after we upgraded from Strapi 4.6.0 to Strapi 4.14.5/4.15.0, ie everything worked perfectly before.
2. In the old version, the `localizations` field linked to `ArticleListResponseDataItemLocalized`, which seems to now be called `ArticleResponseDataObjectLocalized`

### PR DESCRIPTION
**Pull request by ciriousjoker**
### What does it do?

The generated `full_documentation.json` contains an error in the `localizations` property. The `localizations` property only shows up when [strapi-plugin-populate-deep](https://www.npmjs.com/package/strapi-plugin-populate-deep) is also installed, but the issue is in the documentation plugin, not [strapi-plugin-populate-deep](https://www.npmjs.com/package/strapi-plugin-populate-deep).

The edited line is only hit once in the debugger and patching it seems to do exactly what I want and nothing else. It's used in production at our company.

### Why is it needed?

Without this, the localization field in the schema doesn't match the actual api response. The api response contains an id & attributes, which then contain the actual data. The schema makes it seem like the localization field already contains the data.

Api response via Postman:
CleanShot 2023-10-26 at 07 54 51@2x

### How to test it?

1. Clone this: https://github.com/ciriousjoker/demo_strapi_localization_field
2. Check out first, second and third commit in order
3. Notice that by switching to the forked version that matches this PR, the schema now matches the api response

### Related issue(s)/PR(s)

- Fixes #18577
- This pr seems to be related, although I can't figure out if it actually caused this issue: https://github.com/strapi/strapi/pull/13458

### Context

We had a pretty scuffed `package-lock.json` at some point, which for whatever reason produced a correct `full_documentation.json` schema. However, I couldn't reproduce this correct behavior when deleting the `package-lock.json` & the `node_modules` folder. In the working `full_documentation.json`, it used this name: `ArticleListResponseDataItemLocalized`, so when I had the option of choosing the suffix, I chose the one that most closely resembled the (I assume) original, correct behavior.

### CODE REVIEW

**Comment by Boegie19** [comment]
Maby a stupit question but should we not check if i18n plugin is installed and enabled before we add "ListResponseDataItemLocalized" or maby make this documentation come from the i18n package.

**Comment by Boegie19** [comment]
Also @ciriousjoker Mind adding fixes: #18577  to your initial message so that it properly links the issue and your PR.

**Comment by ciriousjoker** [comment]
Do you mean adding it to the commit message or to the PR message?
I added it to the PR message now. Ping me if that's not enough.

**Comment by ciriousjoker** [comment]
Should I bother to keep this in sync with the main branch or can I do it once right before it's (hopefully) being merged?

**Comment by Boegie19** [comment]
Idk don't work for strapi soo.

File: packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js [hunk 1]
```diff
@@ -202,7 +202,7 @@ const cleanSchemaAttributes = (
             properties: {
               data: {
                 type: 'array',
-                items: componentSchemaRefName.length ? { $ref: componentSchemaRefName } : {},
+                items: componentSchemaRefName.length ? { $ref: componentSchemaRefName + "ListResponseDataItemLocalized"} : {},
```
Comment (markkaylor) [inline packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js:205]: Bit of a nitpick but I'd prefer to be consistent and use string interpolation here instead of concatenation.

```suggestion
                items: componentSchemaRefName.length ? { $ref: `${componentSchemaRefName}ListResponseDataItemLocalized`} : {},
```

**Review by markkaylor — COMMENTED** [review]
I think this looks good. I'll just want to test it when I have a second later. I just had one small request 🙏 .

File: packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js (hunk 1 above)
Comment (ciriousjoker) [reply packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js:205]: idk how I can accept the suggested change, but I totally agree

Comment (ciriousjoker) [reply packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js]: nvm, I was on Github Mobile. Fixed now.

**Comment by ciriousjoker** [comment]
Not sure how to fix the PR labels. @markkaylor Do I need to do anything?

**Review by markkaylor — APPROVED** [review]

**Comment by ciriousjoker** [comment]
Thanks for reviewing it. Any eta for when this will be merged?
