### PR TITLE
Fixes #3224

### LINKED ISSUE #3424: Many to many on user causes all related entities plugin property to be removed.
When creating a many to many relationship on users with another entity, a write error is returned. Each entity that has a relationship to users is updated to have the "plugin":"users-permissions" removed. 

**Steps to reproduce the behavior**
1. Go to users entity
2. Click to add relationship
3. Create a many to many relationship with another entity
4. You will get a write error pop up
5. Look at your terminal. You should see that the related entity files have been updated and the "plugin":"users-permissions" property removed.

**System**
- Node.js version: v12.2.0
- NPM version: 6.9.0
- Strapi version: 3..0.0-beta.2
- Database: Mongo
- Operating system: Mac OS

### PR DESCRIPTION
**Pull request by soupette**
#### Description of what you did:
Fixes the  update of a plugin's content type. The bug was due to the source that wasn't updated.

#### My PR is a:

- [ ] 💥 Breaking change
- [X] 🐛 Bug fix #3424 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [x] MongoDB
- [x] MySQL
- [x] Postgres
- [x] SQLite

### CODE REVIEW

File: packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js [hunk 1]
```diff
@@ -81,14 +81,16 @@ export function* submitCT({
       body.plugin = source;
     }
 
+    console.log({ body });
```
Comment (derrickmehaffy) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js]: Probably need to remove the console.logs
