### PR TITLE
Fix Type Generation Checks for Min/Max Default Values

### LINKED ISSUE #19482: Invalid data type for min/max options. Must be string or number, but found 0.
- Node.js version: 18.x.x
- NPM version: 10.2.3
- Strapi version: 4.20.0
- Database: Postgres 11
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

On running `strapi ts:generate-types --debug` getting this error.
`Failed to generate types for contentTypes: Invalid data type for min/max options. Must be string or number, but found 0. Exiting`

It was working on strapi version: 4.17.x

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Fix a behavior where the type generation could fail when min/max values for an attribute were set to a falsy value (e.g. `0`)

### Why is it needed?

It prevents the generation of the type

### How to test it?

- Add a numeric attribute to a schema such as the following
  ```json
  {
    "totalPrice": {
      "type": "decimal",
      "min": 0
    }
  }
  ```

- Run `yarn strapi ts:generate-types`
- The types should be generated correctly, without throwing an error

### Related issue(s)/PR(s)

fix #19482

### CODE REVIEW

File: packages/utils/typescript/lib/generators/common/models/attributes.js [hunk 1]
```diff
@@ -114,21 +114,21 @@ const getAttributeModifiers = (attribute) => {
...
-        break;
-      case 'number':
-        typeKeyword = ts.SyntaxKind.NumberKeyword;
-        break;
-      default:
-        throw new Error(
-          `Invalid data type for min/max options. Must be string or number, but found ${typeofMinMax}`
-        );
+    // use 'string'
+    if (typeofMin === 'string' || typeofMax === 'string') {
```
Comment (innerdvations) [inline packages/utils/typescript/lib/generators/common/models/attributes.js:120]: What if the types differ?

Comment (Convly) [reply packages/utils/typescript/lib/generators/common/models/attributes.js:120]: [They can't](https://github.com/strapi/strapi/pull/19490/files/c9a57597c7b072971eb34a989622cae8c70135ed#diff-ededeca63a5cb676ae858edc8ae032d94abbed72806b9a4a32e7ca5189b588bfR113)

File: packages/utils/typescript/lib/generators/common/models/attributes.js [hunk 2]
```diff
@@ -114,21 +114,21 @@ const getAttributeModifiers = (attribute) => {
...
+      typeKeyword = ts.SyntaxKind.StringKeyword;
+    }
+    // use 'number'
+    else if (typeofMin === 'number' || typeofMax === 'number') {
```
Comment (innerdvations) [inline packages/utils/typescript/lib/generators/common/models/attributes.js:124]:
```suggestion
    if (typeofMin === 'string') {
      typeKeyword = ts.SyntaxKind.StringKeyword;
    }
    // use 'number'
    else if (typeofMin === 'number') {
```
Might be clearer like this, I originally asked "what if they're different" because I didn't notice the hidden lines above checking for that case.

Comment (Convly) [reply packages/utils/typescript/lib/generators/common/models/attributes.js:124]: Except if you want to have 4 ifs here? :thinking:

File: packages/utils/typescript/lib/generators/common/models/attributes.js [hunk 3]
```diff
@@ -114,21 +114,21 @@ const getAttributeModifiers = (attribute) => {
       throw new Error('typeof min/max values mismatch');
     }
 
-    const typeofMinMax = (max && typeofMax) ?? (min && typeofMin);
     let typeKeyword;
```
Comment (innerdvations) [inline packages/utils/typescript/lib/generators/common/models/attributes.js:117]: Do we want to explicitly define this as undefined and/or comment it so it's clear what's happening? I was looking for the `if(typeofMin === 'undefined')` down below and then had to look up to see why that case wasn't there

**Review by innerdvations — APPROVED** [review]
