### PR TITLE
fix(i18n): preserve non-localized media when creating a locale

### LINKED ISSUE #25178: Non-localized media fields disappear when creating localizations via REST API
### Node Version

22.21.1

### NPM/Yarn/PNPM Version

10.9.4

### Strapi Version

5.30.0

### Operating System

Docker/Podman/LXC

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

*No response*

### Description

When creating a localized version of an entry via PUT request following the official documentation, non-localized media fields are being cleared from all localizations if not explicitly included in the request body. This contradicts the documentation which states that non-localized fields should not be passed when creating localizations.

The admin panel works correctly when creating localizations manually through the UI, so this appears to be an API-specific issue.

### Environment

* **Strapi version**: 5.3.0
* **Node.js version**: 22
* **Upload provider**: @strapi/provider-upload-aws-s3 version 5.2.3
* **Database**: Aurora PostgreSQL
* **Infrastructure**: AWS EKS
* **API**: REST API (standard endpoints)
* **Pod configuration**:
  * Memory: request 1024Mi, limit 4096Mi
  * CPU: request 200m, limit 4000m
  * HPA: min 1, max 4 pods

### Affected Collections

* `product` (with draft & publish enabled)
* `technologies` (without draft & publish)
* Both are localized with non-localized media fields

### Case 1: Collection with Draft & Publish (`product`)

**Collection structure:**

* Localized collection with draft & publish enabled
* **Non-localized fields**: `code` (string), `productName` (string), `detailImages` (media list)
* **Localized fields**: `description` (markdown), `materials` (relation many-to-many)

**Steps:**

1. Create a product (e.g., XC342 in Italian locale) via POST API with all fields including `detailImages` (4 images)
   * ✅ Works correctly
2. Get the `documentId` of the created product
3. Create an English localization via PUT request following the [official documentation](<https://docs.strapi.io/cms/api/rest/locale#rest-update>)
4. Pass only localized fields in the body: `description` and `materials`
5. Do NOT pass `detailImages` as per documentation warning

**Result:**

* `detailImages` disappear from the API response for **all localizations**
* In the admin panel (Italian locale - original):
  * **Draft version**: images are still visible in the `detailImages` field
  * **Published version**: images are missing (visible in the "published" tab)
  * No indication that the entry needs to be republished (mismatch between draft and published)
* In the admin panel (English locale - newly created):
  * Images are missing in both draft and published versions

**Workaround:** Manually unpublishing and republishing the original locale (Italian) restores the images, but this is not feasible for bulk operations.

---

### Case 2: Collection without Draft & Publish (`technologies`)

**Collection structure:**

* Localized collection without draft & publish
* **Non-localized field**: `logo` (media)

**Steps:**

1. Create a technology entry in Italian locale with a logo
2. Create an English localization via PUT request
3. Pass only localized fields (not passing the `logo` field)

**Result:** <br>The images disappear permanently from all localizations. Since there's no draft & publish system, there's **no workaround** except manually re-uploading and reconnecting all media files.

### Expected Behavior

According to the [official documentation](<https://docs.strapi.io/cms/api/rest/locale#rest-update>):

> "When creating a localization for existing localized entries, the body of the request can only accept localized fields"

Non-localized fields (like `detailImages` and `logo`) should:

1. **Not** be required in PUT requests when creating localizations
2. **Remain unchanged** across all localizations
3. Be automatically shared between all localizations without requiring explicit inclusion

### Logs

```shell
```

### Code Snippets

*No response*

### Media

*No response*

## Working Solution (but contradicts documentation)

If non-localized media fields are included in the PUT request body when creating a localization (passing image IDs or array of IDs):

* The API does **not** return an error (unlike other non-localized fields such as strings)
* Everything works correctly and images are maintained across all localizations
* This applies to both collections (with and without draft & publish)

**Inconsistent behavior:**

* Passing non-localized **media fields** → No error, but required for images to persist
* Passing non-localized **string fields** (e.g., `code`, `productName`) → Correctly returns an error as per documentation

This suggests media fields are handled differently from other non-localized fields.

## Additional Context

* The admin panel works correctly when creating localizations manually through the UI
* This appears to be an **API-specific issue**

**Note:** Vlad Ocneanu (Strapi Support Engineer) has successfully reproduced this issue and confirmed it as a bug. He recommended creating this GitHub issue for the engineering team to address in a future version.

### Confirmation Checklist

- [X] I have checked the existing [issues](<https://github.com/strapi/strapi/issues>) for duplicates.
- [X] I agree to follow this project's [Code of Conduct](<https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md>).

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

This change fixes locale creation for localized content types when they contain non-localized media fields.

It updates the Document Service i18n path to:
- populate non-localized fields before copying them into a newly created locale
- normalize copied media values into upload file IDs before persistence
- normalize media values during localization sync as well

It also adds a regression test covering locale creation through the Document Service `update()` flow for a content type with a non-localized media field.

### Why is it needed?

Creating a new locale for an existing document could clear non-localized media fields.

The issue happens because:
- the locale-creation path copied non-localized fields without populating media
- the newly created locale could end up with `null` for shared media

As a result, API-driven locale creation did not preserve shared media the same way the expected behavior requires.

### How to test it?

Run:

```bash
yarn test:api tests/api/core/strapi/document-service/update.test.api.ts
```
What to verify:
- create an `en` document with a non-localized media field
- create a new locale for the same document through Document Service `update()`
- confirm the shared media is preserved on both the source locale and the new locale

### Related issue(s)/PR(s)

Fixes #25178

### CODE REVIEW

File: packages/core/core/src/services/document-service/internationalization.ts [hunk 1]
```diff
@@ -92,6 +96,59 @@ const localeToData: Transform = (contentType, params) => {
   return params;
 };
 
+const normalizeMediaIds = (schema: SchemaWithAttributes, data: Record<string, any>) => {
```
Comment (jhoward1994) [inline packages/core/core/src/services/document-service/internationalization.ts]: This looks very similar to `packages/plugins/i18n/server/src/services/localizations.ts` L7 is there any way this could be shared ?

File: packages/core/core/src/services/document-service/internationalization.ts [hunk 2]
```diff
@@ -92,6 +96,59 @@ const localeToData: Transform = (contentType, params) => {
...
+  Object.entries(schema.attributes).forEach(([attributeName, attribute]) => {
+    const value = data[attributeName];
+
+    if (value == null) {
+      return;
+    }
+
+    if (attribute.type === 'media') {
+      if (attribute.multiple) {
+        data[attributeName] = Array.isArray(value)
```
Comment (jhoward1994) [inline packages/core/core/src/services/document-service/internationalization.ts:116]:
```suggestion
        const files = Array.isArray(value) ? value : [value];
        data[attributeName] = files.map((file: unknown) =>
          file && typeof file === 'object' && 'id' in file ? file.id : file
        );
```

is it worth doing it this way?

File: packages/core/core/src/services/document-service/internationalization.ts [hunk 3]
```diff
@@ -92,6 +92,65 @@ const localeToData: Transform = (contentType, params) => {
...
+      if (attribute.repeatable && Array.isArray(value)) {
+        value.forEach((componentValue: Record<string, any>) =>
+          normalizeMediaIds(componentSchema, componentValue)
+        );
+      } else {
+        normalizeMediaIds(componentSchema, value);
+      }
+
+      return;
+    }
```
Comment (markkaylor) [inline packages/core/core/src/services/document-service/internationalization.ts:141]: Will this work for nested components? 🤔

Comment (Bassel17) [reply packages/core/core/src/services/document-service/internationalization.ts:141]: it should, I added a test case for it

**Review by jhoward1994 — DISMISSED** [review]

**Review by jhoward1994 — APPROVED** [review]
