### PR TITLE
Put inversedBy only once for manyToMany and oneToOne relations

### LINKED ISSUE #14428: Two join tables are created for many-to-many relations instead of one
### Required System information

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version: 4.3.8
- Database: SQLite
- Operating system: macOS

### Describe the bug

Two join tables are created for many-to-many relations instead of one.
It is because the created attributes for the relation both have "inversedBy" instead of one having "inversedBy" and the other "mappedBy".

### Steps to reproduce the behavior

Follow what is done in this video:

https://user-images.githubusercontent.com/11708220/190352181-196c7b4c-d89d-4ae8-8fc6-4961ee7e1d4e.mov

Notice at the end, if I edit the content-type a second time, then the relation is back to what it is supposed to be + the second join table is deleted.

### Expected behavior

Only one join table should exist + the 2 attributes of the many-to-many relations should have, for on "inverseBy", for the other "mappedBy".

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

Put `inversedBy` only on one side of the many to many relations

### Why is it needed?

`inversedBy` was put in both relation sides whereas it should be `inversedBy` and `mappedBy`.
It was creating 2 join tables 

### How to test it?

Create a many to many relation with the CTB and check the 2 schemas.

### Related issue(s)/PR(s)

Fix #14428

### CODE REVIEW

File: packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js [hunk 1]
```diff
@@ -207,6 +207,10 @@ module.exports = function createComponentBuilder() {
         const attribute = newAttributes[key];
 
         if (isRelation(attribute)) {
+          if (['manyToMany', 'oneToOne'].includes(attribute.relation)) {
+            attribute.dominant = true;
```
Comment (nathan-pichon) [inline packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js:211]: Do we have some documentation describing this dominant boolean inside attributes? I think its missing on our doc https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-attributes

Comment (petersg83) [reply packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js:211]: No the `dominant` attribute is only an internal and temporary variable (used during the creation/edit process).
In the model schema the information already exists with `inversedBy` and `mappedBy`. One side of the relation has `inversedBy` and the other side has `mappedBy`. We can consider that the side with the `inversedBy` is the dominant.

Comment (nathan-pichon) [reply packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js:211]: Ok ! Thanks for the explanation @petersg83 🤗

Comment (petersg83) [reply packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js:211]: with pleasure 😊

**Review by Marc-Roig — APPROVED** [review]
LGTM! It is working alright to me.

For people that now has `inversedBy` in both sides I guess it will stay the same and they will keep the two join tables right? 

Would it make sense to implement this if for relations that are not new too? So it would remove one of the join tables. (Maybe too risky?)

**Comment by derrickmehaffy** [comment]
This really needs a migration guide, realistically I shouldn't have been merged without it.

**Comment by petersg83** [comment]
@derrickmehaffy no it's ok, it won't change existing schemas of existing projects. It impacts only newly created relations.

**Comment by derrickmehaffy** [comment]
I mean to fix the but and remove the bad table, users need to update and fix their schemas no?

**Comment by Marc-Roig** [comment]
@derrickmehaffy yes, and there is an issue caused by this https://github.com/strapi/strapi/issues/14912#top
I am in the process of creating a migration guide. We have to be careful, content types relations with 2 inversedBy have two tables, so if you change the wrong side to mappedBy you will be losing your relations data.

We thought of notifying user on startup which content type you have to modify.
