### PR TITLE
strapi-plugin-upload accepts localServer configuration

### LINKED ISSUE #8809: Uploaded assets have no maxAge
## Bug report

I  notice that upload middleware is loaded before the public in the default config.
In this way, every uploaded asset has `maxAge=0`, because it's not directly served by the public middleware.

### Expected behavior

Every uploaded asset should inherit the [global public](https://strapi.io/documentation/v3.x/concepts/middlewares.html#global-middlewares) maxAge setting.
As an alternative, give the possibility to overwrite the default upload maxAge setting.

### System

- Node.js version: 14.13.0
- NPM version: 6.14.8
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: macOS Catalina

### PR DESCRIPTION
**Pull request by ThewBear**
### What does it do?

Make `strapi-plugin-upload` accepts `localServer` configuration for `koa-static`.

### Why is it needed?

To support custom `koa-static` options such as `maxage`

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/6645#issuecomment-645217698
fixes #8809

### CODE REVIEW

File: packages/strapi-plugin-upload/middlewares/upload/index.js [hunk 1]
```diff
@@ -23,6 +24,7 @@ module.exports = strapi => ({
       strapi.app.onerror(err);
     });
 
-    strapi.router.get('/uploads/(.*)', range, koaStatic(staticDir, { defer: true }));
+    const localServerConfig = _.get(strapi.plugins.upload.config, 'localServer', {});
```
Comment (jbgraug) [inline packages/strapi-plugin-upload/middlewares/upload/index.js:27]: To get the most of _.get and to prevent failing if config.localServer was set to null. (null is a value for _.get)
const localServerConfig = _.get(strapi, 'plugins.upload.config.localServer') || {}

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
To make it a bit more consistent with the provider options 

can you get this key from the providerOptions so we can later move this hanlder into the locale provider logic for example

File: packages/strapi-plugin-upload/middlewares/upload/index.js [hunk 2]
```diff
@@ -23,6 +24,7 @@ module.exports = strapi => ({
       strapi.app.onerror(err);
     });
 
-    strapi.router.get('/uploads/(.*)', range, koaStatic(staticDir, { defer: true }));
+    const localServerConfig = _.get(strapi, 'plugins.upload.providerOptions.localServer') || {};
```
Comment (alexandrebodin) [inline packages/strapi-plugin-upload/middlewares/upload/index.js:27]: you are missing a config key :) when setting the key into `plugins.js`, the options will be  at `strapi.plugins.upload.config.providerOptions.localServer`

Comment (ThewBear) [reply packages/strapi-plugin-upload/middlewares/upload/index.js:27]: Oops. Sorry

**Review by alexandrebodin — APPROVED** [review]
LGTM. Thanks for the addition. Can you add a Doc PR on the documentation repo ? @derrickmehaffy  can help you with that if necessary ;)

**Comment by ThewBear** [comment]
Doc PR https://github.com/strapi/documentation/pull/78.
