### PR TITLE
Fix copy from another locale with DZ

### LINKED ISSUE #11908: Admin sometimes crash when filling from another locale
### Describe the bug

Admin sometimes crashes when filling from another locale.

### Steps to reproduce the behavior

You can reproduce this behaviour using FoodAdvisor
1. `git clone https://github.com/strapi/foodadvisor.git`
2. `git checkout remove-plugins`
3.  `cd api && yarn && yarn seed && yarn develop`
4. Find a restaurant without an fr-FR locale and try to create one using `Fill from another locale`
5. Reproduce to other restaurants if the error didn't happen on the previous one.

### Expected behavior

Data should be filled with en locale.

### Screenshots

Capture d’écran 2021-12-14 à 17 15 32

### System

- Node.js version: v12.8.4
- NPM version: 6.14.6
- Strapi version: v4.0.0
- Database: SQLite3
- Operating system: Mac OS

### Additional context

I also figured out the fact that UID fields are not regenerated when filling from another locale. This causes a Bad request when trying to save the content unless you regenerate them

Capture d’écran 2021-12-14 à 17 56 26
.

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril@strapi.io>

### What does it do?

It fixes #11908 

### Why is it needed?

To prevent the admin from crashing.

### How to test it?

The issue should be fixed.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

File: packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js [hunk 1]
```diff
@@ -37,11 +37,33 @@ const DynamicZone = ({
...
+  useEffect(() => {
+    setComponentsCollapses(createCollapses(dynamicDisplayedComponentsLength));
+  }, [dynamicDisplayedComponentsLength]);
+
+  useEffect(() => {
+    if (shouldOpenAddedComponent) {
+      setComponentsCollapses(prev =>
+        prev.map((collapse, index) => {
+          if (index === prev.length - 1) {
+            return { isOpen: true };
```
Comment (HichamELBSI) [inline packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js:56]: Can you spread the collapse object before. If ever another value was added, it would be lost here. WDYT?

`{ ...collapse, isOpen: true }`

**Review by HichamELBSI — CHANGES_REQUESTED** [review]

File: packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js (hunk 1 above)
Comment (soupette) [reply packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js:56]: The collapse is  an object that only has one key : `isOpen`

Comment (HichamELBSI) [reply packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js:56]: I know but if we add another key to that object (for any reason), it will be lost here anyway.

**Review by HichamELBSI — APPROVED** [review]
LGTM, good job! Can you just update the branch please 😅
