### PR TITLE
enhancement: debounce blocks editor update

### LINKED ISSUE #23208: Blocks editor performance issue (input lag)
### Node Version

22.14.0

### NPM/Yarn/PNPM Version

10.9.2

### Strapi Version

5.11.2

### Operating System

Linux (Debian/Ubuntu)

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Bug Description

While running some tests on my side, I noticed performance issues with the Rich Text (Blocks) field.
When I type quickly, each letter takes time to appear, and the more characters there are in the field, the slower I need to type to get these slowdowns.
I'm attaching a video to show you.

I ran additional tests to make sure my environment wasn’t the cause of the issue. I tried:

- Creating a new project with a simple entity containing a Rich Text (Blocks) field
- Downgrading Strapi (down to version 5.5.2)
- Running Strapi in production mode
- Testing on multiple browsers

Each test gave me the same result.

I couldn’t find any reference to this issue on Discord. However, I did find a related issue on GitHub: https://github.com/strapi/strapi/pull/18852.
It’s quite old and seems to have been resolved, so I suppose it’s not the same issue.

Do you have a solution to work around this problem?

Thanks in advance!

_(In the video, I am typing continuously.)_ 

https://github.com/user-attachments/assets/c2ef2d37-d8b3-4ed3-aa42-36fcf66cfa6a

### Steps to Reproduce

1. Add a Rich Text (Blocks) to a Collection Type
2. Quickly tap in
3. Observe input lag

### Expected Behavior

The letters should be displayed instantly on each input.

### Logs

```shell

```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by remidej**
### What does it do?

Debounces the updates that keep the Strapi form state in sync with Slate's internal state.

>Slate handles the state of the editor internally. We just need to keep Strapi's form state in sync with it in order to make sure that things like the "modified" state isn't broken. Updating the whole state on every change is very expensive however, so we debounce calls to onChange to mitigate input lag.
### Why is it needed?

The blocks editor has way too much input lag. This helps a lot

### How to test it?

Type in the blocks editor. Things should feel snappier. Try on a content type with a lot of fields and a lot of content in particular.

You can use the devtools performance tab too, which gives you an Interaction to Next Paint (INP) metric

Also make sure the "discard changes" button still works for updates made in a blocks field.

### Related issue(s)/PR(s)

fixes #23208

### CODE REVIEW

File: packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksContent.tsx [hunk 1]
```diff
@@ -533,55 +535,52 @@ const BlocksContent = ({ placeholder, ariaLabelId }: BlocksContentProps) => {
...
+    //   case 'Tab':
+    //     return handleTab(event);
+    //   case 'Escape':
+    //     return ReactEditor.blur(editor);
+    // }
+    // handleKeyboardShortcuts(event);
+    // // Check if a snippet was triggered
+    // if (event.key === ' ') {
+    //   checkSnippet(event);
+    // }
```
Comment (markkaylor) [inline packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksContent.tsx]: Is this on purpose?

Comment (remidej) [reply packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksContent.tsx]: oopsie

**Comment by markkaylor** [comment]
Screenshot 2025-06-10 at 10 52 25

I'm just hitting an error when I discard changes otherwise LGTM
