### PR TITLE
fix(content-manager): dont perform unnecessary requests

### LINKED ISSUE #20736: v5: `countDraftRelations` is called for every entry in the list view
### Required System information

- Node.js version: 20
- Yarn version: 1.22
- Strapi version: 5 rc 3
- Database: sqlite
- Operating system: macOS
- Is your project Javascript or Typescript: JS

### Describe the bug

Just gave the RC3 a spin. Something I notice is that the list view is significantly slower because it calls `countDraftRelations` for every entry in view. If you set it to 100 entries, it will DDoS it's own backend with 100 tiny API calls. Is this really necessary?

### Steps to reproduce the behavior

1. Go to a list view
2. Set viewing entries to 100
3. Wait until the UI stops crashing
4. See the logs go crazy with API calls

### Expected behavior

I think this could be solved smarter than calling the API so many times, all of the time.

### Additional context

As discussed in the v5 beta discord channel

### PR DESCRIPTION
**Pull request by Feranchz**
### What does it do?

`DescriptionComponentRenderer` receive all the possible buttons and all the components are rendered even if at the end they are not showed. So we explicitly remove the publish button as it is not showed in the ListView and because the PublishAction button performs requests that we don't want to make at the list view.

### How to test it?

1. Go to any CT on the Content Manager. 
2. It should not have any request to countDraftRelations endpoint

### Related issue(s)/PR(s)

closes #20736

### CODE REVIEW

File: packages/core/content-manager/admin/src/pages/ListView/components/TableActions.tsx [hunk 1]
```diff
@@ -52,9 +52,10 @@ const TableActions = ({ document }: TableActionsProps) => {
   return (
     <DescriptionComponentRenderer
       props={props}
-      descriptions={(
-        plugins['content-manager'].apis as ContentManagerPlugin['config']['apis']
-      ).getDocumentActions()}
+      descriptions={(plugins['content-manager'].apis as ContentManagerPlugin['config']['apis'])
+        .getDocumentActions()
+        // We explicitly remove the PublishAction from description so we never render it and we don't make unnecessary requests.
+        .filter((action) => action.name !== 'PublishAction')}
```
Comment (madhurisandbhor) [inline packages/core/content-manager/admin/src/pages/ListView/components/TableActions.tsx:58]: why we don't need bulk publish?

Comment (Feranchz) [reply packages/core/content-manager/admin/src/pages/ListView/components/TableActions.tsx:58]: This is not related to Bulk Publish. Is about the individual publish button which is not showed on the ListView, so here we avoid run the component

**Review by madhurisandbhor — APPROVED** [review]

**Review by simotae14 — APPROVED** [review]
