### PR TITLE
Fixed input checkbox behavior

### LINKED ISSUE #5437: Bad behavior of endpoint fields in roles-permissions plugin admin panel
**Describe the bug**
When configuring the permissions of a role the endpoint fields of the endpoints have multiple behavior issues: 
1. The clickable area is the word (text) and the checkbox only
2. The configuration wheel (when field checked) appears when hovering the endpoint field and has `cursor = pointer` when hovered, but is not clickable
3. If you want to show the endpoint configurations you have to uncheck and recheck the endpoint, since there is no selection without toggle possible

**Steps to reproduce the behavior**
1. Reproduction of clickable area check
    1. Enable `Roles & Permissions` plugin
    2. Go to `Roles & Permissions` plugin's Admin panel
    3. Select a role 
    4. Go to the Permissions and hover over the checkbox, the text and the empty area of an unchecked endpoint field
2. Reproduction of missing click action on configuration wheel
    1. Follow the steps 1.1 - 1.3
    2. Check an endpoint
    3. Select an other endpoint (this will toggle the endpoint's check state)
    4. Hover over the unselected but checked endpoint field (the configuration wheel appears)
    5. Click on the configuration wheel (no click action)
3. Reproduction of missing select action without toggling
    1. Follow the steps 2.1 - 2.4
    3. Try to select the endpoint field (to configure) without toggling the endpoint check status

**Expected behavior**
1. I would expect that I can click on the whole field area (see below screenshots) where the highlighting happens and toggle only the check state of the endpoint when clicking on the checkbox or text. I would also expect here a hovering effect like when checked 
2. I would expect a selection of the endpoint field and an opening of the advanced settings (but click action is missing atm)
3. The expected behavior here is a possibility to select the endpoint without toggling it's checked state (see also 1.)

**Screenshots**
Screenshot of expected areas
Terminology: 
* *expected toggle area*: the area which toggles the checked state of the endpoint field on click (text and checkbox)
* *expected selection area*: the area which selects the endpoint field (without toggling the checked state). This area is the same as the highlighted (in grey) area of the selected field
* *expected image button*: The image button of the configuration wheel which opens the configuration / advanced settings

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.18.7
- Database: Any (it is view related)
- Operating system: Any (it is view related)
- Browser: Chrome (but probably any)

**Additional context**
* The problem with the configuration wheel is probably because the bubbling events are not handled properly
* The missing hover effect of unchecked endpoint fields and the clickable area might be on purpose, but doesn't reflects the user's expectations (at least not my expectations)
* The `Select All` checkbox affects also the appearance of the focused / selected / checked endpoint views causing unreproducable (by single single endpoint selection) view states. This might be fixed if the above issues are fixed correctly

P.S. I wrote these issues together since they are hardly related to the same object and it's behavior / user interaction.

### PR DESCRIPTION
**Pull request by malliaridis**
#### Description of what you did:
Updated the click behavior of the input checkbox field. Now the fields can be selected without 
toggling the checkbox by clicking on the white surface or the config wheel. Toggling still possible
by clicking on the word or checkbox (like before). 

Also moved the input selected state to the plugin (from controller) to prevent multiple selections
of input fields (with highlighting) from different controllers. This visibility bug occurred while 
fixing the actual behavior of the input checkboxes.

Fix #5437

### CODE REVIEW

File: packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js [hunk 1]
```diff
@@ -14,9 +14,8 @@ import InputCheckbox from '../InputCheckboxPlugin';
 
 import { Header, Label, Separator, Wrapper } from './Components';
 
-function Controller({ actions, inputNamePath, isOpen, name }) {
+function Controller({ actions, inputNamePath, isOpen, name, inputSelected, setInputSelected }) {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js:17]: Can you remove the `{ useState }` import since it is not needed anymore?

Comment (malliaridis) [reply packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js:16]: Bad idea to skip once the linter. ^^' 
I updated the branch and removed the import. :)

Comment (malliaridis) [reply packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js:16]: Bad idea to skip once the linter. 
Updated the branch and removed the import. :) 

P.S. Sorry for the multiple force-pushes (if you got any notifications). I seem to have some auto formatting issues while commiting.
