### PR TITLE
Use custom field's sizes when restarting strapi to calculate edit layout

### LINKED ISSUE #16933: Custom field resets input size and position on server restart
### Required System information

- Node.js version: v18.14.2
- NPM version: 9.5.0
- Strapi version: v4.10.7
- Database: SQLite3
- Operating system: Linux (Ubuntu-based, `5.15.0-72-generic #79~20.04.1-Ubuntu`)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I made a simple (unpublished) plugin for internal use at my company that for now simply registers a custom field type and does nothing else, it has no admin page and no options. The plugin code lives in `src/plugins` in my Strapi app and is loaded through the `resolve` property in `config/plugins.ts`, it is not an external package at the moment. The custom field saves a JSON field to the database.

I've noticed that whenever I move or resize the field through the content manager, the changes revert when the server restarts. This only seems to happen to that field type, builtin field types are not affected. The issue happens regardless of which content type (collection or single) the field is added to.

I have verified that the `plugin_content_manager_configuration_content_types::api::<type>.<type>` setting in the `strapi_core_store_settings` table in the database gets updated on server start, and the `layouts.edit` value gets reverted. This happens both when the server is restarted in development and in production.

In the following example, the field `site_link` uses my custom field type plugin.
The layouts value after I change the layout through the content-manager:

```json
"layouts": {
    "edit": [
      [
        { "name": "title", "size": 6 },
        { "name": "slug", "size": 6 }
      ],
      [
        { "name": "cover_image", "size": 6 },
        { "name": "site_link", "size": 6 }
      ],
      [{ "name": "content_blocks", "size": 12 }]
    ],
    "list": ["id", "title", "createdAt", "updatedAt"]
  }
```

The layouts value right after the server restarts:

```json
"layouts": {
    "list": ["id", "title", "createdAt", "updatedAt"],
    "edit": [
      [
        { "name": "title", "size": 6 },
        { "name": "slug", "size": 6 }
      ],
      [{ "name": "cover_image", "size": 6 }],
      [{ "name": "content_blocks", "size": 12 }],
      [{ "name": "site_link", "size": 6 }]
    ]
  }
```

### Steps to reproduce the behavior

1. Create a custom field plugin using `strapi generate`
2. Keep the default server code, register the plugin as shown in the code snippets section
3. Add the custom field to a content type
4. Resize and/or move the field though the "Configure the view" option
5. Restart the server

### Expected behavior

The server should not overwrite the custom field layout on restart.

### Code snippets

The custom field is registered like so:

<details>
  <summary>server/register.ts</summary>

  ```ts
  import { Strapi } from '@strapi/strapi';

  export default ({ strapi }: { strapi: Strapi }) => {
    strapi.customFields.register({
      name: 'link',
      plugin: 'mashvp-link',
      type: 'json',
      inputSize: {
        default: 6,
        isResizable: true,
      },
    });
  };
  ```
</details>

<details>
  <summary>admin/index.ts</summary>

  ```ts
  /* ... */

  export default {
    register(app: any) {
      app.customFields.register({
        name: 'link',
        pluginId: 'mashvp-link',
        type: 'json',
        intlLabel: {
          id: 'mashvp-link.label',
          defaultMessage: 'Link',
        },
        intlDescription: {
          id: 'mashvp-link.description',
          defaultMessage: 'Link selector with label and target options',
        },
        icon: PluginIcon,
        components: {
          Input: async () =>
            import(
              /* webpackChunkName: "input-component" */ './components/MashvpLink'
            ),
        },
      });

      app.registerPlugin({
        id: pluginId,
        initializer: Initializer,
        isReady: false,
        name,
      });
    },

    /* ... */
  };
  ```
</details>

### PR DESCRIPTION
**Pull request by Feranchz**
### What does it do?

`isAllowedFieldSize` is used to verify whether a field has changed its type to one with a different size. With this PR, we check if the field is a custom field with its own custom size. Instead of employing the size associated with the data type, we use the user-defined custom size.

### Why is it needed?

This solve two different issues at the same time:
1. Users have the ability to create a custom field with a JSON type, while specifying a custom size such as 6 (the default size for a JSON type is 12). But, when restarting Strapi, the edit layout reverts to using the size of 12 instead of 6. (Additional context: Issue #16933)
2. During the development of a custom field, it is common for developers to adjust the default size of their custom fields to explore  different options. With this modification, the field now automatically adapts to its new size each time, eliminating the need for developers to manually adjust it in the configure the view page.

### How to test it?

1. Create a content type with a custom field with **NO** custom sizes set. You can create the custom field with the type you want.
2. Change the custom field and now set a custom size different to the type size and not resizable.
3. When restarting the app it should change the custom field size to the new one

### Related issue(s)/PR(s)

Closes #16933

### CODE REVIEW

File: packages/core/content-manager/server/services/utils/configuration/layouts.js [hunk 1]
```diff
@@ -7,9 +7,16 @@ const { isListable, hasEditableAttribute, hasRelationAttribute } = require('./at
...
   const { getFieldSize } = getService('field-sizes');
-  const fieldSize = getFieldSize(type);
+  let fieldSize = getFieldSize(type);
+
+  if (customFieldUid) {
+    const customField = strapi.container.get('custom-fields').get(customFieldUid);
+    if (customField.inputSize) {
+      fieldSize = customField.inputSize;
+    }
+  }
```
Comment (gu-stav) [inline packages/core/content-manager/server/services/utils/configuration/layouts.js:19]: I am not a backend developer, but wouldn't it be cleaner if `getFieldSize` returns the proper field-size regardless of the type? Proposing to move this bit into the function itself.

It would also be great if you could add a test for it 🙏🏼

Comment (markkaylor) [inline packages/core/content-manager/server/services/utils/configuration/layouts.js:19]: - I think sole responsibility of this function should be to return a boolean, not set a value. It seems like the custom field value should already be set when we call getFieldSize.
- It looks like we have a function here that sets the user provided field size for all custom fields. Why do we need this addition here? https://github.com/strapi/strapi/blob/ee14338b977d4d3b4271a2d61fe3807ef4bfff8c/packages/core/content-manager/server/services/field-sizes.js#L80-L91
Which is called in bootstrap:
https://github.com/strapi/strapi/blob/207938b001795705e278ef1fcfd6d32534590d20/packages/core/content-manager/server/bootstrap.js#L14

File: packages/core/content-manager/server/services/utils/configuration/__tests__/layouts.test.js [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+    attributes: {
+      title: {},
+      nodes: {},
+    },
+  },
+});
+
+describe('Layouts', () => {
+  describe('synchronisation functions', () => {
+    describe('syncLayouts', () => {
```
Comment (remidej) [inline packages/core/content-manager/server/services/utils/configuration/__tests__/layouts.test.js:39]: Do we need 3 different suites here? Seems a bit overkill

File: packages/core/content-manager/server/services/field-sizes.js [hunk 3]
```diff
@@ -52,6 +52,10 @@ const createFieldSizesService = ({ strapi }) => {
       return fieldSizes;
     },
 
+    hasFieldSize(type) {
+      return !!fieldSizes[type];
+    },
```
Comment (remidej) [inline packages/core/content-manager/server/services/field-sizes.js:57]: Do you think hasFieldSize could be implemented as part of getFieldSize? They seem to always be called together

File: packages/core/content-manager/server/bootstrap.js [hunk 4]
```diff
@@ -8,8 +8,8 @@ module.exports = async () => {
     strapi.webhookStore.addAllowedEvent(key, value);
   });
 
+  getService('field-sizes').setCustomFieldInputSizes();
```
Comment (remidej) [inline packages/core/content-manager/server/bootstrap.js:11]: Nice catch here 👍

File: packages/core/content-manager/server/services/field-sizes.js (hunk 3 above)
Comment (remidej) [reply packages/core/content-manager/server/services/field-sizes.js:57]: No I think throwing the error is good, so both options you mention are okay. Let's keep it like that then 👍

**Review by remidej — APPROVED** [review]
Tested and looks good 🚀
