### PR TITLE
Enable session middleware by default (fixes U&P provider authentication)

### LINKED ISSUE #7405: Plugin users-permissions providers Custom callback url doesn't work
**Describe the bug**

Passing callback url instead of using the default registered provider callback doesn't seems to be working. In my case I'm using SPA on many domains with one API. In this case i need the API to redirect to correct SPA instance. 

```
GET https://API.com/connect/facebook?callback=https://DOMAIN1.com/en/auth/google
GET https://API.com//connect/facebook?callback=https://DOMAIN2.com/en/auth/google
GET https://API.com//connect/facebook?callback=https://DOMAIN3.com/en/auth/google
``` 
is not working as expected 

**Steps to reproduce the behavior**

Follow tutorial on https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers part that says 

> You can also pass a custom callback url instead of using the default registered provider callback, by passing callback in the query. eg: GET /connect/facebook?callback=https://my-frontend.com/en/auth/facebook.

I was testing Google OAuth. 

**Expected behavior**

URL like http://localhost:5000/connect/google?callback=http://localhost:3001/connect/google should redirect to http://localhost:3001/connect/google after successful login. 

Seems like `callback` is not a valid name to be passed to OAuth provider and this is trimmed from actual call, so once Provider redirects back to API callback url is lost. What I have found out that `state` is a parameter that can be used here (https://developers.google.com/identity/protocols/oauth2/web-server) 

> You can use this parameter for several purposes, such as directing the user to the correct resource in your application, sending nonces, and mitigating cross-site request forgery.

**Code snippets**

Changing the following code seems to be fixing the issue 
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L264
```js
    // Ability to pass OAuth callback dynamically
    grantConfig[provider].callback = _.get(ctx, 'query.callback') || _.get(ctx, 'query.state') || grantConfig[provider].callback;
    grantConfig[provider].state = _.get(ctx, 'query.callback') || grantConfig[provider].callback;
```

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0
- Database: sqlite
- Operating system: MacOS 10.15.5

**Additional context**

I'm not creating a MR so far, because I'm not sure if my solution is valid, I'm not OAuth expert and I haven't tested any other providers except Google.

### PR DESCRIPTION
**Pull request by petersg83**
It enables session middleware by default (which fixes U&P provider authentication)
It removes the possibility to authenticate requests using access_token url query param
It fixes a wording where the displayed provider name was wrong

Based on a previous PR created by @rgoupil https://github.com/strapi/strapi/pull/11777

also fix #7405 (thank you @borm for showing a fix)

### CODE REVIEW

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 1]
```diff
@@ -6,6 +6,7 @@ module.exports = [
     path: '/connect/(.*)',
     handler: 'auth.connect',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:9]: Do we really need to hard-code these as false even though the user can set permissions in users-permissions that will effectively do nothing? I think it would be better to pre-populate the database keys instead no?

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 2]
```diff
@@ -15,6 +16,7 @@ module.exports = [
     path: '/auth/local',
     handler: 'auth.callback',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:19]: same

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 3]
```diff
@@ -24,6 +26,7 @@ module.exports = [
     path: '/auth/local/register',
     handler: 'auth.register',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:29]: same

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 4]
```diff
@@ -33,6 +36,7 @@ module.exports = [
     path: '/auth/:provider/callback',
     handler: 'auth.callback',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:39]: same

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 5]
```diff
@@ -41,6 +45,7 @@ module.exports = [
     path: '/auth/forgot-password',
     handler: 'auth.forgotPassword',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:48]: same

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 6]
```diff
@@ -50,6 +55,7 @@ module.exports = [
     path: '/auth/reset-password',
     handler: 'auth.resetPassword',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:58]: same

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 7]
```diff
@@ -59,6 +65,7 @@ module.exports = [
     path: '/auth/email-confirmation',
     handler: 'auth.emailConfirmation',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:68]: same

File: packages/plugins/users-permissions/server/routes/content-api/auth.js [hunk 8]
```diff
@@ -67,6 +74,7 @@ module.exports = [
     path: '/auth/send-email-confirmation',
     handler: 'auth.sendEmailConfirmation',
     config: {
+      auth: false,
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/routes/content-api/auth.js:77]: same

**Review by derrickmehaffy — CHANGES_REQUESTED** [review]

File: packages/plugins/users-permissions/server/routes/content-api/auth.js (hunk 1 above)
Comment (petersg83) [reply packages/plugins/users-permissions/server/routes/content-api/auth.js:9]: You're right, I need to dig this a little bit. Will do after the cooldown then

File: packages/core/strapi/lib/Strapi.js [hunk 9]
```diff
@@ -189,15 +189,13 @@ class Strapi {
...
     // Emit started event.
     // do not await to avoid slower startup
     this.telemetry.send('didStartServer', {
-      database: databaseClients,
-      plugins: this.config.installedPlugins,
-      providers: this.config.installedProviders,
+      database: strapi.config.get('database.connection.client'),
+      plugins: Object.keys(strapi.plugins),
+      // TODO: to add back
+      // providers: this.config.installedProviders,
```
Comment (rgoupil) [inline packages/core/strapi/lib/Strapi.js:198]: What is the proper way to send the installed providers in v4? This is beyond my current understanding of the codebase but I am curious 😅

File: packages/core/strapi/lib/middlewares/session.js [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+  if (!isEmpty(userConfig.client) && userConfig.client !== 'cookie') {
+    throw new Error(
+      'The session middleware only handles the `cookie` client. Please update your config.'
+    );
+  }
+
+  const config = defaultsDeep(defaultConfig, userConfig);
+  config.client = 'cookie'; // forces cookie store
+
+  strapi.server.app.keys = config.secretKeys;
```
Comment (rgoupil) [inline packages/core/strapi/lib/middlewares/session.js:32]: Should we add a check to ensure that at least one key has been provided? I haven't tested if it work without any keys, but I can't imagine it to be secure.
If not throwing an `Error`, logging a warning could go a long way, don't you think?

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/core/strapi/lib/middlewares/session.js [hunk 11]
```diff
@@ -0,0 +1,40 @@
+'use strict';
+
+const { defaultsDeep, isEmpty } = require('lodash/fp');
+const session = require('koa-session');
+
+const defaultConfig = {
```
[the remark this answers is not in the document]
Comment (petersg83) [reply packages/core/strapi/lib/middlewares/session.js:6]: You are right, I didn't touch the default config but it actually doesn't match at all, even in V3.

[the remark this answers is not in the document]
Comment (derrickmehaffy) [reply packages/core/strapi/lib/middlewares/session.js:6]: That middleware has basically been in the same state since at least 2018/2019 it was never properly updated for anything.

[the remark this answers is not in the document]
Comment (alexandrebodin) [reply packages/core/strapi/lib/middlewares/session.js:6]: Yeah let's take the time to do this cleanly then

File: packages/core/strapi/lib/Strapi.js (hunk 9 above)
Comment (petersg83) [reply packages/core/strapi/lib/Strapi.js:198]: There is no way for the moment :P

File: packages/core/strapi/lib/middlewares/session.js (hunk 11 above)
[the remark this answers is not in the document]
Comment (petersg83) [reply packages/core/strapi/lib/middlewares/session.js:6]: Yes :)

File: examples/getstarted/config/middlewares.js [hunk 12]
```diff
@@ -10,6 +10,24 @@ module.exports = [
   'strapi::logger',
   'strapi::query',
   'strapi::body',
+  {
+    name: 'strapi::session',
+    config: {
```
[the remark this answers is not in the document]
Comment (petersg83) [reply examples/getstarted/config/middlewares.js:15]: I let secretKeys since it is mandatory to provide it otherwise it is generated in any case

**Comment by derrickmehaffy** [comment]
Will test it after the monday meeting @petersg83 :+1:

File: packages/core/strapi/lib/middlewares/session.js [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+    strapi.server.app.keys = secretKeys;
+  }
+
+  const config = defaultsDeep(defaultConfig, omit('secretKeys', userConfig));
+
+  strapi.server.use(session(config, strapi.server.app));
+  strapi.server.use((ctx, next) => {
+    ctx.state = defaultsDeep({ session: {} }, ctx.state);
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/middlewares/session.js:46]: we should avoid using lodash/fp here I think it might cause bugs to replace ctx.state instead of just setting session to an empty object.

File: packages/core/strapi/lib/middlewares/session.js [hunk 14]
```diff
@@ -0,0 +1,50 @@
...
+    let secretKeys = [];
+
+    if (has('secretKeys', userConfig)) {
+      secretKeys = userConfig.secretKeys;
+    } else if (has('SESSION_SECRET_KEYS', process.env)) {
+      secretKeys = process.env.SESSION_SECRET_KEYS.split(',');
+    } else {
+      // auto generate secret keys if they are not provided
+      for (let i = 0; i < 4; i++) {
+        secretKeys.push(uuid());
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/middlewares/session.js:31]: can we use the crypto lib to avoid adding a dependency for this

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 15]
```diff
@@ -32,6 +32,9 @@ module.exports = async ({ strapi }) => {
 
     if (!process.env.JWT_SECRET) {
       strapi.fs.appendFile('.env', `JWT_SECRET=${jwtSecret}\n`);
+      console.log(
```
Comment (alexandrebodin) [inline packages/plugins/users-permissions/server/bootstrap/index.js:35]: can you use strapi.log.debug or info instead

File: packages/core/strapi/lib/middlewares/session.js [hunk 16]
```diff
@@ -0,0 +1,50 @@
...
+      }
+      strapi.fs.appendFile('.env', `SESSION_SECRET_KEYS=${secretKeys.join(',')}\n`);
+      console.log(
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/middlewares/session.js:34]: can you use strapi.log.debug or info instead

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/core/strapi/lib/middlewares/session.js [hunk 17]
```diff
@@ -0,0 +1,45 @@
...
+    if (has('secretKeys', userConfig)) {
+      secretKeys = userConfig.secretKeys;
+    } else if (has('SESSION_SECRET_KEYS', process.env)) {
+      secretKeys = process.env.SESSION_SECRET_KEYS.split(',');
+    } else {
+      // auto generate secret keys if they are not provided
+      for (let i = 0; i < 4; i++) {
+        secretKeys.push(crypto.randomBytes(64).toString('hex'));
+      }
+      strapi.fs.appendFile('.env', `SESSION_SECRET_KEYS=${secretKeys.join(',')}\n`);
```
Comment (alexandrebodin) [inline packages/core/strapi/lib/middlewares/session.js:33]: As mentioned in DMs, we will need to handle some read-only mode for the .env file eventually. let's keep this in mind

Comment (petersg83) [reply packages/core/strapi/lib/middlewares/session.js:33]: Yes, we are doing that in a few places (U&P, api token, session middlewares). No issues from the community so far?

Comment (derrickmehaffy) [reply packages/core/strapi/lib/middlewares/session.js:33]: There is an issue with how we are writing to the .env yes. It was just mentioned in Discord and I'm having them create a bug report.

image

I also don't really care for how we are writing these either and we do it for some but not others, it's quite odd.

File: packages/core/strapi/lib/services/server/middleware.js [hunk 18]
```diff
@@ -45,7 +53,7 @@ const resolveMiddlewares = (config, strapi) => {
 
       middlewares.push({
         name: item,
-        handler: middlewareFactory({}, { strapi }),
+        handler: instanciateMiddleware(middlewareFactory, item, {}, strapi),
       });
```
Comment (hdeadman) [inline packages/core/strapi/lib/services/server/middleware.js:57]: Should be `instantiateMiddleware` rather than `instanciateMiddleware`

File: packages/core/strapi/lib/middlewares/session.js (hunk 17 above)
Comment (petersg83) [reply packages/core/strapi/lib/middlewares/session.js:33]: Interesting, @derrickmehaffy do you have any recommendation on how to handle this usecase?
We need the user to provide some secrets in order for Strapi to properly work. It is easier if they are autogenerated, but where should we store them and with which logic?

File: packages/core/strapi/lib/services/server/middleware.js (hunk 18 above)
Comment (petersg83) [reply packages/core/strapi/lib/services/server/middleware.js:57]: Thank you, fixed!

File: packages/core/strapi/lib/middlewares/session.js (hunk 17 above)
Comment (derrickmehaffy) [reply packages/core/strapi/lib/middlewares/session.js:35]: TBH I don't like that we are auto-writing to a .env, this is not something you usually do without asking the user.

I think every single one of these needs to have a config file option (server, admin, api, plugins, middlewares, whatever) by default and we set the generic random as the 2nd param like we used to. If they aren't using quickstart then we can ask at the CLI if they want a .env file but not every reboot.

Comment (derrickmehaffy) [reply packages/core/strapi/lib/middlewares/session.js:35]: Certain providers (like google) have very strict read-only filesystems that auto-writing files simply will not work and just crash the application.

File: packages/plugins/users-permissions/server/controllers/auth.js [hunk 19]
```diff
@@ -188,7 +188,10 @@ module.exports = {
     }
 
     // Ability to pass OAuth callback dynamically
-    grantConfig[provider].callback = _.get(ctx, 'query.callback') || grantConfig[provider].callback;
+    grantConfig[provider].callback =
+      _.get(ctx, 'query.callback') ||
+      _.get(ctx, 'session.grant.dynamic.callback') ||
```
Comment (alexandrebodin) [inline packages/plugins/users-permissions/server/controllers/auth.js:193]: what is this for ?

File: packages/core/strapi/lib/middlewares/session.js (hunk 17 above)
Comment (derrickmehaffy) [reply packages/core/strapi/lib/middlewares/session.js:35]: FYI another user just had an issue on this. I'm having them open a github issue on it
image

image

They are declaring the var using env vars and don't need the .env but we are trying to write it anyway on a system that is a enforced ROFS

File: packages/plugins/users-permissions/server/controllers/auth.js (hunk 19 above)
Comment (petersg83) [reply packages/plugins/users-permissions/server/controllers/auth.js:193]: It's a fix for https://github.com/strapi/strapi/issues/7405
The callback query param get lost along the flow and some usecases needs to keep it

File: packages/core/strapi/lib/middlewares/session.js (hunk 17 above)
Comment (alexandrebodin) [reply packages/core/strapi/lib/middlewares/session.js:35]: We only write the key if it's not defined in the conf or in the end vars. Which means it should be good for production as you should only deploy once you have set your env vars anyway. 

We will handle this in another PR so we can move forward with this one

**Review by alexandrebodin — APPROVED** [review]

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
I still have an issue with the default config not setting any keys and failing on startup. We just have to fix this so we can move forward

File: examples/getstarted/config/middlewares.js [hunk 20]
```diff
@@ -2,14 +2,15 @@
 
 const responseHandlers = require('./src/response-handlers');
 
-module.exports = [
+module.exports = ({ env }) => [
```
Comment (alexandrebodin) [inline examples/getstarted/config/middlewares.js:5]:
```suggestion
module.exports = [
```

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
I don't understand why we need all the env_path manipulations for the tests. If we use the generator we should just have a valid .env in the testApp 🤔 

Also I would keep the .env.example as when the dev will push their app they won't get a .env we should generate one with the missing env vars

**Comment by petersg83** [comment]
`env_path` : The `.env` is not detected because the script run is not located next to the `.env` file, so we need to specify the correct path. Before that the `.env` file of the testApp was full of generated token (each time the app was restarted they were generated again). Do you think we can do something simpler?

File: test/e2e.js [hunk 21]
```diff
@@ -52,7 +60,8 @@ const main = async (database, args) => {
     await cleanTestApp(appName);
     await generateTestApp({ appName, database });
 
-    await runAllTests(args).catch(() => {
+    await runAllTests(args).catch(e => {
+      console.error(e);
```
Comment (alexandrebodin) [inline test/e2e.js:64]: you can remove this I guess

Comment (petersg83) [reply test/e2e.js:64]: In some cases the error message was not printed in the shell without it. I think it's better to keep it then. Wdyt?

Comment (alexandrebodin) [reply test/e2e.js:64]: Is it logging twice in some cases then?

Comment (petersg83) [reply test/e2e.js:64]: It's not logged twice but we may want to avoid certain error logs, I'll change the code

Comment (petersg83) [reply test/e2e.js]: updated 👌

File: packages/generators/app/lib/resources/files/config/server.js [hunk 22]
```diff
@@ -1,4 +1,7 @@
 module.exports = ({ env }) => ({
   host: env('HOST', '0.0.0.0'),
   port: env.int('PORT', 1337),
+  app: {
+    keys: env.array('APP_SECRETS'),
```
Comment (alexandrebodin) [inline packages/generators/app/lib/resources/files/config/server.js:5]: shouldn't we call that APP_KEYS ?

Comment (petersg83) [reply packages/generators/app/lib/resources/files/config/server.js:5]: Yes let's do that

**Review by alexandrebodin — APPROVED** [review]
LGTM. It's a lot cleaner than previously
