### PR TITLE
Fix `hasTable` is undefined for schema postgres users

### LINKED ISSUE #15603: Upgrading 4.6.0 hasTable undefined error
### Required System information

- Node.js version: v16.17.0
- NPM version: 8.15.0
- Strapi version: 4.6.0
- Database: PostgreSQL 14.6
- Operating system: macOS Monterey v12.6

### Describe the bug

After upgrading strapi from 4.5.6 to 4.6.0
```
error: Cannot read properties of undefined (reading 'hasTable')
TypeError: Cannot read properties of undefined (reading 'hasTable')
    at isLinkTableEmpty (/Users/***/node_modules/@strapi/database/lib/validations/relations/bidirectional.js:35:49)
    at validateBidirectionalRelations (/Users/***/node_modules/@strapi/database/lib/validations/relations/bidirectional.js:63:34)
    at validateRelations (/Users/***/node_modules/@strapi/database/lib/validations/relations/index.js:10:46)
    at validateDatabase (/Users/***/node_modules/@strapi/database/lib/validations/index.js:11:32)
    at Function.Database.init (/Users/***/node_modules/@strapi/database/lib/index.js:117:9)
    at Strapi.bootstrap (/Users/***/node_modules/@strapi/strapi/lib/Strapi.js:417:30)
    at Strapi.load (/Users/***/node_modules/@strapi/strapi/lib/Strapi.js:488:16)
    at async Strapi.start (/Users/***/node_modules/@strapi/strapi/lib/Strapi.js:217:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

I have deleted node_modules and yarn.lock and run ```yarn build```  but no luck 

### Additional context

Project dependencies in package.json:

```
"devDependencies": {},
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "1.1.3",
    "@retikolo/drag-drop-content-types": "^1.3.4",
    "@strapi/plugin-i18n": "^4.6.0",
    "@strapi/plugin-upload": "^4.6.0",
    "@strapi/plugin-users-permissions": "^4.6.0",
    "@strapi/provider-email-sendgrid": "^4.6.0",
    "@strapi/provider-upload-aws-s3": "^4.6.0",
    "@strapi/strapi": "4.6.0",
    "@strapi/utils": "^4.6.0",
    "aws-sdk": "^2.1303.0",
    "minio-for-strapi-v4": "^1.0.7",
    "pg": "^8.8.0",
    "slugify": "^1.6.5",
    "strapi-plugin-populate-deep": "^2.0.0",
    "strapi-plugin-preview-button": "^1.1.2",
    "strapi-provider-upload-minio-ce": "^1.1.0"
  },
```

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

Fix #15603 

### Why is it needed?

Users using postgres with a schema and having the double inverseBy bug (#14428) cannot start Strapi.

### How to test it?

1. Create a schema in your postgres DB:
```SQL
# SQL
CREATE SCHEMA myschema;
```
2. Set the schema in the database config `./config/database.js`: 
```JS
module.exports = ({ env }) => ({
  client: 'postgres',
  connection: {
    // ...
    schema: 'myschema',
    // ...
  },
});
```
3. Create a many-many relation between 2 content-types through the content-type builder
4. Identify the content-type schema where the previously created relation has the key `mappedBy`
5. Modify this schema file by replacing the key `mappedBy` by `inversedBy`
6. Restart the app
7. See that there is no error anymore

### Related issue(s)/PR(s)

#15603

### CODE REVIEW

File: packages/core/database/lib/validations/relations/bidirectional.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ const getLinksWithoutMappedBy = (db) => {
 
 const isLinkTableEmpty = async (db, linkTableName) => {
   // If the table doesn't exist, it's empty
-  const exists = await db.getConnection().schema.hasTable(linkTableName);
+  const exists = await db.getSchemaConnection().hasTable(linkTableName);
```
Comment (Marc-Roig) [inline packages/core/database/lib/validations/relations/bidirectional.js:35]: Forgot we had  getSchemaConnection. Good catch!

**Review by Marc-Roig — APPROVED** [review]
LGTM!

File: packages/core/database/lib/validations/relations/bidirectional.js (hunk 1 above)
Comment (gu-stav) [reply packages/core/database/lib/validations/relations/bidirectional.js:35]: Just a random question: why is this not catched by any test? :)

Comment (Marc-Roig) [reply packages/core/database/lib/validations/relations/bidirectional.js:35]: That is a very good question and a thing we could discuss better.

This is caused by a custom configuration on postgres we didnt account for. For the default config is working ok.

We have faced multiple issues caused by db configs

GTID issues
Mariadb clusters
Postgress custom schemas

We could extend a list and periodically test for it, or see if there is a possibility to add it in the CI.

It is quite complicated to account for things like this in our current tests today.

Comment (gu-stav) [reply packages/core/database/lib/validations/relations/bidirectional.js:35]: Interesting. I imagine it would be quite hard to run all tests against every combination of configuration. Do you see a way to create tests, e.g. to mimic a specific configuration? E.g. to mock something in a way to simulate such a configuration?
