### PR TITLE
Fix init reset password permission

### LINKED ISSUE #6440: Reset Password permission is disabled by default
**Describe the bug**
Reset Password permission is disabled by default. So you can send an email for a password reset but can't actually reset it.

**Steps to reproduce the behavior**

1. **POST** `/auth/forgot-password { email: 'some@email.com' }`
2. **POST** `/auth/reset-password { code: 'codeFromEmail', password: 'newPassword', ... }`
3. Receive `Forbidden 403`

**Expected behavior**
Password reset successfully.

**System**

- Node.js version: v14.2.0
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: mongodb
- Operating system: MacOs

**Additional context**
I've debugged a code a little and I guess the issue is related to https://github.com/strapi/strapi/pull/5655 (Change Password was renamed to Reset Password) and especially to the following code: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L25

Changing `changepassword` to `resetpassword` might resolve the issue.

### PR DESCRIPTION
**Pull request by lauriejim**
#### Description of what you did:
When the `changepassword` function has been renamed `resetpassword`.
the init permissions hasn't been updated?
So the function has been no longer available by default for the public role.

close #6440

### CODE REVIEW

File: packages/strapi-plugin-users-permissions/services/UsersPermissions.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ const DEFAULT_PERMISSIONS = [
     type: 'users-permissions',
     roleType: 'public',
   },
-  { action: 'changepassword', controller: 'auth', type: 'users-permissions', roleType: 'public' },
+  { action: 'resetPassword', controller: 'auth', type: 'users-permissions', roleType: 'public' },
```
Comment (nicksp) [inline packages/strapi-plugin-users-permissions/services/UsersPermissions.js:25]: @alexandrebodin I know this is merged already, but this seems like will not work as one might expected. The correct action name is `resetpassword`. 🤔
