### PR TITLE
Store emails in lowercase + add /api as prefix

### LINKED ISSUE #8235: Emails stored in mixed case when created with provider login/registration
**Describe the bug**
When logging in with a provider (Microsoft for example), a user account is automatically created if there is not one already. When this account is created, the username/email can be mixed case from the provider (Test_User@domain.com). If you then modify this user account, the admin user-edit function will save as lowercase email (which is what should happen). However, when the user tries to log in again, it compares the received email (mixed case) to the stored email in the database (lowercase) and will not match. 

**Steps to reproduce the behavior**

1. Create user with OAuth provider that has mixed case email (Microsoft)
2. Note that user is created in database with mixed case email and username
3. User should be able to login to system
4. Open user account in admin panel and edit any parameter (role for example)
5. Notice user's email is now lowercase
6. User is no longer able to login to system

**Expected behavior**
There's one of two routes Strapi can go on this, but it needs to be consistent and global:
1. ALL emails and usernames should ALWAYS be stored lowercase so the comparison can always be done with lowercased strings
2. Whenever querying the database for username/email, the LOWER()/UPPER() should ALWAYS be used on the field and value before comparison
- SELECT * FROM sometable WHERE UPPER(email) = UPPER('value') 

**Screenshots**
When user created by logging in with provider
image
After editing role for user
image

**System**

- Node.js version: 14.13.0
- NPM version: 6.14.8
- Strapi version: 3.2.0
- Database: Heroku Postgres
- Operating system: Heroku dyno

### PR DESCRIPTION
**Pull request by petersg83**
Replaces https://github.com/strapi/strapi/pull/8247
fix #8235 

Emails are now stored in lowercase in database, in order to always compare lowercased emails.

All routes are now prefixed with `/api`. It might change in the future for something like `/plugin-api/users-permissions/` in order to scope the different apis.

### CODE REVIEW

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 1]
```diff
@@ -39,6 +38,9 @@ module.exports = async ({ strapi }) => {
 
 const initGrant = async pluginStore => {
   const grantConfig = {
+    defaults: {
+      prefix: '/api/connect',
```
Comment (alexandrebodin) [inline packages/plugins/users-permissions/server/bootstrap/index.js:42]: is it used by grant autmatically ?

Comment (petersg83) [reply packages/plugins/users-permissions/server/bootstrap/index.js:42]: yes

**Review by alexandrebodin — APPROVED** [review]
LGTM
