### PR TITLE
Fix JSON parse on Postgres & Bulk Publish JSON validations

### LINKED ISSUE #16672: Issue with JSON field that has value as string
## Bug report
A json field with value as json string gets turned into object after upgrading from 4.9.0 to 4.10.1

### Required System information

- Node.js version: v16.13.2
- NPM version: v8.1.2
- Strapi version: v4.10.1
- Database: PostgreSQL v12.0
- Operating system: Ubuntu 20.04.6 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug
A json field that has a value being string is turned into an object. This shouldn't happen because string is indeed a valid json value regardless of what that string contains. But now if that string contains a json object it will explicitly be turned into an object. If that was the wanted behavior, I would just entered the value as an object not string.
This behavior appeared after [#16310](https://github.com/strapi/strapi/pull/16310)

### Steps to reproduce the behavior

1. Create a json field.
2. Set the value of the field to "{\"a\": 123}"
3. Save the entry.

### Expected behavior

The value of the field should remain "{\"a\": 123}". Instead it is turned into { "a": 123 }

### Additional context

I know that it's not likely that anyone would enter the value of json field as json string explicitly from the admin UI but this examples shows the issue better.
Our real case is that we have a custom field that has a type json and the value we store in that field is a json string. so when the value of the filed is fetched from the server it tries to parse it then crashes because it finds the value to be an object not a string.

#### Before saving:
Field
create

### After saving
find
error
page

### PR DESCRIPTION
**Pull request by Feranchz**
### What does it do?

This PR handle 2 different issues, both related to the JSON input.

- #16672: On this PR (#16310) we removed the custom parsed for JSONB from postgres, this means that right now are parsing JSON values two times when using PostgresSQL. First time is automatically by Postgres parsers, and a second time on this [file](https://github.com/strapi/strapi/blob/main/packages/core/database/lib/fields/json.js). Because of the catch we didn't see the error, but this cause problems with string values like `{\"a\": 123}`. We are parsing it one time (we get the string) and the second time (we transform it from a string to a object even if that is not what we want). For more details see the issue
- #17598: To validate JSON fields we send the json stringified, so we parse it and if nothing happens, if okay. This is fine for the Edit Page because the JSON input automatically send the stringified version (just for validiting). But on Bulk Publish we have the entry with the json as an object (if it is), so I added a option to the schema validator to stringify the json before validate if we want

### How to test it?

- Run Strapi app using Postgres as DB and try to save this value as a JSON: `"{\"a\": 123}"`, it should keep the string format and not transform it to an object before saving it
- Try to publish entries with JSON values

### Related issue(s)/PR(s)

Fixes #16672 & #17598

### CODE REVIEW

File: packages/core/admin/admin/src/content-manager/utils/schema.js [hunk 1]
```diff
@@ -55,7 +55,12 @@ const getAttributes = (data) => get(data, ['attributes'], {});
 const createYupSchema = (
   model,
   { components },
-  options = { isCreatingEntry: true, isDraft: true, isFromComponent: false }
+  options = {
+    isCreatingEntry: true,
+    isDraft: true,
+    isFromComponent: false,
+    formatJsonBeforeValidate: false,
```
Comment (markkaylor) [inline packages/core/admin/admin/src/content-manager/utils/schema.js:62]: I think it would be nice if we could avoid adding another option. I haven't had time to look but I'm confused why the JSON is stringified in the edit view but still an object in the list view. Do you know why that is the case? IMO it would be better to have consistent data instead of handling different cases.

Comment (markkaylor) [reply packages/core/admin/admin/src/content-manager/utils/schema.js:62]: oh sorry missed this:

Run Strapi app using Postgres as DB and try to save this value as a JSON: "{\"a\": 123}", it should keep the string format and not transform it to an object before saving it

so the data from the server is an object not a string?

Comment (markkaylor) [reply packages/core/admin/admin/src/content-manager/utils/schema.js:62]: > On the Edit View, the JSON input would stringify that before make the validation
Do you know where this happens and why? 

Sorry not trying to be a bug, I'm just thinking we are going to end up stringifying in two places when it could be done in one place.

File: packages/core/admin/admin/src/content-manager/utils/schema.js [hunk 2]
```diff
@@ -214,6 +219,7 @@ const createYupSchemaAttribute = (type, validations, options) => {
   if (type === 'json') {
     schema = yup
       .mixed(errorsTrads.json)
+      .transform((value) => (options.formatJsonBeforeValidate ? JSON.stringify(value) : value))
```
Comment (markkaylor) [inline packages/core/admin/admin/src/content-manager/utils/schema.js:222]: Could we avoid the option with a typeof check?

Comment (markkaylor) [reply packages/core/admin/admin/src/content-manager/utils/schema.js:222]: That's true. Also it looks like it is impossible to save a draft with invalid JSON. So if we have an object then the input must be valid, right? We only need to run JSON format validation in the edit view since it is impossible to have invalid JSON in the ListView. 

So would it make sense to get rid of this transform and just return true `if typeof === object || null`? It sounds like the only validation error we should be reporting in the list view for JSON is `required`.

File: packages/core/admin/admin/src/content-manager/utils/schema.js [hunk 3]
```diff
@@ -55,7 +55,12 @@ const getAttributes = (data) => get(data, ['attributes'], {});
 const createYupSchema = (
   model,
   { components },
-  options = { isCreatingEntry: true, isDraft: true, isFromComponent: false }
+  options = {
+    isCreatingEntry: true,
+    isDraft: true,
+    isFromComponent: false,
+    disabledIsJSONTest: false,
```
Comment (markkaylor) [inline packages/core/admin/admin/src/content-manager/utils/schema.js:62]: ok I guess we will have to do it this way. Maybe we can find something better in the future. I don't like the name though. What do you think of `isJSONTestDisabled`? I was also considering `isListView` and just use that to determine what to do. What do you think is best?

**Comment by markkaylor** [comment]
@Feranchz I've tested the first issue this PR handles and looks like it is working

For the JSON validations in bulk publish I think we have another issue:
- If I mark the field as required even if I save a draft with a value the validation in the modal still says it is required.
- It is impossible to save an empty JSON field that is required on a draft entry. Draft entries should not consider validation. For example Restaurant can be saved with all fields empty despite the fact that many of them are required. This is on main.

Although this PR resolves two issues around JSON, I do not think the issues are related and therefore, in my opinion, they should be separate PRs. I think the second issue you are resolving is going to stall the merge of the first issue you are solving. Not really a big deal but just something to keep in mind :)

**Review by markkaylor — APPROVED** [review]

**Review by Marc-Roig — APPROVED** [review]
