### PR TITLE
fix: ids in query.createMany return type

### LINKED ISSUE #16877: Wrong typing on createMany() function
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.7
- Strapi version: 4.10.7
- Database: SQLite 3
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am not able to use the `createMany()` function of Query Engine API due to wrong typing. As for now, this function does not return ids of created entities as it should be by docs:

https://docs.strapi.io/dev-docs/api/query-engine/bulk-operations#createmany

In node_modules\@strapi\database\lib\index.d.ts the  `createMany()` function definition looks like this:

`createMany(params: CreateManyParams<AllTypes[T]>): Promise<{ count: number }>;`

It should look like this:

`createMany(params: CreateManyParams<AllTypes[T]>): Promise<{ count: number, ids: ID[] }>;`

### Steps to reproduce the behavior

1. Create Typescript file, e.g. book.ts
2. Write the `createMany()` Query 
3. Try to fetch `ids` from the result object

### Expected behavior

I am able to fetch the ids with no errors.

### Screenshots

image

### Code snippets

```    
    // Create roles with permissions.
    // Source: node_modules/@strapi/plugin-users-permissions/server/services/role.js
    const roles = await strapi.db
      .query('plugin::users-permissions.role')
      .createMany({
        data: missingRoles,
      });

    // We need to fetch ids of created roles from result object
    const { ids } = roles;
```

### Additional context

This problem arose when I started migrating the Strapi project from JavaScript to TypeScript.

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

`strapi.db.query(uid).createMany()` returns:

https://github.com/strapi/strapi/blob/e3bb9a99942a8373355fdf88259ebddfa28a2108/packages/core/database/lib/entity-manager/index.js#L273-L276

But our current types were defined as if it only returned the count.

https://github.com/strapi/strapi/blob/e3bb9a99942a8373355fdf88259ebddfa28a2108/packages/core/database/lib/index.d.ts#L122

This PRs updates those types.

### Related issue(s)/PR(s)

Fixes #16877

### CODE REVIEW

File: packages/core/database/lib/index.d.ts [hunk 1]
```diff
@@ -54,6 +54,7 @@ interface FindParams<T> {
     | { [K in Sortables<T>]?: Direction }[];
   // TODO: define nested obj
   populate?: (keyof T)[];
+  fre;
```
Comment (nathan-pichon) [inline packages/core/database/lib/index.d.ts:57]: ?

Comment (Marc-Roig) [reply packages/core/database/lib/index.d.ts:57]: woops

Comment (Marc-Roig) [reply packages/core/database/lib/index.d.ts]: fixed 🌚

**Review by Convly — COMMENTED** [review]
Where is this ID type coming from?

**Review by nathan-pichon — APPROVED** [review]
Also, we cannot trust those types, as the result can be mutated by hooks 😅 

Don't we have an ID type?

**Comment by Marc-Roig** [comment]
> Where is this ID type coming from?
Not really sure but it's used in this file

**Comment by Convly** [comment]
> Also, we cannot trust those types, as the result can be mutated by hooks sweat_smile
> 
> Don't we have an ID type?

tbh, the types defined here are reminiscences from v4 development and are nowhere near the quality that we're targeting. It was mostly experiments rather than a precise type system.
It's currently more about trying to keep things working while we wait for the new types overhaul rather than trying to spawn something smart.

**Comment by Convly** [comment]
> apparently there is an ID defined here [`main`/packages/core/strapi/lib/services/entity-service/index.d.ts#L4](https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/services/entity-service/index.d.ts?rgh-link-date=2023-06-01T14%3A45%3A43Z#L4)

Well... Since it's not exported, then how is it resolved from this file, that's weird :sweat_smile:

**Comment by Marc-Roig** [comment]
apparently it is not resolved 🤔 it treats ID as any

**Comment by Marc-Roig** [comment]
@Convly @nathan-pichon I added the ID type in the database type definitions [`52b37c3` (#16884)](https://github.com/strapi/strapi/pull/16884/commits/52b37c3fcfc928363cbc7cb278ef72a3eff9621b)

File: packages/core/strapi/lib/services/entity-service/index.d.ts [hunk 2]
```diff
@@ -1,5 +1,4 @@
-import { Database } from '@strapi/database';
-import type { ID } from '@strapi/database';
+import { Database, ID } from '@strapi/database';
```
Comment (Convly) [inline packages/core/strapi/lib/services/entity-service/index.d.ts:1]:
```suggestion
import type { Database, ID } from '@strapi/database';
```

**Review by Convly — APPROVED** [review]

**Review by nathan-pichon — APPROVED** [review]
