### PR TITLE
Assume selection is text when creating a link

### LINKED ISSUE #7890: Link creation might not be intuitive in RichText fields
**Describe the bug**
In a RichText editor, when creating a link after selecting some content, the default behavior is that it takes the selected content and put it in the (), and not in the [].

[video here](https://drive.google.com/file/d/1onPW5fMa14IzF2nJQBrHYLIk_0EZZ73_/view?usp=sharing
)
The () is where to put the URL
The [] is where to put the text that is going to be linked

The default behavior works well if you first write the URL then add the text, but it's not that great the other way around

**Steps to reproduce the behavior**
1. Create a new entity of a CT which has a RichText field
2. Write some content in the RichText field
3. Select some text to link
4. Click on the link icon in the top of the editor
5. See the behavior

**Expected behavior**
I propose we change it to do it the other way around as it is today. 
when selecting content and creating a link, the content will be put in the [] and a placeholder will be put in the () (ex: https://www.url.com)

But before that, I need to know if it's really something that could help people or if the current behavior is preferred.
What do you think Community and Strapi team? Let me know in the comment?

**System**
- Strapi version: tested on v3.0.0 beta 20 & v3.1.3

### PR DESCRIPTION
**Pull request by jlsjonas**
Fixes #7890

#### Description of what you did:
Title says it all, when replacing a selection, assume the selection is text and not a link; as per the issue

### CODE REVIEW

**Comment by sam-pires** [comment]
Hello @jlsjonas,
Thanks for the PR 👍 

I still have the same behavior as the current one. It has not changed.
@soupette wdyt?

File: packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/helpers.js [hunk 1]
```diff
@@ -55,9 +55,9 @@ export function getBlockContent(style) {
       };
     case 'LINK':
       return {
-        innerContent: 'link',
-        endReplacer: ')',
-        startReplacer: '[text](',
+        innerContent: 'text',
+        endReplacer: '](https://example.org)',
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/helpers.js:59]: the endReplacer could just be `]`

**Review by soupette — CHANGES_REQUESTED** [review]
In order to make the selected change you'll also need to update `Wysiwyg/constants.js` file L.79 with the following:


```
{
  label: 'Link',
  style: 'LINK',
  className: 'link',
  hideLabel: true,
  handler: 'addContent',
  text: '[textToReplace](link)',
},
```

**Review by soupette — APPROVED** [review]
LGTM!

Thanks a lot for your contribution.

**Comment by jlsjonas** [comment]
@soupette You're welcome!
What do we do with the coverage report failing at -0% due to lack of testing in that area of the code?

**Comment by soupette** [comment]
> @soupette You're welcome!
> What do we do with the coverage report failing at -0% due to lack of testing in that area of the code?

Appart from adding some tests to this component not much. Even though the coverage doesn't pass we will still merge this PR.
