### PR TITLE
Manage email and upload providers from an npm organisation

### LINKED ISSUE #2723: Org namespaced email providers do not get registered
**Informations**
- **Node.js version**: 11.6.0
- **NPM version**: 6.5.0
- **Strapi version**: alpha 20
- **Database**: 10.3.8-MariaDB
- **Operating system**: macos 10.14.2
- **(Optional) Link to your Project**:  https://www.npmjs.com/package/@teamgi/strapi-provider-email-sparkpost

**What is the current behavior?**
I'm not seeing my custom email provider in the admin after installing it via npm.

**Steps to reproduce the problem**
- I run the following command in my project root:
`npm i @teamgi/strapi-provider-email-sparkpost --save`
- I start strapi
- I visit `/admin/plugins/email/configurations/development`
- Under providers I only see `Sendmail`

**What is the expected behavior?**
I expect to see a provider named `Sparkpost`

**Suggested solutions**
The issue seems to be in `plugins/email/config/functions/bootstrap.js`. It looks like it does not support org namespaced package names. I think it would be better to try to programmatically retrieve the list of npm packages rather than simply relying on the folder names.

### PR DESCRIPTION
**Pull request by lauriejim**
#### Description:

Know you can install provider from a npm organisation.
This fix #2723 issue.

#### My PR is a:
- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:
- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

File: packages/strapi-plugin-email/config/functions/bootstrap.js [hunk 1]
```diff
@@ -30,6 +30,20 @@ module.exports = async cb => {
         return _.startsWith(node_module, 'strapi-provider-email') || _.startsWith(node_module, 'strapi-email');
       });
 
+      node_modules.filter((node_module) => {
+        return node_module.startsWith('@');
+      })
+        .forEach((orga) => {
```
Comment (Aurelsicoko) [inline packages/strapi-plugin-email/config/functions/bootstrap.js]: Do we really need to loop on all organization whereas we look for a specific package `@strapi/strapi-provider-email`?

File: packages/strapi-plugin-upload/config/functions/bootstrap.js [hunk 2]
```diff
@@ -30,6 +30,20 @@ module.exports = async cb => {
         return _.startsWith(node_module, 'strapi-provider-upload') || _.startsWith(node_module, 'strapi-upload');
       });
 
+      node_modules.filter((node_module) => {
+        return node_module.startsWith('@');
+      })
+        .forEach((orga) => {
```
Comment (Aurelsicoko) [inline packages/strapi-plugin-upload/config/functions/bootstrap.js]: Same here...
