### PR TITLE
Fix #5302 - Uninstall plugin: function to delete folder with files

### LINKED ISSUE #5302: Uninstall script for documentation plugin doesn't work
**Describe the bug**
Uninstall script for documentation plugin doesn't work.

**Steps to reproduce the behavior**
1. Install documentation plugin
2. Add some new content types.
3. Try to uninstall documentation plugin
```
yarn strapi uninstall documentation
```
4. See error. 
```
╰─ yarn strapi uninstall documentation                                                                                                                                                                                                     ─╯
yarn run v1.21.1
$ strapi uninstall documentation
? Do you want to delete the plugin generated files in the extensions folder? Yes
✔ Uninstalling dependencies
The "path" argument must be one of type string, Buffer, or URL. Received type undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
5. Run Strapi and `Documentation` section is still in the admin panel but throws an error when we try to open it.

**Expected behavior**
Documentation plugin is removed without error and admin panel UI is updated correctly.

**System**
- Node.js version: 10.18.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: MongoDB
- Operating system: macOS Catalina

### PR DESCRIPTION
**Pull request by LucasMatuszewski**
#### Description of what you did:
Fix for #5302 - there were no argument with folder path to delete. And previously used function didn't delete folder with it's content. The new `removeSync` delete folder with all content.
Tested locally and works fine.

I don't see any tests for /lib/uninstall.js
Documentation needs no changes, imho.

**Before Merge:**  shouldn't it also delete this folders?
```
/extensions/user-permissions/documentation
/extensions/email/documentation/1.0.0 
/extensions/upload/documentation/1.0.0
```
I could add some code to delete this folders if plugin name === "documentation".

**FYI:** this is my first Open Source contribution. Any suggestions appreciated :)

### CODE REVIEW

File: packages/strapi/lib/commands/uninstall.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ module.exports = async (plugins, { deleteFiles }) => {
   const loader = ora();
   const dir = process.cwd();
 
-  const pluginArgs = plugins.map(name => `strapi-plugin-${name}`);
+  const pluginArgs = plugins.map((name) => `strapi-plugin-${name}`);
```
Comment (LucasMatuszewski) [inline packages/strapi/lib/commands/uninstall.js:24]: If you wold like to avoid Arrow Function Parentheses I suggest to add in `.prettierrc.js` file:
```
arrowParens: 'avoid',
```

**Comment by alexandrebodin** [comment]
Hi @LucasMatuszewski thank you and congrats on your first open source contribution 🎉 

Can you check the DCO check in the PR so the PR is mergeable :)

**Comment by LucasMatuszewski** [comment]
> Can you check the DCO check in the PR so the PR is mergeable :)
Hi @alexandrebodin - sorry for delay. I had too much on my head. I will fix it during a weekend.

Could you answer this?

> shouldn't it also delete this folders?
```
> /extensions/user-permissions/documentation
> /extensions/email/documentation/1.0.0 
> /extensions/upload/documentation/1.0.0
```
> I could add some code to delete this folders if plugin name === "documentation".

**Comment by alexandrebodin** [comment]
> > Can you check the DCO check in the PR so the PR is mergeable :)
> 
> Hi @alexandrebodin - sorry for delay. I had too much on my head. I will fix it during a weekend.
> 
> Could you answer this?
> 
> > shouldn't it also delete this folders?
> 
> ```
> > /extensions/user-permissions/documentation
> > /extensions/email/documentation/1.0.0 
> > /extensions/upload/documentation/1.0.0
> ```
> 
> > I could add some code to delete this folders if plugin name === "documentation".

Hi, no problem ;) 

For the question, I think a plugin should cleanup what it created. For now this is not something we developed in the plugins as there are not real plugin APIs but this will change in the future and it wil be a good opprotunity to add this behavior then :)

**Comment by LucasMatuszewski** [comment]
@alexandrebodin Done, Only sign off ?
If I would know that it will take only 2 minutes... I would do it sooner :)

**Comment by LucasMatuszewski** [comment]
Thanks for approval :)
