### PR TITLE
Yarn support

### LINKED ISSUE #1183: Can't install strapi-cli globally with yarn
**Informations**
- **Node.js version**: v10.1.0
- **yarn version**: 1.6.0
- **Strapi version**: latest of alpha version
- **Database**:
- **Operating system**: Ubuntu 18.04
 

**What is the current behavior?**
Can't install strapi-cli globally with yarn

**Steps to reproduce the problem**
just run the following command
`yarn global add strapi@alpha`

**What is the expected behavior?**

**Suggested solutions**

---

- [x] I'm sure that this issue hasn't already been referenced.

### PR DESCRIPTION
**Pull request by soupette**
My PR is a:
🚀 New feature

Main update on the:
Framework

This PR allows to install Strapi with [Yarn](https://yarnpkg.com/lang/en/).
Fixes #1183

**In order to test this PR**:

- Create a private registry like explained in @Aurelsicoko's [blog post](https://yarnpkg.com/lang/en/)
- Publish Strapi to this registry
- Uninstall npm globally `nom uninstall npm -g`
  - Check that npm is uninstalled by running `npm -v`
- Install yarn `brew install without-node`
- Change yarn registry : `yarn config set registry http://localhost:4873/`

***Expected behaviour*** : Strapi should be installed and be able to start and used with `yarn`.

Run `yarn global add strapi@alpha` to install strap globally.

**Important**

`This PR only allows to install Strapi globally with yarn.`
The development to allow to customise the admin (changing the logo...) when Strapi is installed with yarn has not been undertaken yet . We need to update all the packages' scripts that use `npm run` in order to make it work completely. Also, installing a plugin with yarn is not currently possible as explained previously.

### CODE REVIEW

**Comment by lauriejim** [comment]
screen shot 2018-06-30 at 18 05 31
Have an issue, still have a `npm` dependency

File: packages/strapi-generate-new/lib/after.js [hunk 1]
```diff
@@ -46,52 +50,71 @@ module.exports = (scope, cb) => {
   const dependencies = _.get(packageJSON, 'dependencies');
   const strapiDependencies = Object.keys(dependencies).filter(key => key.indexOf('strapi') !== -1);
   const othersDependencies = Object.keys(dependencies).filter(key => key.indexOf('strapi') === -1);
-  const globalRootPath = execSync('npm root -g');
+  // Add this check to know if we are in development mode so the creation is faster.
+  const isStrapiInstalledWithNPM = packageManager.isStrapiInstalledWithNPM();
+  const globalRootPath = isStrapiInstalledWithNPM ? execSync('npm root -g') : execSync(packageManager.commands('root -g'));
```
Comment (Aurelsicoko) [inline packages/strapi-generate-new/lib/after.js]:
```js
const globalRootPath = packageManager.commands('root -g');
````

In the `commands` function, it already verifies is the package has been installed using npm or not?

File: packages/strapi-generate-new/lib/before.js [hunk 2]
```diff
@@ -207,7 +210,14 @@ module.exports = (scope, cb) => {
               });
           }),
           new Promise(resolve => {
-            let cmd = `npm install --prefix "${scope.tmpPath}" ${scope.client.connector}@alpha`;
+            const isStrapiInstalledWithNPM = packageManager.isStrapiInstalledWithNPM();
+            let packageCmd = isStrapiInstalledWithNPM ? `npm install --prefix "${scope.tmpPath}" ${scope.client.connector}@alpha` : packageManager.commands('install --prefix', scope.tmpPath);
```
Comment (Aurelsicoko) [inline packages/strapi-generate-new/lib/before.js]: Write a command for this one? Also, the first command installs a specific package with npm and it seems to install nothing with yarn?

```js
let packageCmd = packageManager.commands('install --prefix', scope.tmpPath, scope.client.connector);
```

Comment (soupette) [reply packages/strapi-generate-new/lib/before.js]: We don't need to pass the connector since the `packageManager` will return either `npm install --prefix ${path}` or `yarn --cwd ${path} add` and we add the connector to install in the next line.

**Comment by Aurelsicoko** [comment]
LGTM 👍
