### PR TITLE
Fix hasMany admin users making app crash

### LINKED ISSUE #11891: [v4] relation to admin users making app crash
### Describe the bug

When you make a relation to admin users the detail of the resource crashed

### Steps to reproduce the behavior

Create a relation to admin users:
image

Go to the detail of one row of this resource and you'll have a blank page
image

### Expected behavior

We should be able to access detail and like admin users to the resource.

### System

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: MySQL
- Operating system: Windows 11

### LINKED ISSUE #12014: Cannot edit existing collection entries
### Describe the bug

I have bootstrapped a brand new Strapi app, v. 4.0.2 with node 16.13.1 using the yarn installation script.
I am creating a simple Blog application. With my "Post" content type (collection) I can create entries but when I save it, though it actually saves it, I get a blank screen and I have to restart from the admin home. Also, when accessing these entries, I get the same white screen and no possibility to access again to edit my content. For all the other content types, instead, I get no errors.

Here's the errors shown in the console in both cases:
```shell
main.d3ce37d0.js:2 TypeError: te.map is not a function
    at content-manager.b0919fbd.chunk.js:1:170710
    at Object.useMemo (main.d3ce37d0.js:2:1927855)
    at t.useMemo (main.d3ce37d0.js:2:2093530)
    at B (content-manager.b0919fbd.chunk.js:1:170673)
    at si (main.d3ce37d0.js:2:1921890)
    at Xu (main.d3ce37d0.js:2:1974187)
    at ks (main.d3ce37d0.js:2:1961428)
    at Ps (main.d3ce37d0.js:2:1961356)
    at Ms (main.d3ce37d0.js:2:1961219)
    at xs (main.d3ce37d0.js:2:1958185)
fu @ main.d3ce37d0.js:2
main.d3ce37d0.js:2 Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (3706.37d8dec1.chunk.js:2:1600017)
    at Gi (main.d3ce37d0.js:2:1934521)
    at Qi (main.d3ce37d0.js:2:1934318)
    at Xu (main.d3ce37d0.js:2:1975260)
    at ks (main.d3ce37d0.js:2:1961428)
    at Ps (main.d3ce37d0.js:2:1961356)
    at Ms (main.d3ce37d0.js:2:1961219)
    at xs (main.d3ce37d0.js:2:1958185)
    at main.d3ce37d0.js:2:1907682
    at t.unstable_runWithPriority (main.d3ce37d0.js:2:2108478)
fu @ main.d3ce37d0.js:2
main.d3ce37d0.js:2 Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (3706.37d8dec1.chunk.js:2:1600017)
    at Gi (main.d3ce37d0.js:2:1934521)
    at Qi (main.d3ce37d0.js:2:1934318)
    at Xu (main.d3ce37d0.js:2:1975260)
    at ks (main.d3ce37d0.js:2:1961428)
    at Ps (main.d3ce37d0.js:2:1961356)
    at Ms (main.d3ce37d0.js:2:1961219)
    at xs (main.d3ce37d0.js:2:1958185)
    at main.d3ce37d0.js:2:1907682
    at t.unstable_runWithPriority (main.d3ce37d0.js:2:2108478)
```

### Steps to reproduce the behavior

1. Clone my [public repo](https://github.com/artcoded-net/strapi-template-corporateblog)
2. Start the app in dev mode
3. Create a "Post" entry
4. See the error when saving the entry and when trying to access/edit the already created entry

### Code snippets

Here is my "post" content schema:
```
{
  "kind": "collectionType",
  "collectionName": "posts",
  "info": {
    "singularName": "post",
    "pluralName": "posts",
    "displayName": "Post",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string",
      "required": true,
      "unique": true,
      "minLength": 3
    },
    "Authors": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "admin::user"
    },
    "Cover": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "Content": {
      "type": "richtext",
      "required": true
    },
    "PostSEO": {
      "type": "component",
      "repeatable": false,
      "component": "seo.seo-information"
    },
    "Slug": {
      "type": "uid",
      "targetField": "Title",
      "required": true
    },
    "tags": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::tag.tag"
    }
  }
}
```

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: v. 4.0.2
- Database: sqlite (default settings)
- Operating system: reproduced in both Mac OS 11.6.1 and on Windows 10

### PR DESCRIPTION
**Pull request by iicdii**
Signed-off-by: harimkims <harimkims@gmail.com>

### What does it do?

- Consider array when sanitizing admin users relation
- Execute sanitizing only when value exists (otherwise it returns `{}` and it causes problems in admin)

### Why is it needed?

- In order to get a correct API response 
- Not to crash Strapi admin

### How to test it?

1. Create a collection-type
2. Add a field has-many admin users

### Related issue(s)/PR(s)

Closes #11891, Closes #12014

### CODE REVIEW

File: packages/core/admin/server/services/permission/permissions-manager/sanitize.js [hunk 1]
```diff
@@ -108,8 +108,12 @@ module.exports = ({ action, ability, model }) => {
...
 
   const pickAllowedAdminUserFields = ({ attribute, key, value }, { set }) => {
-    if (attribute.type === 'relation' && attribute.target === 'admin::user') {
-      set(key, pick(['id', 'firstname', 'lastname', 'username'], value));
+    if (attribute.type === 'relation' && attribute.target === 'admin::user' && value) {
+      if (Array.isArray(value)) {
+        set(key, value.map(val => pick(['id', 'firstname', 'lastname', 'username'], val)), value);
+      } else {
+        set(key, pick(['id', 'firstname', 'lastname', 'username'], value));
+      }
```
Comment (Convly) [inline packages/core/admin/server/services/permission/permissions-manager/sanitize.js:116]: WDYT? (here we can use `pick` directly in the `map` since it has a fixed arity of 2 in `lodash/fp`)

```suggestion
    const pickAllowedFields = pick(['id', 'firstname', 'lastname', 'username']);

    if (attribute.type === 'relation' && attribute.target === 'admin::user' && value) {
      if (Array.isArray(value)) {
        set(key, value.map(pickAllowedFields));
      } else {
        set(key, pickAllowedFields(value));
      }
    }
```

**Review by Convly — COMMENTED** [review]
WDYT?

File: packages/core/admin/server/services/permission/permissions-manager/sanitize.js (hunk 1 above)
Comment (iicdii) [reply packages/core/admin/server/services/permission/permissions-manager/sanitize.js:116]: Looks good to me! I'll make a commit :)

**Review by petersg83 — APPROVED** [review]
LGTM ! Thank you for your help :)
