### PR TITLE
Fix query when populating morph relations

### LINKED ISSUE #6347: Break Media Lib when deleting a Media field from an Content Type
# **Bug**
In Strapi, after deleting a **Media** Field from a **Collection-Type**, a **GET request to /upload/files** throws an **Error**.  
This should not happened.  

**Steps to reproduce the behavior**

1. Create a new Strapi App.
2. Create a **Collection-Type** with a **Media** Field.
3. Create a new **Entry** from this **Collection-Type** with a **File** uploaded.
4. Delete the **Media** Field from the **Collection-Type**.
5. Finally going to the Media Library (**GET request to /upload/files**) will result in an **ERROR**. 

**Expected behavior**
When deleting a **Media** Field from a **Collection-Type** should remove any relation between the Entries that used **Media** as a Fields and the uploaded files.

**Screenshots**
steps

**Code snippets**
This Bug can be achieved **without** using code, this scenario **only uses the Strapi CMS**.

**System**

- Node.js version: v12.16.1.
- NPM version: 6.13.2.
- Strapi version: v3.0.0-beta.20.1
- Database: Default (SQLlite I believe).
- Operating system: Windows.

# **FIX**
I did find a "solution" to this issue.
1. Add the Media field back to the Collection-Type.
2. Remove the Media field manually from every Entry.
3. Now you can remove the Media field from the collection-type without triggering this error.

## **Possible solution**
As stated before, when deleting the Media field from the Collection-Type should remove the Media attached to every Entry that uses it.

### PR DESCRIPTION
**Pull request by petersg83**
fix #6347

### CODE REVIEW

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 1]
```diff
@@ -413,12 +428,29 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
           // Upload has many Upload_morph that morph to different model.
+          const populateFn = qb => {
+            qb.where(qb => {
+              for (const modelAndFields of morphModelsAndFields) {
+                qb.where({ related_type: modelAndFields.collectionName }).whereIn(
+                  'field',
+                  modelAndFields.relatedFields
+                );
+              }
+            }).orderBy('order');
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:439]: the order will not mean anything in this direction

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 2]
```diff
@@ -413,12 +428,29 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
 
           // Hack Bookshelf to create a many-to-many polymorphic association.
           // Upload has many Upload_morph that morph to different model.
+          const populateFn = qb => {
+            qb.where(qb => {
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:432]: shouldn't it be a orWhere ?

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 3]
```diff
@@ -354,40 +354,55 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
 
-            if (models.length === 0) {
+            if (!modelFound) {
               strapi.log.error(`Impossible to register the '${model}' model.`);
               strapi.log.error('The collection name cannot be found for the morphTo method.');
               strapi.stop();
             }
 
-            return models[0].collectionName;
+            const relatedFields = _.reduce(
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:379]: do we realy need this added complexity ? Does bookshelf throw if a media attributes is removed ?

**Review by derrickmehaffy — DISMISSED** [review]
LGTM on docs

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 4]
```diff
@@ -354,40 +354,55 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
         case 'belongsToMorph':
         case 'belongsToManyMorph': {
-          const association = definition.associations.find(
-            association => association.alias === name
-          );
+          const association = _.find(definition.associations, { alias: name });
 
-          const morphValues = association.related.map(id => {
-            let models = Object.values(strapi.models).filter(model => model.globalId === id);
+          const morphModelsAndFields = association.related.map(id => {
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:359]: here the association.related are models that exists it should be necessary to verify that. consider using getModelByGlobalId instead. Be carefull it must be called of model are mounted (e.g in the relation function)

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/strapi-connector-bookshelf/lib/mount-models.js (hunk 3 above)
Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/mount-models.js:379]: Yes bookshelf throws if it cannot find the field become it has been removed :/

File: packages/strapi-connector-bookshelf/lib/mount-models.js (hunk 2 above)
Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/mount-models.js:432]: good catch, it's a typo !

Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/mount-models.js:432]: No, it's more than that, I messed when moving the code in the function

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 5]
```diff
@@ -354,38 +354,34 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
+                const sameModel = [attr.model, attr.collection].includes(definition.modelName);
+                const isMorph = attr.via === 'related';
+
+                return isMorph && sameModel && samePlugin ? fields.concat(attrName) : fields;
+              },
+              []
+            );
 
-            if (models.length === 0) {
+            if (relatedFields.length === 0) {
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:373]: Isn't this error  already thrown during the defineAssociation phase ?

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 6]
```diff
@@ -354,38 +354,34 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
+          const association = _.find(definition.associations, { alias: name });
+          const morphModelsAndFields = association.related.map(morphModel => {
+            const relatedFields = _.reduce(
+              morphModel.attributes,
+              (fields, attr, attrName) => {
+                const samePlugin =
+                  definition.plugin === attr.plugin ||
+                  (_.isNil(definition.plugin) && _.isNil(attr.plugin));
+                const sameModel = [attr.model, attr.collection].includes(definition.modelName);
+                const isMorph = attr.via === 'related';
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:366]: the via attribute might be something else than 'related'. I think you should be using `name` here

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 7]
```diff
@@ -354,38 +354,34 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
-                }
-
-                return acc;
-              }, []);
-            }
+          const association = _.find(definition.associations, { alias: name });
+          const morphModelsAndFields = association.related.map(morphModel => {
+            const relatedFields = _.reduce(
+              morphModel.attributes,
+              (fields, attr, attrName) => {
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:361]: split this into a function

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 8]
```diff
@@ -401,7 +391,10 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
             related: function() {
               return this.morphTo(
                 name,
-                ...association.related.map((id, index) => [GLOBALS[id], morphValues[index]])
+                ...association.related.map(morphModel => [
+                  GLOBALS[morphModel.globalId],
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:395]: isn't morphModel already the instance of the model ? I think you can return [morphModel, morphModel.collectionName)

File: packages/strapi-connector-bookshelf/lib/mount-models.js [hunk 9]
```diff
@@ -354,39 +354,29 @@ module.exports = async ({ models, target }, ctx, { selfFinalize = false } = {})
...
-                );
-
-                if (acc.length === 0 && models.length > 0) {
-                  acc = models;
-                }
-
-                return acc;
-              }, []);
-            }
+          const isARelatedField = attr => {
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/mount-models.js:357]: Can you move those utils into the modelsUtils for now are at least delcare them outside the main function to avoid recreating the function for each relation ?

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/strapi-connector-bookshelf/lib/mount-models.js (hunk 9 above)
Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/mount-models.js:357]: I'll move it outside of the main function but for readability I'm not confortable with spreading the code in different places, especially that this function is kind of specific to this piece of code

Comment (petersg83) [reply packages/strapi-connector-bookshelf/lib/mount-models.js]: I've put it outside of the main function but still in the file as I find it too specific for this piece of code to be in utils

**Review by alexandrebodin — APPROVED** [review]
LGTM
