### PR TITLE
fix #13453 Documentation Plugin doesn't generate Proper Type for the …

### LINKED ISSUE #13453: Documentation Plugin doesn't generate Proper Type for the Localization prop , and doesn't generate Refs for Components in Dynamic Zones
### Required System information

- Node.js version: 14.17.6
- NPM version: 8.5.3
- Strapi version: 4.1.12
- Database: Postgres
- Operating system: MacOS

### Describe the bug

When Generating a OpenAPI documentation with the Documentation Plugin , Content-Types that Are localized have an Empty array for the "localizations" prop instead of the correct type.

Also it doesn't generate Proper refs for Components in Dynamic Zones, which Bloats the Documentation if there are many Components in Dynamic Zones that are used in multiple Content-Types.
This also Makes it not as UserFriendly to use with CodeGens ( i use Orval) because the Component-types in Dynamic Zones are not Named properly (for example A Slider Component is named AnyOf instead of Slider)

### Steps to reproduce the behavior

1. Go to Content Types , create A localized Content-type, add a Dynamic Zone, Create one or more Components and add them to the Dynamic Zone.
2. Go To Documentation Plugin and Create Documentation
3. Look at the Generated Documentation and see that Localizations prop shows an empty array as type instead of the proper Content-Type. also see that Dynamic Zone Components are not Reffed but just defined inside an AnyOf

### Expected behavior

Components in Dynamic Zones are Reffed.
the localizations prop shows the "parent" content type aswell

### Additional context
i Created A Patch for it and would like to submit it as a PR or have it implemented by someone from Strapi:

<snip> too much of a wall of text

### PR DESCRIPTION
**Pull request by meganoob1337**
fixes https://github.com/strapi/strapi/issues/13453

### CODE REVIEW

**Comment by markkaylor** [comment]
Thanks for this PR, I might be able to review it before the end of today, otherwise it will have to be early next week.

**Comment by meganoob1337** [comment]
> Thanks for this PR, I might be able to review it before the end of today, otherwise it will have to be early next week.

If you have any questions im in the strapi discord aswell.

I hope the code is okay like this, its my first PR here and was just my Fix for it, so bear with me please :D

File: packages/plugins/documentation/server/services/helpers/build-component-schema.js [hunk 1]
```diff
@@ -94,17 +105,26 @@ const getAllSchemasForContentType = ({ routeInfo, attributes, uniqueName }) => {
...
+            attributes: { type: 'object', properties: cleanSchemaAttributes(attributes, { addSchema, dataTypeName: `#/components/schemas/${pascalCase(uniqueName)}ListResponseDataItemLocalized`}) },
+          },
+        },
+      [`${pascalCase(uniqueName)}ListResponseDataItemLocalized`]:  {
+            type: 'object',
+            properties: {
+              id: { type: 'string' },
+              attributes: { type: 'object', properties: cleanSchemaAttributes(attributes, { addSchema }) },
+            },
+        },
```
Comment (markkaylor) [inline packages/plugins/documentation/server/services/helpers/build-component-schema.js:121]: Are these necessary? Could you just use `ResponseDataObject` on the `ListResponse` below?

```js
[`${pascalCase(uniqueName)}ListResponse`]: {
  properties: {
    data: {
      type: 'array',
      items: {
        "$ref": `#/components/schemas/${pascalCase(uniqueName)}ResponseDataObject`
//...
```

**Review by markkaylor — CHANGES_REQUESTED** [review]
Thanks for submitting this PR, nice work! My comments are mostly about cleaning things up and code style. Let me know if you have any questions or if something isn't clear.

**Comment by meganoob1337** [comment]
@markkaylor thx for the review and sorry for all the small things. ill probably come to it next week, as im away for the next days

**Comment by meganoob1337** [comment]
Sorry, had corona, will start soon :)

File: packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js [hunk 2]
```diff
@@ -108,21 +95,58 @@ const cleanSchemaAttributes = (attributes, { typeMap = new Map(), isRequest = fa
...
-          };
+          })
+          return componentExists ? {"$ref": `#/components/schemas/${pascalCase(component)}`} : {
+            type: 'object',
+            properties: {
+              ...(isRequest ? {} : { id: { type: 'string' } }),
+              __component: { type: 'string' },
+              ...cleanSchemaAttributes(componentAttributes, { typeMap, isRequest, addSchema }),
+            },
+          }
```
[the remark this answers is not in the document]
Comment (meganoob1337) [reply packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js:149]: it is not the same object, as in the Dynamic Zone cleanSchemaAttributes needs the addSchema method for Components inside the DynamicZoneComponent

File: packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js [hunk 3]
```diff
@@ -171,8 +195,11 @@ const cleanSchemaAttributes = (attributes, { typeMap = new Map(), isRequest = fa
 
         if (prop === 'localizations') {
           attributesCopy[prop] = {
-            type: 'array',
-            items: { type: 'object', properties: {} },
+            type: 'object',
+            properties: { data: {
+              type: 'array',
+              items: dataTypeName.length ? { '$ref' : dataTypeName } : {}
```
[the remark this answers is not in the document]
Comment (meganoob1337) [reply packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js]: it gets initialized by default with an empty string, so its never undefined :

```
 */
const cleanSchemaAttributes = (
  attributes,
  { typeMap = new Map(), isRequest = false, addSchema = () => {}, componentSchemaRefName = '' } = {}
) => {
```

File: packages/plugins/documentation/server/services/helpers/build-component-schema.js (hunk 1 above)
Comment (meganoob1337) [reply packages/plugins/documentation/server/services/helpers/build-component-schema.js]: This is because the Type is used for the Localizations Part of the Response Object. and since we cannot Re-Use the original Object, as it would have Localizations aswell and would go in a loop kinda, i needed to move it out of there.
feel free to text me in Discord if i didn't explain it well enough 

```
 "PageListResponseDataItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "attributes": {
          ....,
          ....,
          "localizations": {
                "type": "object",
                "properties": {
                  "data": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/PageListResponseDataItemLocalized"
                    }
                  }
                }
              },
```

**Comment by meganoob1337** [comment]
@markkaylor  any updates here?

**Comment by markkaylor** [comment]
Sorry @meganoob1337 didn't see the notification that this PR was up for review again. I will take a look this week and get back to you.

File: packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js [hunk 4]
```diff
@@ -86,43 +89,49 @@ const cleanSchemaAttributes = (attributes, { typeMap = new Map(), isRequest = fa
...
+          properties: {
+            ...(isRequest ? {} : { id: { type: 'string' } }),
+            ...cleanSchemaAttributes(componentAttributes, {
+              typeMap,
+              isRequest,
+            }),
+          },
+        };
+        const refComponentSchema = {
+          $ref: `#/components/schemas/${`${pascalCase(attribute.component)}Component`}`,
```
Comment (markkaylor) [inline packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js:103]: I think this can be simplified
```suggestion
          $ref: `#/components/schemas/${pascalCase(attribute.component)}Component`,
```

File: packages/plugins/documentation/server/services/helpers/build-component-schema.js [hunk 5]
```diff
@@ -19,6 +19,18 @@ const { hasFindMethod, isLocalizedPath } = require('./utils/routes');
 const getAllSchemasForContentType = ({ routeInfo, attributes, uniqueName }) => {
   // Store response and request schemas in an object
   let schemas = {};
+  let componentSchemas = {};
+  // adds a ComponentSchema to the Schemas so it can be used as Ref
+  const addSchema = (schemaName, schema) => {
```
Comment (markkaylor) [inline packages/plugins/documentation/server/services/helpers/build-component-schema.js:24]: Can you name the function `addComponentSchema`?

**Review by markkaylor — CHANGES_REQUESTED** [review]

**Comment by meganoob1337** [comment]
@markkaylor i added your requested Changes, have a look please :) (had some vacation - took a bit longer )

**Review by markkaylor — APPROVED** [review]
