### PR TITLE
fix: handle component structure properly for conditional fields [CMS-197]

### LINKED ISSUE #25118: Strapi 5.33.1 regression: conditional fields fail on top‑level component fields after upgrade
### Node Version

22.18.0

### NPM/Yarn/PNPM Version

11.5.2

### Strapi Version

5.33.1

### Operating System

Windows 11

### Database

PostgreSQL

### Javascript or Typescript

Javascript

### Reproduction URL

_No response_

### Bug Description

After upgrading to Strapi 5.33.1, conditional fields defined on the top level of a component no longer render in the Content Manager. The component appears in the dynamic zone, but when a condition is met (e.g., enum/boolean toggle), the dependent fields show as an empty block with no inputs. The same conditional fields worked correctly on 5.31.3.

### Steps to Reproduce

1. Upgrade Strapi from 5.31.3 to 5.33.1.
2. Open Content Manager and edit a component that has conditional fields on the top level (e.g., blocks.one-column-content).
3. Select a value that should reveal conditional fields (e.g., columnContent = cards).

### Expected Behavior

Conditional fields render normally.

### Logs

```shell

```

### Code Snippets

_No response_

### Media

Image

Image

### Additional information

- Conditional fields inside nested components still work.
- Example: blocks.two-column-content works because conditional fields are inside shared.second-column (nested component), not on the top level of the block.
- No server-side errors.
- Downgrading back to 5.31.3 fixes the issue.

Possibly related to #25098 (conditional fields in components used in dynamic zones not rendering).

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

Fixes conditional-field evaluation for dynamic zone / component inputs and cleans up duplicated conditional logic in the dynamic-zone renderer.

### Why is it needed?

Conditional fields inside dynamic zones could throw runtime errors or be evaluated against the wrong values because the rules evaluation assumed a flat form-value layout. The dynamic-zone renderer also contained duplicate/unsafe conditional logic causing inconsistencies and regressions.

### How to test it?

- Create a component with conditional fields, try all different forms of logic 
- Add component to dynamic zone
- fields should be hidden or visible as expected

### Related issue(s)/PR(s)

fixes  #25118, #25098

### CODE REVIEW

File: packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx [hunk 1]
```diff
@@ -276,7 +277,11 @@ const ConditionAwareInputRenderer = ({
 }: InputRendererProps & { condition: JsonLogicCondition }) => {
   // Note: this selector causes a re-render every time any form value on the page changes
   const fieldValues = useForm('ConditionalInputRenderer', (state) => state.values);
-  const isVisible = rulesEngine.evaluate(condition, fieldValues);
+  // For nested fields, we evaluate against the parent scope so conditions can read siblings.
+  // Top-level fields resolve to the full form values.
+  const targetValues = getDirectParent(fieldValues, props.name);
+
+  const isVisible = rulesEngine.evaluate(condition, targetValues);
```
Comment (butcherZ) [inline packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx:284]: Do we want it to be re-rendered on every form change? Maybe we can do something like this, so it only get re-rendered when the visibility changes
```
const isVisible = useForm('ConditionalInputRenderer', (state) => {
    const targetValues = getDirectParent(state.values, props.name);
    return rulesEngine.evaluate(condition, targetValues);
  });
```

File: packages/core/content-manager/admin/src/pages/EditView/utils/data.ts [hunk 2]
```diff
@@ -26,6 +26,33 @@ type AnyData = Omit<Document, 'id'>;
 
 const BLOCK_LIST_ATTRIBUTE_KEYS = ['__component', '__temp_key__'];
 
+/**
+ * @internal
+ * @description Returns the direct parent object for a dot-separated path.
+ */
+const getDirectParent = (data: unknown, path: string): unknown => {
+  if (!path) return undefined;
+  const isNumericIndex = (value: string) => /^\d+$/.test(value);
```
Comment (butcherZ) [inline packages/core/content-manager/admin/src/pages/EditView/utils/data.ts:35]: not really a big issue, but here the regex gets created each call to `getDirectParent`, could we try something like 
```
  const NUMERIC_INDEX_REGEX = /^\d+$/;

  const getDirectParent = (data: unknown, path: string): unknown => {
    if (!path) return undefined;
    const isNumericIndex = (value: string) => NUMERIC_INDEX_REGEX.test(value);
```

😄

**Comment by jhoward1994** [comment]
Behaviour in the listed issues is fixed for me but I spotted a couple of other things:

- If boolean 'false' hides a field - when you first load the DZ 'false' will appear selected but the field is still visible - you have to toggle once for the correct logic to kick in
- [Minor issue] Fill a conditional fields value - hide it - then re show it. All without saving anything. The value is cleared, it feels like it should persist from the last time you filled it in?

**Review by jhoward1994 — APPROVED** [review]
