### PR TITLE
use streams instead of buffers

### LINKED ISSUE #6432: Multiple Image Uploads result in memory leak
**Describe the bug**
Memory leak due to image uploading both with and without `responsiveDimensions` and `sizeOptimization` disabled via Media Library settings.

If you upload multiple images at the same, the memory consumption increases according to the number of images you're uploading.

Tested with:
- `strapi-provider-upload-local` `3.0.1` 
- `strapi-provider-upload-aws-s3` `3.0.0`

**Steps to reproduce the behavior**
I run Strapi inside Docker, so I monitor memory usage by running `docker stats`

Have made a video:

1. Start a fresh Strapi server ... memory usage `93 MB`
2. turn off Image optimization and Responsive Dimensions via `/admin/settings/media-library` 3. go to the Media Library and upload an image `490 kB` in size ... memory usage now `122 MB`
4. upload another image `149 kB` in size ... memory usage now `135 MB`
5. enable Image optimization and Responsive Dimension via `/admin/settings/media-library`
6. upload another image `325 kB` in size ... memory usage now `257 MB`

**Expected behavior**
I would expect the additional memory usage to be much lower and stable.

**Screenshots**
Video: https://drive.google.com/file/d/1wNVkRLKagVQuRp8Vuld6FADrilfmS00n/view?usp=sharing

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: Debian Buster running inside Docker

### PR DESCRIPTION
**Pull request by petersg83**
Done:
- use streams instead of buffers

Should fix #6432

### CODE REVIEW

File: packages/core/upload/server/controllers/admin-api.js [hunk 1]
```diff
@@ -173,15 +174,23 @@ module.exports = {
...
+        throw new ApplicationError('Files are empty');
+      }
+
+      await (id ? this.replaceFile : this.uploadFiles)(ctx);
+    } finally {
+      if (Array.isArray(files)) {
+        files.map(file => rimraf(file.path, () => {}));
+      } else if (files.path) {
+        rimraf(files.path, () => {});
+      }
```
Comment (petersg83) [inline packages/core/upload/server/controllers/admin-api.js:192]: It may be better to do that into a middleware, at the end at all requests. Wdyt ? Checking if there is `ctx.request.files`

Comment (alexandrebodin) [reply packages/core/upload/server/controllers/admin-api.js:192]: I think I would do this in the upload or replace service instead. 
You can use fs-extra to do the delete without installing rimraf as a dependency by the way

File: packages/core/upload/server/graphql.js [hunk 2]
```diff
@@ -41,6 +41,7 @@ module.exports = ({ strapi }) => {
    * @return {Promise<object>}
    */
   const formatFile = async (upload, extraInfo, metas) => {
+    // ICI
```
Comment (alexandrebodin) [inline packages/core/upload/server/graphql.js:44]:
```suggestion
    
```

File: packages/providers/upload-local/lib/index.js [hunk 3]
```diff
@@ -5,6 +5,7 @@
  */
 
 // Public node modules.
+const { pipeline } = require('stream');
```
Comment (alexandrebodin) [inline packages/providers/upload-local/lib/index.js:8]: is this available on all our node supported versions ?

Comment (petersg83) [reply packages/providers/upload-local/lib/index.js:8]: Yes :)

File: packages/core/upload/server/controllers/admin-api.js (hunk 1 above)
Comment (petersg83) [reply packages/core/upload/server/controllers/admin-api.js:192]: But what if a middleware wants to use the files afterwards? Then they would not be available anymore.
Thus my proposition to delete them inside a middleware a the correct place (first place, after the next()).

I need rimraf anyway somewhere else to delete a whole folder (doesn't work well natively in Node 12).
But you're right I'll change for `unlink` that can be awaited, it's prettier

Comment (petersg83) [reply packages/core/upload/server/controllers/admin-api.js:192]: @alexandrebodin What do you think?

File: packages/core/upload/server/graphql.js [hunk 4]
```diff
@@ -98,12 +97,29 @@ module.exports = ({ strapi }) => {
...
+                {},
+                { tmpFolderPath }
+              );
+              sanitizedEntity = await toEntityResponse(uploadedFile, {
+                args,
+                resourceUID: fileTypeName,
+              });
+            } finally {
+              // delete temporary folder
+              await fse.remove(tmpFolderPath);
```
[the remark this answers is not in the document]
Comment (petersg83) [reply packages/core/upload/server/graphql.js:119]: Thank for being careful on that! Actually it will be ok because the function `fs.mkdtemp` (https://nodejs.org/api/fs.html#fspromisesmkdtempprefix-options) creates a unique folder by appending six random characters at the end. So the folder will be used only by the current request

File: packages/core/upload/server/graphql.js [hunk 5]
```diff
@@ -98,12 +97,29 @@ module.exports = ({ strapi }) => {
           },
 
           async resolve(parent, args) {
-            const { file: upload, info, ...fields } = args;
-
-            const file = await formatFile(upload, info, fields);
-            const uploadedFile = await getUploadService('upload').uploadFileAndPersist(file);
+            // create temporary folder to store files for stream manipulation
+            const tmpFolderPath = await fse.mkdtemp(path.join(os.tmpdir(), 'strapi-upload-'));
```
Comment (alexandrebodin) [inline packages/core/upload/server/graphql.js:101]: it feels heavy to create a temp folder and pass it around everywhere. Can't we create tmp dirs on the fly to make the code simpler? or set a tmpDir info on the file descriptor

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/core/upload/server/controllers/admin-api.js (hunk 1 above)
Comment (petersg83) [reply packages/core/upload/server/controllers/admin-api.js:192]: No, exactly, I'm proposing to change that to a middleware. However I have to check if I can control the middleware order enough

**Review by alexandrebodin — APPROVED** [review]
LGTM. Great improvements!

**Review by alexandrebodin — APPROVED** [review]

**Comment by pedrosimao** [comment]
Yey! Thanks a lot @petersg83 !
