### PR TITLE
fix: do not validate locale if not creating

### LINKED ISSUE #19528: Issue directly publishing a translated entity after translating
### Describe the bug

When creating a translation of an entity and directly publishing it we get an error that complains about the related entity not existing or the entity already existing the locale.

Warning:
The related entity doesn't exist or the entity already exists in this locale

Possibly related to this recent fix in Strapi 4.20.1?
https://github.com/strapi/strapi/pull/19510

### Steps to reproduce the behavior

1. Have 2 localizations set up
2. Create an entity
3. Create a translation for the entity
4. Save the translated entity
5. Publish the translated entity

### Expected behavior

The entity is published

### Additional context

When creating a translation you end up on an URL like this:
http://localhost:1337/admin/content-manager/collection-types/api::page.page/create?plugins[i18n][locale]=sv&plugins[i18n][relatedEntityId]=4

When the new entity is saved you end up on an URL like this:
http://localhost:1337/admin/content-manager/collection-types/api::page.page/21?plugins[i18n][locale]=sv&plugins[i18n][relatedEntityId]=4

Publishing the entity from that URL generates an error (as describe above).

If you remove the `relatedEntityId` part of the URL (`&plugins[i18n][relatedEntityId]=4`) and trying to publish it does not give an error and the entity gets published.

There seems to be a validation check when publishing the entity that throws an error. Either this check should not be done when publishing the entity, or once you save the entity the `relatedEntityId` part should be removed from the URL.

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

I18n Backend koa middlweare was matching all CM routes, and validating locale creation even for actions that were not related (publishing, unpublishing)

If the API received the "relatedEntityId" param when publishing, it assumed this was for creating a new locale (and checked if the locale already existed), and failed because the action was to publish an existing locale.

My only worry here is that the url matching is not smart enough and we miss some cases

### How to test?

Create single types and collection type locales, and publish them. You should not get an error

### Related issues

* resolves CONTENT-2279
* resolves #19528

### CODE REVIEW

File: packages/plugins/i18n/server/src/register.ts [hunk 1]
```diff
@@ -14,21 +14,44 @@ export default ({ strapi }: { strapi: Strapi }) => {
...
+const isUrlForCreation = (url: string) => {
+  if (!url) return false;
+
+  // Split path and remove empty strings
+  // [ 'content-manager', 'collection-types', 'api::category.category' ]
+  const splittedUrl = url.split('/').filter(Boolean);
+
+  // Get the last element of the array
+  // api::category.category / 1 / publish
+  const model = splittedUrl[splittedUrl.length - 1];
```
[the remark this answers is not in the document]
Comment (Marc-Roig) [reply packages/plugins/i18n/server/src/register.ts:34]: I still have hopes for an AI to automatically translate from spanish

File: packages/plugins/i18n/server/src/register.ts [hunk 2]
```diff
@@ -14,21 +14,44 @@ export default ({ strapi }: { strapi: Strapi }) => {
...
+const isUrlForCreation = (url: string) => {
+  if (!url) return false;
+
+  // Split path and remove empty strings
+  // [ 'content-manager', 'collection-types', 'api::category.category' ]
+  const splitUrl = url.split('/').filter(Boolean);
+
+  // Get the last element of the array
+  // api::category.category / 1 / publish
+  const model = splitUrl[splittedUrl.length - 1];
```
Comment (innerdvations) [inline packages/plugins/i18n/server/src/register.ts:34]:
```suggestion
  const model = splitUrl[splitUrl.length - 1];
```

File: packages/plugins/i18n/server/src/register.ts [hunk 3]
```diff
@@ -14,21 +14,44 @@ export default ({ strapi }: { strapi: Strapi }) => {
...
+  // Split path and remove empty strings
+  // [ 'content-manager', 'collection-types', 'api::category.category' ]
+  const splitUrl = url.split('/').filter(Boolean);
+
+  // Get the last element of the array
+  // api::category.category / 1 / publish
+  const model = splitUrl[splitUrl.length - 1];
+
+  // If the model contains :: it means it's a uid
+  return model.includes('::');
```
Comment (Marc-Roig) [inline packages/plugins/i18n/server/src/register.ts:37]: @innerdvations just in case, all uids do have the XX::XX.XX format right?

Comment (innerdvations) [reply packages/plugins/i18n/server/src/register.ts:37]: This is one thing I'm worried about. I'm trying to think if there's a better way to do this, it seems a bit fragile

Comment (Marc-Roig) [reply packages/plugins/i18n/server/src/register.ts:37]: what about this:

```ts
  const splitUrl = url.split('/').filter(Boolean);
  return split.Url.lenght === 3
  ```

Comment (Marc-Roig) [reply packages/plugins/i18n/server/src/register.ts:37]: is it possible for people to have prefixes in their CM url?

Comment (jhoward1994) [reply packages/plugins/i18n/server/src/register.ts:37]:
```suggestion
return mode instanceof UID_FROM_TYPES
```
Is something like that possible?

Comment (Marc-Roig) [reply packages/plugins/i18n/server/src/register.ts:37]: I would prefer not to, just in case people use models that are not stored in strapi

**Review by innerdvations — APPROVED** [review]
As we discussed, neither of us like this, but it fixes the problem and there doesn't appear to be a better way 😆

I suspect that even though this will solve 99% of the cases, there will be a handful of edge cases we didn't anticipate that will have to be solved later, but we'll find out then, and it shouldn't actually break anything

**Review by jhoward1994 — APPROVED** [review]

**Comment by minht11** [comment]
This PR did not account for query parameters so url like this `content-manager/single-types/api::home-page.home-page/?locale=fr` returns false, because last item is `?locale=fr`. Breaking while saving non default locale.

**Comment by Marc-Roig** [comment]
@minht11 thank you for the report :) Will create a ticket with the fix
