### PR TITLE
Prune obsolete files relations on startup

### LINKED ISSUE #4918: Error on File list after deleting Content Type MongoDB
**Describe the bug**
I have created content type which has media attachment. When I am deleting content type it does not delete attachment as well so when I am opening Files upload dashboard it throws an error as it tries to find a related model which is deleted

**Expected behavior**
Either it should delete related attachment or it will show correctly on the Files upload dashboard

**System**
- Node.js version: 12.6.0
- NPM version: yarn v1.17.3
- Strapi version: 3.0.0-beta.18.3
- Database: Mongoose
- Operating system: macOS Mojave

### PR DESCRIPTION
**Pull request by Convly**
Signed-off-by: Convly <jean-sebastien.herbaux@epitech.eu>

#### Description of what you did:

fix #4918

Currently, on MongoDB, deleting a content-type doesn't update the `related` field of the `upload_file` entries which can cause some issues (eg: #4918)

This PR introduces a new query ran in the bootstrap function of the `strapi-plugin-upload` package.
This query search for obsolete relations in the `upload_file` document and remove them.

### CODE REVIEW

File: packages/strapi-plugin-upload/config/functions/bootstrap.js [hunk 1]
```diff
@@ -1,15 +1,17 @@
 'use strict';
 /**
- * Upload plugin bootstrapi.
+ * Upload plugin bootstrap.
  *
  * It initializes the provider and sets the default settings in db.
  */
 
 module.exports = async () => {
+  const name = 'upload';
```
Comment (petersg83) [inline packages/strapi-plugin-upload/config/functions/bootstrap.js:9]: Can we name it `pluginName` for readibility ?

File: packages/strapi-plugin-upload/config/functions/bootstrap.js [hunk 2]
```diff
@@ -52,3 +56,23 @@ const baseProvider = {
     throw new Error('Provider delete method is not implemented');
   },
 };
+
+const pruneObsoleteRelations = async name => {
```
Comment (petersg83) [inline packages/strapi-plugin-upload/config/functions/bootstrap.js:60]: Also here `pluginName`

File: packages/strapi-plugin-upload/config/functions/bootstrap.js [hunk 3]
```diff
@@ -52,3 +56,23 @@ const baseProvider = {
...
+  const { orm } = strapi.plugins[name].models.file;
+
+  if (orm !== 'mongoose') {
+    return;
+  }
+
+  await strapi.query('file', 'upload').custom(pruneObsoleteRelationsQuery)();
```
Comment (petersg83) [inline packages/strapi-plugin-upload/config/functions/bootstrap.js:67]: Should it be `pluginName` instead of `'upload'` ?
I'm thinking, do we need the name as a parameter ? Since it's only for this plugin

**Comment by derrickmehaffy** [comment]
Is this needed on beta.20.x ?

File: packages/strapi-plugin-upload/config/functions/bootstrap.js [hunk 4]
```diff
@@ -52,3 +56,23 @@ const baseProvider = {
...
+};
+
+const pruneObsoleteRelationsQuery = ({ model }) => {
+  const models = Array.from(strapi.db.models.values());
+  const modelsId = models.map(model => model.globalId);
+
+  return model.updateMany(
+    { related: { $elemMatch: { kind: { $nin: modelsId } } } },
+    { $pull: { related: { kind: { $nin: modelsId } } } }
```
Comment (petersg83) [inline packages/strapi-plugin-upload/config/functions/bootstrap.js:76]: Love it when it's short like that, well done :)

File: packages/strapi-plugin-upload/config/functions/bootstrap.js (hunk 1 above)
Comment (soupette) [reply packages/strapi-plugin-upload/config/functions/bootstrap.js:9]: You can also get the name from the package.json

```
const pluginPkg = require('../../package.json');

const pluginId = pluginPkg.name.replace(/^strapi-plugin-/i, '');

export default pluginId;
```

File: packages/strapi-plugin-upload/config/functions/bootstrap.js (hunk 3 above)
Comment (alexandrebodin) [reply packages/strapi-plugin-upload/config/functions/bootstrap.js:67]: I agree I don't think we need this variable. this would reduce readability.

Comment (Convly) [reply packages/strapi-plugin-upload/config/functions/bootstrap.js:66]: Makes sense, removed in 8a2050add05d12bdb9ed68e380bde1ec9c24ca75
