### PR TITLE
fix shadow crud breaking build when resolvers are not defined in a plugin

### LINKED ISSUE #4224: GraphQL breaks the build with a custom local plugin
**Describe the bug**
When creating a local plugin that contains a custom model, installing strapi-plugin-graphql will break the build at runtime

**Steps to reproduce the behavior**
1: spin up a new strapi project `strapi new strapi-test`
2: install graphql plugin `strapi install graphql`
3: create a custom plugin `strapi generate:plugin awsome-plugin`
4: create a custom model for that plugin `strapi generate:model awsomething --plugin=awesome-plugin`
5: go to the `plugins/awesome-plugin/models/models` and move your models up a level to `plugins/awesome-plugin/models` because it creates a duplicate folder on generate (another bug i think ????)
6: try and run it `strapi develop`
7: see error
```
[2019-10-09T20:31:11.874Z] error Error: Cannot find the controller's action custommodel.findOne
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Query.js:163:16
    at Object.composeQueryResolver (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Query.js:199:7)
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Resolvers.js:331:19
    at Array.reduce (<anonymous>)
    at Object.buildShadowCRUD (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Resolvers.js:269:30)
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Schema.js:147:23
    at Array.reduce (<anonymous>)
    at Object.generateSchema (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Schema.js:141:48)
    at Object.initialize (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi/lib/hooks/index.js:43:28
```

**Expected behavior**
The server should start without an error.

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: beta16.5-16.8
- Database: sqlite,mongodb
- Operating system: macOS 10.14.6

**Additional context**
This is a fresh install with no other moving parts. I've also tried to put an empty schema.graphql file that only contains `module.exports = {}` in the plugins config folder like the getstarted project in the strapi monorepo, and it still fails at runtime.

### PR DESCRIPTION
**Pull request by petersg83**
fix #4224 

#### Description of what you did:
- Checks if the resolver exists before trying to add it the graphql schema. If it doesn't exist, it doesn't add it to the schema.
- Moved some functions in utils

### CODE REVIEW

File: packages/strapi-plugin-graphql/services/type-definitions.js [hunk 1]
```diff
@@ -370,60 +371,69 @@ const buildCollectionType = model => {
...
-      },
-      resolvers: {
-        Query: {
-          [singularName]: buildQuery(singularName, {
-            resolver: `${uid}.findOne`,
-            ..._.get(_schema, ['resolver', 'Query', singularName], {}),
-          }),
+    const resolverOpts = {
+      resolver: `${uid}.findOne`,
+      ..._.get(_schema, `resolver.Query.${pluralName}`, {}),
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-definitions.js:376]: Is there a reason to switch from a path arrray to a template string ? You have both usage in the file now.

File: packages/strapi-plugin-graphql/services/type-definitions.js [hunk 2]
```diff
@@ -370,60 +371,69 @@ const buildCollectionType = model => {
...
+    }
   }
 
   // Add model Input definition.
   localSchema.definition += types.generateInputModel(model, modelName);
 
   // build every mutation
   ['create', 'update', 'delete'].forEach(action => {
-    const mutationScheam = buildMutationTypeDef({ model, action }, { _schema });
+    const mutationName = `${action}${_.upperFirst(toSingular(model.modelName))}`;
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-definitions.js:427]: You could move this to the buildMutationTypeDef function instead so you don't define the resolverOpts twice. and jsut return an empty object to be merged if the action doesn't exist.

File: packages/strapi-plugin-graphql/services/type-definitions.js (hunk 1 above)
Comment (petersg83) [reply packages/strapi-plugin-graphql/services/type-definitions.js:376]: When I was workinng on it the line width was too long and it was a way to make it shorter. Also I find it more readable.
I changed all the file to be consistent
