### PR TITLE
fix(admin): force an absolute URL if the BACKEND_URL is relative

### LINKED ISSUE #18175: Media Library crashes with an error message while loading one or more images
### Required System information
- Strapi Version: 4.13.7
- Operating System: Ubuntu 20.04.6 LTS
- Database: mySQL 8.0.34 (using mysql2 as driver)
- Node Version: 18.18.0
- NPM Version: 9.8.1
- Yarn Version: none
- Dev language: typescript

### Describe the bug
When I try to load one or more images (size: 5kb) Strapi Admin get an error message:
`Woops! Something went wrong. Please, try again.`

### Steps to reproduce the behavior

1. Go to `Media Library`
2. Click on `Add new assets`
3. Browsing files or dragging the image (max image size used is 5kb)
4. See error `Woops! Something went wrong. Please, try again.`
5. The error reported in the console is:

immagine

No error messages on server log.

### Additional context

The production strapi configuration is under the sub path `/strapi`

My `config/server.ts`:

~~~js
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('STRAPI_URL', '/strapi'),
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
~~~

My `config/admin.ts`:
~~~js
export default ({ env }) => ({
  url: env('STRAPI_ADMIN_URL', '/strapi/admin'),
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT'),
    },
  },
});
~~~

No `api prefix` configured in `config/admin.ts`.

Any other configuration do not work with my apache proxy configuration (`HTTP 404 Not found` error message emitted by strapi).

Admin build command:
`NODE_ENV=production STRAPI_URL=/strapi STRAPI_ADMIN_URL=/strapi/admin npm run build`

My apache proxy config:
~~~code
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName mydomain
        ServerAlias mydomain
        ServerAdmin myemail
        DocumentRoot /var/www/mydomain/html

        <Directory /var/www/mydomain/html>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

	ProxyPreserveHost On
  	ProxyRequests Off
	ProxyPass /strapi http://localhost:1337
	ProxyPassReverse /strapi http://localhost:1337
</VirtualHost>
</IfModule>
~~~

When I make the same test on local machine, without server url field definition, strapi admin works fine.

Can someone help me? Thank you in advance

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* enforces the `BACKEND_URL` to always be an absolute URL falling back to use `window.location.origin` in cases where it's relative or for some reason does not exist.

### Why is it needed?

* the `url` property of the `server` config file can be relative and this currently breaks the `appendSearchParams` helper. Realistically, we always want it to be absolute.

### Related issue(s)/PR(s)

* resolves #18175
* resolves DX-1312

### CODE REVIEW

File: packages/core/admin/admin/src/utils/urls.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/**
+ * @description Creates an absolute URL, if there is no URL or it
+ * is relative, we use the `window.location.origin` as a fallback.
+ * IF it's an absolute URL, we return it as is.
+ */
+const createAbsoluteUrl = (url?: string): string => {
+  if (!url) {
+    return window.location.origin;
+  }
+  if (url.startsWith('/')) {
```
Comment (innerdvations) [inline packages/core/admin/admin/src/utils/urls.ts:10]: Just a note: this will catch protocol-relative URLS (like `//strapi.com/foo`) and then ignore window.location.origin since it already has a base URL.

So ultimately it will arrive at the correct place -- if someone puts backend url as "//myserver" `new URL toString` afaik will return "//myserver" despite hitting this line -- but probably not intentionally, so it might be worth commenting that, or adding an explicit check for that case

**Review by innerdvations — APPROVED** [review]
LGTM, just one comment

File: packages/core/admin/admin/src/utils/urls.ts (hunk 1 above)
Comment (joshuaellis) [reply packages/core/admin/admin/src/utils/urls.ts:10]: I've added a test case and a comment 🤓

**Review by jhoward1994 — APPROVED** [review]
