### PR TITLE
GraphQL Plugin (bug): Content type's attributes marked as private are being exposed in the exported GraphQL schema

### LINKED ISSUE #9804: Content type's attributes marked as private are being exposed
### Describe the bug

Content type's attributes marked as private are available in the Strapi exported GraphQL schema.

### Steps to reproduce the behavior

1. Go to Content type builder
2. Create a new content type with one attribute marked as private
3. Go to the graphql playground (http://localhost:1337/graphql) and click on the schema on the right hand side
4. See the private attribute in the graphql schema

### Expected behavior

The content type's attribute marked as private should not be available in the graphql schema in the graphql playground

### System

- Node.js version: v14
- Strapi version: 3.5.3

---

**Edited by** @derrickmehaffy

This is not just limited to GraphQL, per https://github.com/strapi/strapi/issues/10236

### PR DESCRIPTION
**Pull request by ralphsomeday**
### What does it do?

It fixes a bug in the strapi graphql plugin in the functions generating input  and types for graphql. The detection of an attribute as private was only applied to the privateAttributes array in the model.json file instead of also looking at the private property on an attribute within a model. There was also a bug in how the private attributes were filtered the attribute name was not being passed in the function so added the right filtering rule to only process fields that are not private and export them to the graphql schema file.

### Why is it needed?

This fix will remove all private attributes from the graphql schema as this data is not meant to be exposed to the outside world if marked as private by the user.

### How to test it?

In the content type builder, create an enum attribute and a string attribute as part of a content type and mark both as private and hit the save button. Open the graphql playground and click on the schema button on the right side of the screen and see if your enum and string value are not present in the exported schema.

### Related issue(s)/PR(s)

Fixes issue #9804

### CODE REVIEW

**Comment by ralphsomeday** [comment]
@alexandrebodin can you have a look at this one as this bug is blocking us as it exposes private data in graphql schema.

**Comment by ralphsomeday** [comment]
@alexandrebodin not sure why those tests are failing, not related to what I changed. Maybe you can help me understand why is it failing?

**Comment by rmaroun** [comment]
@Convly is there any chance we can review this one this week? thanks

**Comment by alexandrebodin** [comment]
@ralphsomeday We won't be able to review this until at least next week

**Comment by ralphsomeday** [comment]
@alexandrebodin ok noted. Will then wait for next week. Cheers.

**Comment by ralphsomeday** [comment]
@alexandrebodin is there any chance this can be reviewed this week?

File: packages/strapi-plugin-graphql/services/type-definitions.js [hunk 1]
```diff
@@ -99,7 +99,7 @@ const buildTypeDefObj = model => {
 
 const generateEnumDefinitions = (attributes, globalId) => {
   return Object.keys(attributes)
-    .filter(attribute => attributes[attribute].type === 'enumeration')
+    .filter(attribute => attributes[attribute].type === 'enumeration' && !attributes[attribute].private)
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-definitions.js:102]: You should use `!isPrivateAttribute` instead

File: packages/strapi-utils/lib/content-types.js [hunk 2]
```diff
@@ -92,7 +92,11 @@ const getPrivateAttributes = (model = {}) => {
 };
 
 const isPrivateAttribute = (model = {}, attributeName) => {
-  return model && model.privateAttributes && model.privateAttributes.includes(attributeName);
+  if (model && model.attributes && model.attributes[attributeName] && model.attributes[attributeName].private) {
```
Comment (alexandrebodin) [inline packages/strapi-utils/lib/content-types.js:95]: model.privateAttributes is built at startup and should already contain the private properties. If it is not the case it's not here that we should fix it. but make sure that model.privateAttributes is generated correctly. I think we already have a fix for this in the features/i18n branch we will be merging soon.

File: packages/strapi-plugin-graphql/services/type-builder.js [hunk 3]
```diff
@@ -216,7 +221,9 @@ module.exports = {
     const globalId = model.globalId;
     const inputName = `${_.upperFirst(toSingular(name))}Input`;
 
-    if (_.isEmpty(model.attributes)) {
+    if (_.isEmpty(model.attributes) ||
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-builder.js:224]: Use a temp var to clarify what this condition checks


```js
const hasOnlyPrivateAttributes =  keys(model.attributes).filter(atttributeName => !isPrivateAttribute(model, attribute)).length === 0

if (isEmpty(model.attributes) || hasOnlyPrivateAttributes) { /* ... */ }
```

File: packages/strapi-plugin-graphql/services/type-builder.js [hunk 4]
```diff
@@ -232,6 +239,7 @@ module.exports = {
       input ${inputName} {
 
         ${Object.keys(model.attributes)
+          .filter(attributeName => isNotPrivate(model, attributeName))
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-builder.js:242]: avoid creating a new method and use `!isPrivateAttribute(model, attributeName)`

File: packages/strapi-plugin-graphql/services/type-builder.js [hunk 5]
```diff
@@ -246,6 +254,7 @@ module.exports = {
       input edit${inputName} {
         ${allowIds ? 'id: ID' : ''}
         ${Object.keys(model.attributes)
+          .filter(attributeName => isNotPrivate(model, attributeName))
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-builder.js:257]: same :)

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Will need to refactor in v4 to avoid doing all the filtering everywhere that's too error prone

File: packages/strapi-utils/lib/content-types.js (hunk 2 above)
Comment (ralphsomeday) [reply packages/strapi-utils/lib/content-types.js:95]: @alexandrebodin the thing is that privateAttributes is not updated when you select an attribute as private in the content type builder UI. If you set this array with
```json
    "privateAttributes": [
      "created_by",
      "updated_by",
      "created_at",
      "updated_at"
    ]
```
nothing changes only the properties marked as private have a private attribute set to true and this is not being taken into account in the isPrivateAttribute function which only checks the privateAttributes array.

File: packages/strapi-plugin-graphql/services/type-definitions.js (hunk 1 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-graphql/services/type-definitions.js:102]: This function needs a model as a parameter to be able to check if an attribute is private and the generateEnumbDefinitions does not have the model passed as a parameter that is why i am doing the check in the function itself.

File: packages/strapi-plugin-graphql/services/type-builder.js (hunk 3 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-graphql/services/type-builder.js:224]: Will update it.

File: packages/strapi-plugin-graphql/services/type-builder.js (hunk 4 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-graphql/services/type-builder.js:242]: same here

File: packages/strapi-plugin-graphql/services/type-builder.js (hunk 5 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-graphql/services/type-builder.js:257]: Fixing it ;)

File: packages/strapi-utils/lib/content-types.js (hunk 2 above)
Comment (alexandrebodin) [reply packages/strapi-utils/lib/content-types.js:95]: As mentionned in my previous comment, the `privateAttributes` property in the code  is defined here https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/mount-models.js#L654 on the model.
It is not the value set in the file.

File: packages/strapi-plugin-graphql/services/type-definitions.js (hunk 1 above)
Comment (alexandrebodin) [reply packages/strapi-plugin-graphql/services/type-definitions.js:102]: Pass the model instead of the attributes in the function instead. This way we make sure we can change the implementation if isPrivateAttributes & it will propagte at once

Comment (ralphsomeday) [reply packages/strapi-plugin-graphql/services/type-definitions.js:102]: Ok got you changing it.

File: packages/strapi-utils/lib/content-types.js (hunk 2 above)
Comment (ralphsomeday) [reply packages/strapi-utils/lib/content-types.js:95]: Yeah I see it now. thanks for the clarification.

Comment (ralphsomeday) [reply packages/strapi-utils/lib/content-types.js]: fixed

File: packages/strapi-plugin-graphql/services/type-definitions.js (hunk 1 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-graphql/services/type-definitions.js]: fixed

**Comment by ralphsomeday** [comment]
@alexandrebodin updated the code with your input. Let me know if all is fine and if we can look into the reason why the tests are failing. thanks.

**Comment by alexandrebodin** [comment]
@ralphsomeday the code looks good. Indeed the tests are breaking in graphql because it now prevents users from creating entries with private attributes but the API should actually allow creating/editing private fields for now if the mutation is allowed

**Comment by ralphsomeday** [comment]
> @ralphsomeday the code looks good. Indeed the tests are breaking in graphql because it now prevents users from creating entries with private attributes but the API should actually allow creating/editing private fields for now if the mutation is allowed. We should not remove private fields from the inputs

@alexandrebodin the privately marked inputs should not be part of the graphql export. It should have the same behaviour as in the REST API. Those private fields are not available via the REST API and should not be via graphql. Isn't this the idea of the private fields?

**Comment by alexandrebodin** [comment]
> > @ralphsomeday the code looks good. Indeed the tests are breaking in graphql because it now prevents users from creating entries with private attributes but the API should actually allow creating/editing private fields for now if the mutation is allowed. We should not remove private fields from the inputs
> 
> @alexandrebodin the privately marked inputs should not be part of the graphql export. It should have the same behaviour as in the REST API. Those private fields are not available via the REST API and should not be via graphql. Isn't this the idea of the private fields?

In the API If you have the right to Create/Update an entry you should be able to fill the private fields. Private is only for Read queries. In Rest too.

**Comment by ralphsomeday** [comment]
> > > @ralphsomeday the code looks good. Indeed the tests are breaking in graphql because it now prevents users from creating entries with private attributes but the API should actually allow creating/editing private fields for now if the mutation is allowed. We should not remove private fields from the inputs
> > 
> > 
> > @alexandrebodin the privately marked inputs should not be part of the graphql export. It should have the same behaviour as in the REST API. Those private fields are not available via the REST API and should not be via graphql. Isn't this the idea of the private fields?
> 
> In the API If you have the right to Create/Update an entry you should be able to fill the private fields. Private is only for Read queries. In Rest too.

Ok and where do you recon to do a check on this in the code?

**Comment by alexandrebodin** [comment]
The only thing we can do is remove them from the Type but not from the input Type

**Comment by ralphsomeday** [comment]
> The only thing we can do is remove them from the Type but not from the input Type

can you point me to where does this happen in the graphql plugin?

**Comment by ralphsomeday** [comment]
generateInputModel?

**Comment by ralphsomeday** [comment]
> The only thing we can do is remove them from the Type but not from the input Type

if you remove them them then it won't work and you will get something like `Unknown type "XXXXXX"`? Private fields shouldn't be available at all even for mutation. If you need to do anything on those you should add a custom controller to mutate them. Those are values for example for configuration that are only available for the backend and not exposed in any way to the API side. How do you want to proceed from here?

**Comment by alexandrebodin** [comment]
> > The only thing we can do is remove them from the Type but not from the input Type
> 
> if you remove them them then it won't work and you will get something like `Unknown type "XXXXXX"`? Private fields shouldn't be available at all even for mutation. If you need to do anything on those you should add a custom controller to mutate them. Those are values for example for configuration that are only available for the backend and not exposed in any way to the API side. How do you want to proceed from here?

you should have 

```graphql
type Model {
  publicAttribute: String
}

input createModelInput {
  publicAttribute: String
  privateAttributesToo: String
}
```

We don't have a concept of a completly private attributes right now so we won't be breaking the current implementation. 
We will consider making private attributes 100% invisible to the API but I consider this to be a permission concern instead so developpers can decide what should be readable or updatable via the API vs the Admin Panel. A private property won't offer enough flexibility

**Comment by ralphsomeday** [comment]
@alexandrebodin the thing is that i will still be exposing the enums that i want to have hidden from the graphql export as those enum values are only used for configuration purpose in the adminpanel UI. How can i manage to still hide my enums from the export? And keeping the privateAttributesToo where would you do this in the code? Is it fine to convert enums into String type when those enums are marked as private, would that be fine and wont break the current implementation?

**Comment by ralphsomeday** [comment]
@alexandrebodin can you tell me how do you see this work? It looks like what you are suggesting would not work with the current Strapi implementation. Private information is being exposed int he graphql export but we do not have this issue on the REST API side.

**Comment by alexandrebodin** [comment]
I'm saying the enum values will be exposed indeed. Nothin we can do about it that's how graphql works. We just don't support the feature you want for now & we can change the way private fields work to support it for now. The only thing we could add to support your need is a way to remove fields from a type with the graphql config instead. We already have an option to remove a type we could add an option to remove fields from a type. That would allow you to remove them from the schema completely without breaking the private implementation.

In https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#define-a-new-type

we could allow to remove the properties completely 
```
module.exports = {
 type: {
    Person: {
      firstname: false,
      lastname: false,
    }
  }
}

**Comment by ralphsomeday** [comment]
@alexandrebodin what if we add an attribute in the model something exportToGraphql: false (optional by default it is true) then this would be easier to filter on in the current updated files. Would that work for you?

**Comment by alexandrebodin** [comment]
> @alexandrebodin what if we add an attribute in the model something exportToGraphql: false (optional by default it is true) then this would be easier to filter on in the current updated files. Would that work for you?

To keep the graphql consistent in v3 this should stay in the schema.graphql.js files for now. We are creating convention in the model files for plugin options but it is not ready yet.

**Comment by ralphsomeday** [comment]
@alexandrebodin can you point me in a direction where I can start so I can implement this setup?  Taking into account that we want to hide fields that are part of the model and not custom fields.

**Comment by alexandrebodin** [comment]
> @alexandrebodin can you point me in a direction where I can start so I can implement this setup? Taking into account that we want to hide fields that are part of the model and not custom fields.

you can look into https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/schema-definitions.js#L30

This function receives the types generated and transforms them into the schema. you have a configurations object that will contain the values you have set in the schema.graphql.js file so you can use them to remove certain attributes in https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/schema-definitions.js#L45

**Comment by ralphsomeday** [comment]
@alexandrebodin this is way too complex to implement as this is not only part of the input but also part of types that may have already been generated by the ShadowCrud and that you would like to overwrite. Same way for enums how do you want to do this? It is way easier to do it at mutation and query level (like you can already do by flagging queries or mutations to false) but too complex at type and input level (no idea how to do it for enums). It would be way easier to add an optional attribute to the model (exportToGraphql) so that we can just add it to false to indicate to the graphql plugin that we do not wish to export that attribute in the graphql schema. Could you please discuss it within the team tomorrow and get back to me as this is a working solution that does not require too much refactoring and easy to maintain and document. thanks

**Comment by alexandrebodin** [comment]
@ralphsomeday 

I don't see how this is too complexe ? instead of working in the toSDL functions you can work in the generation phase.
Instead of using isPrivate you can create another method like in the following example

e.g

```js
const isEnabled = (model, attr) => _.get(strapi.plugins.graphql, `config._schema.graphql.type.${model.globalId}.${attr}`) !== false

// e.g for enums
const generateEnumDefinitions (model, globalId) => {
  
  return Object.keys(attributes)
    // you can do this for inputs / type everywhere
    .filter(attribute => isEnabled(model, attribute)
    .filter(attribute => attributes[attribute].type === 'enumeration')
    .map(attribute => {
      const definition = attributes[attribute];
     

      return `enum ....`
    })
    .join('');
}
```

**Comment by ralphsomeday** [comment]
> @ralphsomeday
> 
> I don't see how this is too complexe ? instead of working in the toSDL functions you can work in the generation phase.
> Instead of using isPrivate you can create another method like in the following example
> 
> e.g
> 
> ```js
> const isEnabled = (model, attr) => _.get(strapi.plugins.graphql, `config._schema.graphql.type.${model.globalId}.${attr}`) !== false
> 
> // e.g for enums
> const generateEnumDefinitions (model, globalId) => {
>   
>   return Object.keys(attributes)
>     // you can do this for inputs / type everywhere
>     .filter(attribute => isEnabled(model, attribute)
>     .filter(attribute => attributes[attribute].type === 'enumeration')
>     .map(attribute => {
>       const definition = attributes[attribute];
>      
> 
>       return `enum ....`
>     })
>     .join('');
> }
> ```

@alexandrebodin thanks for sharing a solution. Can you review it and let me know what you think. Thanks.

File: packages/strapi-plugin-graphql/services/type-definitions.js [hunk 6]
```diff
@@ -72,7 +70,7 @@ const buildTypeDefObj = model => {
   }
 
   Object.keys(attributes)
-    .filter(isNotPrivate(model))
+    .filter(attributeName => isTypeAttributeEnabled(model, attributeName))
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-definitions.js:73]: you can keep both isPrivate & isEnabled in the type

File: packages/strapi-plugin-graphql/services/type-definitions.js [hunk 7]
```diff
@@ -86,7 +84,7 @@ const buildTypeDefObj = model => {
   // Change field definition for collection relations
   associations
     .filter(association => association.type === 'collection')
-    .filter(association => isNotPrivate(model, association.alias))
+    .filter(association => !contentTypes.isPrivateAttribute(model, association.alias))
```
Comment (alexandrebodin) [inline packages/strapi-plugin-graphql/services/type-definitions.js:87]: you can also add the isEnabled to remove assocations if you want to

**Review by alexandrebodin — COMMENTED** [review]
that's looking like a good approach hopefully we can refactor this to get the valid fields just once at some point

**Comment by ralphsomeday** [comment]
@alexandrebodin updated the code but tests are still failing can you help to understand what the issue is? thanks

**Comment by alexandrebodin** [comment]
if you look at the logs in https://github.com/strapi/strapi/pull/9805/checks?check_run_id=2352859017 you can see there are two tests failing on private fields. You should read what they are doing to find out what is broken

**Comment by ralphsomeday** [comment]
@alexandrebodin should be GTM

**Review by alexandrebodin — COMMENTED** [review]
That looks good to me. Nice work. 

Before we can merge I would like to see some testing to check this. Are you up for it ?

**Comment by ralphsomeday** [comment]
@alexandrebodin what would you like to add for testing? Where would that be?

**Comment by ralphsomeday** [comment]
@alexandrebodin can you recommend how to take this PR forward. Thanks

**Review by alexandrebodin — COMMENTED** [review]
You can add a unit test file that will call the modified functions. You can mock the global strapi var to fake some disable attribute & verify the function removes them corectly

**Comment by ralphsomeday** [comment]
@alexandrebodin can you give me an example for this specific case as I am not able to find the unit test for removing CRUD mutations and queries by creating your own schema.graphql.js and setting mutations and queries to false and testing that those are not available in the schema anymore. If you have this unit test somewhere can you point me to it if not can you share a quick example so I can start from there. thanks

**Comment by alexandrebodin** [comment]
> @alexandrebodin can you give me an example for this specific case as I am not able to find the unit test for removing CRUD mutations and queries by creating your own schema.graphql.js and setting mutations and queries to false and testing that those are not available in the schema anymore. If you have this unit test somewhere can you point me to it if not can you share a quick example so I can start from there. thanks

There are no examples no. Here is one

```js
const { generateInput } = require('../type-builder')

describe('generateInput', () => {

  test('removes disabled attributes', () => {
   global.strapi = {
     plugins: { 
       graphql: {
         config: {
           _schema: {
             graphql: {
               type: {
                 someTestType: {
                   testAttr: false
                 }
               }
             }
           }
         }
       }
     };
      
   expect(generateInputModel(/* ... */)).toEqual(/* ... */)

 })

})

```

**Comment by ralphsomeday** [comment]
@alexandrebodin any idea why the tests are not reporting their status?

**Comment by alexandrebodin** [comment]
No idea no. Can you fix the conflicts & add more test to the other functions you modified ?

**Comment by ralphsomeday** [comment]
@alexandrebodin added the test and all working fine.

**Comment by alexandrebodin** [comment]
Hi @ralphsomeday can you add test to the other functions you modified please ?

**Comment by ralphsomeday** [comment]
@alexandrebodin done. GTM.

**Review by Convly — CHANGES_REQUESTED** [review]
Works well on my side, one suggestion though

**Comment by alexandrebodin** [comment]
Looks good. Last thing would be to add some documentation in our documentation repository :) @pwizla  & @derrickmehaffy  can help you with that :)

**Comment by ralphsomeday** [comment]
Hi @pwizla & @derrickmehaffy can you guys point me out to where would be the best place in the documentation to add this? thanks

**Comment by alexandrebodin** [comment]
I think youc an add this arround here https://github.com/strapi/documentation/blob/main/docs/developer-docs/latest/development/plugins/graphql.md#disable-a-query-or-a-type

**Comment by ralphsomeday** [comment]
@alexandrebodin done [PR#269](https://github.com/strapi/documentation/pull/269)

**Comment by ralphsomeday** [comment]
@alexandrebodin can you let me know if this PR can now be merged. thanks

**Comment by alexandrebodin** [comment]
The PR looks good We will wait for the doc PR to be approved first :)

**Comment by pwizla** [comment]
> The PR looks good We will wait for the doc PR to be approved first :)

I've just approved the docs PR, thank you @ralphsomeday ! 👍 
@alexandrebodin please let me know when you merge this PR and I'll merge the docs one (won't be live before next week, though)

**Comment by ralphsomeday** [comment]
@alexandrebodin do you think this one can be added to v3.6.2? and when do you plan to release v3.6.2?
