### PR TITLE
fix: rerendering and flickering issue on i18n fields

### LINKED ISSUE #20409: i18n locale overrides other locales
### Required System information

- Node.js version: 18.19.0
- NPM version: 10.5.1
- Strapi version: 4.24.3
- Database: postgres
- Operating system: Mac OS darwin-x64
- Is your project Javascript or Typescript: typescript

### Describe the bug
Hi all,
I have started creating a new app and opted to use Strapi, however I have an issue with i18n.

The issue is that when I try to change internationalization I manage to select one in the dropdown but fields (which do have an internationalization enabled icon) are prefilled with data from the old locale. when i change and save something the original locale changes as well and i don’t have a different version of the locale in my db.
Also when i click fill with another localization I have nothing to choose from.

Some other fields work as expected and change the localization normally.

### Steps to reproduce the behavior

It's hard to reproduce since i've come across it only on two fields (one collection and one single type).
create a type (internationalization true) go to content manager create a collection and sometimes that collection has options in one dropdown so change language but whenever i change something it mirrors to the other language.

### Expected behavior
When internationalization changes present me with another language version or empty if it wasn't filled previously. Fill with another language should offer me another language but it doesn't.

### Screenshots

Screenshot 2024-05-31 at 11 56 08
Screenshot 2024-05-31 at 11 56 19
Screenshot 2024-05-31 at 11 56 28
Screenshot 2024-05-31 at 12 03 42

### Code snippets

`{
  "kind": "singleType",
  "collectionName": "footer_bars",
  "info": {
    "singularName": "footer-bar",
    "pluralName": "footer-bars",
    "displayName": "FooterBar"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "versions": {
      "versioned": true
    },
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "nav_items": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::navbar-item.navbar-item"
    },
    "socialsLabel": {
      "pluginOptions": {
        "versions": {
          "versioned": true
        },
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "required": true
    }
  }
}
`

### PR DESCRIPTION
**Pull request by Adzouz**
### What does it do?

_I know it's related to admin + content manager package but flagging it as plugin:i18n to better track the issue._

There are a few weird behaviours currently with i18n fields.
The first is that a few fields don't rerender correctly with the correct data when switching locales right after a save and can cause wrong data to be overriden in the wrong locale (this one is pretty serious).

Video to show the problem:

https://github.com/user-attachments/assets/a0d56d86-f88f-4847-9083-29f8a3f08eae

The second is a little flickering when clicking on Publish after editing fields in an entry (caused by a resetForm action triggered when publishing entries).

Video to show the problem:
_(focus on the text field to see the flickering issue when publushing)_

https://github.com/user-attachments/assets/52b216c1-61d4-4d3a-839e-9c8bab0bcf5f

### Why is it needed?

It would prevent data from a locale to override content of another one in translated fields and prevent flickering issue displaying the old value for a second when clicking on Publish button.

### How to test it?

For the first issue, it's tricky but here are the steps:
- Go to the content manager and select a collection type where Draft and Publish and Internationalization are enabled and where there's a number field (also localized)
- Create a new entry in the first locale and put a number
- Save and publish
- Switch to another locale
- Put another value for the number and save + publish too
- Switch back to the first locale, change the number and save (put another number than the one you choose for the second locale to see the difference)
- Switch to the second locale again and check the value in the number field
-> Before the fix, the value would be wrong and the one you set on the first locale
-> After the fix, the value is the one you should see for the second locale

For the second issue (flickering):
- Go to the content manager and again select the same collection type than for the first test
- Put some content in any field (a text one for example)
- Click Save and Publish
- Edit the value of the field again and click Publish
-> Before the fix, for a second you'll see the previous value
-> After the fix, no more flickering, the value stays the latest

### Related issue(s)/PR(s)

Resolves #20409 #21063 #23765

🚀

### CODE REVIEW

File: packages/core/admin/admin/src/components/Form.tsx [hunk 1]
```diff
@@ -306,7 +306,8 @@ const Form = React.forwardRef<HTMLFormElement, FormProps>(
 
     const modified = React.useMemo(
       () => !isEqual(initialValues.current, state.values),
-      [state.values]
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+      [state.values, initialValues.current]
```
Comment (Adzouz) [inline packages/core/admin/admin/src/components/Form.tsx:310]: For an obscure reason I need to add the eslint disable because I do need to watch changes on `initialValues.current` but I don't know why it's complaining that it's not part of dependencies 🤷‍♂️

**Review by mathildeleg — DISMISSED** [review]

File: packages/core/admin/admin/src/components/Form.tsx (hunk 1 above)
Comment (HichamELBSI) [reply packages/core/admin/admin/src/components/Form.tsx:310]: eslint is mad because `initialValues` is a ref which means that initialValues persist across renders. Updating `.current` of a ref won't trigger the useEffect. This seems wrong to me.

File: packages/core/admin/admin/src/components/FormInputs/Boolean.tsx [hunk 2]
```diff
@@ -8,18 +9,23 @@ import { useField } from '../Form';
...
   ({ name, required, label, hint, labelAction, ...props }, ref) => {
     const { formatMessage } = useIntl();
     const field = useField<boolean | null>(name);
     const fieldRef = useFocusInputField<HTMLInputElement>(name);
+    const [{ query }] = useQueryParams<{ plugins?: { i18n?: { locale?: string } } }>();
 
     const composedRefs = useComposedRefs(ref, fieldRef);
 
+    // Create a key that changes when locale changes to force re-render
+    const localeKey = query?.plugins?.i18n?.locale || 'default';
```
Comment (HichamELBSI) [inline packages/core/admin/admin/src/components/FormInputs/Boolean.tsx]: Do these changes work correctly on a collection type that is not internationalised?

Comment (HichamELBSI) [reply packages/core/admin/admin/src/components/FormInputs/Boolean.tsx]: Same question for all the inputs.

File: packages/core/admin/admin/src/components/Form.tsx (hunk 1 above)
Comment (Adzouz) [reply packages/core/admin/admin/src/components/Form.tsx:310]: Ah good catch. So what should I do? Because the resetForm is resetting to the initialValues for a second causing the flickering effect so I didn't really have other idea than setting initialValues.current to the new values after saving / publish (which actually makes sense for me since the initial values become the new ones).

File: packages/core/admin/admin/src/components/FormInputs/Boolean.tsx (hunk 2 above)
Comment (Adzouz) [reply packages/core/admin/admin/src/components/FormInputs/Boolean.tsx]: Yes it will fallback to default and since we can't switch between languages, we don't have the rerender issue. But the only thing I'm not really fan of is that it's referring to the i18n plugin in the admin package but I don't really have other idea on how to do it in another way since it's really the switching between two locales that causes the issue.

Comment (Adzouz) [reply packages/core/admin/admin/src/components/FormInputs/Boolean.tsx]: I tried a different approach (the hook). I put the logic to fetch the locale directly in the i18n plugin and exported it as a hook that I load in both admin and the CM. Then I created a useLocaleKey in both packages to call the hook. Does that makes sense to you?

File: packages/core/admin/admin/src/components/Form.tsx (hunk 1 above)
Comment (HichamELBSI) [reply packages/core/admin/admin/src/components/Form.tsx:310]: I've just tested without this update and I can't see any flickering 🤔

File: packages/core/admin/admin/src/components/FormInputs/Boolean.tsx [hunk 3]
```diff
@@ -1,25 +1,28 @@
...
 
 import { InputProps } from './types';
 
-const BooleanInput = forwardRef<HTMLInputElement, InputProps>(
+const BooleanInput = React.forwardRef<HTMLInputElement, InputProps>(
   ({ name, required, label, hint, labelAction, ...props }, ref) => {
     const { formatMessage } = useIntl();
     const field = useField<boolean | null>(name);
     const fieldRef = useFocusInputField<HTMLInputElement>(name);
+    const localeKey = useLocaleKey();
```
Comment (HichamELBSI) [inline packages/core/admin/admin/src/components/FormInputs/Boolean.tsx]: The fact that there is a mention of locale in the fields is a problem. On a content type that does not have the i18n feature enabled, this hook will be called in all inputs. This is unnecessary. We have the information on whether i18n is enabled or not in the schema.pluginOptions.i18n object. 

Another big issue is that the hook is called in all dynamic forms of the app. For example, in the profile page.

File: packages/core/admin/admin/src/components/Form.tsx (hunk 1 above)
Comment (Adzouz) [reply packages/core/admin/admin/src/components/Form.tsx:310]: Yes but this part is not about the flickering. If you remove this part, the modified status won't change after submitting the form, keeping it in modified status even after publishing / saving 😕

Comment (HichamELBSI) [reply packages/core/admin/admin/src/components/Form.tsx:310]: Alright, I'll test it again

File: packages/core/admin/admin/src/components/FormInputs/Boolean.tsx (hunk 3 above)
Comment (Adzouz) [reply packages/core/admin/admin/src/components/FormInputs/Boolean.tsx]: Yes I know, I thought that using a hook would be "cleaner" because if i18n isn't available, it will just fallback to default but I understand your point, I'll try to find another solution. I'll let you know if I'm stuck. Thanks for your patience 🙏

File: packages/core/admin/admin/src/components/Form.tsx (hunk 1 above)
Comment (Adzouz) [reply packages/core/admin/admin/src/components/Form.tsx:310]: I could use another state variable to store the actual version of the values so it wouldn't rely on a ref anymore. But I don't find it much cleaner tbh. Wdyt?

**Comment by Adzouz** [comment]
I tried to go with a simpler solution and scope it for edit view page only (getting rid of the hook + removing everything in the field children elements).
