### PR TITLE
Fix - keep autoPopulate:false options on update

### LINKED ISSUE #4150: Content type builder always remove "autoPopulate" options in models
**Describe the bug**
Content type builder always remove "autoPopulate" options in models

**Steps to reproduce the behavior**
1. create many to many relationship with 2 models
2. edit model setting to disable autoPopulate by adding `"autoPopulate": false`
3. add some field in one of model using content type builder. and save it.
4. see the different using `git diff`
```
-    "chapters": {
-      "collection": "chapter",
-      "via": "novel",
-      "autoPopulate": false
-    },


+    "chapters": {
+      "collection": "chapter",
+      "via": "novel"
+    },

```

**Expected behavior**
dont remove edited custom model while using content type builder

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.9.1
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.16.1 
- Database: mongodb
- Operating system: ubuntu

**Additional context**

### PR DESCRIPTION
**Pull request by pataiadam**
#### Description of what you did:
fix #4150

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

#### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

File: packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js [hunk 1]
```diff
@@ -172,6 +172,10 @@ module.exports = function createComponentBuilder() {
             this.unsetRelation(oldAttribute);
           }
 
+          if (Object.keys(oldAttribute).includes('autoPopulate')) {
+            newAttribute.autoPopulate = oldAttribute.autoPopulate;
+          }
```
Comment (pataiadam) [inline packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js]: Or here, we can just write:

`newAttribute.autoPopulate = oldAttribute.autoPopulate === false ? false : undefined`

**Comment by alexandrebodin** [comment]
HI @pataiadam Thank your for this PR but I would like it to also keep autoPopulate set to true if set too :) 
Do you think you can make this happen ? WOuld be awesome ! 💯

**Comment by pataiadam** [comment]
Hi @alexandrebodin ! I've made a new commit with the requested changes. Could you please review that :) Thanks! 👍

**Comment by pataiadam** [comment]
@alexandrebodin You were right, I didn't see that case! I've pushed an other commit. :)

**Comment by alexandrebodin** [comment]
Nice job ! Will test and validate this week ;) Great work 💯

File: packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js [hunk 2]
```diff
@@ -174,6 +177,8 @@ module.exports = function createComponentBuilder() {
             this.unsetRelation(oldAttribute);
           }
 
+          newAttribute.autoPopulate = oldAttribute.autoPopulate;
```
Comment (alexandrebodin) [inline packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js]: I just tested your branch and I discovered an issue with this statement :)
I tried not setting the autoPopulate first and then call the api with an autopopulate value. This will override the edit and leave autopopulate to undefined. (Really a edge case because the interface doesn't offer the option)

For the sake of completness could you please check do sth like

`newAttribute.autoPopulate = newAttribute.autoPopulate || oldAttribute.autoPopulate` ? 

Thanks !

**Comment by pataiadam** [comment]
Sure! :) 
By the way, we should put this option into the interface too. Right? I might create another PR, if this one will be merged :)

**Comment by alexandrebodin** [comment]
> Sure! :)
> By the way, we should put this option into the interface too. Right? I might create another PR, if this one will be merged :)

Thanks ! We prefer keep technical field to json to avoid too much options in the client :)

**Comment by alexandrebodin** [comment]
@pataiadam We just added a DCO which requires you to sign-off your commit. 

You an check https://github.com/strapi/strapi/pull/4949/checks?check_run_id=395223776 for more details ;)

**Comment by pataiadam** [comment]
> We prefer keep technical field to json to avoid too much options in the client :)

I see, I like this concept :)

> Waiting for your commits to be signed-off before merging :)

Honestly, I've never done this "sign-off" thing before 😟
I've checked the page you linked, it says I need to do a rebase:

```
git rebase HEAD~7 --signoff
```

But it is just completely messing up the code base (I've got a ton of conflicted files, but I only modified 4), and then it says I need to force-push it to my branch. I think I'm doing something wrong 😅 

Could you help me with this please? :)
