### PR TITLE
Fix relations not correctly set when uploading a new file to an entity

### LINKED ISSUE #14125: Upload Plugin does not update the refId
### Required System information

 

- Node.js version: 16
- NPM version: 6.14
- Strapi version: v4.3.2
- Database:PG
- Operating system: Linux/Win

### Describe the bug

When Updating a file using `{{ _.baseURL }}api/upload` to an entity of type `plugin::users-permissions.user` The image gets uploaded and corresponding row in `files_related_morphs` table will be added. However it adds a new row instead of updating the existing row which cause strapi to return the first uploaded file
image

### Steps to reproduce the behavior
1. Add a user object as following setting ```"image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },```
2. upload a file using upload api
3. upload another using the same upload api
4. The user image is not updated with the second image

### Expected behavior

I think we need to update refId row in `files_related_morphs` table instead on creating, or check if it exists update it.
### Additional context
[
I guess this line should change?
](@strapi/plugin-upload/server/services/upload.js#L337-L338

```javascript
    const res = await strapi.query(FILE_MODEL_UID).create({ data: fileValues });

```)

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

Fix #14125

### Why is it needed?

In certain cases with polymorphic relations (morphOne) the update of the relation was not correctly removing the previous relations.
NB: The issue is revealed in the upload plugin but the root cause is in the database layer.

### How to test it?

Tests are in PR

### Related issue(s)/PR(s)

Fix #14125

### CODE REVIEW

File: packages/core/database/lib/entity-manager.js [hunk 1]
```diff
@@ -402,6 +402,21 @@ const createEntityManager = (db) => {
...
           }
 
+          // delete previous relations
+          const where = { $or: [] };
+
+          for (const { field, related_type: relatedType, related_id: relatedId } of rows) {
+            const isMorphOne =
+              db.metadata.get(relatedType).attributes[field].relation === 'morphOne';
+            if (isMorphOne) {
+              where.$or.push({ related_type: relatedType, field, related_id: relatedId });
```
Comment (alexandrebodin) [inline packages/core/database/lib/entity-manager.js:412]: you could simplify by pushing those conditions in one simple array and applying the $or in the .where({ $or: conditions })) call

Comment (alexandrebodin) [inline packages/core/database/lib/entity-manager.js:412]: I'm wondering if it would be better to group by type to allow doing an $in for each type instead of one condition per row 🤔

Comment (petersg83) [reply packages/core/database/lib/entity-manager.js:412]: Grouping by type **and** field. I thought about it and why not honestly. I hesitated because it adds some code complexity for maybe not so much gain. I see the gain in case there are many many ids. So maybe it's worth it after all. wdyt?

Comment (alexandrebodin) [reply packages/core/database/lib/entity-manager.js:412]: I have the feeling what we would win in query we might loose in js. The only win I see is it condenses the query so will avoid the "too many arguments" error in most cases

Comment (petersg83) [reply packages/core/database/lib/entity-manager.js]: I updated the PR

File: packages/core/database/lib/entity-manager.js [hunk 2]
```diff
@@ -398,10 +411,37 @@ const createEntityManager = (db) => {
...
+              db.metadata.get(relatedType).attributes[field].relation === 'morphOne';
+            if (isMorphOne) {
+              const key = `${relatedType}+${field}`;
+              typeAndFieldIdsMap[key] = typeAndFieldIdsMap[key] || [];
+              typeAndFieldIdsMap[key].push(relatedId);
+            }
+          }
+
+          const orWhere = _.map(typeAndFieldIdsMap, (ids, typeAndField) => {
+            const [type, field] = typeAndField.split('+');
```
Comment (alexandrebodin) [inline packages/core/database/lib/entity-manager.js:434]: That concat string approach might not look like a problem because there isn't supposed to be a `+` in the string but it's brittle code. 

You could use 2 groupBy to make the code safer 

I made an example with lodash fp lib here https://replit.com/@alexandrebodin/map#index.js

File: packages/core/database/lib/entity-manager.js [hunk 3]
```diff
@@ -577,10 +619,27 @@ const createEntityManager = (db) => {
...
 
-          if (_.isEmpty(rows)) {
+          if (isEmpty(rows)) {
             continue;
           }
 
+          // delete previous relations
+          const where = { $or: [] };
+
+          for (const { field, related_type: relatedType, related_id: relatedId } of rows) {
```
Comment (alexandrebodin) [inline packages/core/database/lib/entity-manager.js:629]: same remark here

File: packages/core/database/lib/entity-manager.js [hunk 4]
```diff
@@ -577,10 +634,49 @@ const createEntityManager = (db) => {
             ...(data.__pivot || {}),
           }));
 
-          if (_.isEmpty(rows)) {
+          if (isEmpty(rows)) {
             continue;
           }
 
+          // delete previous relations
+          const morphOneRows = rows.filter((row) => {
```
Comment (alexandrebodin) [inline packages/core/database/lib/entity-manager.js:642]: I would suggest to put this logic in one function to be reused

**Review by alexandrebodin — COMMENTED** [review]
This looks good just some factoring could be nice

File: packages/core/upload/tests/content-api/upload.test.e2e.js [hunk 5]
```diff
@@ -183,6 +186,51 @@ describe('Upload plugin end to end tests', () => {
           id: expect.anything(),
         },
       });
+      data.dogs.push(res.body);
+    });
+  });
+
+  // see https://github.com/strapi/strapi/issues/14125
```
Comment (alexandrebodin) [inline packages/core/upload/tests/content-api/upload.test.e2e.js:193]: Do we realy want to reference that issue in the code?

**Review by alexandrebodin — COMMENTED** [review]
This looks good, 

Can we run some QA on it before we merge it? (validating component behaviors are unchanged & the ML is still 100% functional?

**Review by MarionLemaire — COMMENTED** [review]
Tested on Gestarted using Chrome (functional QA focused on Media Libary and components) : 

**- Media Library seems OK :**
- Upload a file on ML : OK
Replace a file on ML : OK
Rename a file on ML : OK
Add 2 pics from ML to CTB item : OK (with the reflected changes from the ML)
Delete a file on ML : OK
Move a file from ML to nested folder (level 4) : OK

**- Had an issue while testing components :** 
In CTB, I created an entity Dog with : 
- A fied short text
- A field rich text
- A media field
- A relation (many to many)
- A component using an existing component (apple) on which I added another field Media >> this made my app crash
image

ebug: :no_entry:️ Server wasn't able to start properly.
error: CREATE TABLE `_knex_temp_alter453` (`permission_id` integer NULL, `role_id` integer NULL, `id` integer not null primary key autoincrement NOT NULL, CONSTRAINT `admin_permissions_role_links_fk` FOREIGN KEY (`permission_id`) REFERENCES `admin_permissions` (`id`) ON DELETE CASCADE, CONSTRAINT `admin_permissions_role_links_inv_fk` FOREIGN KEY (`role_id`) REFERENCES `admin_roles` (`id`) ON DELETE CASCADE, CONSTRAINT `admin_permissions_role_links_fk` FOREIGN KEY (`permission_id`) REFERENCES `admin_permissions` (`id`) ON DELETE CASCADE, CONSTRAINT `admin_permissions_role_links_inv_fk` FOREIGN KEY (`role_id`) REFERENCES `admin_roles` (`id`) ON DELETE CASCADE, PRIMARY KEY (`id`)) - table "_knex_temp_alter453" has more than one primary key
SqliteError: CREATE TABLE `_knex_temp_alter453` (`permission_id` integer NULL, `role_id` integer NULL, `id` integer not null primary key autoincrement NOT NULL, CONSTRAINT `admin_permissions_role_links_fk` FOREIGN KEY (`permission_id`) REFERENCES `admin_permissions` (`id`) ON DELETE CASCADE, CONSTRAINT `admin_permissions_role_links_inv_fk` FOREIGN KEY (`role_id`) REFERENCES `admin_roles` (`id`) ON DELETE CASCADE, CONSTRAINT `admin_permissions_role_links_fk` FOREIGN KEY (`permission_id`) REFERENCES `admin_permissions` (`id`) ON DELETE CASCADE, CONSTRAINT `admin_permissions_role_links_inv_fk` FOREIGN KEY (`role_id`) REFERENCES `admin_roles` (`id`) ON DELETE CASCADE, PRIMARY KEY (`id`)) - table "_knex_temp_alter453" has more than one primary key
    at Database.prepare (/home/yon/strapiii/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (/home/yon/strapiii/node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
    at executeQuery (/home/yon/strapiii/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/home/yon/strapiii/node_modules/knex/lib/client.js:146:12)
    at /home/yon/strapiii/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_BetterSQLite3.trxClient.query (/home/yon/strapiii/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/home/yon/strapiii/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/home/yon/strapiii/node_modules/knex/lib/execution/runner.js:224:21)
    at Runner.queryArray (/home/yon/strapiii/node_modules/knex/lib/execution/runner.js:276:31)
error Command failed with exit code 1.

(I tried to reproduce in Main branch and it worked well)

**Comment by alexandrebodin** [comment]
FYI, the bug encountered wasn't due to this PR and is fixed in https://github.com/strapi/strapi/pull/14332 :)

**Review by alexandrebodin — APPROVED** [review]

**Review by MarionLemaire — COMMENTED** [review]
Quickly re-tested on Chrome using Gestsarted : 
Upload a file on ML : OK
Replace a file on ML : OK
Rename a file on ML : OK
Add 2 pics from ML to CTB item : OK (with the reflected changes from the ML)
Delete a file on ML : OK
Move a file from ML to nested folder (level 2) : OK
Create a CTB with a component and create an entry for it : OK

LGTM :)
