### PR TITLE
Generate fileInfo for every file when uploading in bulk

### LINKED ISSUE #13999: MediaLibrary Content Is genrating New Auto Folders and save images there automatic while Upload from postman or App
- Node.js version:16
- NPM version:6
- Strapi version:4.3.2

- Operating system:windows

### Describe the bug
I've tried a lot of methods to skip this but there's no way Every Time i upload and media images to Media Library Content Is generating new folder is (API Upload) and save only one Image for each upload and save other's out the folder in assets ....
can some one help ;
https://user-images.githubusercontent.com/96669613/183116817-3f9c25db-eca6-4a57-99e3-b3a7be71a64d.png

### PR DESCRIPTION
**Pull request by WalkingPizza**
### What does it do?

Fixes #13999.

### Why is it needed?

Uploading multiple files via API only moves the first file to the _API Uploads_ folder instead of all of them.

### How to test it?

Try uploading multiple files via API and notice that all end up in the appropriate folder.

### Related issue(s)/PR(s)

#13999

### CODE REVIEW

**Comment by WalkingPizza** [comment]
PS: I'd consider reworking the `validateUploadBody` function a bit because I don't think it's working as intended.

File: packages/core/upload/server/controllers/content-api.js [hunk 1]
```diff
@@ -94,8 +94,14 @@ module.exports = {
...
 
     const apiUploadFolder = await apiUploadFolderService.getAPIUploadFolder();
+
     data.fileInfo = data.fileInfo || {};
-    data.fileInfo = Array.isArray(data.fileInfo) ? data.fileInfo : [data.fileInfo];
+
+    data.fileInfo =
+      Array.isArray(data.fileInfo) && data.fileInfo.length === files.length
+        ? data.fileInfo
+        : Array.from({ length: files.length || 1 }, () => data.fileInfo);
```
Comment (petersg83) [inline packages/core/upload/server/controllers/content-api.js:103]: `files` is not always an array so the `fileInfo` may not be one neither. What do you think of this code:
```js
    const data = await validateUploadBody(body, Array.isArray(files));

    const apiUploadFolderService = getService('api-upload-folder');

    const apiUploadFolder = await apiUploadFolderService.getAPIUploadFolder();

    if (Array.isArray(files)) {
      data.fileInfo = data.fileInfo || [];
      data.fileInfo = files
        .map((f, i) => data.fileInfo[i] || {})
        .map(fileInfo => ({ ...fileInfo, folder: apiUploadFolder.id }));
    } else {
      data.fileInfo = data.fileInfo || {};
      data.fileInfo = { ...data.fileInfo, folder: apiUploadFolder.id  } ;
    }
```

**Review by petersg83 — CHANGES_REQUESTED** [review]
Thank you for your help! :) I put a comment.

There should be a release wednesday. Would you have time to update the PR today?
Also would you like to write the corresponding tests to ensure it doesn't happen again? Otherwise I will do it :)

File: packages/core/upload/server/controllers/content-api.js (hunk 1 above)
Comment (WalkingPizza) [reply packages/core/upload/server/controllers/content-api.js:103]: Correct me if I am wrong, but it looks like the pre-PR code was always converting `fileInfo` to an array even when there was only one file, do you know why that was happening?

Comment (petersg83) [reply packages/core/upload/server/controllers/content-api.js:103]: Yes you're right! The code is a bit messy around here.
Both `files` and `fileInfo` are converted to arrays just after, there: https://github.com/strapi/strapi/blob/master/packages/core/upload/server/services/upload.js#L157

I would say it's best to convert both to arrays at the same moment, so either here or later in the upload service.
I would avoid modifying the upload service to avoid the risk of breaking changes (some users may already use it).
So if we keep the array conversion in the service, I would avoid doing it here.
So technically it works but maybe it makes more sense to not convert to arrays now?

What do you think?
Or we can convert to arrays now too, it's redundant but I would not have an objection for that.

Comment (WalkingPizza) [reply packages/core/upload/server/controllers/content-api.js:103]: You are right!

Just looked at the `upload` service and noticed they also get converted there.

I'll go ahead and apply your suggestion so the `upload` service remains untouched!

For tests, what would you test exactly? Maybe the length of the `fileInfo` array?

Comment (petersg83) [reply packages/core/upload/server/controllers/content-api.js]: Alright thank you!

I have in mind a e2e test : to upload multiple files and check that the files go in the correct folder
It would be located in and similar to `packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js`

File: packages/core/upload/server/controllers/content-api.js [hunk 2]
```diff
@@ -94,9 +94,13 @@ module.exports = {
     const apiUploadFolderService = getService('api-upload-folder');
 
     const apiUploadFolder = await apiUploadFolderService.getAPIUploadFolder();
-    data.fileInfo = data.fileInfo || {};
-    data.fileInfo = Array.isArray(data.fileInfo) ? data.fileInfo : [data.fileInfo];
-    data.fileInfo.forEach(fileInfo => (fileInfo.folder = apiUploadFolder.id));
+
+    if (Array.isArray(files)) {
+      data.fileInfo = data.fileInfo || [];
+      data.fileInfo = files.map((_f, i) => ({ ...data.fileInfo[i], folder: apiUploadFolder.id }));
```
Comment (petersg83) [inline packages/core/upload/server/controllers/content-api.js:100]: I think the spread wont work if `fileInfo` is empty. If you want to do it in one line I guess it would be 
```js
data.fileInfo = files.map((_f, i) => ({ ...(data.fileInfo[i] || {}), folder: apiUploadFolder.id }));
```

Also, line 92, I think you can replace the line by :
```js
const data = await validateUploadBody(body, Array.isArray(files));
```
As you said, something was wrong with `validateUploadBody`

Comment (WalkingPizza) [reply packages/core/upload/server/controllers/content-api.js:100]: Tested the spread and I think it works!

In this case, `data.fileInfo[i]` could either be an object or `undefined`, and spreading `undefined` should be equivalent to spreading an empty object.

I also applied the suggestion on line 92.

File: packages/core/upload/server/controllers/content-api.js (hunk 1 above)
Comment (WalkingPizza) [reply packages/core/upload/server/controllers/content-api.js]: Just pushed some tests.
I have basically re-adapted the tests from the first suite to work with multiple uploads.
Let me know what you think!

File: packages/core/upload/server/controllers/content-api.js (hunk 2 above)
Comment (petersg83) [reply packages/core/upload/server/controllers/content-api.js:100]: Indeed, I didn't know we could spread `undefined`! I'm glad to know now :D

File: packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js [hunk 3]
```diff
@@ -413,4 +413,141 @@ describe('Uploads folder', () => {
...
+      });
+
+      expect(res.statusCode).toBe(200);
+
+      const {
+        body: { results: files },
+      } = await rqAdmin({
+        method: 'GET',
+        url: `/upload/files?filters[id][$in][0]=${res.body[0].id}&filters[id][$in][1]=${res.body[1].id}`,
+      });
```
Comment (petersg83) [inline packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js:437]: I think you can simplify with:
```js
const {
  body: { results: files },
} = await rqAdmin({
  method: 'GET',
  url: '/upload/files',
  qs: {
    id: {
      $in: res.body.map(f => f.id),
    },
  },
});
```
`qs` will be used for the query string

**Review by petersg83 — CHANGES_REQUESTED** [review]
Thank you! That seems to work well! 🎉 
I made a suggestion + can I propose to also write a test that use fileInfo? Just one that would rename the 2 files (In postman it looked like that)
Capture d’écran 2022-08-08 à 17 19 16

**Review by petersg83 — APPROVED** [review]
Thank you very much for the quality and your responsiveness! 🚀 
It looks perfect! I'm waiting for the tests to pass and I'll merge :) Should be released wednesday
