### PR TITLE
fix(review-workflows): cannot create or update workflow & data doesn't invalidate correctly

### LINKED ISSUE #19439: Not able to create new Review Workflows in Strapi 4.19.1 - 400 Response on Admin request not attaching a payload
### Required System information

- Node.js version: v18.18.0
- NPM version: 9.8.1
- Strapi version: 4.19.1
- Database: SQLite
- Operating system: Darwin Kernel Version 23.0.0 (Apple M2 Pro)
- Is your project Javascript or Typescript: JS

### Describe the bug

Review Workflows don't work at all.

### Steps to reproduce the behavior

1. Add a licence to your project to run EE version
2. Open the Admin Panel > Settings > Review Workflows
3. Try to create a new Review Workflow
4. Populate all the fields and even manually add more stages > Click Save
5. No visual error is displayed so it looks like nothing happens but in the Network tab in Dev Tools we can see the error
6. The error received in a 400, validation error, "A workflow must have at least one stage."
7. The failed request shows no payload tab which leads me to believe we are not attaching a body to the request at all

### Expected behavior

It should create a Review Workflow

### Screenshots

image

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* The types we're incorrect so they're amended to highlight we send the data nested under `data` in the body
* The provides tag set up was wrong where `id===""` but we should be checking it's not an empty string to correctly provide the list tag & in addition provide a single `ReviewWorkflow` not `User`
* We use the param from react-router instead of redux to update the workflow with it's correct `id` 

### Why is it needed?

* Users could not create or update workflows
* Data was not invalidated correctly

### How to test it?

* As a user I should be able to create a workflow
* then update that workflow
* then go to the list view of workflows see that workflow
* edit that workflow again
* go back to the list view and delete the workflow 
* it should not be in the list view no longer

### Related issue(s)/PR(s)

* resolves #19439

### CODE REVIEW

**Review by Marc-Roig — APPROVED** [review]

File: packages/core/admin/ee/admin/src/services/reviewWorkflows.ts [hunk 1]
```diff
@@ -64,10 +64,10 @@ const reviewWorkflowsApi = adminApi.injectEndpoints({
       ReviewWorkflows.Update.Response['data'],
       ReviewWorkflows.Update.Request['body'] & ReviewWorkflows.Update.Params
     >({
-      query: ({ id, ...body }) => ({
+      query: ({ id, ...data }) => ({
         url: `/admin/review-workflows/workflows/${id}`,
         method: 'PUT',
-        body,
+        data: data,
       }),
```
Comment (jhoward1994) [inline packages/core/admin/ee/admin/src/services/reviewWorkflows.ts:71]:
```suggestion
      query: ({ id, ...data }) => ({
        url: `/admin/review-workflows/workflows/${id}`,
        method: 'PUT',
        data,
      }),
```
?

**Review by jhoward1994 — APPROVED** [review]

File: packages/core/admin/ee/admin/src/services/reviewWorkflows.ts [hunk 2]
```diff
@@ -64,10 +64,10 @@ const reviewWorkflowsApi = adminApi.injectEndpoints({
       ReviewWorkflows.Update.Response['data'],
       ReviewWorkflows.Update.Request['body'] & ReviewWorkflows.Update.Params
     >({
-      query: ({ id, ...body }) => ({
+      query: ({ id, ...data }) => ({
         url: `/admin/review-workflows/workflows/${id}`,
         method: 'PUT',
-        body,
+        data: data,
```
Comment (joshuaellis) [inline packages/core/admin/ee/admin/src/services/reviewWorkflows.ts:70]:
```suggestion
        data,
```
