### PR TITLE
Handle redirect after reset password

### LINKED ISSUE #2108: Password Reset redirects authenticated users to admin
**Informations**
- **Node.js version**: 10.4.1
- **npm version**: 6.4.1
- **Strapi version**: Beta 14.2
- **Database**: MongoDB
- **Operating system**: macOS 

**What is the current behavior?**
When using the password reset link below, the user is redirected into the admin
area, which he/she should not have access to. After trying to click any link then,
an error occurs and nothing works.

**Steps to reproduce the problem**
1. Send a POST request to `http://localhost:1337/auth/forgot-password` with the following body:
```json
{ 
	"email": "john@doe.com", 
	"url": "https://localhost:1337/admin/plugins/users-permissions/auth/reset-password"
}
```

**What is the expected behavior?**
After the password reset, redirect the user either to a specified URL or to the main page. But in any case, do not redirect the user to the /admin area.

**Suggested solutions**
Either add a redirect URL or redirect users based on their roles.

### PR DESCRIPTION
**Pull request by aDEVE**
fix #2108 : handle redirect after reset password

update : add destructuring of props to be consistant in file, it was started but not complete. 

My PR is a:

💅 Enhancement

Main update on the:
Admin

### CODE REVIEW

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 1]
```diff
@@ -40,73 +41,90 @@ import styles from './styles.scss';
...
+    setForm(authType, params);
   }
 
-  componentWillReceiveProps(nextProps) {
-    if (this.props.match.params.authType !== nextProps.match.params.authType) {
-      const params = nextProps.location.search ? replace(nextProps.location.search, '?code=', '') : nextProps.match.params.id;
-      this.props.setForm(nextProps.match.params.authType, params);
-      this.props.hideLoginErrorsInput(false);
+  componentDidUpdate(prevProps) {
+    const { hideLoginErrorsInput, location: { search }, match: { params :{ authType, id }}, setForm, submitSuccess } = this.props;
```
Comment (maturanomx) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: This is hard to read. Can we use multi-line to make more visible what is happening here?. Plus, avoiding long lines...

```suggestion
    const {
      hideLoginErrorsInput,
      location: { search },
      match: {
        params: { authType, id }
      },
      setForm,
      submitSuccess
    } = this.props; 
```

Or maybe do it in two steps to destruturing nested properties 🤷‍♂️

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 2]
```diff
@@ -40,73 +41,90 @@ import styles from './styles.scss';
...
+    if (authType !== prevProps.match.params.authType) {
+      const params = search ? replace(search, '?code=', '') : id;
+      setForm(authType, params);
+      hideLoginErrorsInput(false);
     }
-
-    if (nextProps.submitSuccess) {
-      switch (this.props.match.params.authType) {
+    if (submitSuccess !== prevProps.submitSuccess && submitSuccess) {
```
Comment (maturanomx) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: Should not be inverted?; checking first if `submitSuccess` is truly? 🤔

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 3]
```diff
@@ -143,67 +162,67 @@ export class AuthPage extends React.Component { // eslint-disable-line react/pre
...
       <Input
         autoFocus={key === 0}
         customBootstrapClass={get(input, 'customBootstrapClass')}
-        didCheckErrors={this.props.didCheckErrors}
-        errors={get(this.props.formErrors, [findIndex(this.props.formErrors, ['name', input.name]), 'errors'])}
+        didCheckErrors={didCheckErrors}
+        errors={get(formErrors, [findIndex(formErrors, ['name', input.name]), 'errors'])}
         key={get(input, 'name')}
-        label={authType === 'forgot-password' && this.props.submitSuccess? { id: 'users-permissions.Auth.form.forgot-password.email.label.success' } : get(input, 'label')}
+        label={this.isAuthType('forgot-password') && submitSuccess? { id: 'users-permissions.Auth.form.forgot-password.email.label.success' } : get(input, 'label')}
```
Comment (maturanomx) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: Isn't better move logic to is own sentence and promote the declarative intention of JSX?. Plus, we avoiding this long lines and making more readable.

File: packages/strapi-plugin-users-permissions/controllers/Auth.js [hunk 4]
```diff
@@ -199,7 +199,6 @@ module.exports = {
     settings.object = await strapi.plugins['users-permissions'].services.userspermissions.template(settings.object, {
       USER: _.omit(user.toJSON ? user.toJSON() : user, ['password', 'resetPasswordToken', 'role', 'provider'])
     });
-
     try {
```
Comment (maturanomx) [inline packages/strapi-plugin-users-permissions/controllers/Auth.js]: Vertical space is important 😕

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js (hunk 1 above)
Comment (aDEVE) [reply packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: For your information, i will add prettier in next few days to prevent this kind of feedback from code review.

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 5]
```diff
@@ -40,73 +41,99 @@ import styles from './styles.scss';
...
+      }, 
+      setForm,
+      submitSuccess ,
+    } = this.props;
 
-    if (nextProps.submitSuccess) {
-      switch (this.props.match.params.authType) {
+    if (authType !== prevProps.match.params.authType) {
+      const params = search ? replace(search, '?code=', '') : id;
+      setForm(authType, params);
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: With the method from above you can do 

```
if (...) {
  this.setForm();
  hideLoginErrorsInput(false);
}
```

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 6]
```diff
@@ -40,73 +41,99 @@ import styles from './styles.scss';
...
-    this.props.setErrors(formErrors);
+    setErrors(formErrors);
 
     if (isEmpty(formErrors)) {
-      this.props.submit(this.context);
+      submit(this.context);
     }
   }
 
+  isAuthType = type => {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: I think a more explicit naming like `getAuthType` would be more understandable than `isAuthType`

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 7]
```diff
@@ -143,67 +171,74 @@ export class AuthPage extends React.Component { // eslint-disable-line react/pre
   }
 
   renderInputs = () => {
-    const { match: { params: { authType } } } = this.props;
+    const { didCheckErrors, formErrors, match: { params: { authType } }, modifiedData, noErrorsDescription, onChangeInput, submitSuccess } = this.props;
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: Like @maturanomx said can you put the destructured object on a multi line?

```
const {
  didCheckErrors,
  formErrors,
  match: {
    {
       params,
       // ...
    }
  }
};
```

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 8]
```diff
@@ -143,67 +171,74 @@ export class AuthPage extends React.Component { // eslint-disable-line react/pre
...
-        type={get(input, 'type')}
-        validations={{ required: true }}
-        value={get(this.props.modifiedData, get(input, 'name'), get(input, 'value'))}
-        noErrorsDescription={this.props.noErrorsDescription}
-      />
-    ));
+    
+    return map(inputs, (input, key) => {
+      const label = 
+        this.isAuthType('forgot-password') && submitSuccess
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: This condition is not really explicit, maybe we can put in a method `isForgotEmailSent` ?

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js (hunk 3 above)
Comment (soupette) [reply packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: I agree

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 9]
```diff
@@ -40,73 +41,90 @@ import styles from './styles.scss';
...
   }
 
-  componentWillReceiveProps(nextProps) {
-    if (this.props.match.params.authType !== nextProps.match.params.authType) {
-      const params = nextProps.location.search ? replace(nextProps.location.search, '?code=', '') : nextProps.match.params.id;
-      this.props.setForm(nextProps.match.params.authType, params);
-      this.props.hideLoginErrorsInput(false);
+  componentDidUpdate(prevProps) {
+    const { hideLoginErrorsInput, location: { search }, match: { params :{ authType, id }}, setForm, submitSuccess } = this.props;
+    if (authType !== prevProps.match.params.authType) {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: You need an extra line before the if it makes the code more readable.

**Comment by soupette** [comment]
I have tested your PR but I receive an error after the forgot password email has been sent. Can you check?

**Comment by aDEVE** [comment]
@soupette, it should be good

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 10]
```diff
@@ -40,73 +41,114 @@ import styles from './styles.scss';
...
+    } = this.props;
+
+    if (authType !== prevProps.match.params.authType) {
+      this.setForm();
+      hideLoginErrorsInput(false);
     }
-
-    if (nextProps.submitSuccess) {
-      switch (this.props.match.params.authType) {
+    if (submitSuccess && submitSuccess !== prevProps.submitSuccess) {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: `if (submitSuccess) { //... }` is enough as a check here.

(Plus there's an extra line missing before the condition 😉)

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 11]
```diff
@@ -40,73 +41,114 @@ import styles from './styles.scss';
...
+      switch (authType) {
         case 'login':
-        case 'reset-password':
-          this.props.history.push('/');
+        case 'reset-password': 
+          auth.getToken()
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: Can you add some comments here so we can remember why we need this check?
