### PR TITLE
fix: update of logo

### LINKED ISSUE #20755: Menu logo not applied
When you try to update the logo in the Overview settings the logo is not applied even if you have a successful message. It appears only after a refresh.

https://github.com/user-attachments/assets/ba9e6cac-7e82-46e6-9d74-0606a7b4713f

### PR DESCRIPTION
**Pull request by Adzouz**
### What does it do?

Fix the update of the logo after sending the request due to wrong value of permission canRead in configuration.

https://github.com/user-attachments/assets/821019e2-27f0-442d-ba26-a3e3d504e5d9

### Why is it needed?

When clicking on save, the old logo is displayed giving the illusion to the user that the logo wasn't updated (even if it was the case).

### How to test it?

- Go to admin interface > Settings
- Scroll to Customization section
- Click on the + icon to change the logo
- Load a new image from your computer
- Click on Save

### Related issue(s)/PR(s)

Resolves #20755

🚀

### CODE REVIEW

**Review by simotae14 — CHANGES_REQUESTED** [review]
I still have the issue

https://github.com/user-attachments/assets/6f2f2e75-d97d-4e69-a655-ef6b8d39693a

Also it is not clear to me why the destructuring of canRead doesn't work...and when you find a solution please add a test to prevent having regression errors in the future, thanks

File: packages/core/admin/admin/src/features/Configuration.tsx [hunk 1]
```diff
@@ -76,9 +76,7 @@ const ConfigurationProvider = ({
   );
   const token = useAuth('ConfigurationProvider', (state) => state.token);
 
-  const {
-    allowedActions: { canRead },
-  } = useRBAC(permissions);
+  const { allowedActions } = useRBAC(permissions);
```
Comment (remidej) [inline packages/core/admin/admin/src/features/Configuration.tsx]: I haven't tested the fix but this looks like the only change is you made is to no longer destructure canRead right? I don't see how that would change the runtime behavior

Comment (Adzouz) [reply packages/core/admin/admin/src/features/Configuration.tsx]: I don't either but when I logged allowedActions, canRead was true but if I logged directly canRead, it was false for some reason 🤷‍♂️ I'll continue investigating

**Comment by Adzouz** [comment]
I put back the logic of permissions since the issue was elsewhere. I stored the result of the updated image and use it in the rendering. Can you please tell me if it's better now @simotae14?

File: packages/core/admin/admin/src/features/Configuration.tsx [hunk 2]
```diff
@@ -159,19 +163,23 @@ const ConfigurationProvider = ({
...
-            : {
-                url: customAuthLogo ?? '',
-              },
+          custom: authLogoUpdated
+            ? authLogoUpdated
+            : isSuccess
+              ? data?.authLogo
+              : {
+                  url: customAuthLogo ?? '',
+                },
```
Comment (remidej) [inline packages/core/admin/admin/src/features/Configuration.tsx]: we try to avoid nested ternaries as they're not super readable

File: packages/core/admin/admin/src/features/Configuration.tsx [hunk 3]
```diff
@@ -67,6 +67,8 @@ const ConfigurationProvider = ({
   defaultMenuLogo,
   showReleaseNotification = false,
 }: ConfigurationProviderProps) => {
+  const [authLogoUpdated, setAuthLogoUpdated] = React.useState<Partial<Logo> | null>(null);
+  const [menuLogoUpdated, setMenuLogoUpdated] = React.useState<Partial<Logo> | null>(null);
```
Comment (remidej) [inline packages/core/admin/admin/src/features/Configuration.tsx]: I understand what you're doing, but I think it's worth taking a step back here and considering a refactor.

I don't really like the way the existing code works by fetching data with RTK and exposing it via context. It adds complexity and it's error prone. The app logo is server state, so we should probably rely on the RTK Query cache to manage it just like we manage the rest of the app's server state.

in my opinion, the preferred workflow would be:
- the left menu (or NavBrand directly) accesses the logo via useInitQuery. It should be available in the cache by the time the menu renders so no loading state required
- invalidate the init query cache tag when the user uploads a new logo

Comment (Adzouz) [reply packages/core/admin/admin/src/features/Configuration.tsx]: Good call, I updated the query and provided tags so that it could be invalidated on image update. It should work as expected. I also updated the image from the NavBrand to use the one from the same query.

File: packages/core/admin/admin/src/components/MainNav/NavBrand.tsx [hunk 4]
```diff
@@ -16,21 +16,21 @@ const BrandIconWrapper = styled<FlexComponent>(Flex)`
 
 export const NavBrand = () => {
   const { formatMessage } = useIntl();
-  const {
-    logos: { menu },
-  } = useConfiguration('LeftMenu');
+  const { data: { menuLogo } = {} } = useInitQuery();
```
Comment (remidej) [inline packages/core/admin/admin/src/components/MainNav/NavBrand.tsx]: Thanks for the change!

I think you should now be able to remove the menuLogo code from the Configuration file. Ideally we'd remove the logos key from the configuration context altogether, but this requires changes on the login page so it doesn't need to be in this PR

Comment (Adzouz) [reply packages/core/admin/admin/src/components/MainNav/NavBrand.tsx]: Ok so after we discussed, I revert to what we had before because even if it's not ideal, configuration is already using RTK query. The only thing is that the init query wasn't invalidated because it was missing the providesTags. Let me know if anything!

**Review by remidej — APPROVED** [review]
love a simple fix!

**Review by simotae14 — APPROVED** [review]
