### PR TITLE
fix(i18n): locale swapping with content-types & D&P disabled

### LINKED ISSUE #19267: Switching locales when viewing a collection-type entity won't load the entity data for the locale even if it exists
### Required System information

- Node.js version: 18.19.0
- NPM version: 10.2.3
- Strapi version: 4.17.1
- Database: mysql
- Operating system: macOS Sonoma 14.2.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

If you are viewing a collection entity and switch locale in the menu to the the right, Strapi will assume you are creating a new entity with that locale even if one exists.

### Steps to reproduce the behavior

1. Create a new collection content-type with i18n enabled and add a single text field
2. Add an additional locale to your project
3. Create a new entity of the new content-type in your default locale and save it
4. When viewing the new entity, select the other locale in the menu to the right, add some data and save it
5. Switch back to the other locale in the menu to the right, and Strapi enters create-mode rather than edit mode, it won't load the existing entity

### Expected behavior

When switching to another locale from an entity and that entity exists, it should load the existing entity.

### Screenshots

strapi-locale-bug-1
strapi-locale-bug-2
strapi-locale-bug-3

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* checks if there's an ID as well before we try to create a new locale entry

### Why is it needed?

* locales without D&P would be given the status of "we don't have a draft or published" which is true, but we still had the ID signifying that it existed.

### How to test it?

* Have a content-type without D&P enabled & i18n enabled
* save default locale of content-type
* swap to alternate locale (should be empty form)
* swap back to original (should be filled)

### Related issue(s)/PR(s)

* resolves CONTENT-2177
* resolves #19267

### CODE REVIEW

File: packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx [hunk 1]
```diff
@@ -82,7 +82,12 @@ const CMEditViewLocalePicker = ({
       return;
     }
 
-    if (status === 'did-not-create-locale') {
+    /**
+     * TODO: if D&P is not enabled, then the status will always say there's no locale so
+     * we also should check there's no ID incase. This logic will be removed in V5 when
+     * we _always_ have D&P.
```
Comment (Marc-Roig) [inline packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx:88]: this behaviour probably will have to be in V5 as we will have disabled D&P on content types too!

Comment (Marc-Roig) [reply packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx:88]: Probably because I lack context here, but I do not quite understand the if case, and how D&P is interacting with locale creation. 

From what  I understood the status is `did-not-create-locale` when that locale doesnt exist, but also when D&P is not enabled?

should the status be set to that value when there is an actual locale?

Also, would it be enough just to check if the id of the locale exists or not?

Comment (joshuaellis) [reply packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx:88]: Yeah I can probably make a better solution for this now we know D&P isn't always enabled. Because it doesn't make a great deal of sense & there will be new hooks as well to work with...

Have you QA'd the fix? 👀

Comment (Marc-Roig) [reply packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx:88]: nope! going to tesst it in 5 min

Comment (Marc-Roig) [reply packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx:88]: functionality seems to be working ! can swap the locale with a content type with disabled D&P

Comment (joshuaellis) [reply packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx:88]: Ey, oh, let's merge!

**Review by Marc-Roig — APPROVED** [review]
