### PR TITLE
Fix blocked users being able to sign in using forgot password

### LINKED ISSUE #10776: Blocked user can still login by using the forgot password feature
### Describe the bug

Blocked user can still login by using the forgot password feature 
### Steps to reproduce the behavior

1. Open the forgot password page
2. Submit with an email of a blocked account
3. Click on the reset password link from the reset password email
4. Enter a valid password and confirm password
5. Submit and check

### Expected behavior

Blocked user shouldn't be able to send forgot password request

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.3
- NPM version: 6.14.11
- Strapi version: v3.6.6
- Database: postgre
- Operating system: Ubuntu

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Adds a check in the forgot password controller to see if a user is blocked and return the valid error message if they are

### Why is it needed?

Blocked users should not be able to perform any request at all

### How to test it?

Create a user, set them as blocked, and attempt to send a password reset request

### Related issue(s)/PR(s)

fixes #10776

### CODE REVIEW

File: packages/strapi-plugin-users-permissions/controllers/Auth.js [hunk 1]
```diff
@@ -310,6 +310,11 @@ module.exports = {
       );
     }
 
+    // User blocked
+    if (user.blocked) {
+      return ctx.badRequest('blocked.user');
```
Comment (petersg83) [inline packages/strapi-plugin-users-permissions/controllers/Auth.js:315]: Can you use the same format as line 304? Thus the message can be directly displayed in the front!

(and if you can fix the missing "a" line 286 too :p)

**Review by petersg83 — CHANGES_REQUESTED** [review]

**Review by petersg83 — APPROVED** [review]
LGTM :)
