### PR TITLE
Fix GraphQL pagination results

### LINKED ISSUE #16170: GraphQL pagination results not respecting filters on createdAt
### Required System information

- Node.js version: 18.15
- NPM version: 8.19
- Strapi version: 4.8.0
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

As of 4.8.0, Strapi GraphQL ignores all filters on `createdAt` and returns the count of all records in the pagination results. The actual records are filtered as expected, but the numbers in `pagination` return the counts of all records.

I've confirmed this bug does not exist in 4.7.1

### Steps to reproduce the behavior

```
query BrokenResults {
  records(
    filters: {createdAt: {between: ["2022-03-21T16:22:02.429Z", "2023-03-21T16:22:02.429Z"]}}
  ) {
    meta {
      pagination {
        total
      }
    }
  }
}
```

### Expected behavior

meta.pagination.total should return the filtered count, not the total record count.

### Screenshots

4.7.1 (Working)
Screenshot 2023-03-21 at 11 05 46 AM

4.8.0 (Broken)
Screenshot 2023-03-21 at 11 07 20 AM

### Code snippets

See above

### PR DESCRIPTION
**Pull request by innerdvations**
### What does it do?

Fixes the GraphQL pagination query sanitization, which was previously sanitizing against a content type of `undefined` instead of the actual content type.

### Why is it needed?

GraphQL pagination counts are wrong

### How to test it?

GraphQL pagination should report the correct count for a query

An API pagination test has been provided that fails on the previous code and passes with the changes in this PR.

### Related issue(s)/PR(s)

Based on branch (and pending acceptance of) https://github.com/strapi/strapi/pull/17139

Fixes #16170

### CODE REVIEW

File: packages/plugins/graphql/server/services/internals/types/response-collection-meta.js [hunk 1]
```diff
@@ -25,8 +25,9 @@ module.exports = ({ strapi }) => {
             const { args, resourceUID } = parent;
             const { start, limit } = args;
             const safeLimit = Math.max(limit, 1);
+            const contentType = strapi.contentTypes[resourceUID];
```
Comment (Convly) [inline packages/plugins/graphql/server/services/internals/types/response-collection-meta.js]: We should use .getModel instead of .contentTypes, I'll make the change as @innerdvations is off

Comment (Convly) [reply packages/plugins/graphql/server/services/internals/types/response-collection-meta.js]: Done :heavy_check_mark:

**Review by Convly — APPROVED** [review]
LGTM, waiting for the tests to pass & merging
