### PR TITLE
Fix numerical 0 display in data list

### LINKED ISSUE #1077: Numerical Field does not properly show value Zero
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: v5.6.0
- **Strapi version**: 12.0.1
- **Database**: MongoDB v3.6.4
- **Operating system**: Ubuntu Server 16.04 LTS

**What is the current behavior?**
When using numerical field (Int, Dec, or Float) if a value of `0` is entered the content manager will show a `-` instead of the value. Also while editing a record if you place any value in the text field then delete it, the value will default to `0`

**Steps to reproduce the problem**
Add a numerical field to any endpoint, place a `0` in the field, then return to the content manager.
Note that if the column is displayed in the content manager it will show `-` instead of `0`. Does not affect the API as it will return the proper value.

Second issue, attempt to modify the record and delete the value of the numerical field, which after clicking away it will auto-default back to `0` again. While not breaking, in some cases you may not want a default value of `0` and instead want a default value of `null`

**What is the expected behavior?**
Content Management should display the exact value and not assume that `0` is equal to `null`
Numerical fields should not assume that a default numerical value is `0` and should default to `null`

**Suggested solutions**
Unsure as I'm not sure how the content management plugin determines default values. Recommend adding the option to set a default value on a numerical field to null.

- [x] I'm sure that this issue hasn't already been referenced

- Possible related issues/fixes:
https://github.com/strapi/strapi/issues/670
https://github.com/strapi/strapi/commit/f5571af1c17fc27fb3bda3a208826920a9a7d02c

Issue is likely a "Quality of Life" fix and not a breaking bug

### PR DESCRIPTION
**Pull request by lauriejim**
My PR is a: 🐛 Bug fix #1077
Main update on the:  Plugin

Change numerical display in data list when value is `0`
Display `0` instead of `-`.

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Thanks Jim, that bug has been around so long I forgot about it :smile:

File: packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ class TableRow extends React.Component {
       case 'integer':
       case 'biginteger':
       case 'decimal':
-        return value && !isEmpty(value.toString()) ? value.toString() : '-';
+        return !isNull(value) ? value.toString() : '-';
```
Comment (derrickmehaffy) [inline packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js]: Not sure, but I think this should also be done with Integer and Float values. Just taking a look at an example of project of an integer value that is set to zero:

image


image

Comment (derrickmehaffy) [reply packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js]: DB also shows the value of 0 instead of null:

image

Comment (derrickmehaffy) [reply packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js]: Nope this was on a 14.2 project, didn't test directly just assumed based on where that code is :p

Comment (derrickmehaffy) [reply packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js]: Ah I see how this works now @lauriejim should be good I was thinking bookshelf files... Need more coffee
