### PR TITLE
Avoid content type `pluralName` DB clashes

### LINKED ISSUE #13893: Creating collections with existing table names can cause the entire system to crash.
### Required System information

- Node.js version: 14.19.3
- NPM version: 7.16.0
- Strapi version: 4.3.0
- Database: Sqlite
- Operating system: Windows 10 64-bit

### Describe the bug

When creating a collection using the admin Content-Type builder, one can erroneously create a collection having the same name as an existing table. This will effectively nuke the existing table and cause unexpected errors and the inability to restart the server.

### Steps to reproduce the behavior

1. Create a collection using the Content-Type Builder called "Admin Role". The system will try to generate a plural table name called `admin_roles`.
2. Restart the server.
3. Errors emitted as the expected internal table structure has been modified.

### Expected behavior

The system should either continue on merrily, distinguishing the user-created table from the built-in ones, or should throw a soft error to the user preventing overwriting of the table.

### Additional context

A possible solution could be to have user tables prefixed instead? Distantly related to #5080

### PR DESCRIPTION
**Pull request by jhoward1994**
### What does it do?

Detects `collectionName` clashes with Strapi admin DB tables when creating content types.

### Why is it needed?

Previously, creating a content type with a clashing name would cause Strapi to crash (see issue)

### How to test it?

Attempt to create a content type with the `pluralName`=`admin-roles`

When Strapi restarts you should see an error like this in the terminal
image

### Related issue(s)/PR(s)

Fixes #13893

### CODE REVIEW

File: packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js [hunk 1]
```diff
@@ -121,12 +121,13 @@ const forms = {
...
-      const contentTypeShape = createContentTypeSchema(
-        takenNames,
-        reservedNames.models,
-        takenSingularNames,
-        takenPluralNames
-      );
+      const contentTypeShape = createContentTypeSchema({
+        usedContentTypeNames: takenNames,
+        reservedModels: reservedNames.models,
+        reservedCollectionNames: reservedNames.collectionNames,
```
Comment (Marc-Roig) [inline packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js:127]: Just curious, from where do you get this reservedNames list?

Comment (jhoward1994) [reply packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js:127]: They come from `packages/core/content-type-builder/server/services/builder.js`

Comment (Marc-Roig) [reply packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js:127]: Aham! I am trying to find the request to get that data (trying to learn a little bit of the frontend side)
could you point me where it is made?

**Comment by Marc-Roig** [comment]
Congrats for your first PR @jhoward1994  🥳 
well done with this ! I am testing your branch and I had some questions about it.

- When trying to create a collection with a reserved name I get a Validation error. That looks good 👍 
- I am trying to understand how the validation looks in the frontend. Because:
   - Is the desired behavior this [one](https://scribehow.com/shared/Avoid_content_type_pluralName_DB_clashes__3RZVfXHQSXCSiSImSN9Rpw)?
   - Trying to see the changes you made in frontend side, I understand you should see a validation error in the form when you try to use a reserved collection name.

**Comment by jhoward1994** [comment]
> 
Thanks @Marc-Roig!
Yes you should see a form validation error in the frontend like:
image
Do you not get that?

**Comment by Marc-Roig** [comment]
> > 
> 
> Thanks @Marc-Roig! Yes you should see a form validation error in the frontend like: image Do you not get that?

Yes I do get that now! My bad, forgot to rebuild the project :) 
Everything seems to be working for me then !

File: packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js (hunk 1 above)
Comment (jhoward1994) [reply packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js:127]: It seems to be managed by the `DataManagerProvider` [here](https://github.com/strapi/strapi/blob/cf49ddbbfc33fa6a0145f9ddf50677e31c1d711e/packages/core/content-type-builder/admin/src/components/DataManagerProvider/index.js#L97)

**Review by Marc-Roig — DISMISSED** [review]

**Review by petersg83 — CHANGES_REQUESTED** [review]
Hello :)
Nice work !
I have a few comments:
- The database table names are customizable by the user (https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-settings). If I understand correctly, you deduce the table name from the content-type name? If yes, then it may not work correctly as it's not always based on the content-type name. Maybe the way to go, if we want to do the check directly in the front, is to create a backend route that sends the tables names and check against them.
- The users can create content-types directly by creating the schema files, not using the CTB then. This fix won't prevent them from doing so. I think then that it would be helpful to throw an error at launch. Here are some parts of the code that can help you understand where: Database metadata are created here : https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/Strapi.js#L394 (metadata contains full table informations, including the tables names) and here : https://github.com/strapi/strapi/blob/main/packages/core/database/lib/metadata/index.js#L20. Once the metadata are created, the database can be modified (create new tables, delete some etc.), this modification is done using the sync function called here : https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/Strapi.js#L431.

I would suggest that the most important thing to do is the check in the database layer.
The error directly in the CTB (using the new route) seems a nice to have but if it takes to much time, it can be done in another iteration.

What do you think?

File: packages/core/database/lib/metadata/index.js [hunk 2]
```diff
@@ -21,7 +21,13 @@ const createMetadata = (models = []) => {
   const metadata = new Metadata();
 
   // init pass
+  const seenTables = new Map();
   for (const model of _.cloneDeep(models)) {
+    if (seenTables.get(model.tableName)) {
```
Comment (jhoward1994) [inline packages/core/database/lib/metadata/index.js:26]: @petersg83 - this check in the database layer that errors out when it detects clashing DB names.

Would you suggest I either revert the CTB changes or create the new route for checking DB table names?

Comment (petersg83) [reply packages/core/database/lib/metadata/index.js:26]: Cool :) It will fix the error if 2 content-types have the same table names. However there are other tables (relational tables) that are automatically created and that can clash also. I believe that the best place to do the check is after the metadata has been created. I believe in the constructor in `database/lib/index.js`.

Regarding the CTB, let's discuss about it during our meeting later?

**Review by petersg83 — APPROVED** [review]
LGTM for the backend part. I let you update the error message before merging

**Review by petersg83 — APPROVED** [review]

**Review by Marc-Roig — APPROVED** [review]

**Comment by jhoward1994** [comment]
Thanks both, I'm waiting on QA then will merge this
