### PR TITLE
fix(upload-aws-s3): support root-level credentials and update AWS SDK

### LINKED ISSUE #25526: @strapi/provider-upload-aws-s3 depends on critical vulnerable package of @aws-sdk -> @fast-xml-parser
### Node Version

22

### NPM/Yarn/PNPM Version

NPM 10.9.2

### Strapi Version

5.36.1

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Bug Description

Recently updated everything to 5.36.1 to fix other critical package vulnerabilities, now to see it has a new one. 

There are also some other high-vulnerabilities mostly around the @strapi/plugin-users-permissions. 

### Steps to Reproduce

1. Install strapi `npx create-strapi@latest my-strapi-project`
2. Install the latest `@strapi/provider-upload-aws-s3`
3. Run audit

If you also install ` @strapi/plugin-users-permissions` you will see more high-vulnerabilities

### Expected Behavior

No critical dependencies - preferably even no high vulnerabilities.

### Logs

```shell
fast-xml-parser  4.1.3 - 5.3.5
Severity: critical
fast-xml-parser has RangeError DoS Numeric Entities Bug - https://github.com/advisories/GHSA-37qj-frw5-hhjh
fast-xml-parser affected by DoS through entity expansion in DOCTYPE (no expansion limit) - https://github.com/advisories/GHSA-jmr7-xgp7-cmfj
fast-xml-parser has an entity encoding bypass via regex injection in DOCTYPE entity names - https://github.com/advisories/GHSA-m7jm-9gc2-mpf2
fix available via `npm audit fix --force`
Will install @strapi/provider-upload-aws-s3@5.35.0, which is a breaking change
node_modules/@aws-sdk/signature-v4-multi-region/node_modules/fast-xml-parser
node_modules/fast-xml-parser
  @aws-sdk/xml-builder  3.894.0 - 3.972.4
  Depends on vulnerable versions of fast-xml-parser
  Depends on vulnerable versions of fast-xml-parser
  node_modules/@aws-sdk/signature-v4-multi-region/node_modules/@aws-sdk/xml-builder
  node_modules/@aws-sdk/xml-builder
    @aws-sdk/core  3.894.0 - 3.972.0
    Depends on vulnerable versions of @aws-sdk/xml-builder
    node_modules/@aws-sdk/signature-v4-multi-region/node_modules/@aws-sdk/core
      @aws-sdk/middleware-sdk-s3  3.894.0 - 3.972.0
      Depends on vulnerable versions of @aws-sdk/core
      node_modules/@aws-sdk/signature-v4-multi-region/node_modules/@aws-sdk/middleware-sdk-s3
        @aws-sdk/signature-v4-multi-region  3.894.0 - 3.972.0
        Depends on vulnerable versions of @aws-sdk/middleware-sdk-s3
        node_modules/@aws-sdk/signature-v4-multi-region
          @aws-sdk/client-s3  3.894.0 - 3.978.0
          Depends on vulnerable versions of @aws-sdk/signature-v4-multi-region
          node_modules/@aws-sdk/client-s3
            @aws-sdk/lib-storage  3.967.0 - 3.978.0
            Depends on vulnerable versions of @aws-sdk/client-s3
            node_modules/@aws-sdk/lib-storage
            @strapi/provider-upload-aws-s3  <=0.0.0-next.f3cd3c71c61b40fc223cc5763ac300261d3dff16 || >=5.36.0
            Depends on vulnerable versions of @aws-sdk/client-s3
            Depends on vulnerable versions of @aws-sdk/lib-storage
            Depends on vulnerable versions of @aws-sdk/s3-request-presigner
            node_modules/@strapi/provider-upload-aws-s3
          @aws-sdk/s3-request-presigner  3.894.0 - 3.978.0
          Depends on vulnerable versions of @aws-sdk/signature-v4-multi-region
          node_modules/@aws-sdk/s3-request-presigner

--- other

lodash  4.0.0 - 4.17.21
Severity: moderate
Lodash has Prototype Pollution Vulnerability in `_.unset` and `_.omit` functions - https://github.com/advisories/GHSA-xxjr-mmjv-4gpg
fix available via `npm audit fix --force`
Will install @strapi/plugin-users-permissions@5.9.0, which is a breaking change
node_modules/lodash
  @strapi/content-manager  <=0.0.0-next.ffc36acb308febe288f1a31b62cbbb75b286585c || >=5.0.0-beta.6
  Depends on vulnerable versions of @strapi/admin
  Depends on vulnerable versions of @strapi/design-system
  Depends on vulnerable versions of @strapi/types
  Depends on vulnerable versions of @strapi/utils
  Depends on vulnerable versions of lodash
  Depends on vulnerable versions of markdown-it
  Depends on vulnerable versions of react-query
  node_modules/@strapi/content-manager
    @strapi/i18n  <=0.0.0-next.ffc36acb308febe288f1a31b62cbbb75b286585c || >=5.0.0-beta.6
    Depends on vulnerable versions of @strapi/admin
    Depends on vulnerable versions of @strapi/content-manager
    Depends on vulnerable versions of @strapi/design-system
    Depends on vulnerable versions of @strapi/utils
    node_modules/@strapi/i18n
  @strapi/design-system  >=1.20.0-typescript.0
  Depends on vulnerable versions of lodash
  node_modules/@strapi/design-system
    @strapi/content-type-builder  <=0.0.0-next.ffc36acb308febe288f1a31b62cbbb75b286585c || >=5.0.0-beta.6
    Depends on vulnerable versions of @strapi/admin
    Depends on vulnerable versions of @strapi/design-system
    Depends on vulnerable versions of @strapi/generators
    Depends on vulnerable versions of @strapi/utils
    node_modules/@strapi/content-type-builder
    @strapi/email  <=0.0.0-next.ffc36acb308febe288f1a31b62cbbb75b286585c || >=5.0.0-beta.6
    Depends on vulnerable versions of @strapi/admin
    Depends on vulnerable versions of @strapi/design-system
    Depends on vulnerable versions of @strapi/provider-email-sendmail
    Depends on vulnerable versions of @strapi/utils
    Depends on vulnerable versions of lodash
    Depends on vulnerable versions of react-query
    node_modules/@strapi/email
  @strapi/permissions  *
  Depends on vulnerable versions of @strapi/utils
  Depends on vulnerable versions of lodash
  node_modules/@strapi/permissions
  @strapi/utils  *
  Depends on vulnerable versions of lodash
  node_modules/@strapi/utils
    @strapi/generators  *
    Depends on vulnerable versions of @strapi/utils
    Depends on vulnerable versions of copyfiles
    node_modules/@strapi/generators
    @strapi/provider-email-sendmail  *
    Depends on vulnerable versions of @strapi/utils
    node_modules/@strapi/provider-email-sendmail
    @strapi/provider-upload-haas  
    Depends on vulnerable versions of @strapi/utils
    node_modules/@strapi/provider-upload-haas
    @strapi/provider-upload-local  *
    Depends on vulnerable versions of @strapi/utils
    node_modules/@strapi/provider-upload-local
lodash-es  4.0.0 - 4.17.22
Severity: moderate
Lodash has Prototype Pollution Vulnerability in `_.unset` and `_.omit` functions - https://github.com/advisories/GHSA-xxjr-mmjv-4gpg
fix available via `npm audit fix`
node_modules/lodash-es
markdown-it  13.0.0 - 14.1.0
Severity: moderate
markdown-it is has a Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-38c4-r59v-3vqw
fix available via `npm audit fix --force`
Will install @strapi/plugin-users-permissions@5.9.0, which is a breaking change
@strapi/plugin-users-permissions
```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

See https://github.com/advisories/GHSA-37qj-frw5-hhjh and https://github.com/aws/aws-sdk-js-v3/issues/7743 

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### LINKED ISSUE #25721: S3 upload Access Denied
### Node Version

20.19.4

### NPM/Yarn/PNPM Version

10.8.2

### Strapi Version

5.39.0

### Operating System

Linux (Debian/Ubuntu)

### Database

MySQL

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Bug Description

Hello everyone, when I try to upload a new media content in Strapi, I get the "Internal server error" result, console tells that the error message is "Access Denied".

I tried to debug the error, in the npm package "provider-upload-aws-s3", I tried to print the S3Client config object:

Image

The resulting object (with secret removed) is this:

```
{
  accessKeyId: 'REMOVED',
  secretAccessKey: 'REMOVED',
  region: 'REMOVED',
  params: { ACL: 'public-read', Bucket: 'REMOVED' }
}
```

I tried to wrap accessKeyId and secretAccessKey in a "credentials" object, following the typescript suggestions, like this:

```
{
  credentials: {
    accessKeyId: 'REMOVED',
    secretAccessKey: 'REMOVED',
  }
  region: 'REMOVED',
  params: { ACL: 'public-read', Bucket: 'REMOVED' }
}
```

With this change, the upload working again.
When I restore the original object, I get the “Access denied” error again.

The S3 bucket is configured according to this guide
https://strapi.io/blog/how-to-set-up-amazon-s3-upload-provider-plugin-for-our-strapi-app

### Steps to Reproduce

Upload a media content with S3 Strapi plugin

### Expected Behavior

The media succesfully uploaded without error.

### Logs

```shell
AccessDenied: Access Denied
    at AwsRestXmlProtocol.handleError (C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@aws-sdk\core\dist-cjs\submodules\protocols\index.js:1809:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AwsRestXmlProtocol.deserializeResponse (C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@smithy\core\dist-cjs\submodules\protocols\index.js:334:13)
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@smithy\core\dist-cjs\submodules\schema\index.js:26:24
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\index.js:385:20
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@smithy\middleware-retry\dist-cjs\index.js:254:46
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\index.js:243:24
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\index.js:62:28
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\index.js:89:20
    at async C:\Users\dev03\Documents\Progetti\Webapp\FivesGroup\Strapi\node_modules\@aws-sdk\middleware-logger\dist-cjs\index.js:5:26 {
  '$fault': 'client',
  '$retryable': undefined,
  '$metadata': {
    httpStatusCode: 403,
    requestId: '3CJ0Z9DGDHBGCB5Q',
    extendedRequestId: 'mC3TlYF3Rg09QUx4E1yS50LXgsR7qedD6tPO85YB5YMAoR/tPrzZzQB0ynxeSRMmppd1tpoVou8=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'AccessDenied',
  RequestId: '3CJ0Z9DGDHBGCB5Q',
  HostId: 'mC3TlYF3Rg09QUx4E1yS50LXgsR7qedD6tPO85YB5YMAoR/tPrzZzQB0ynxeSRMmppd1tpoVou8='
}
```

### Code Snippets

```
upload: {
    config: {
      provider: 'aws-s3',
      sizeLimit: 10737418240,
      providerOptions: {
        s3Options: {
          accessKeyId: env('AWS_ACCESS_KEY_ID'),
          secretAccessKey: env('AWS_ACCESS_SECRET'),
          region: env('AWS_REGION'),
          params: {
            ACL: 'public-read',
            Bucket: env('AWS_BUCKET_NAME')
          }
        }
      },
    },
  }
```

### Media

_No response_

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by Schero94**
### What does it do?

**Bug Fix – AccessDenied with root-level credentials (#25721):**
- `extractCredentials()` in `utils.ts` now detects `accessKeyId` and `secretAccessKey` passed directly in `s3Options` (outside of a `credentials` object) and auto-wraps them into the `credentials` structure that AWS SDK v3 requires.
- Emits a deprecation warning guiding users to migrate to the correct `credentials: { accessKeyId, secretAccessKey }` format.
- Adds 4 new unit tests covering: root-level extraction, precedence of `credentials` object, deprecation warning emission, and partial credentials handling.

**Security – @aws-sdk dependency update (#25526):**
- Updates `@aws-sdk/client-s3`, `@aws-sdk/lib-storage`, and `@aws-sdk/s3-request-presigner` from `3.995.0` → `3.1023.0`
- Updates `@aws-sdk/types` from `3.973.1` → `3.973.6`
- Resolves the critical `@fast-xml-parser` vulnerability in the AWS SDK transitive dependency chain.

### Why is it needed?

1. **AccessDenied regression (#25721):** After the AWS SDK was updated from v3.600 to v3.975+ in #25263 (v5.36.0), users who pass credentials at the root level of `s3Options` (a pattern commonly shown in older Strapi guides and blog posts) started getting `AccessDenied` errors. AWS SDK v3 silently ignores top-level `accessKeyId`/`secretAccessKey` and requires them inside a `credentials` object. This fix maintains backward compatibility while encouraging migration via a deprecation warning.

2. **Security vulnerability (#25526):** The `@aws-sdk/client-s3@3.995.0` dependency pulls in a version of `@fast-xml-parser` with a known critical vulnerability. Updating to `3.1023.0` resolves this.

### How to test it?

**Unit tests:**
```bash
npx jest packages/providers/upload-aws-s3 --no-coverage
# Expected: 80 tests pass (4 new tests for credential extraction)
```

**Manual test for #25721:**
1. Configure the S3 provider with root-level credentials:
```javascript
upload: {
  config: {
    provider: 'aws-s3',
    providerOptions: {
      s3Options: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        params: {
          ACL: 'public-read',
          Bucket: env('AWS_BUCKET_NAME'),
        },
      },
    },
  },
}
```
2. Upload a file via the Media Library → should succeed (previously: AccessDenied)
3. Check server logs for deprecation warning suggesting migration to `credentials: {}` format

### Related issue(s)/PR(s)

- Fixes #25721 (S3 upload Access Denied)
- Fixes #25526 (@aws-sdk security vulnerability)

### CODE REVIEW

File: packages/providers/upload-aws-s3/src/utils.ts [hunk 1]
```diff
@@ -101,5 +98,20 @@ export const extractCredentials = (options: InitOptions): AwsCredentialIdentity
         : {}),
     };
   }
+
+  // Support root-level accessKeyId/secretAccessKey in s3Options for backwards
+  // compatibility. AWS SDK v3 requires these inside a `credentials` object;
+  // passing them at the top level silently fails (Access Denied).
+  if (s3Options?.accessKeyId && s3Options?.secretAccessKey) {
+    process.emitWarning(
```
Comment (markkaylor) [inline packages/providers/upload-aws-s3/src/utils.ts]: What about using strapi.log.warn instead for this?

**Review by markkaylor — COMMENTED** [review]
Thanks for the PR ! Looks good to me, tested and working as expected. Just one quick question before merging.

**Comment by markkaylor** [comment]
Could you also run yarn prettier:write, check on the build, and shouldn't we have a yarn.lock update since the dep was updated?

File: packages/providers/upload-aws-s3/src/utils.ts (hunk 1 above)
Comment (Schero94) [reply packages/providers/upload-aws-s3/src/utils.ts]: Good suggestion! I looked into this, but provider plugins don't have access to the strapi instance —> init() only receives providerOptions, not the Strapi core object. Even Strapi's own upload registration code uses process.emitWarning for provider-level warnings (see packages/core/upload/server/src/register.ts line 88).

I've switched to console.warn as a middle ground — it shows up in Strapi's logger output and is more visible to developers than process.emitWarning. If you'd prefer a different approach, happy to adjust.

**Comment by Schero94** [comment]
Done! I've pushed a follow-up commit (959e903) addressing all of this.

prettier:write ran on all changed files, everything was already formatted. Lint passes and all 84 tests are green. The yarn.lock was updated via the merge with develop.

I also added the hardening fixes from the latest force-push: try/catch for malformed URLs in isUrlFromBucket, null-check for result.Location after Upload.done(). Test expectations were updated to match the new constructFileUrl fallback from the merged develop changes.

File: packages/providers/upload-aws-s3/src/utils.ts (hunk 1 above)
Comment (markkaylor) [reply packages/providers/upload-aws-s3/src/utils.ts]: No problem thanks for looking into it. Makes sense let's stick with console.warn then.

File: packages/providers/upload-aws-s3/package.json [hunk 2]
```diff
@@ -48,11 +48,11 @@
...
-    "@aws-sdk/client-s3": "3.995.0",
-    "@aws-sdk/lib-storage": "3.995.0",
-    "@aws-sdk/s3-request-presigner": "3.995.0",
-    "@aws-sdk/types": "3.973.1",
-    "lodash": "4.18.1"
+    "@aws-sdk/client-s3": "3.1023.0",
+    "@aws-sdk/lib-storage": "3.1023.0",
+    "@aws-sdk/s3-request-presigner": "3.1023.0",
+    "@aws-sdk/types": "3.973.6",
+    "lodash": "4.17.23"
```
Comment (markkaylor) [inline packages/providers/upload-aws-s3/package.json]: Is there a specific reason for the lodash downgrade here?

**Review by markkaylor — DISMISSED** [review]
Pushed to update yarn.lock which I think was causing build and test to exit in the CI. Just have 1 small question but otherwise I think we should be good to merge if the CI will cooperate 😆

File: packages/providers/upload-aws-s3/package.json (hunk 2 above)
Comment (Schero94) [reply packages/providers/upload-aws-s3/package.json]: No reason for the downgrade, it was just left over from the previous version before my first PR (#25263). Bumped it to 4.18.1 to align with the rest of the monorepo in 6c839f6.

**Review by markkaylor — APPROVED** [review]
@Schero94 Thanks again for another contribution!
