### PR TITLE
[CustomInputs]: add global cache to useLazyComponents

### LINKED ISSUE #15053: 4.5.3 does not support custom fields inside components
### Required System information

- Node.js version: latest LTS
- Strapi version: 4.5.3

### Describe the bug

4.5.3 shows "not supported" for custom fields that are part of a component type.
Custom fields in collection / singleton types still works.
This was no issue on 4.5.2

### Steps to reproduce the behavior

Create a custom field with a plugin
Add this custom field to a component type
Use the component type in a collection / singleton

### Expected behavior

Custom fields should work in component types as they did in 4.5.2

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Adds global cache for custom components
* Adds cleanup function to clear cache if required

### Why is it needed?

* Because we don't want to pass the components all the way from the root of the page down 10 levels of components
* Allows components that require the data to access it without the need for suspense

### How to test it?

* Automated test has been added

### Related issue(s)/PR(s)

* resolves #15053

### CODE REVIEW

File: packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js [hunk 1]
```diff
@@ -1,44 +1,75 @@
...
       const modules = await Promise.all(components);
 
+      const internalStore = {};
+
       uids.forEach((uid, index) => {
-        if (!Object.keys(lazyComponentStore).includes(uid)) {
-          setLazyComponentStore({ ...lazyComponentStore, [uid]: modules[index].default });
-        }
+        componentStore.set(uid, modules[index].default);
+        internalStore[uid] = modules[index].default;
```
Comment (markkaylor) [inline packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js:36]: Instead of managing a separate `internalStore` could you just call `setStore(Object.fromEntries(componentStore));` after the `forEach`? Would that not be the same result?

File: packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js [hunk 2]
```diff
@@ -1,44 +1,75 @@
...
 
         return customField.components.Input();
       });
 
-      lazyLoadComponents(componentUids, componentPromises);
+      if (componentPromises.length > 0) {
+        lazyLoadComponents(newUids, componentPromises);
+      } else {
+        const store = Object.fromEntries(componentStore);
+        setStore(store);
```
Comment (markkaylor) [inline packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js:58]: Is this else block necessary since you init the `lazyComponentStore` with this value?

**Review by markkaylor — COMMENTED** [review]
Thanks again @joshuaellis, this is a really clever and clean solution.

I just left a couple questions but it looks good to me

File: packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js (hunk 2 above)
Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js:58]: I think it might be omitable. i'll do so and review going forward.

File: packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js [hunk 3]
```diff
@@ -1,44 +1,69 @@
...
  */
-const useLazyComponents = (componentUids) => {
-  const [lazyComponentStore, setLazyComponentStore] = useState({});
-  const [loading, setLoading] = useState(true);
+const useLazyComponents = (componentUids = []) => {
+  const [lazyComponentStore, setLazyComponentStore] = useState(Object.fromEntries(componentStore));
+  const [loading, setLoading] = useState(() => {
+    if (componentStore.size === 0 && componentUids.length > 0) {
+      return true;
+    }
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js:17]: @joshuaellis Just wondering: would this create problems for users who don't have a component defined yet at all? Would this result in an infinite `loading` state?

Comment (joshuaellis) [reply packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js:17]: I don't think so, the check here is "is there an empty cache and do we have a list of components to fetch", so someone typically has to be passing inputs to be fetched for loading to be default true.

There is a test around this, I think we're okay?
