### PR TITLE
Make locale/localizations private for non-localized cts

### LINKED ISSUE #21401: [Strapi V5] Localisations required when not enabled on collection type with GraphQL
## Bug Report

We use GraphQL in our Next.js application along with codegen to generate types based on the GraphQL schema and queries. In Strapi v5, we have a collection type where localization is disabled, but in the GraphQL schema, the `localizations` field is still marked as required.

When I include the `localizations` field in my query, it triggers the same error on the subsequent `localizations` field (possibly due to a circular dependency).

### System Information

- **Node.js version**: 18.20.4
- **NPM version**: 10.7.0
- **Strapi version**: 5.0.0
- **Database**: MySQL
- **Operating System**: macOS (darwin-arm64)
- **Project Language**: TypeScript

### Steps to Reproduce

1. Enable the GraphQL plugin in Strapi v5.
2. Create a collection type with localization disabled.

While the following steps might not be necessary to trigger the issue, they reflect our specific setup:

3. Create a component that uses the collection type as a relation.
4. Add this component to a Dynamic Zone.
5. Create a GraphQL query that queries the component in the dynamic zone
6. Run codegen in Next.js to generate `types.ts`.
7. Use the generated type in your application and build the Next.js project.
8. You will encounter an error stating that `localizations` is required, despite being disabled.

### Expected Behavior

When localization is disabled, the `localizations` field should not be required in the query.

### Screenshots

In the screenshot below, the `localizations` field is marked as required, even though it is disabled for blogs:

image

### PR DESCRIPTION
**Pull request by Convly**
### What does it do?

Make `locale` and `localizations` attributes private if a content-type is not localized. 

### Why is it needed?

Prevent those fields from appearing in the GraphQL schema or REST API response

### How to test it?

- Create a CT with and without i18n enabled. 
- Check the graphql queries

### Related issue(s)/PR(s)

fix #21401

### CODE REVIEW

**Review by alexandrebodin — COMMENTED** [review]
I'm not sure this is what we should do here. 

Always having the fields means we have a consistent and more predictable API response & GraphQL schema and the only thing that changes is the data 🤔

**Comment by Convly** [comment]
The thing is that it makes no sense to use i18n-related fields on non-localized CTs, the locale will always be null and localizations an empty array.

I just feel like it's more confusing than anything

**Comment by Convly** [comment]
When D&P is disabled, the publishedAt doesn't exist, does it?

**Comment by Marc-Roig** [comment]
@Convly publishedAt does exist even if D&P is disabled

**Comment by Convly** [comment]
Damn, that's true, forgot about that :slightly_frowning_face:

**Comment by innerdvations** [comment]
> I'm not sure this is what we should do here.
> 
> Always having the fields means we have a consistent and more predictable API response & GraphQL schema and the only thing that changes is the data 🤔

If a content type doesn't have localization, shouldn't it should throw an error if you try to access it by locale or populate localizations from the content API?

If anything, I would say the consistency should go a step deeper, and the document service should also sanitize those attributes out.

**Comment by innerdvations** [comment]
> All content-types have both published at and locale so we have structural consistency.
> 
> The structure (ct, db model) should remained unchanged but the data sanitized out / or removed from the schema rather than made private. Using private to remove it from the schema is a "lucky" but very brittle consequence. It's a matter of encapsulation here. Private has a meaning that is different from "this feature should not be enabled so I will not add it to the schema or sanitize it out"

For localizations, that works fine, but for locale won't that cause us to delete locale data on startup if it gets temporarily disabled? Or do we keep that column anyway?

**Comment by alexandrebodin** [comment]
What I meant with 

> Private has a meaning that is different from "this feature should not be enabled so I will not add it to the schema or sanitize it out"

is that you need to add some dedicated logic for it instead of using private :)

**Comment by alexandrebodin** [comment]
> > > The structure (ct, db model) should remained unchanged but the data sanitized out / or removed from the schema rather than made private.
> > 
> > 
> > > is that you need to add some dedicated logic for it instead of using private :)
> > 
> > 
> > `private` is defined as "sanitized from the content API" so I'm not sure why we would need to create custom logic for these two fields. I think I'm misinterpreting something. At what level would you remove the attributes?
> 
> I guess that technically, we could add a custom visitor to sanitize/validate the incoming data based on i18n rules, directly from i18n, just like we do in U&P ([`develop`/packages/plugins/users-permissions/server/utils/sanitize](https://github.com/strapi/strapi/tree/develop/packages/plugins/users-permissions/server/utils/sanitize?rgh-link-date=2024-10-01T13%3A25%3A06Z)).
> 
> But then, the fields would still appear in the generated type definitions (next/etc...) since the structure hasn't changed

I was only thinking about the graphql issue with the schema generation that should check if i18n is enabled or not instead of rellying on private attributes 🤔 

It's ok to use private for the time being with a good comment for the sanitization at least. mid term this should be addressed with the split between content-types & models

File: packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx [hunk 1]
```diff
@@ -374,7 +374,7 @@ export const BrowseStep = ({
         </>
       )}
 
-      {pagination.pageCount > 0 && (
+      {pagination.total > pagination.pageSize && (
```
Comment (innerdvations) [inline packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx:377]: what's happening here (and with the other pagination changes)?

File: tests/api/core/content-manager/search.test.api.js [hunk 2]
```diff
@@ -192,9 +192,9 @@ describe('Search query', () => {
       expect(Array.isArray(res.body.results)).toBe(true);
       expect(res.body.results.length).toBe(data.beds.length);
       // TODO V5: Filter out i18n fields if content type is not localized
```
Comment (innerdvations) [inline tests/api/core/content-manager/search.test.api.js:194]: I think you can remove this comment now

File: packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx (hunk 1 above)
Comment (Convly) [reply packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx:377]: uh? I just updated the branch with develop and it brought this, no idea where this comes from :thinking:

Comment (Convly) [reply packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx:377]: https://github.com/strapi/strapi/pull/21495/commits

Comment (innerdvations) [reply packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx:375]: weird, maybe you need to rebase

File: tests/api/core/content-manager/search.test.api.js [hunk 3]
```diff
@@ -191,10 +191,9 @@ describe('Search query', () => {
 
       expect(Array.isArray(res.body.results)).toBe(true);
       expect(res.body.results.length).toBe(data.beds.length);
-      // TODO V5: Filter out i18n fields if content type is not localized
-      expect(res.body.results.map(omit([...CREATOR_FIELDS, 'localizations', 'status']))).toEqual(
-        expect.arrayContaining(data.beds)
-      );
+      expect(
```
Comment (innerdvations) [inline tests/api/core/content-manager/search.test.api.js:194]: Sorry to be annoying on this, but could we add a test for if i18n is enabled on roles and see that the fields still show up? That's the one case where this would potentially become a breaking change, since we have our own custom sanitization on this I could see someone potentially breaking it by accident in the future.

**Review by innerdvations — COMMENTED** [review]
Are we totally sure a user wouldn't intentionally want locale to be in the results?

Do we allow someone to enable i18n on he role, for example if they want to translate their role names?

File: tests/api/core/content-manager/search.test.api.js (hunk 3 above)
Comment (Convly) [reply tests/api/core/content-manager/search.test.api.js:194]: How do you want to enable i18n on the roles content type though? Or are you talking about the relation? :thinking:

**Comment by Convly** [comment]
@innerdvations I've rewritten the branch history, should be cleaner now

File: tests/api/core/content-manager/search.test.api.js (hunk 3 above)
Comment (innerdvations) [reply tests/api/core/content-manager/search.test.api.js:194]: My bad, I thought we let it be customized like the User ct. It looks like we don't allow it, so it's fine, someone would have to be messing with things they shouldn't

**Review by innerdvations — APPROVED** [review]

File: packages/plugins/users-permissions/server/controllers/role.js [hunk 4]
```diff
@@ -30,13 +39,17 @@ module.exports = {
       return ctx.notFound();
     }
 
-    ctx.send({ role });
+    const safeRole = await sanitizeOutput(role);
```
Comment (alexandrebodin) [inline packages/plugins/users-permissions/server/controllers/role.js:42]: Can't this use the defaultSanitizers instead of manually requiring i18n? I don't see how we need this specifically here ?

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/plugins/users-permissions/server/controllers/role.js (hunk 4 above)
Comment (Convly) [reply packages/plugins/users-permissions/server/controllers/role.js:42]: I didn't want to change the current behavior of returning all the fields (including potentially private ones) since it wasn't present before, hence the custom sanitization.

If you have more context on what should/shouldn't be returned from this API and why, I'm all ears :sweat_smile:

Comment (alexandrebodin) [reply packages/plugins/users-permissions/server/controllers/role.js:42]: I don't know, just strange to see this done here only 🤔
