### PR TITLE
fix: do not display fill from locales if i18n no enabled

### LINKED ISSUE #21203: “Fill from another locale” button should not appear when i18n is not activated
### **Steps to reproduce**
- Go an entry without i18n enabled
- See that the fill from another locale button is there and disabled

### **Expected behavior**

We should not show the disabled icon when i18n is disabled

### **Screenshots**

Image

### PR DESCRIPTION
**Pull request by Marc-Roig**
### What does it do?

Do not display the "Fill from locale" button if i18n is not enabled or there is not more than one locale.

fixes #21203

### CODE REVIEW

File: packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx [hunk 1]
```diff
@@ -278,6 +279,10 @@ const FillFromAnotherLocaleAction = ({
     onClose();
   };
 
+  if (!hasI18n || !Array.isArray(locales) || locales.length === 0) {
```
Comment (remidej) [inline packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx:282]: if i18n is enable but the locales aren't loaded, should we fall back to the disabled state defined below? otherwise I don't see what it's for

Comment (Marc-Roig) [reply packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx:282]: good point, will do that!

**Review by remidej — APPROVED** [review]
simple and effective 👌

tested locally
