### PR TITLE
fix(content-manager): wrap single type displayName with formatMessage

### LINKED ISSUE #25829: Single type edit view heading does not use formatMessage for displayName translation
### Node Version

22.x

### Package Manager

npm

### Package Manager Version

10.9.4

### Strapi Version

5.39.0 

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Javascript

### Reproduction URL

_No response_

### Bug Description

                                                                                                                                                                      
  The edit view heading for single types renders `schema.info.displayName` as a raw string without passing it through `formatMessage`. This means custom admin        
  translations registered via `config.translations` in `app.js` are ignored for single type page headings, while they work correctly for:
                                                                                                                                                                      
  - The sidebar/left menu (uses `formatMessage` in `LeftMenu.js`)                                                                                                     
  - The collection type list view heading (uses `formatMessage` in `ListViewPage.mjs`)                                                                                                                          
                                                                                                                                                             


### Steps to Reproduce

                                                                                                                                                                      
  1. Create a single type with `displayName: "About"`                                                                                                                 
  2. Add a translation override in `src/admin/app.js`:
     ```js                                                                                                                                                            
     const config = {                                                                                                                                        
       locales: ['de'],                                                                                                                                               
       translations: {                                                                                                                                       
         de: { 'About': 'Über uns' },    
       },                                                                                                                                                             
     }
  3. Switch admin interface to German                                                                                                                                 
  4. Observe: sidebar correctly shows "Über uns", but the edit view page heading still shows "About"                                                         


### Expected Behavior

  The edit view heading should show "Über uns" when the admin locale is German, matching the sidebar behavior.                                                        

### Logs

```shell

```

### Code Snippets

_No response_

### Media

_No response_

### Additional information
                                                                                                                                                             
  **Root cause**
  In packages/core/content-manager/admin/src/hooks/useDocument.ts, the getTitle function returns schema.info.displayName as a plain string for single types:          

```ts
  if (isSingleType && schema?.info.displayName) {                                                                                                                     
    return schema.info.displayName  // raw string, no formatMessage                                                                                          
  }
```
                                                                                                                                                    
The fix should match the pattern used in ListViewPage which correctly wraps it:                                                                                     

```ts
  if (isSingleType && schema?.info.displayName) {                                                                                                                     
    return formatMessage({                                                                                                                                            
      id: schema.info.displayName,       
      defaultMessage: schema.info.displayName,                                                                                                                        
    })                                                                                                                                                       
  }                                      
```

formatMessage (from useIntl) is already imported and available in the useDocument hook.    

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by guoyangzhen**
## Description

The edit view heading for single types renders `schema.info.displayName` as a raw string without passing it through `formatMessage`. This means custom admin translations registered via `config.translations` in `app.js` are ignored for single type page headings, while they work correctly for:

- The sidebar/left menu (uses `formatMessage` in `LeftMenu.tsx`)
- The collection type list view heading (uses `formatMessage`)

This PR wraps the single type displayName with `formatMessage`, matching the pattern used in LeftMenu:

```js
// Before
return schema.info.displayName;

// After
return formatMessage({
  id: schema.info.displayName,
  defaultMessage: schema.info.displayName,
});
```

This tries to find a translation for the displayName first, falling back to the raw string if none exists — exactly how `LeftMenu.tsx:70` handles link titles.

## How to reproduce

1. Create a single type with `displayName: "About"`
2. Add a translation override in `src/admin/app.js`
3. Navigate to the single type edit view — heading shows raw "About" instead of the translation

## Related Issue

Fixes #25829

### CODE REVIEW

File: packages/core/content-manager/admin/src/hooks/useDocument.ts [hunk 1]
```diff
@@ -351,4 +354,4 @@ const useContentManagerContext = () => {
 };
 
 export { useDocument, useDoc, useContentManagerContext };
-export type { UseDocument, UseDocumentArgs, Document, Schema, ComponentsDictionary };
+export type { UseDocument, UseDocumentArgs, Document, Schema, ComponentsDictionary };
```
Comment (innerdvations) [inline packages/core/content-manager/admin/src/hooks/useDocument.ts]:
```suggestion
export type { UseDocument, UseDocumentArgs, Document, Schema, ComponentsDictionary };

```

**Comment by guoyangzhen** [comment]
I've signed the CLA. Could you please recheck?
