### PR TITLE
Content Manager - Edit view (group & repeatable fields support)

### LINKED ISSUE #1114: Deleting/Updating content-type doesn't drop/migrate the database
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha 12.1.2
- **Database**: MySQL
- **Operating system**: Windows 10

**What is the current behavior?**

Deleting a content-type does not drop the database table in MySQL, & when I navigate to roles & permissions, I can still see the deleted content-type and edit its permissions. When i create a new user role however, it only shows the non-deleted content-types. So for some reason, the content-types don't get deleted from the memory of existing user roles

**Steps to reproduce the problem**

1) create content-type 
2) add a string field to it 
3) save
4) delete content-type
5) content-type is not in the list of content-types anymore but the database table still exists + the reference to the content-type remains in the roles & permissions folder of a user role, when editing permissions.

**What is the expected behavior?**

deleting a content-type should remove all references of this content-type ever existing + drop its database automatically. Dropping the database manually still doesn't make the reference to the content-type in roles & permissions disappear. Dropping the whole database and re-creating it does however fix the problem

**Suggested solutions**

N.A.

- [ x ] I'm sure that this issue hasn't already been referenced

### PR DESCRIPTION
**Pull request by soupette**
#### Description of what you did:
Complete update of the edit view. What has currently been done:
- complete rewrite using hooks
- migration to styled-components
- Group & Repeatable support in the edit view
- upgrade to react-selects v2

#### My PR is a:

- [X] 💥 Breaking change
- [X] 🐛 Bug fix #1114 #1457 #2769 #2471 #2421 #2893 #3105 #3428 #3098 #3317 
- [X] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

#### Manual testing done on the following databases:

- [ ] Not applicable
- [X] MongoDB
- [X] MySQL
- [X] Postgres
- [X] SQLite

### CODE REVIEW

File: packages/strapi-plugin-content-manager/admin/src/components/Group/Form.js [hunk 1]
```diff
@@ -0,0 +1,50 @@
+import React, { memo } from 'react';
+import PropTypes from 'prop-types';
+import { get } from 'lodash';
+
+import Inputs from '../Inputs';
+import SelectWrapper from '../SelectWrapper';
+
+const Form = ({ keys, layout, modifiedData, fieldName, onChange }) => {
+  const currentField = get(layout, ['schema', 'attributes', fieldName], '');
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/Group/Form.js]: This value is constant throughout the lifecycle of the component so it should be changed to 
`const currentField = useMemo(() => get(layout, ['schema', 'attributes', fieldName], ''))`;

File: packages/strapi-plugin-content-manager/admin/src/components/Group/Form.js [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+  const currentFieldMeta = get(layout, ['metadatas', fieldName, 'edit'], {});
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/Group/Form.js]: Same here

File: packages/strapi-plugin-content-manager/admin/src/components/Group/GroupCollapse.js [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+  isOpen: PropTypes.bool,
+  layout: PropTypes.object,
+  modifiedData: PropTypes.object,
+  name: PropTypes.string.isRequired,
+  onChange: PropTypes.func.isRequired,
+  onClick: PropTypes.func.isRequired,
+  removeField: PropTypes.func,
+};
+
+export default DropTarget(
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/Group/GroupCollapse.js]: Use the hook API instead

File: packages/strapi-plugin-content-manager/admin/src/components/Group/index.js [hunk 4]
```diff
@@ -0,0 +1,233 @@
...
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+    [groupValue]
+  );
+
+  useEffect(() => {
+    const collapsesToOpen = Object.keys(errors)
+      .filter(errorPath => errorPath.split('.')[0] === name && isRepeatable)
+      .map(errorPath => errorPath.split('.')[1]);
+
+    dispatch({
```
Comment (soupette) [inline packages/strapi-plugin-content-manager/admin/src/components/Group/index.js]:
```
if (collapseToOpen.length > 0) { 
  dispatch(...)
}
```

So it doesn't conflict with the init function.

File: packages/strapi-admin/admin/src/config.js [hunk 5]
```diff
@@ -0,0 +1 @@
+export const SHOW_TUTORIALS = true;
```
[the remark this answers is not in the document]
Comment (derrickmehaffy) [reply packages/strapi-admin/admin/src/config.js]: Awesome thank you

[the remark this answers is not in the document]
Comment (soupette) [reply packages/strapi-admin/admin/src/config.js]: I will add the documentation as well

**Comment by derrickmehaffy** [comment]
updated OP to auto close: https://github.com/strapi/strapi/issues/1114

File: packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js [hunk 6]
```diff
@@ -1,7 +1,714 @@
...
+              },
+              false,
+              false
+            );
+
+            collection[current] = uploadedFiles;
+
+            return collection;
+          } catch (err) {
+            console.log('upload error', err);
```
[the remark this answers is not in the document]
Comment (soupette) [reply packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js]: I left the logs in purpose since we are not handling the errors from the back-end correctly right now. However, if you think that they should be removed I'll do it

File: packages/strapi-plugin-content-manager/admin/src/components/FieldsReorder/Item.js [hunk 7]
```diff
@@ -0,0 +1,226 @@
+import React, { useEffect, useRef } from 'react';
```
[the remark this answers is not in the document]
Comment (soupette) [reply packages/strapi-plugin-content-manager/admin/src/components/FieldsReorder/Item.js]: I have added the source line 31

File: packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+        moveRelation(draggedId, overIndex);
+      }
+    },
+  });
+
+  useEffect(() => {
+    preview(getEmptyImage(), { captureDraggingState: true });
+  }, [preview]);
+
+  const opacity = isDragging ? 0.2 : 1;
```
[the remark this answers is not in the document]
Comment (soupette) [reply packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js]: Well since the displayed dragged component for the select is different than the group which is also different than the one for the layout I need to add the same condition to each single one of them. I don't see how I can manage that with a css class or a styled component.

File: packages/strapi-plugin-content-manager/admin/src/components/FieldsReorder/Item.js [hunk 9]
```diff
@@ -0,0 +1,232 @@
...
+    />
+  );
+};
+
+Item.defaultProps = {
+  type: 'string',
+};
+
+Item.propTypes = {
+  groupUid: PropTypes.string,
```
Comment (virginieky) [inline packages/strapi-plugin-content-manager/admin/src/components/FieldsReorder/Item.js]: Is groupUid required or does it need a default prop ?

File: packages/strapi-plugin-content-manager/admin/src/components/Group/index.js [hunk 10]
```diff
@@ -0,0 +1,235 @@
...
+
+Group.defaultProps = {
+  addRelation: () => {},
+  groupValue: {},
+  label: '',
+  layout: {},
+  max: Infinity,
+  min: -Infinity,
+  modifiedData: {},
+  onChange: () => {},
```
Comment (virginieky) [inline packages/strapi-plugin-content-manager/admin/src/components/Group/index.js]: No need if required

File: packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+  nextSearch: '',
+  onRemove: () => {},
+  targetModel: '',
+};
+
+ListItem.propTypes = {
+  data: PropTypes.object.isRequired,
+  findRelation: PropTypes.func,
+  mainField: PropTypes.string.isRequired,
+  moveRelation: PropTypes.func,
```
Comment (virginieky) [inline packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js]: default prop is missing

File: packages/strapi-plugin-content-manager/admin/src/components/AddDropdown/index.js [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+  ButtonDropdown,
+  DropdownToggle,
+  DropdownMenu,
+  DropdownItem,
+} from 'reactstrap';
+
+import { Wrapper } from './components';
+
+function Add({ data, onClick, pStyle, style }) {
+  const [state, setState] = useState(false);
```
Comment (virginieky) [inline packages/strapi-plugin-content-manager/admin/src/components/AddDropdown/index.js]: [isOpen, setIsOpen] may be more explicite
