### PR TITLE
AWS Cognito provider

### LINKED ISSUE #6822: Custom authentication provider (e.g. AWS Cognito User Pools) not working because subdomain parameter not set in grant object configuration
**Describe the bug**
When trying to create a new custom authentication provider for strapi, I am calling the strapi server base url /connect/new_provider_name then I am getting a dns error from the browser. When looking at the network log I can see a 302 response with a redirection to https://[subdomain]/oauth2/authorize. The subdomain is not being replaced by the link to the Identity provider (in this case AWS Cognito User Pools)

**Steps to reproduce the behavior**

1. Follow the documentation to add a new Custom provider
2. Go to https://strapi_server_url/collect/name_of_your_provider
3. Redirection fails

**Expected behavior**
The redirection from https://strapi_server_url/collect/name_of_your_provider to the identity provider authorize page works

**Code snippets**
The issue seems to be in not having the subdomain property configurable in the grant object configuration in the user-permissions plugin and more precisely in the connect method located in the Auth.js controller (users-permissions > controllers > Auth.js

```javascript
async connect (ctx, next) {
    const grantConfig = await strapi
      .store({
        environment: '',
        type: 'plugin',
        name: 'users-permissions',
        key: 'grant'
      })
      .get()

    const [requestPath] = ctx.request.url.split('?')
    const provider =
      process.platform === 'win32' ? requestPath.split('\\')[2] : requestPath.split('/')[2]

    if (!_.get(grantConfig[provider], 'enabled')) {
      return ctx.badRequest(null, 'This provider is disabled.')
    }
    // Ability to pass OAuth callback dynamically
    grantConfig[provider].callback = _.get(ctx, 'query.callback') || grantConfig[provider].callback
    grantConfig[provider].redirect_uri = `${strapi.config.server.url}/connect/${provider}/callback`
    // Adding the following code seems to solve the issue
    grantConfig[provider].subdomain = strapi.config.custom.cognitoHost

    return grant(grantConfig)(ctx, next)
},
```
Adding the following code in the previous method seems to work:
```javascript
    // Adding the following sentence seems to solve the issue
    grantConfig[provider].subdomain = strapi.config.custom.cognitoHost
```

**System**

- Node.js version: v12
- Strapi version: v3.0.5

### PR DESCRIPTION
**Pull request by ralphsomeday**
#### Description of what you did:
fix #6822

### CODE REVIEW

**Comment by alexandrebodin** [comment]
Closing for inactivity @ralphsomeday  Let me know when you can takle this again so I reopen it ;)

**Comment by JiboStore** [comment]
Hi, I am new to strapi (just evaluating) and would need to integrate AWS Cognito user-pool as its auth provider (is it possible) but the documentation is minimum.

@ralphsomeday is your PR for cognito integration? Would you please share any resources you use to get it up?

**Comment by ralphsomeday** [comment]
@JiboStore i will review the comments from @alexandrebodin and update the PR.

**Comment by ralphsomeday** [comment]
@alexandrebodin can you re-open it?

**Comment by ralphsomeday** [comment]
image


image

@alexandrebodin how can we solve the merge issue with Travis? thanks

**Comment by ralphsomeday** [comment]
@alexandrebodin would you mind reviewing this PR? this will allow to add support for a new provider AWS Cognito.

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Hi, thanks for this PR. Using extra config folder is not pactical as it requires more user work. I think this should be set in the plugins.js users-permissions configuration. We could do it a better cleaner buy allowing to overxwritte any provider config from the configuraation directly like so:

`./config/plugins.js`
```js
module.exports = () => ({
  users-permissions: {
    grantProviders: {
      cognito: { // or any other provider
         subdomain: 'azdaz',
       }
    }
  }
})
```

This way we only merge the configs together instead of having to had code for each new properties that will come up in the future

**Comment by ralphsomeday** [comment]
@alexandrebodin made it even easier by adding an extra field in the provider configuration and added a translation key in all supported languages see below screenshot:

image

**Comment by ralphsomeday** [comment]
@alexandrebodin any chance this can be reviewed so that we can add support for cognito auth provider in next release?

**Comment by alexandrebodin** [comment]
Hi, your PR contains a ton of conflicts right now. Once it is fixed we will review it again. From What I saw already adding the input in the UI won't scale as we can't just add every possible input one PR at a time. I think we should still allow passing those configuration in the configs instead of the UI.

**Comment by ralphsomeday** [comment]
@alexandrebodin the conflicts are only one translation key added ("PopUpForm.Providers.subdomain.label": "Host URI (Subdomain)") in the translation files, the auth file has been cleaned up to remove the changes and go back to its original shape and the bootstrap has just added the new AWS Cognito provider. I do not see why this won't scale at UI level, any new provider you are adding is going in the bootstrap and this is a new provider that is now working which allows companies using cognito as an idp to be able to connect it with strapi.

**Comment by alexandrebodin** [comment]
I wasn't clear. I meant we won't be able to add input for every single options avaialbe for each providers. In this case I only see in the diff that you added the cognito provider. no issue with that but the PR is just not mergeable so we won't approve it until cleaned up :)

**Comment by ralphsomeday** [comment]
@alexandrebodin the thing is that the subdomain is not a custom property of cognito it is provided with grant and can be configured for some providers that needs it. So i guess this is something we can leave in the UI. For the rest let me know what you would like me to have cleaned up so that this PR can go ahead? The subdomain in the UI will allow to configure different providers that may require different subdomains directly in the UI way more handy than having it in the configuration of the plugin.

**Comment by alexandrebodin** [comment]
You need to fix all the conflicts so the PR can go ahead

**Comment by alexandrebodin** [comment]
Not there yet :/

**Comment by ralphsomeday** [comment]
@alexandrebodin should be better now no more merge conflicts. Can you let me know if all is fine from your side after the travis has passed? thanks

**Comment by ralphsomeday** [comment]
@alexandrebodin should be good to go

**Comment by alexandrebodin** [comment]
@ralphsomeday testing your PR right now. It doesn't have the subdomain input anymore

**Comment by ralphsomeday** [comment]
> @ralphsomeday testing your PR right now. It doesn't have the subdomain input anymore

@alexandrebodin you mean you are not seeing the subdomain input field in the AWS Cognito provider?

**Comment by alexandrebodin** [comment]
> > @ralphsomeday testing your PR right now. It doesn't have the subdomain input anymore
> 
> @alexandrebodin you mean you are not seeing the subdomain input field in the AWS Cognito provider?

Yep exactly

**Comment by ralphsomeday** [comment]
@alexandrebodin i see this on the latest version was testing on 3.0.x let me investigate this and come back to you.

**Comment by ralphsomeday** [comment]
@alexandrebodin this should be it. Now working with the latest branch. Let me know if anything is not working. thanks

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js [hunk 1]
```diff
@@ -3,10 +3,14 @@ import { sortBy } from 'lodash';
 const createProvidersArray = data => {
   return sortBy(
     Object.keys(data).reduce((acc, current) => {
-      const { icon: iconName, enabled } = data[current];
+      const { icon: iconName, enabled, subdomain } = data[current];
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js:6]:
```
const { icon: iconName, enabled, subdomain } = data[current];
```

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js [hunk 2]
```diff
@@ -3,10 +3,14 @@ import { sortBy } from 'lodash';
...
       const icon = iconName === 'envelope' ? ['fas', 'envelope'] : ['fab', iconName];
 
-      acc.push({ name: current, icon, enabled });
+      if (subdomain) {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js:9]: The condition here is not needed you can use null for the subdomain

```
acc.push({ name: current, icon, enabled, subdomain });

return acc;
```

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js [hunk 3]
```diff
@@ -30,6 +30,7 @@ const ProvidersPage = () => {
   const buttonSubmitRef = useRef(null);
   const [showForm, setShowForm] = useState(false);
   const [providerToEditName, setProviderToEditName] = useState(null);
+  const [providerIsWithSubdomain, setProviderIsWithSubdomain] = useState(false);
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js:33]: The useState hook is not needed here you can replace it by the following:


```

import { get, has, upperFirst } from 'lodash';
const isProviderWithSubdomain = useMemo(() => {
    if (!providerToEditName) {
      return false;
    }

    const providerToEdit = providers.find(obj => obj.name === providerToEditName);

    return has(providerToEdit, 'subdomain');
  }, [providers, providerToEditName]);
```


Then you will just need to update the formToRender constant:

```
const formToRender = useMemo(() => {
  if (providerToEditName === 'email') {
    return forms.email;
  }

  if (isProviderWithSubdomain) {
    return forms.providersWithSubdomain;
  }

  return forms.providers;
}, [providerToEditName, isProviderWithSubdomain]);
```

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js [hunk 4]
```diff
@@ -97,6 +96,7 @@ const ProvidersPage = () => {
     provider => {
       if (canUpdate) {
         setProviderToEditName(provider.name);
+        setProviderIsWithSubdomain(provider.subdomain && provider.subdomain !== '');
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js:99]: With the comment from above you can remove this line.

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js [hunk 5]
```diff
@@ -105,6 +105,7 @@ const ProvidersPage = () => {
 
   const handleClosed = useCallback(() => {
     setProviderToEditName(null);
+    setProviderIsWithSubdomain(false);
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js:108]: Same here.

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/forms.js [hunk 6]
```diff
@@ -57,6 +57,17 @@ const forms = {
           required: true,
         },
       },
+      {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/forms.js:60]: Instead of adding a new input here I think it's better to add a new key: `providersWithSubdomain` so you have a specific form and a dedicated yup schema:


```
const forms = {
  email: {},
  providers: {},
  providersWithSubdomain: {
    form: [
      {
        autoFocus: true,
        label: getTrad('PopUpForm.Providers.enabled.label'),
        name: 'enabled',
        type: 'bool',
        description: getTrad('PopUpForm.Providers.enabled.description'),
        size: { xs: 6 },
        validations: {
          required: true,
        },
      },
      {
        autoFocus: false,
        label: getTrad('PopUpForm.Providers.key.label'),
        name: 'key',
        type: 'text',
        placeholder: getTrad('PopUpForm.Providers.key.placeholder'),
        size: { xs: 12 },
        validations: {
          required: true,
        },
      },
      {
        autoFocus: false,
        label: getTrad('PopUpForm.Providers.secret.label'),
        name: 'secret',
        type: 'text',
        placeholder: getTrad('PopUpForm.Providers.secret.placeholder'),
        size: { xs: 12 },
        validations: {
          required: true,
        },
      },
      {
        autoFocus: false,
        label: getTrad('PopUpForm.Providers.subdomain.label'),
        name: 'subdomain',
        type: 'text',
        placeholder: getTrad('PopUpForm.Providers.subdomain.placeholder'),
        size: { xs: 12 },
        validations: {
          required: true,
        },
      },
      {
        autoFocus: false,
        label: getTrad('PopUpForm.Providers.redirectURL.front-end.label'),
        placeholder: 'http://www.client-app.com',
        name: 'callback',
        type: 'text',
        size: { xs: 12 },
        validations: {
          required: true,
        },
      },
      {
        label: {
          id: getTrad('PopUpForm.Providers.redirectURL.label'),
          params: {
            provider: 'VK',
          },
        },
        name: 'noName',
        type: 'text',
        validations: {},
        size: {
          xs: 12,
        },
        disabled: true,
      },
    ],
    schema: yup.object().shape({
      enabled: yup.bool().required(translatedErrors.required),
      key: yup.string().when('enabled', {
        is: true,
        then: yup.string().required(translatedErrors.required),
        otherwise: yup.string(),
      }),
      secret: yup.string().when('enabled', {
        is: true,
        then: yup.string().required(translatedErrors.required),
        otherwise: yup.string(),
      }),
      subdomain: yup.string().when('enabled', {
        is: true,
        then: yup.string().required(translatedErrors.required),
        otherwise: yup.string(),
      }),
      callback: yup.string().when('enabled', {
        is: true,
        then: yup.string().required(translatedErrors.required),
        otherwise: yup.string(),
      }),
    }),
  }
}
```

Then it will simplify the index.js file.

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js [hunk 7]
```diff
@@ -219,14 +220,40 @@ const ProvidersPage = () => {
           <form onSubmit={handleSubmit}>
             <Row>
               {formToRender.form.map(input => {
+                if (input.name === 'subdomain') {
```
Comment (soupette) [inline packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js:223]: Regarding the comment I have added in the utils/forms.js  file, this line won't be needed so you can remove them.

**Review by soupette — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution!

In order to simplify the logic you can simply create a new type of form for the providers that have a subdomain with this you can also update the validation schema without adding more complexity to the code.

Then, in the index.js file you will just need to add a condition in order to map the correct with the correct provider.

Let me know if my comments are not clear enough.

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js (hunk 3 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js:33]: for the `return has(...)` I had to add     return has(providerToEdit, 'subdomain') && providerToEdit.subdomain !== undefined; as the previous code in the createProviderArray is adding the subdomain property to all providers.

Comment (soupette) [reply packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js]: I am sorry I have forgotten to remove my comment on the createProvidersArray file if you keep your old code (really sorry about that) the has condition should work.

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js (hunk 2 above)
Comment (soupette) [reply packages/strapi-plugin-users-permissions/admin/src/containers/Providers/utils/createProvidersArray.js]: I am sorry you could leave this file as you did it originally.

File: packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js (hunk 3 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-users-permissions/admin/src/containers/Providers/index.js]: @soupette rolled back to my previous code

**Comment by ralphsomeday** [comment]
@soupette should now be GTM

**Review by soupette — APPROVED** [review]
LGTM for the front-end part!

Thanks a lot for your contribution  👏

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Hey, the code looks good to me, 

One last thing though. I think we should add a section in the doc for this provider to explain how to set it up on the aws side (configure the oauth2 conf, authorization flow and such...) cc @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> Hey, the code looks good to me,
> 
> One last thing though. I think we should add a section in the doc for this provider to explain how to set it up on the aws side (configure the oauth2 conf, authorization flow and such...) cc @derrickmehaffy

Yup exactly, if there is any non-standard steps (or just in general for all providers merged into the mono-repo) we will need any relevant information added to the docs. Bad link due to how vuepress handles markdown but somewhere around here: https://github.com/strapi/strapi/blob/master/docs/v3.x/plugins/users-permissions.md#providers

**Comment by ralphsomeday** [comment]
@alexandrebodin and @derrickmehaffy doc is updated please review and let me know if anything need to be amended or added.

File: docs/v3.x/plugins/users-permissions.md [hunk 8]
```diff
@@ -317,6 +317,42 @@ Wait a few seconds while the application is created.
...
+- Go to the **App integration section** and click on **App client settings**
+- Look for your app client named `Strapi Auth` and enable Cognito User Pool by checking it in the **Enabled Identity Providers** section of your newly created App client
+- Feel in your callback URL and Sign out URL with the value `http://localhost:1337/connect/cognito/callback` or the one provided by your AWS Cognito provider in Strapi
+- In the **Oauth 2.0** section select `Authorization code grant` and `Implicit grant` for the **Allowed OAuth Flows** and select `email`, `openid` and `profile` for the **Allowed OAuth Scopes**
+- You can now click on **Save changes** and a link to the **Launch Hosted UI** will now be visible. You can click on it in order to display the AWS Cognito login page. Copy the URL of that login page (everything between `https` and `/login`). This will be the **Host URI (Subdomain)** value for your strapi configuration
+
```
Comment (petersg83) [inline docs/v3.x/plugins/users-permissions.md:342]: The hosted UI was no available because the Domain Name was not set. Can you add a step for that please?

File: docs/v3.x/plugins/users-permissions.md [hunk 9]
```diff
@@ -317,6 +317,42 @@ Wait a few seconds while the application is created.
...
+#### Strapi configuration
+
+- Visit the User Permissions provider settings page <br> [http://localhost:1337/admin/plugins/users-permissions/providers](http://localhost:1337/admin/plugins/users-permissions/providers)
```
Comment (petersg83) [inline docs/v3.x/plugins/users-permissions.md:345]: The settings have moved to `http://localhost:1337/admin/settings/users-permissions/providers`

File: docs/v3.x/plugins/users-permissions.md [hunk 10]
```diff
@@ -860,3 +896,7 @@ module.exports = {
 ::: tip
 You can learn more on configuration in the documentation [here](../concepts/configurations.md)
 :::
+
+## Custom providers HOST URI (subdomain) configuration
+
+Some external Identity providers like AWS Cognito will require you to provide the link to the IDP host url (e.g. your_idp_name.auth.eu-central-1.amazoncognito.com) so that you can access the IDP login page using `htts://your_strapi_url/connect/your_custom_provider_name`. In order to do that you will have to fill in that value in the configuration popup of the provider in the Host URI (subdomain) field.
```
Comment (petersg83) [inline docs/v3.x/plugins/users-permissions.md:902]: Why did you add that? The doc for aws isn't enough?

**Review by petersg83 — CHANGES_REQUESTED** [review]
Hi, 
Thanks for you contribution !
It doesn't work on my side, I've been through the whole process but at the end I have "unknown provider". I think some code is missing in the PR here: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Providers.js#L452

File: docs/v3.x/plugins/users-permissions.md [hunk 11]
```diff
@@ -317,6 +317,42 @@ Wait a few seconds while the application is created.
...
+- If applicable either create or use an existing user pool. You will find hereafter a tutorial to create a User Pool <br> [https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-create-user-pool.html](https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-create-user-pool.html)
+- Go to the **App clients** section in your cognito user pool and create a new client with the name `Strapi Auth` and set all the parameters and then click on **Create app client**
+- You should now have an **App client id** and by clicking on the button **Show Details** you will be able to see the **App client secret**. Do copy those two values **App client id** and **App client secret** somewhere for later use when configuring the AWS Cognito provider in Strapi.
+- Go to the **App integration section** and click on **App client settings**
+- Look for your app client named `Strapi Auth` and enable Cognito User Pool by checking it in the **Enabled Identity Providers** section of your newly created App client
+- Feel in your callback URL and Sign out URL with the value `http://localhost:1337/connect/cognito/callback` or the one provided by your AWS Cognito provider in Strapi
```
[the remark this answers is not in the document]
Comment (ralphsomeday) [reply docs/v3.x/plugins/users-permissions.md:339]: yes good catch

File: docs/v3.x/plugins/users-permissions.md (hunk 10 above)
Comment (ralphsomeday) [reply docs/v3.x/plugins/users-permissions.md:902]: yes it is, it was added before the doc for AWS was written. Will remove it.

File: docs/v3.x/plugins/users-permissions.md (hunk 8 above)
Comment (ralphsomeday) [reply docs/v3.x/plugins/users-permissions.md:342]: Sure

**Comment by alexandrebodin** [comment]
> Hi,
> Thanks for you contribution !
> It doesn't work on my side, I've been through the whole process but at the end I have "unknown provider". I think some code is missing in the PR here: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Providers.js#L452

I tested it and it works fine.

**Comment by alexandrebodin** [comment]
As @petersg83 mentionned you need to add a handler once you get the access_token back from aws cognito and call the callback with the right user infos :).

**Comment by ralphsomeday** [comment]
Yes I am on it

**Comment by alexandrebodin** [comment]
FYI, when you customize the client redirect URI you don't have that issue as you handle the access_token directly in your front-end app

**Comment by ralphsomeday** [comment]
Yes that is what I assumed. The access_token will be sent to frontend and then they can handle the api calls from the front end. I am now getting a 431 Request Header Fields Too Large as the access token from Cognito is quite Large more than 7K characters. How would you deal with this limitation on the server side @alexandrebodin ?

**Comment by alexandrebodin** [comment]
When are you getting this error exactly ?

**Comment by ralphsomeday** [comment]
When passing the access token to the connect endpoint via the query parameter

**Comment by alexandrebodin** [comment]
Hum I don't get an error. do you run this under a proxy ?

**Comment by ralphsomeday** [comment]
Can you share you configuration for the provider?

**Comment by petersg83** [comment]
For information, I tested the PR with this front-end example : https://github.com/strapi/strapi-examples/tree/master/login-react. I just added `'cognito'` there: https://github.com/strapi/strapi-examples/blob/master/login-react/src/pages/Home.js#L13

**Comment by ralphsomeday** [comment]
Thanks @petersg83 
Just updated the doc taking into account your input and added a case for the Cognito provider. Please let me know if now all is working fine. thanks.

File: docs/v3.x/plugins/users-permissions.md [hunk 12]
```diff
@@ -336,20 +336,20 @@ The use of `ngrok` is not needed.
...
-- Visit the User Permissions provider settings page <br> [http://localhost:1337/admin/plugins/users-permissions/providers](http://localhost:1337/admin/plugins/users-permissions/providers)
+- Visit the User Permissions provider settings page <br> [http://localhost:1337/admin/settings/users-permissions/providers](http://localhost:1337/admin/settings/users-permissions/providers)
 - Click on the **Cognito** provider
 - Fill the information (replace with your own client ID and secret):
   - **Enable**: `ON`
   - **Client ID**: fill in the **App client id** (`5bd7a786qdupjmi0b3s10vegdt`)
   - **Client Secret**: fill in the **App client secret** (`19c5c78dsfsdfssfsdfhpdb4nkpb145vesdfdsfsffgh7vwd6g45jlipbpb`)
   - **Host URI (Subdomain)**: fill in the URL value that you copied earlier (`myapp67b50345-67b50b17-local.auth.eu-central-1.amazoncognito.com`)
-  - **The redirect URL to your front-end app**: `http://localhost:3000/connect/cognito/redirect`
+  - **The redirect URL to your front-end app**: `http://localhost:1337/auth/cognito/callback`
```
Comment (petersg83) [inline docs/v3.x/plugins/users-permissions.md:352]: Why did you change? It was the correct value: `http://localhost:3000/connect/cognito/redirect`

File: packages/strapi-plugin-users-permissions/services/Providers.js [hunk 13]
```diff
@@ -161,6 +162,23 @@ const getProfile = async (provider, query, callback) => {
         });
       break;
     }
+    case 'cognito': {
+      // get the id_token
+      const idToken = query.id_token;
```
Comment (petersg83) [inline packages/strapi-plugin-users-permissions/services/Providers.js:167]: `id_token` doesn't seem to exist. In the query to `auth/cognito/callback` I see the params `access_token`, `refresh_token`, `raw[access_token]`, `raw[refresh_token]`, `raw[expires_in]` and `raw[token_type]`.

Also, to do like the other providers, the code here is supposed to make a call to the cognito API to retrieve the username.

Does it work on your side with this front-end app: https://github.com/strapi/strapi-examples/tree/master/login-react ?

**Review by petersg83 — CHANGES_REQUESTED** [review]

File: packages/strapi-plugin-users-permissions/services/Providers.js (hunk 13 above)
Comment (ralphsomeday) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: you have to empty your core_store from the grant permissions as I had to update the provider oauth scope in the bootstrap file in order to retrieve the user profile information. So instead of only email we now retrieve the openid and profile scopes and you will now receive the id_token back from cognito.

File: docs/v3.x/plugins/users-permissions.md (hunk 12 above)
Comment (ralphsomeday) [reply docs/v3.x/plugins/users-permissions.md:352]: For testing on my local dev i used this redirect URL and it worked pretty well and created the user in strapi and returned the strapi jwt with the profile information. It is a backend URL I know but for testing purpose if you do not have a frontend then this one works and after you can change it to your front end.

File: packages/strapi-plugin-users-permissions/services/Providers.js (hunk 13 above)
Comment (petersg83) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: Thank, you are right and it works great with the front-end app now !

Comment (rmaroun) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: @petersg83 and @alexandrebodin can we merge?

File: docs/v3.x/plugins/users-permissions.md (hunk 12 above)
Comment (petersg83) [reply docs/v3.x/plugins/users-permissions.md:352]: Thanks I understand! However, to be consistent with the other providers and to follow the standard flow can you put it back? It is supposed to work along with the strapi-example https://github.com/strapi/strapi-examples/tree/master/login-react/ :)

File: packages/strapi-plugin-users-permissions/services/Providers.js (hunk 13 above)
Comment (petersg83) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: Yes, it's good for me :) Just waiting for this: https://github.com/strapi/strapi/pull/6917#discussion_r499655530

Comment (petersg83) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: Also after that, can you update with master, squash your commits into one and signing-it off so the DCO pass?

Comment (rangoc) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: > Yes that is what I assumed. The access_token will be sent to frontend and then they can handle the api calls from the front end. I am now getting a 431 Request Header Fields Too Large as the access token from Cognito is quite Large more than 7K characters. How would you deal with this limitation on the server side @alexandrebodin ?

Sorry to barge in on the conversation like this, but this topic here is the only resource that's mentioning the problem occurring to me. I've tried implementing Cognito as authentication provider for Strapi, following the documentation, and using login-react as example for front-end, and I am experiencing the same error 431 Request Header Fields Too Large that you've experienced in the message above. Could you elaborate a bit more on how you solved it and what should be done to fix it? 

Steps to reproduce the error are the following: 

1. On front end, when you click on "Connect with Cognito" button you get redirected to Cognito's sign-in/sign-up form. 
2. When you choose Sign-up, create a user, and enter the verification code, apparently user gets successfully created in Cognito's User Pool ( under the hub ) but in browser, redirection happens and redirection leads to 431 Request Header Fields Too Large. 
3. When you navigate back to the URL of frontend ( ex. https://localhost:3000 ) and click again on "Connect with Cognito" you get successfully redirected to the front-end's page that's showing  successful log-in message with your Strapi's username in it.

Comment (ralphsomeday) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: @rangoc this limitation seems to come from node and I think it was introduced in version 10. To overcome this I had to run the following command `node --max-http-header-size=16384 ./node_modules/strapi/bin/strapi develop` try it and let me know if that works for you.

Comment (rangoc) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: @ralphsomeday  Error still persists, version of Node that I am currently using is v12.16.1.

Comment (rangoc) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: > @ralphsomeday Error still persists, version of Node that I am currently using is v12.16.1. I think I should update my Node version to > 14 in order to be able to set --max-http-header-size=16384

Now it works 👍

Comment (rangoc) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: @ralphsomeday Sorry for taking this conversation in here, if it's not a good place to post this please tell me and I will delete this comment. 

I just wanted to ask, would it be possible to implement this whole flow ( the one that's implemented by react-login example ) successfully while avoiding Cognito's Hosted UI, and instead using my own custom built UI ( that I've implemented by using SDK, which enables me to authenticate with Cognito without Hosted UI )? What would be the additional steps needed to be taken for Strapi's authentication part? 

Once again, sorry for opening this topic in here, sources are scarce.

Comment (ralphsomeday) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: Good question! You will have to research this one as usually the flow allows you to convert a cognito token into a strapi token which you then use to call the strapi api endpoints. If you authenticate using amplify or the sdk you will get a cognito token that won't be recognised by strapi. Maybe after getting the cognito token, you can call the redirect url to of the cognito provider with the access_token?

Comment (rangoc) [reply packages/strapi-plugin-users-permissions/services/Providers.js:167]: Hm, sounds like an idea :) If I try and when I try I will definitely write about it. Thanks :)
