### PR TITLE
Fix the same password requirements when registering a user

### LINKED ISSUE #1785: The password requirements are different for different input methods
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: alpha 13.1
- **Database**: pg
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**

Right now you have the following mechanisms to set a password:

- Initial strapi start - creating a user (no requirements - was able to use 5 characters)
- Reset password (currently failing, see #1784)
- Set password via profile (6 characters required)
- Create new user from admin (6 characters required)

**Steps to reproduce the problem**

**What is the expected behavior?**

Always have the same rules about setting a password

**Suggested solutions**

Use the same mechanism for setting a password in each part of the user interface

### PR DESCRIPTION
**Pull request by soupette**
My PR is a:
🐛 Bug fix #1785

Main update on the:
Plugin

Set the same password requirements when registering a user

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Related Issue: https://github.com/strapi/strapi/issues/1785

File: packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js [hunk 1]
```diff
@@ -75,7 +75,13 @@ export class AuthPage extends React.Component { // eslint-disable-line react/pre
         acc.push({ name: key, errors: [{ id: 'components.Input.error.validation.required' }] });
       }
 
+      console.log(this.props.modifiedData.password.length);
```
Comment (lauriejim) [inline packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js]: Log to remove
