### PR TITLE
fix: relativeURLs fail with appendSearchParamsToUrl

### LINKED ISSUE #17931: Media library broken - strapi 4.13.2
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.7.1
- Strapi version: 4.13.2
- Database: Mysql
- Operating system: Debian
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I open the media library, I get a white page and the following error
> TypeError: Failed to construct 'URL': Invalid URL

### Expected behavior

The media library page should appear.

### Screenshots

スクリーンショット 2023-09-05 12 02 33

スクリーンショット 2023-09-05 11 13 33

### Additional context

| Command | Result |
| --- | --- |
| `npx strapi develop --watch-admin` | works fine |
| `npx strapi develop` | broken |
| `npx strapi build --no-optimization && npx strapi develop --no-build` | broken |

No change after deleting .cache and dist folders.

----

Updates:
In my data, all the `files.url` values in the database start with a slash.
This appears to be the cause.

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* branches from #17955 – thanks @itsramiel for getting this started
* uses `window.strapi.backendURL` as a the baseURL for `URL` constructor

### Why is it needed?

* `URL` cannot take relative urls without a `baseUrl` argument
* imo I think this direction is perhaps better because we're not doing string manipulation and we're using web APIs still, there's also less code branches compared to the former PR

### How to test it?

* automated test

### Related issue(s)/PR(s)

* resolves #17931
* resolves CONTENT-1487
* closes #17955

### CODE REVIEW

File: packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js [hunk 1]
```diff
@@ -6,15 +6,15 @@
  * @returns {String} A string representing the URL with the search params appended
  */
 const appendSearchParamsToUrl = ({ url, params }) => {
-  if (url === undefined || params === undefined || typeof params !== 'object' || Object.entries(params).length === 0) {
+  if (url === undefined || typeof params !== 'object') {
     return url;
   }
```
Comment (gu-stav) [inline packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js:11]: Should we move this check outside the helper and only call it, when url is defined? Would make it even cleaner imo.

**Review by gu-stav — COMMENTED** [review]
Just a minor comment. Nice tests!

File: packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js (hunk 1 above)
Comment (joshuaellis) [reply packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js:11]: i can't think of a scenario where url would not be defined, but my only case not to move it outside is that URL throws if you pass it undefined, so given our current issues, it might be safer to keep it inside... what do you think?

Comment (gu-stav) [reply packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js:11]: I was thinking `appendSearchParamsToUrl` should add the passed params to the URL, so there is no point in calling it, if there is no URL, so I'd have catched that outside to make the util itself lighter. In case url is empty I'd instead throw an error.

But both ways are fine - it's just different styles of programming. I'll approve it.

**Review by gu-stav — APPROVED** [review]

File: packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js (hunk 1 above)
Comment (joshuaellis) [reply packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js:11]: oh yes i see, i think that's really interesting, I think there's a lot of space in upload to do all this work, i'm quite excited to move to TS because we can really discuss this and refine naming / function scope etc. 🤩

File: packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js [hunk 2]
```diff
@@ -6,15 +6,15 @@
...
 
-  const urlObj = new URL(url);
-  const urlParams = urlObj.searchParams;
+  const urlObj = new URL(url, window.strapi.backendURL);
```
Comment (Torsten85) [inline packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js:13]: in our instance (and I guess in many others) `window.strapi.backendURL` is an empty string, so it will still break for us right? This would work: `new URL(url, window.strapi.backendURL || window.location.origin)`

Comment (LeftoversTodayAppAdmin) [reply packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js:13]: Hey! I am on Strapi 4.25.1 and the code it breaks on for me still shows: 
const Rn = new URL(Ye,window.strapi.backendURL); and not the fix you are proposing. If we dont have the change you are proposing, what do I need to set in the .env file or config to get it working?
