### PR TITLE
Transfer assets to and from external providers

### LINKED ISSUE #15940: Import, Export, and Transfer Copy Data Between Different Media Providers on Sender and Receiver Side
### Required System information

- Node.js version: v18.14.2
- NPM version: 9.3.1
- Strapi version: 4.7.0
- Database: mysql => psql
- Operating system: Linux => Heroku
- Is your project Javascript or Typescript: JS

### Describe the bug

I am trying the new transfer feature as introduced in [v4.7.0](https://github.com/strapi/strapi/releases/tag/v4.7.0) (https://github.com/strapi/strapi/pull/15607). On the sender side my set-up is a mysql database instance of Strapi 4.7.0 with local file support. On the receiver side I am running a Strapi 4.7.0 instance in Heroku with postgres and Amazon AWS S3 bucket. The transfer is working perfectly without any problems reported on the console. Both content and files are transferred but the files are not stored in the AWS bucket but locally. If I am updating a file in Strapi, the updated file can be found in AWS bucket but not the original one after transfer.

### Steps to reproduce the behavior

1. Start transfer.
```sh
NODE_ENV=production yarn strapi transfer --to https://***/admin --to-token ***
```
grafik

2. On the receiver side, I see all files and I can download all of them
grafik

3. AWS Bucket is empty (unexpected)
grafik

4. Replaced files on the receiver side in the Strapi Media Library are stored in AWS bucket again. (expected)
grafik

### Expected behavior

All files end up in Amazon AWS S3 bucket after `yarn transfer` is completed.

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?

- Use the upload provider to upload assets
- Transfer assets to or from external providers

### Why is it needed?
- to be able to export, import or Transfer files from or to the different providers

### How to test it?
- try the transfer features (pull, push, import and export) with different upload providers (local provider, aws provider and cloudinary provider)
- you should be able too export assets from different providers
- you should be able to transfer your assets to your providers successfully

fixes #15940

### CODE REVIEW

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 1]
```diff
@@ -143,13 +149,16 @@ class LocalFileSourceProvider implements ISourceProvider {
...
             }
             return isFilePathInDirname('assets/uploads', filePath);
+            // isFilePathInDirname('assets/metadata', filePath)
           },
-          onentry(entry) {
+          async onentry(entry) {
             const { path: filePath, size = 0 } = entry;
             const normalizedPath = unknownPathToPosix(filePath);
             const file = path.basename(normalizedPath);
+            const metadata = await loadAssetMetadata(`assets/metadata/${file}.json`);
```
Comment (innerdvations) [inline packages/core/data-transfer/src/file/providers/source/index.ts:158]: Can we try/catch this and still support backups that don't include the metadata folder? And in those cases we would know it's all local media.

**Comment by derrickmehaffy** [comment]
Experimental release: `0.0.0-experimental.dd47104357263cea53dd63ad1ccbad38db09e848`

**Comment by derrickmehaffy** [comment]
Tested this today and I get an error (local project, local provider -> Strapi Cloud)
image

```json
{
  "name": "pr-17105",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "0.0.0-experimental.dd47104357263cea53dd63ad1ccbad38db09e848",
    "@strapi/plugin-users-permissions": "0.0.0-experimental.dd47104357263cea53dd63ad1ccbad38db09e848",
    "@strapi/plugin-i18n": "0.0.0-experimental.dd47104357263cea53dd63ad1ccbad38db09e848",
    "better-sqlite3": "8.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "5eba87d2-9e69-47ba-804f-343a5cea849a"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

image
image

**Comment by derrickmehaffy** [comment]
If needed, I can provide access to my cloud project, repo for the code is here: https://github.com/derrickmehaffy/strapi-test-v4-pr17105

File: packages/core/data-transfer/src/file/providers/destination/index.ts [hunk 2]
```diff
@@ -252,13 +252,22 @@ class LocalFileDestinationProvider implements IDestinationProvider {
         // always write tar files with posix paths so we have a standard format for paths regardless of system
         const entryPath = path.posix.join('assets', 'uploads', data.filename);
 
+        const entryMetadataPath = path.posix.join('assets', 'metadata', `${data.filename}.json`);
+        archiveStream.entry(
+          {
+            name: entryMetadataPath,
+            size: JSON.stringify(data.metadata).length,
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/destination/index.ts:259]: JSON.stringify is quite slow, you could improve that by only parsing once & reusing the result here & L261

File: packages/core/data-transfer/src/file/providers/source/index.ts [hunk 3]
```diff
@@ -143,13 +149,20 @@ class LocalFileSourceProvider implements ISourceProvider {
...
-          onentry(entry) {
+          async onentry(entry) {
             const { path: filePath, size = 0 } = entry;
             const normalizedPath = unknownPathToPosix(filePath);
             const file = path.basename(normalizedPath);
-
+            let metadata;
+            try {
+              metadata = await loadAssetMetadata(`assets/metadata/${file}.json`);
+            } catch (error) {
```
Comment (Convly) [inline packages/core/data-transfer/src/file/providers/source/index.ts:161]: Is this the handling of old backup files? If yes, we could emit a warning or info diagnostic to warn the user that we're attempting to read assets from an old export & it might have errors or so?

Comment (Convly) [reply packages/core/data-transfer/src/file/providers/source/index.ts:161]: Maybe something like "Failed to read metadata for filename, it might be because you're trying to import assets from an old file format or because the export file is corrupted. Strapi will try to fix this issue automatically" (or shorter, or longer, idk)

File: packages/core/data-transfer/src/strapi/providers/local-destination/index.ts [hunk 4]
```diff
@@ -78,6 +82,31 @@ class LocalStrapiDestinationProvider implements IDestinationProvider {
     return restore.deleteRecords(this.strapi, this.options.restore);
   }
 
+  async #deleteAllAssets() {
+    assertValidStrapi(this.strapi);
+
+    if (strapi.config.get('plugin.upload').provider === 'local') {
+      const uploadsDirectory = path.join(
+        this.strapi.dirs.static.public,
+        this.uploadsBackupDirectoryName
```
Comment (Convly) [inline packages/core/data-transfer/src/strapi/providers/local-destination/index.ts:91]: What if the backup directory name is ''? Will it try to delete the upload folder itself?

File: packages/core/data-transfer/src/strapi/providers/local-source/assets.ts [hunk 5]
```diff
@@ -1,32 +1,100 @@
...
 
-const IGNORED_FILES = ['.gitkeep'];
+function getFileStream(filepath: string, isLocal = false): PassThrough | ReadStream {
+  if (isLocal) {
+    return createReadStream(filepath);
+  }
 
+  const readableStream = new PassThrough();
+
+  https
```
Comment (Convly) [inline packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:15]: Why do we need this library?

File: packages/core/data-transfer/src/strapi/providers/local-source/assets.ts [hunk 6]
```diff
@@ -1,32 +1,100 @@
...
 /**
  * Generate and consume assets streams in order to stream each file individually
  */
 export const createAssetsStream = (strapi: Strapi.Strapi): Duplex => {
-  const assetsDirectory = join(strapi.dirs.static.public, 'uploads');
-
   const generator: () => AsyncGenerator<IAsset, void> = async function* () {
-    const files = await readdir(assetsDirectory);
-    const validFiles = files.filter((file) => !IGNORED_FILES.includes(file));
+    const files: IFile[] = await strapi.query('plugin::upload.file').findMany();
```
Comment (Convly) [inline packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:63]: Instead of querying all the files at once, why don't we stream them?

Comment (Convly) [reply packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:63]: Here's an old example of what I've done to make a POC for the cloud. It's not using the metadata, but maybe you can reuse some stuff about the streaming
```ts
import { Duplex, Readable } from 'stream';
import * as axios from 'axios';
​
import type { IAsset } from '../../../../types';
​
/**
 * Generate and consume assets streams in order to stream each file individually
 */
export const createAssetsStream = (strapi: Strapi.Strapi): Duplex => {
  const generator: () => AsyncGenerator<IAsset, void> = async function* () {
    const stream: Readable = strapi.db
      // Create a query builder instance (default type is 'select')
      .queryBuilder('plugin::upload.file')
      // Fetch all columns
      .select('*')
      // Get a readable stream
      .stream();
​
    for await (const file of stream) {
      const head = await (axios as any).head(file.url, { responseType: 'blob' });
      const res = await (axios as any).get(file.url, { responseType: 'stream' });
​
      yield {
        filename: file.name,
        filepath: `${file.name}.${file.ext}`,
        stream: res.data,
        stats: { size: parseInt(head.headers['content-length'], 10) },
      };
    }
  };
​
  return Duplex.from(generator());
};
```

**Review by Convly — COMMENTED** [review]
Nice work! Some questions :slightly_smiling_face:

File: packages/core/data-transfer/src/strapi/providers/local-source/assets.ts (hunk 5 above)
Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:15]: to get the a file form a en external provider

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 3 above)
Comment (Bassel17) [reply packages/core/data-transfer/src/file/providers/source/index.ts:161]: yeah we can do that, it will however always guess that it is a an old format automatically.

File: packages/core/data-transfer/src/strapi/providers/local-source/assets.ts (hunk 5 above)
Comment (Convly) [reply packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:15]: Sure, but why don't we reuse a library that we already have (like axios for instance) instead of going through a new one? Does this library do smth than the others don't?

Comment (Convly) [reply packages/core/data-transfer/src/strapi/providers/local-source/assets.ts:15]: Damn, I don't know why I was persuaded I saw this added to the package.json and thought "wtf is this new library?". My bad :bow:

File: packages/core/data-transfer/src/file/providers/source/index.ts (hunk 3 above)
Comment (Convly) [reply packages/core/data-transfer/src/file/providers/source/index.ts:160]: Damn, I forgot we are in the provider and currently don't have access to the engine diagnostic reporter...

I would avoid printing messages in the console from a provider. The log part should be handled by the implementation based on the diagnostic reports.

I don't think adding this ref between the engine & the provider is part of this PR. Maybe you can comment it & add a todo comment instead?

What do you think?

**Review by Convly — CHANGES_REQUESTED** [review]
It seems like tests are failing

**Review by Convly — DISMISSED** [review]

**Review by christiancp100 — DISMISSED** [review]

**Review by christiancp100 — APPROVED** [review]
