### PR TITLE
Harmonize secret generation + don't generate in production mode

### LINKED ISSUE #12088: Strapi v4 trying to create a .env file with some vars and platform.sh has a forceful read only file system (ROFS)
### Describe the bug

The problem is on boot, Strapi is trying to create a .env file with some vars and platform.sh has a forceful read-only file system (ROFS). So Strapi throws an error because it can't create the .env and it does not check if it already has the values before it tries to create it

### Steps to reproduce the behaviour

1. Create a new strapi v4 application with a Postgres DB
2. Deploy on [Platform.sh](https://platform.sh) in Production
3. After deployment run `platform app logs`
4. See the error in terminal

### Expected behaviour

The strapi application is expected to start successfully.

### Screenshots

screenshot

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12
- NPM version: v6
- Strapi version:  v4
- Database: Postgres
- Operating system: Linux

### PR DESCRIPTION
**Pull request by petersg83**
Fix #12088
FIX https://github.com/strapi/strapi/issues/12255

What's new :
- After the project creation `API_TOKEN_SALT` is not auto-generated anymore, an error is throw if the config is missing
- The use of env var `API_TOKEN_SALT` is deprecated. Strapi reads the salt value that is in `config/admin.js` first and, if not found, reads `API_TOKEN_SALT` and display a deprecated warning message.
- The env var `ADMIN_JWT_SECRET` is not generated in `config/admin.js` anymore
- `API_TOKEN_SALT` and `ADMIN_JWT_SECRET` are generated in the .env during the project creation and used only `config/admin.js`.
- `JWT_SECRET` is not auto-generated when in production mode anymore, an error is thrown

### CODE REVIEW

File: packages/core/admin/server/services/api-token.js [hunk 1]
```diff
@@ -74,20 +74,13 @@ const create = async attributes => {
...
-    return;
-  }
-
-  if (process.env.API_TOKEN_SALT) {
+const checkSaltIsDefined = () => {
+  if (!strapi.config.get('admin.apiToken.salt')) {
+    const secretExample = crypto.randomBytes(16).toString('base64');
     throw new Error(
-      `There's something wrong with the configuration of your api-token salt. If you have changed the env variable used in the configuration file, please verify that you have created and set the variable in your .env file.`
+      `Missing admin.apiToken.salt. Please set admin.apiToken.salt in config/admin.js (ex: ${secretExample})`
```
Comment (gu-stav) [inline packages/core/admin/server/services/api-token.js:81]: Since the value in `admin.apiToken.salt` defaults to the env variable, would it be more covenient to mention it here and add a link to the documentation for the admin configuration? This could also be a good place to explain what a `salt` actually is, since that might not be obvious.

File: packages/core/admin/server/services/token.js [hunk 2]
```diff
@@ -49,9 +49,22 @@ const decodeJwtToken = token => {
...
 };
 
+/**
+ * @returns {void}
+ */
+const checkSecretIsDefined = () => {
+  if (strapi.config.serveAdminPanel && !strapi.config.get('admin.auth.secret')) {
+    const secretExample = crypto.randomBytes(16).toString('base64');
+    throw new Error(
+      `Missing admin.auth.secret. Please set admin.auth.secret in config/admin.js (ex: ${secretExample})`
```
Comment (gu-stav) [inline packages/core/admin/server/services/token.js:59]: Same as above.

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 3]
```diff
@@ -27,7 +27,14 @@ module.exports = async ({ strapi }) => {
   await getService('users-permissions').initialize();
 
   if (!strapi.config.get('plugin.users-permissions.jwtSecret')) {
-    const jwtSecret = uuid();
+    const jwtSecret = crypto.randomBytes(16).toString('base64');
+
+    if (process.env.NODE_ENV === 'production') {
+      throw new Error(
+        `[Users & Permissions] Missing jwtSecret. Please set jwtSecret in your config or set environment variable JWT_SECRET (ex: ${jwtSecret}).`
```
Comment (gu-stav) [inline packages/plugins/users-permissions/server/bootstrap/index.js:34]: I think it might not be clear to which config you are referring to and therefore I'd suggest to either:

- mention the (file)-path of the config explicitly
- same as above: link to the proper jwt config section in the documentation

What do you think?

File: packages/core/admin/server/services/api-token.js (hunk 1 above)
Comment (petersg83) [reply packages/core/admin/server/services/api-token.js:81]: Actually the idea for me is to prevent the use of `API_TOKEN_SALT` as it is conflicting with the fact that you can set it in the config file too. The idea is to only use the config file.
I think I will propose to delete completely `API_TOKEN_SALT` (it's a breaking change, so we have to discuss it).

The recommended way to do would be that the user sets their own env var that they read in the config file :
```js
// config/admin.js
module.exports = ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
});

```

File: packages/plugins/users-permissions/server/bootstrap/index.js (hunk 3 above)
Comment (petersg83) [reply packages/plugins/users-permissions/server/bootstrap/index.js:34]: I agree, I'll modify it :) 
Regarding the link to documentation we can maybe wait the discussion with the doc team?

**Comment by derrickmehaffy** [comment]
@petersg83 shouldn't we also harmonize this taking the new refactored session middleware into account too and do the same

File: packages/core/admin/server/services/token.js [hunk 4]
```diff
@@ -49,9 +49,22 @@ const decodeJwtToken = token => {
...
 };
 
+/**
+ * @returns {void}
+ */
+const checkSecretIsDefined = () => {
+  if (strapi.config.serveAdminPanel && !strapi.config.get('admin.auth.secret')) {
+    const secretExample = crypto.randomBytes(16).toString('base64');
+    throw new Error(
+      `Missing auth.secret. Please set auth.secret in config/admin.js (ex: ${secretExample})`
```
Comment (derrickmehaffy) [inline packages/core/admin/server/services/token.js:59]: We shouldn't tell them to statically set the key in this file, they should use the environment variable.

File: packages/core/admin/server/services/api-token.js [hunk 5]
```diff
@@ -74,20 +74,13 @@ const create = async attributes => {
...
-    return;
-  }
-
-  if (process.env.API_TOKEN_SALT) {
+const checkSaltIsDefined = () => {
+  if (!strapi.config.get('admin.apiToken.salt')) {
+    const secretExample = crypto.randomBytes(16).toString('base64');
     throw new Error(
-      `There's something wrong with the configuration of your api-token salt. If you have changed the env variable used in the configuration file, please verify that you have created and set the variable in your .env file.`
+      `Missing apiToken.salt. Please set apiToken.salt in config/admin.js (ex: ${secretExample})`
```
Comment (derrickmehaffy) [inline packages/core/admin/server/services/api-token.js:81]: We shouldn't tell them to statically set the key in this file, they should use the environment variable.

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 6]
```diff
@@ -27,7 +27,14 @@ module.exports = async ({ strapi }) => {
   await getService('users-permissions').initialize();
 
   if (!strapi.config.get('plugin.users-permissions.jwtSecret')) {
-    const jwtSecret = uuid();
+    const jwtSecret = crypto.randomBytes(16).toString('base64');
+
+    if (process.env.NODE_ENV === 'production') {
+      throw new Error(
+        `[Users & Permissions] Missing jwtSecret. Please, in config/plugins.js, set config.jwtSecret for the users-permissions plugin or set environment variable JWT_SECRET (ex: ${jwtSecret}).`
```
Comment (derrickmehaffy) [inline packages/plugins/users-permissions/server/bootstrap/index.js:34]: We shouldn't tell them to statically set the key in this file, they should use the environment variable generally.

This message is better than the other two though

**Review by derrickmehaffy — DISMISSED** [review]

**Comment by petersg83** [comment]
I think it's already harmonized. The session keys are not auto-generated at startup. They are created only at the project creation and read and reexported in the config file.
We use only the config file and throw an error if the keys are missing in the config file.
Was it what you had in mind?

File: packages/plugins/users-permissions/server/bootstrap/index.js (hunk 6 above)
Comment (petersg83) [reply packages/plugins/users-permissions/server/bootstrap/index.js:34]: It doesn't work the same for this key, that's why. I'll change the message

**Comment by derrickmehaffy** [comment]
> I think it's already harmonized. The session keys are not auto-generated at startup. They are created only at the project creation and read and reexported in the config file. We use only the config file and throw an error if the keys are missing in the config file. Was it what you had in mind?

I was thinking we create the vars in the config file by default just like we are doing on the others and not just rely on the env vars but maybe I was missing something

**Comment by petersg83** [comment]
Not anymore :)

File: examples/kitchensink/config/server.js [hunk 7]
```diff
@@ -1,10 +1,8 @@
 module.exports = ({ env }) => ({
   host: env('HOST', '0.0.0.0'),
   port: env.int('PORT', 1337),
-  admin: {
-    auth: {
-      secret: env('ADMIN_JWT_SECRET', '6f75e424d1a0307077c294fcc3c7d78d'),
-    },
+  app: {
```
[the remark this answers is not in the document]
Comment (petersg83) [reply examples/kitchensink/config/server.js:4]: No, the kitchensink example was not correctly updated with the V4 config I think

[the remark this answers is not in the document]
Comment (alexandrebodin) [reply examples/kitchensink/config/server.js:4]: I see app.keys twice in the file now though

File: packages/core/admin/server/services/api-token.js [hunk 8]
```diff
@@ -74,20 +74,21 @@ const create = async attributes => {
...
  * @returns {void}
  */
-const createSaltIfNotDefined = () => {
-  if (strapi.config.get('admin.apiToken.salt')) {
-    return;
+const checkSaltIsDefined = () => {
+  if (!strapi.config.get('admin.apiToken.salt')) {
+    // TODO V5: stop reading API_TOKEN_SALT
+    if (process.env.API_TOKEN_SALT) {
+      process.emitWarning(`[deprecated] In future versions Strapi will stop reading directly the env variable API_TOKEN_SALT. Please set apiToken.salt in config/admin.js instead.
```
Comment (gu-stav) [inline packages/core/admin/server/services/api-token.js:81]:
```suggestion
      process.emitWarning(`[deprecated] In future versions, Strapi will stop reading directly from the environment variable API_TOKEN_SALT. Please set apiToken.salt in config/admin.js instead.
```

File: packages/core/admin/server/services/token.js [hunk 9]
```diff
@@ -49,9 +49,23 @@ const decodeJwtToken = token => {
...
 
+/**
+ * @returns {void}
+ */
+const checkSecretIsDefined = () => {
+  if (strapi.config.serveAdminPanel && !strapi.config.get('admin.auth.secret')) {
+    const secretExample = crypto.randomBytes(16).toString('base64');
+    throw new Error(
+      `Missing auth.secret. Please set auth.secret in config/admin.js (ex: ${secretExample}).
+For security reasons, prefere storing the secret in a environment variable. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`
```
Comment (gu-stav) [inline packages/core/admin/server/services/token.js:60]:
```suggestion
For security reasons, prefer storing the secret in an environment variable. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`
```

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 10]
```diff
@@ -28,7 +28,15 @@ module.exports = async ({ strapi }) => {
   await getService('users-permissions').initialize();
 
   if (!strapi.config.get('plugin.users-permissions.jwtSecret')) {
-    const jwtSecret = uuid();
+    const jwtSecret = crypto.randomBytes(16).toString('base64');
+
+    if (process.env.NODE_ENV === 'production') {
+      throw new Error(
+        `[Users & Permissions] Missing jwtSecret. Please, in config/plugins.js, set config.jwtSecret for the users-permissions plugin or set environment variable JWT_SECRET (ex: ${jwtSecret}).
```
Comment (gu-stav) [inline packages/plugins/users-permissions/server/bootstrap/index.js:35]:
```suggestion
        `Missing jwtSecret. Please, set jwtSecret for the users-permissions plugin in config/plugins.js or set environment variable JWT_SECRET (ex: ${jwtSecret}).
```

File: packages/core/admin/server/services/api-token.js [hunk 11]
```diff
@@ -74,20 +74,21 @@ const create = async attributes => {
...
+For security reasons, keep storing the secret in a environment variable and use env() to read it in config/admin.js (ex: \`apiToken: { salt: env('API_TOKEN_SALT') }\`). See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`);
+      strapi.config.set('admin.apiToken.salt', process.env.API_TOKEN_SALT);
+    } else {
+      const secretExample = crypto.randomBytes(16).toString('base64');
+      throw new Error(
+        `Missing apiToken.salt. Please set apiToken.salt in config/admin.js (ex: ${secretExample}).
+For security reasons, prefere storing the secret in a environment variable. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`
```
Comment (gu-stav) [inline packages/core/admin/server/services/api-token.js:88]:
```suggestion
For security reasons, prefer storing the secret in an environment variable. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`
```

File: packages/core/admin/server/services/api-token.js [hunk 12]
```diff
@@ -74,20 +74,21 @@ const create = async attributes => {
...
  */
-const createSaltIfNotDefined = () => {
-  if (strapi.config.get('admin.apiToken.salt')) {
-    return;
+const checkSaltIsDefined = () => {
+  if (!strapi.config.get('admin.apiToken.salt')) {
+    // TODO V5: stop reading API_TOKEN_SALT
+    if (process.env.API_TOKEN_SALT) {
+      process.emitWarning(`[deprecated] In future versions Strapi will stop reading directly the env variable API_TOKEN_SALT. Please set apiToken.salt in config/admin.js instead.
+For security reasons, keep storing the secret in a environment variable and use env() to read it in config/admin.js (ex: \`apiToken: { salt: env('API_TOKEN_SALT') }\`). See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`);
```
Comment (gu-stav) [inline packages/core/admin/server/services/api-token.js:82]:
```suggestion
For security reasons, keep storing the secret in an environment variable and use env() to read it in config/admin.js (ex: \`apiToken: { salt: env('API_TOKEN_SALT') }\`). See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`);
```

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 13]
```diff
@@ -28,7 +28,15 @@ module.exports = async ({ strapi }) => {
...
+For security reasons, prefere storing the secret in a environment variable. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`
```
Comment (gu-stav) [inline packages/plugins/users-permissions/server/bootstrap/index.js:36]:
```suggestion
For security reasons, prefer storing the secret in an environment variable. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.`
```

File: packages/plugins/users-permissions/server/bootstrap/index.js [hunk 14]
```diff
@@ -28,7 +28,15 @@ module.exports = async ({ strapi }) => {
   await getService('users-permissions').initialize();
 
   if (!strapi.config.get('plugin.users-permissions.jwtSecret')) {
-    const jwtSecret = uuid();
+    const jwtSecret = crypto.randomBytes(16).toString('base64');
+
+    if (process.env.NODE_ENV === 'production') {
+      throw new Error(
+        `Missing jwtSecret. Please, set jwtSecret for the users-permissions plugin in config/plugins.js or set environment variable JWT_SECRET (ex: ${jwtSecret}).
```
Comment (alexandrebodin) [inline packages/plugins/users-permissions/server/bootstrap/index.js:35]: I think we have a bit of inconsistency here. 
For API_TOKEN_SALT we deprecated just setting the env var but not for JWT_SECRET. Is there a specific reason I forgot  about 

I think this might create some confusion in the future, wdyt?

File: packages/core/admin/server/services/token.js [hunk 15]
```diff
@@ -49,9 +49,23 @@ const decodeJwtToken = token => {
   }
 };
 
+/**
+ * @returns {void}
+ */
+const checkSecretIsDefined = () => {
+  if (strapi.config.serveAdminPanel && !strapi.config.get('admin.auth.secret')) {
```
Comment (alexandrebodin) [inline packages/core/admin/server/services/token.js:56]: should we generate one in memory in dev mode like with the jwtSecret?

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
I would avoid using the crypto.randomBytes for examples as it just contributes to slower startups could we just use a static value ?

File: packages/plugins/users-permissions/server/bootstrap/index.js (hunk 14 above)
Comment (petersg83) [reply packages/plugins/users-permissions/server/bootstrap/index.js:35]: It's because JWT_SECRET is auto-generated at start-up when in dev mode. Whereas the other are created when the project is created.
However I can change the error message to only mention the config file and not the env var.

**Comment by alexandrebodin** [comment]
> When you say the examples, you refer to the error message? If yes, does it matter to be a bit slower since we will throw anyway?

I think it matters more to display an explicit example lie `thisIsASecret. You can generate one using crypt......` rather than using an actual one. Might just be a matter of opinion but I think people are a lot more used to those fake explicit values

File: packages/plugins/users-permissions/server/bootstrap/index.js (hunk 14 above)
Comment (alexandrebodin) [reply packages/plugins/users-permissions/server/bootstrap/index.js:36]: Hum then I think there are some changes to do with the generation of the env var too. 

It should only happen in dev mode (right now we generate every time it's not prod, I would generate only if it's dev and throw if node_env is not dev)

And Yeah I think we should not mention the JWT_SECRET it self if we want to be as consistent as possible 🤔

Comment (petersg83) [reply packages/plugins/users-permissions/server/bootstrap/index.js:36]: So you would just change that:
```diff
-    if (process.env.NODE_ENV === 'production') {
+    if (process.env.NODE_ENV !== 'development') {
```
?

**Review by alexandrebodin — APPROVED** [review]
LGTM

**Review by gu-stav — APPROVED** [review]
