### PR TITLE
Front/repeatable field create

### LINKED ISSUE #3717: Reserved "id" model's field name collision
Hi,

Using a field name of "id" inside an sql relation is allow, but collides with the auto-generated one at ORM/SQL layer.

**Steps to reproduce the behavior**
Add a new content type.
Add a new field to it.
Use "id" as a field name.

**Expected behavior**
We may, at the most basic point, provide an extra logic inside react input to invalidate "id" string submission. That's just a quick fix. We may add an extra block of logic at model generator/updator layer . I'm new to strapi, no dev env set, I've just completed the quick start guide for now. If someone can provide insights about location and a bit of core logic I would handle one of the solutions with a bit of time.

**Logs**
```
{ [Error: SQLITE_ERROR: duplicate column name: id] errno: 1, code: 'SQLITE_ERROR' }
[2019-08-02T07:50:12.209Z] debug ⛔️ Server wasn't able to start properly.
[2019-08-02T07:50:12.210Z] error Error: SQLITE_ERROR: duplicate column name: id
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utilisateur\AppData\Roaming\npm-cache\_logs\2019-08-02T07_50_12_248Z-debug.log
```

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.14
- Database: Sqlite
- Operating system: Win 64 or GNU/Linux Debian

PS vraiment top de voir une initiative Française. Bonne journée !

### PR DESCRIPTION
**Pull request by virginieky**
#### Description of what you did:
Group Relation field CRUD

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix #3717 
- [ ] 💅 Enhancement
- [X] 🚀 New feature

#### Main update on the:

- [ ] Admin
- [ ] Documentation
- [X] Framework
- [ ] Plugin

#### Manual testing done on the following databases:

- [X] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

File: packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/index.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+import StyledRelationBox from './StyledRelationBox';
+import FeaturePicker from '../FeaturePicker';
+
+const RelationBox = ({
+  autoFocus,
+  didCheckErrors,
+  errors,
+  featureName,
+  features,
+  main,
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/index.js]: `isMain` check out this [rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/boolean-prop-naming.md)

File: packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/index.js [hunk 2]
```diff
@@ -0,0 +1,90 @@
+import React from 'react';
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/index.js]: `import React, { memo } from 'react';`

File: packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/index.js [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+  nature: PropTypes.string,
+  onChange: PropTypes.func.isRequired,
+  onClick: PropTypes.func,
+  plugin: PropTypes.string,
+  selectedFeature: PropTypes.string,
+  source: PropTypes.string,
+  value: PropTypes.string.isRequired,
+};
+
+export default RelationBox;
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/index.js]: `export default memo(RelationBox);`

File: packages/strapi-plugin-content-type-builder/admin/src/components/FeaturePicker/index.js [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+};
+
+FeaturePicker.propTypes = {
+  features: PropTypes.array,
+  onClick: PropTypes.func,
+  plugin: PropTypes.string,
+  selectedFeature: PropTypes.string,
+};
+
+export default FeaturePicker;
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/FeaturePicker/index.js]: `export default memo(FeaturePicker);`

File: packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/tests/index.test.js [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+
+    const span = wrapper
+      .find('p')
+      .at(0)
+      .find('span');
+
+    expect(span.text()).toContain('users-permissions');
+  });
+
+  it('target value should not be value if nature is oneWay or manyWay', () => {
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/RelationBox/tests/index.test.js]: it(`should return '-' for the target's value if the nature is either oneWay or manyWay`, () => {})

File: packages/strapi-plugin-content-type-builder/admin/src/components/RelationNaturePicker/index.js [hunk 6]
```diff
@@ -0,0 +1,77 @@
+import React from 'react';
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/RelationNaturePicker/index.js]: you can use `memo` in this file too.

File: packages/strapi-plugin-content-type-builder/admin/src/components/RelationNaturePicker/index.js [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+                onClick={() => onClick(iconName, featureName)}
+                src={src}
+                alt={iconName}
+              />
+            );
+          })}
+        </div>
+        <div className="nature-txt">
+          <span>{truncate(leftName, { length: 24 })}</span>
+          &nbsp; <FormattedMessage id={`${pluginId}.relation.${nature}`} />{' '}
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/components/RelationNaturePicker/index.js]: Why is the space needed after `FormattedMessage`?

File: packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js [hunk 8]
```diff
@@ -631,16 +724,28 @@ export const formatModelAttributes = attributes =>
...
-    return acc.concat(attribute);
+    if (
+      attributes[current].nature === 'oneWay' ||
+      attributes[current].nature === 'manyWay'
+    ) {
+      const attribute = Object.assign(attributes[current], {
+        key: '-',
+        name: current,
+      });
+      return acc.concat(attribute);
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js]: Can you add extra lines before your return statements?

File: packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js [hunk 9]
```diff
@@ -631,16 +724,28 @@ export const formatModelAttributes = attributes =>
...
+    }
   }, []);
 
 export const formatGroupAttributes = attributes => {
   const formattedAttributes = attributes.reduce((acc, current) => {
-    acc[current.name] = current;
-    delete current['name'];
+    const name = current['name'];
+    let newAttribute = { ...current };
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js]: `const newAttribute`

File: packages/strapi-plugin-content-type-builder/admin/src/containers/App/index.js [hunk 10]
```diff
@@ -133,22 +133,9 @@ export class App extends React.Component {
       return newGroup;
     }
 
-    return get(
-      modifiedDataGroup,
-      [this.getFeatureNameFromSearch(), 'schema'],
-      {}
-    );
+    return get(modifiedDataGroup, this.getFeatureNameFromSearch(), {}, {});
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/App/index.js]: `return get(modifiedDataGroup, this.getFeatureNameFromSearch(), {});` the third argument is not needed here. https://lodash.com/docs/4.17.15#get

File: packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/index.js [hunk 11]
```diff
@@ -245,7 +257,8 @@ export class GroupPage extends React.Component {
       emitEvent('willEditFieldOfGroup');
 
       push({
-        search: `modalType=attributeForm&attributeType=${attributeType}&settingType=base&actionType=edit&attributeName=${attributeIndex}`,
+        search: `modalType=attributeForm&attributeType=${attributeType ||
+          'relation'}&settingType=base&actionType=edit&attributeName=${attributeIndex}`,
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/index.js]: shouldn't it be `attributeIndex` instead of `attributeName`?

File: packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/RelationBox.js [hunk 12]
```diff
@@ -53,11 +53,13 @@ const RelationBox = ({
...
             label="Field Name"
-            disabled={value === '-' || nature === 'oneWay'}
+            disabled={
+              value === '-' || nature === 'oneWay' || nature === 'manyWay'
+            }
             name={main ? 'name' : 'key'}
             onChange={onChange}
             type="text"
-            value={nature === 'oneWay' ? '-' : value}
+            value={nature === 'oneWay' || nature === 'manyWay' ? '-' : value}
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/RelationBox.js]: It seems like you have two RelationBox components? Can't you use the same one?

File: packages/strapi-plugin-content-type-builder/admin/src/containers/RelationFormGroup/index.js [hunk 13]
```diff
@@ -0,0 +1,393 @@
+/**
+ *
+ * RelationFormGroup
+ *
+ */
+
+import React from 'react';
```
Comment (soupette) [inline packages/strapi-plugin-content-type-builder/admin/src/containers/RelationFormGroup/index.js]: This component seems very similar (at the code level not sure about the ui) so if the ui doesn't differ much from the relations modal don't you think it would be great to make the relation form smarter so it can handle both. It's not a hurry but I think it could be great in an update at some point.

File: packages/strapi-plugin-content-type-builder/admin/src/components/FeaturePicker/index.js [hunk 14]
```diff
@@ -0,0 +1,63 @@
+import React from 'react';
```
[the remark this answers is not in the document]
Comment (virginieky) [reply packages/strapi-plugin-content-type-builder/admin/src/components/FeaturePicker/index.js]: When react-testing-library is available, I'll change it and update tests

File: packages/strapi-plugin-content-type-builder/admin/src/containers/RelationFormGroup/index.js (hunk 13 above)
Comment (virginieky) [reply packages/strapi-plugin-content-type-builder/admin/src/containers/RelationFormGroup/index.js]: You're right. They are very similar but some little things are different for now so I note to change it asap for it to handle both.

File: packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/RelationBox.js (hunk 12 above)
Comment (virginieky) [reply packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/RelationBox.js]: Will use the same when RelationFormGroup and RelationForm are the same

Comment (soupette) [reply packages/strapi-plugin-content-type-builder/admin/src/containers/RelationForm/RelationBox.js]: Seems to me they are pretty much the same. We will use the same one in another PR.
