### PR TITLE
fix(content-manager): reduce over-populated localizations and metadata

### LINKED ISSUE #24504: Content Manager over-populates localizations and metadata causing large payloads and slow admin UI
### Node Version

v22.12.0

### NPM/Yarn/PNPM Version

NPM 10.9.0

### Strapi Version

5.24.1

### Operating System

Strapi Cloud

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Summary
The Content Manager endpoints over-populate the `localizations` relation and include heavy `meta.availableLocales` by default. This produces large payloads and slow admin UI, especially with many locales and deep relations. Limiting the populated localization fields and disabling `availableLocales` where not needed yields substantial improvements.

### Steps to Reproduce

1. Use a localized collection type with dynamic zones/components and many entries. Ensure `i18n` and Draft & Publish are enabled. Create ~20 different documents with lots of content and translations
2. In the CM:
   - List view: Loads very slowly and the payload of the API response can be multiple MB's. For each document it contains all the translations with all the content in them which leads to the large payload.
   - Single entry view: Documents contain deeply nested data for translated versions of the document and `meta.availableLocales` object again with deeply nested data. This is most likely not needed

### Actual Behavior (example from our production data)
- List view payloads: ~3 MB
- Single item payloads: ~700 KB
- Admin UI loads slowly.
- With DB debug logging enabled, we see about 700 db queries to load the List View with 10 documents

### Expected Behavior

- Admin responses should not deep-populate `localizations` by default.
- `availableLocales` should be opt-in or minimal, and only included when explicitly requested by the client (e.g., via a query parameter), not in every entry fetch.
- probably other localization specific improvements which don't fetch translations unless needed

### Logs

```shell

```

### Code Snippets

_No response_

### Media

_No response_

### Proposed Improvements
1. Default populate rules for `localizations` in CM endpoints should return minimal identifiers (`id`, `locale`, `documentId`) unless deeper data is explicitly needed/requested.
2. Make `meta.availableLocales` opt-in (e.g., controlled by a query parameter) and avoid computing/sending it by default.
3. Consider a configuration option in CM to control localization population depth and metadata inclusion if there's a use case for it.

### Results (in case the proposal is implemented):
- List view: 3 MB → ~100 KB
- Single item: 700 KB → ~100 KB
- Noticeably faster CM load and potentially persist times. -> a lot happier customers since they don't need to wait

### Notes
- We can share a minimal reproduction or diffs illustrating the controller-level changes that produced these improvements.
- A simple way to reproduce this is to use one of the example projects, enable ~10-20 locales, create the documents, manually fill the translations and inspect the response body of the api calls that these views execute. You can see the data returned contains all the translated content which is overkill and has massive impact in case of large documents with many translations
- As far as I understand strapi and how it persists on save, all the submitted data is sent and persisted again. Therefore it consumes a lot of ressources on the database although it's not needed since there will never be a change in the localized content like this.

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by markkaylor**
### What does it do?
Reduces the amount of data populated for the localizations relation and meta.availableLocales in Content Manager responses.

- Adds withPopulateOverrids to the populate builder. Only populates minimal localization fields for content manager.
- Updates the bulk locale publish dialog to only validate the current document locale client-side, since other locales no longer carry full data. Server-side validation still applies during the actual publish.

### Why is it needed?
When a content type uses i18n with dynamic zones/components and has many locales, the CM endpoints deeply populate every localization and include heavy availableLocales metadata. This causes multi-MB payloads and hundreds of extra DB queries, making the admin panel very slow.

On develop
Screenshot 2026-02-25 at 15 16 23

This branch
Screenshot 2026-02-25 at 15 23 13

### How to test it?

I recommend you first reproduce the issue on develop and then come to this branch to see the fix

1. Enable the i18n plugin and add 10+ locales.
2. Create a localized collection type with dynamic zones or components.
3. Create several documents and fill in translations for each locale.
4. Open the Content Manager list view and single entry view.
5. Inspect the network responses — payloads should be significantly smaller (localizations should only contain locale, documentId, publishedAt, updatedAt instead of full nested content).
6. Verify the locale switcher and bulk locale publish still work correctly.

resolves #24504

### CODE REVIEW

**Comment by innerdvations** [comment]
It feels like we're adding an extra layer of indirection when we could use the existing populate param and just pre-build it with the right shape for `localizations` where we need it.

Basically, keep the isLocalized guard so we only do localizations handling for localized types.

Then for list/find, pre-build the populate with the right localizations shape: add a builder step that merges overrides into the initial populate (e.g. `withPopulate({ localizations: { fields: ['locale', 'documentId', 'publishedAt', 'updatedAt'] } })`) and use that where we currently call `.populateLocalizationsMode('minimal')`. The existing "if initialPopulate use it" in populate.ts will pick it up.

I might be missing something though, but that was my first thought

**Comment by markkaylor** [comment]
> It feels like we're adding an extra layer of indirection when we could use the existing populate param and just pre-build it with the right shape for `localizations` where we need it.
> 
> Basically, keep the isLocalized guard so we only do localizations handling for localized types.
> 
> Then for list/find, pre-build the populate with the right localizations shape: add a builder step that merges overrides into the initial populate (e.g. `withPopulate({ localizations: { fields: ['locale', 'documentId', 'publishedAt', 'updatedAt'] } })`) and use that where we currently call `.populateLocalizationsMode('minimal')`. The existing "if initialPopulate use it" in populate.ts will pick it up.
> 
> I might be missing something though, but that was my first thought

I think I see what you mean, nice suggestion! That could simplify a lot and make this a more flexible override populate system, not just a "let's handle localizations", I'll explore it tomorrow

File: packages/core/content-manager/server/src/services/populate-builder.ts [hunk 1]
```diff
@@ -57,6 +57,18 @@ const populateBuilder = (uid: UID.Schema) => {
...
 
+    /**
+     * Override the populate for specific attributes, taking precedence over
+     * query-derived or deep populate defaults.
+     *
+     * @param overrides - Populate overrides to merge (e.g. { localizations: { fields: ['locale'] } })
+     */
+    withPopulateOverride(overrides: Record<string, any>) {
+      const prev = getInitialPopulate;
+      getInitialPopulate = async () => merge((await prev()) || {}, overrides);
```
Comment (innerdvations) [inline packages/core/content-manager/server/src/services/populate-builder.ts:69]:
```suggestion
      // merge(base, overrides): overrides win for overlapping keys, so e.g. localizations
      // from the override replaces any query/deep default
      getInitialPopulate = async () => merge((await prev()) || {}, overrides);
```

Comment (innerdvations) [reply packages/core/content-manager/server/src/services/populate-builder.ts:69]: since it's a bit confusing

**Comment by derrickmehaffy** [comment]
exp build: https://github.com/strapi/strapi/actions/runs/22680015469
