### PR TITLE
Fix enumeration detection for GraphQL

### LINKED ISSUE #1383: Enum with GraphQL, Server Fails to start
**Informations**
- **Node.js version**: v10.4.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: 10.2-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

Using MySQL and installing the graphql plugin, create a model with a defined enum type. 

After attempting to start the server I am given the following error: 

```
(node:62621) UnhandledPromiseRejectionWarning: Error: Type "ENUM_BODY_EDSMTYPE" not found in document.
    at ASTDefinitionBuilder._resolveType (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:134:11)
    at ASTDefinitionBuilder.buildType (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:218:79)
    at ASTDefinitionBuilder._buildWrappedType (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:227:24)
    at ASTDefinitionBuilder.buildField (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:248:18)
    at /srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:302:21
    at /srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/jsutils/keyValMap.js:28:31
    at Array.reduce (<anonymous>)
    at keyValMap (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/jsutils/keyValMap.js:27:15)
    at ASTDefinitionBuilder._makeFieldDefMap (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:299:49)
    at fields (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/utilities/buildASTSchema.js:284:23)
    at resolveThunk (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/definition.js:370:40)
    at defineFieldMap (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/definition.js:532:18)
    at GraphQLObjectType.getFields (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/definition.js:506:44)
    at typeMapReducer (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/schema.js:232:38)
    at /srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/schema.js:239:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/schema.js:232:51)
    at /srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/schema.js:239:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/schema.js:232:51)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/srv/API/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/type/schema.js:122:28)
```

**Steps to reproduce the problem**

Install Graphql and create a model with the enum value type, attempt to start the server.

**What is the expected behavior?**

NA - Error Message (that shouldn't happen lol)

**Note**
After removing the graphql plugin the server starts fine.

Related PR: https://github.com/strapi/strapi/pull/1288

My Strapi Repo for in depth testing: https://github.com/canonn-science/CAPIv2-Strapi/tree/development (Its big, I know)

### PR DESCRIPTION
**Pull request by johannpinson**
My PR is a:
🐛 Bug fix

Main update on the:
Plugin

Fix #1383 
cc: @lauriejim

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Getting a syntax error manually applying this

```
(node:9627) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected Name, found (
    at syntaxError (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expect (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:1299:32)
    at parseName (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:92:15)
    at parseEnumValueDefinition (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:956:14)
    at many (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:1350:16)
    at parseEnumValuesDefinition (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:945:50)
    at parseEnumTypeDefinition (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:930:16)
    at parseTypeSystemDefinition (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:669:16)
    at parseDefinition (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:143:16)
    at parseDocument (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/node_modules/graphql/language/parser.js:38:10)
    at Object.addPolymorphicUnionType (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/services/GraphQL.js:793:27)
    at Object.generateSchema (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/services/GraphQL.js:712:58)
    at Function.initialize (/mnt/nixstorage/Github/CAPIv2-Strapi/plugins/graphql/hooks/graphql/index.js:103:62)
    at /mnt/nixstorage/Github/CAPIv2-Strapi/node_modules/strapi/lib/hooks/index.js:20:31
    at after (/mnt/nixstorage/Github/CAPIv2-Strapi/node_modules/strapi/lib/hooks/index.js:126:39)
    at /mnt/nixstorage/Github/CAPIv2-Strapi/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (/mnt/nixstorage/Github/CAPIv2-Strapi/node_modules/strapi/lib/hooks/index.js:137:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at loadedModule.initialize.call.err (/mnt/nixstorage/Github/CAPIv2-Strapi/node_modules/strapi/lib/hooks/index.js:33:14)
```

File: packages/strapi-plugin-graphql/services/GraphQL.js [hunk 1]
```diff
@@ -486,7 +486,7 @@ module.exports = {
 
       // Detect enum and generate it for the schema definition
       const enums = Object.keys(model.attributes)
-        .filter(definition => definition.type === 'enumeration')
+        .filter(attribute => model.attributes[attribute].type === 'enumeration')
```
Comment (kamalbennani) [inline packages/strapi-plugin-graphql/services/GraphQL.js]: What do you think about this lodash's version ?

```JS
const enums = _.chain(model.attributes)
  .filter({ type: 'enumeration' })
  .map((definition, attribute) => {
    ...
  })
  .value()
````

Comment (derrickmehaffy) [reply packages/strapi-plugin-graphql/services/GraphQL.js]: @lauriejim @Aurelsicoko thoughts? I don't know how this bit functions to debug it.

Comment (johannpinson) [reply packages/strapi-plugin-graphql/services/GraphQL.js]: @kamalbennani as said @Aurelsicoko (cf. https://github.com/strapi/strapi/pull/1275#pullrequestreview-123560796), I share with him the goal to not use lodash because ES6 and next are really efficient now and it allow to use "simpler" functions to iterate some data (and it also avoid some of us to go to the lodash docs to know what make some mysterious functions).

**Comment by derrickmehaffy** [comment]
PR is fine @Aurelsicoko and @lauriejim the issue was with my environment. GraphQL does not allow spaces and special chars in enum values. Hence the syntax error was due to one of my enum values.
