### PR TITLE
fix: disable lifecycle hooks on transfers [v4]

### LINKED ISSUE #19383: DTS Transfer/export/import Does Not Disable Lifecycle Hook
### Required System information

- Node.js version:   18.18.0
- NPM version:        9.8.1
- Strapi version:      4.19.0
- Database:             Sqlite
- Operating system:  Mac OS
- Is your project Javascript or Typescript: No

### Describe the bug
DTS Transfer Does Not Disable Lifecycle Hook when importing data leading to errors depending on how those lifecycles are written

### Steps to reproduce the behavior

1. Create a content-type
2. Create a lifecycle that does something unique such as setting a relationship that may not exist yet during transfer
3. See error

### Expected behavior

Much like we do with HTTP timeouts we should probably disable lifecycles during the transfer then re-enable them once transfer is complete

### Screenshots

N/A

### Code snippets

Will add if we find some good examples

### Additional context

Reported via community office hours in Discord

### PR DESCRIPTION
**Pull request by Bassel17**
### What does it do?
- disable lifecycle hooks during a transfer
enable them back again after a transfer

### Why is it needed?
- prevent lifecycle hooks from being triggered during transfer operations

### How to test it?
- during a transfer or import or export lifecycle hooks should not be triggered

### Related issue(s)/PR(s)

fixes #19383

### CODE REVIEW

File: packages/core/data-transfer/src/strapi/providers/local-destination/index.ts [hunk 1]
```diff
@@ -102,7 +102,8 @@ class LocalStrapiDestinationProvider implements IDestinationProvider {
   async close(): Promise<void> {
     const { autoDestroy } = this.options;
     this.transaction?.end();
-
+    assertValidStrapi(this.strapi);
+    this.strapi.db.lifecycles.enable();
```
Comment (innerdvations) [inline packages/core/data-transfer/src/strapi/providers/local-destination/index.ts:106]: I haven't checked the code, but does this actually change something that could persist if this fails to run? Or is it just a nice thing to re-enable before shutting down the instance?

**Review by innerdvations — COMMENTED** [review]
Could end up in the situation where other users are relying on them running. What do you think about having a config setting that is checked?

File: packages/core/data-transfer/src/strapi/providers/local-destination/index.ts (hunk 1 above)
Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/local-destination/index.ts:106]: it does have to run, or else strapi has to restart to have lifecycle hooks enabled

Comment (Bassel17) [reply packages/core/data-transfer/src/strapi/providers/local-destination/index.ts:106]: or maybe not actually

**Comment by jhoward1994** [comment]
Not very familiar with this part of the code but I'm wondering if you need to make the same changes for remote destinations and sources?

e.g.
https://github.com/strapi/strapi/blob/c44172f3a1ca2b435f87478ad430530079c84443/packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts#L188-L189

**Comment by innerdvations** [comment]
> I'm not very familiar with this part of the code but I'm wondering if you need to make the same changes for remote destinations and sources?
> 
> e.g.
> 
> https://github.com/strapi/strapi/blob/c44172f3a1ca2b435f87478ad430530079c84443/packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts#L188-L189

I think the remote providers load up the local provider internally, so it should be fine. Is that right @Bassel17 ?

**Comment by Bassel17** [comment]
> LGTM, works well!

If you can take a look at the v5 one too, it's exactly the same @innerdvations https://github.com/strapi/strapi/pull/22651
