### PR TITLE
Fix missing validation error message on media field

### LINKED ISSUE #6123: Media field does not display validation errors
**Describe the bug**
Validation errors are not displayed for a media fields, so it is unclear for users what is wrong.

**Steps to reproduce the behavior**

1. Create a new collection type with media field required
2. Go to creation a new collection type
3. Click on `Save` button
4. See Media field

**Expected behavior**
Validation errors are displayed for media fields

**Screenshots**

Screenshot 2020-05-08 at 14 57 58

Screenshot 2020-05-08 at 13 44 45

Screenshot 2020-05-08 at 15 20 21

Screenshot 2020-05-08 at 14 55 13

**System**

- Node.js version: v12.16.0
- NPM version: v6.14.4
- Strapi version: v3.0.0-beta.20.1
- Database: mongo
- Operating system: macOS

**Additional context**
Dependencies list: 

```
"dependencies": {
    "axios": "0.19.0",
    "ckeditor4-react": "^1.1.0",
    "lodash": "^4.17.5",
    "strapi": "3.0.0-beta.20.1",
    "strapi-admin": "3.0.0-beta.20.1",
    "strapi-connector-mongoose": "3.0.0-beta.20.1",
    "strapi-plugin-content-manager": "3.0.0-beta.20.1",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.1",
    "strapi-plugin-email": "3.0.0-beta.20.1",
    "strapi-plugin-graphql": "^3.0.0-beta.20.1",
    "strapi-plugin-upload": "3.0.0-beta.20.1",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.1",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.20.1",
    "strapi-utils": "3.0.0-beta.20.1"
  }``,`

### PR DESCRIPTION
**Pull request by henrych4**
#### Description of what you did:
Fix #6123 by displaying error message when a required media field is missing on save.

### CODE REVIEW

File: packages/strapi-plugin-upload/admin/src/components/InputMedia/ErrorMessage.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import styled from 'styled-components';
+
+import { colors } from '@buffetjs/styles';
+
+const ErrorMessage = styled.p`
+  font-size: 1.3rem !important;
+  padding-top: 10px;
```
Comment (soupette) [inline packages/strapi-plugin-upload/admin/src/components/InputMedia/ErrorMessage.js:7]: In order to keep the baseline can you change the padding-top to `5px` in this component and add a `margin: 0;` property?

Also, could you update the `./Wrapper` component as follow so the baseline is kept in case of error:

```
import styled from 'styled-components';

const Wrapper = styled.div`
  margin-bottom: ${({ hasError }) => (hasError ? '1.7rem' : '2.3rem')};
`;

Wrapper.defaultProps = {
  hasError: false,
};

export default Wrapper;
```

File: packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js [hunk 2]
```diff
@@ -16,8 +16,9 @@ import InputModalStepper from '../../containers/InputModalStepper';
 import Name from './Name';
 import Wrapper from './Wrapper';
 import Input from '../Input';
+import ErrorMessage from './ErrorMessage';
 
-const InputMedia = ({ label, onChange, name, attribute, value, type }) => {
+const InputMedia = ({ label, onChange, name, attribute, value, type, id, error }) => {
```
Comment (soupette) [inline packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js:21]: The id and error props needs to be added to the `propTypes`.

Comment (soupette) [reply packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js:21]: Regarding the comment about the baseline could you add the following in this file:

```
import { get, isEmpty } from 'lodash';
// ...

return (
  <Wrapper hasError={!isEmpty(error)}>
   // ...
  </Wrapper>
);
```

File: packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js [hunk 3]
```diff
@@ -182,6 +186,8 @@ InputMedia.propTypes = {
   onChange: PropTypes.func.isRequired,
   type: PropTypes.string.isRequired,
   value: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
+  id: PropTypes.string.isRequired,
```
Comment (soupette) [inline packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js:189]: The `id` and `error` should be `PropTypes.string` 

You will need to add them to defaultProps:

```
InputMedia.propTypes = {
  attribute: PropTypes.shape({
    allowedTypes: PropTypes.arrayOf(PropTypes.string),
    multiple: PropTypes.bool,
    required: PropTypes.bool,
    type: PropTypes.string,
  }).isRequired,
  error: PropTypes.string,
  id: PropTypes.string,
  label: PropTypes.string,
  name: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired,
  type: PropTypes.string.isRequired,
  value: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
};

InputMedia.defaultProps = {
  id: null,
  error: null,
  label: '',
  value: null,
};
```

Comment (henrych4) [reply packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js]: Updated
