### PR TITLE
Check Mime or Ext are not nullish in useAsset hook

### LINKED ISSUE #16005: Media Library fails "cannot read properties of null (reading 'includes')
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.6.1
- Database: Sqlite
- Operating system: Debian 5.10.92-1
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Similar to #12761 clicking the media library crashes all of Strapi's front end and outputs the following errors:

```
TypeError: Cannot read properties of null (reading 'includes')
    at le (main.890a972d.js:1376:839)
    at Zl (main.890a972d.js:1744:54681)
    at Hc (main.890a972d.js:1748:9133)
    at Bc (main.890a972d.js:1748:989)
    at qc (main.890a972d.js:1748:917)
    at cu (main.890a972d.js:1748:768)
    at Iu (main.890a972d.js:1746:11068)
    at main.890a972d.js:1744:39503
    at n.unstable_runWithPriority (main.890a972d.js:1776:3795)
    at ta (main.890a972d.js:1744:39281)
```
This makes Strapi completely unusable.

### Steps to reproduce the behavior

1. Log in to Strapi.
2. Upload some media files to the Media Library.
3. Come back later and click the Media Library in the menu.
4. See a quick flash of the Media Library UI (without any user-provided content in it).
5. Crash to a white screen.

### Expected behavior

A working Media Library and some resilience on the front end to prevent user confusion.

### Screenshots

image
image

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Checks if the name of an asset is present and removes it from the list if not
* Checks if either `mime` or `ext` are nullish after fetching from the server and replaces with empty strings

### Why is it needed?

* Having no `name` errors the admin panel
* `mime` or `ext` not being a string causes a complete crash as we run `includes` on the strings.

### How to test it?

* You'll need to set mime to `null` in your DB and fetch your images
* There are automated tests simulating server response and what the hook now does

### Related issue(s)/PR(s)

* partially resolves #16005

CC @gu-stav for visibility as he looked into the original issue.

### CODE REVIEW

**Review by simotae14 — APPROVED** [review]
LGTM 👍🏽

File: packages/core/upload/admin/src/hooks/useAssets.js [hunk 1]
```diff
@@ -71,6 +71,31 @@ export const useAssets = ({ skipWhen = false, query = {} } = {}) => {
...
+             * and get errors.
+             */
+            .filter((asset) => asset.name)
+            .map((asset) => ({
+              ...asset,
+              /**
+               * Mime and ext cannot be null in the front-end because
+               * we expect them to be strings and use the `includes` method.
+               */
+              mime: asset.mime ?? '',
```
Comment (gu-stav) [inline packages/core/upload/admin/src/hooks/useAssets.js:91]: What do you think about setting the fallback to `application/octet-stream` instead (which is the most generic mime-type possible)?

Comment (Marc-Roig) [reply packages/core/upload/admin/src/hooks/useAssets.js:91]: sounds good to me , we could check if we can not get the mime type of the asset and assign `application/octet-stream` by default! good point

Comment (joshuaellis) [reply packages/core/upload/admin/src/hooks/useAssets.js:91]: > What do you think about setting the fallback to application/octet-stream instead (which is the most generic mime-type possible)?

I think one thing to think about is how this would impact the `allowedTypes` filtering? 🤔 is that based on `mime`?

Comment (gu-stav) [reply packages/core/upload/admin/src/hooks/useAssets.js:91]: @joshuaellis Good point it is and it is not very smart: it only uses the first part of the mime-type, e.g. the filter for image searches all assets with a mime-type starting with image, such as image/png.

But it wouldn't break the file-filter, because this is the filter it creates: `filters[$and][0][mime][$not][$contains][0]=image&filters[$and][0][mime][$not][$contains][1]=video` in the FE.

Comment (joshuaellis) [reply packages/core/upload/admin/src/hooks/useAssets.js:91]: Me and @Marc-Roig also have a session today to look at some "broken assets" and understand why it's failing in the first place. Because the mime comes from the file.type so it's odd that it breaks.
