### PR TITLE
Remove auto-sync indexes for mongodb from production envs

### LINKED ISSUE #5682: strapi-connector-mongoose 3.0.0-beta.19.4 removes all manually created indexes
**Describe the bug**
After upgrading to 3.0.0-beta.19.4, strapi-connector-mongoose started to remove manually created indexes at launch point.

Breaking changes at mount-models.js:

>     
    // Ensure indexes are synced with the model, prevent duplicate index errors
    Model.syncIndexes(null, () => {
      Model.on('index', error => {
        if (error) {
          if (error.code === 11000) {
            strapi.log.error(
              `Unique constraint fails, make sure to update your data and restart to apply the unique constraint.\n\t- ${error.message}`
            );
          } else {
            strapi.log.error(`An index error happened, it wasn't applied.\n\t- ${error.message}`);
          }
        }
      });
    });

**Expected behavior**
Indexes should remain

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.4
- Database: MongoDB
- Operating system: All

**Additional context**
I think if we would replace syncIndexes to ensureIndexes then it could solve this problem.

### PR DESCRIPTION
**Pull request by Convly**
resolves #5682 

#### Description of what you did:
https://github.com/strapi/strapi/pull/5612 forced MongoDB indexes to be synced with the JSON model.
However, this pr caused some breaking changes for peoples using manually created indexes.
After discussing it in #5682 and while it's not possible to create compound indexes in models.json, the `syncIndex` will now be executed only in a development environment.

### CODE REVIEW

File: packages/strapi-connector-mongoose/lib/mount-models.js [hunk 1]
```diff
@@ -291,7 +290,17 @@ module.exports = ({ models, target }, ctx) => {
           }
         }
       });
-    });
+    };
+
+    // Only sync indexes in development env while it's not possible to create complex indexes directly from models
+    // In other environments it will simply create missing indexes (those defined in the models but not present in db)
+    if (strapi.app.env === 'development') {
```
Comment (petersg83) [inline packages/strapi-connector-mongoose/lib/mount-models.js:297]: @alexandrebodin @Convly Sometimes in the code I see `=== development` and sometimes `!== production`. Is it supposed to be the same? (ie. do we really handle other environments? I saw staging in config but not sure that we really have that case in mind when we code).
If it is supposed to be the same, can we agree on a standard? Either `=== production` && `!== production` or `===development` && `!== development`

File: packages/strapi-connector-mongoose/lib/mount-models.js [hunk 2]
```diff
@@ -291,7 +290,17 @@ module.exports = ({ models, target }, ctx) => {
...
+      // Ensure indexes are synced with the model, prevent duplicate index errors
+      // Side-effect: Delete all the indexes not present in the model.json
+      Model.syncIndexes(null, handleIndexesErrors);
+    } else {
+      handleIndexesErrors();
+    }
```
Comment (petersg83) [inline packages/strapi-connector-mongoose/lib/mount-models.js:303]: `handleIndexesErrors` is used in both `if` and `else`. Can it be written once outside? Since `syncIndexes` is sync, it is not needed to use the callback argument.

File: packages/strapi-connector-mongoose/lib/mount-models.js (hunk 1 above)
Comment (Convly) [reply packages/strapi-connector-mongoose/lib/mount-models.js:297]: In this specific case, we want to restrict the use (and the side-effects) of syncIndexes to the development mode only.
By doing `=== development`, we make sure it will not impact `production` but also `test` and other environment we could have.
About your question, I think it really depends on the situation and it would be difficult to define a standard here.

File: packages/strapi-connector-mongoose/lib/mount-models.js (hunk 2 above)
Comment (Convly) [reply packages/strapi-connector-mongoose/lib/mount-models.js:303]: `syncIndexes` is asynchronous (sync is for synchronization here, not synchronous), thus the callback is needed and it can't be written outside

File: packages/strapi-connector-mongoose/lib/mount-models.js (hunk 1 above)
Comment (alexandrebodin) [reply packages/strapi-connector-mongoose/lib/mount-models.js:297]: These are not the same. As you said users can create as many envs as they want. This means  `env === development` really doesn't have the same meaning as `env !== production`. Here we really only want the development env :)

Simple example si when adding a `test` env to run tests against our strapi app.

File: packages/strapi-connector-mongoose/lib/mount-models.js (hunk 2 above)
Comment (Convly) [reply packages/strapi-connector-mongoose/lib/mount-models.js:303]: syncIndexes is asynchronous (sync is for synchronization here, not synchronous), thus the callback is needed and it can't be written outside.

ref: https://mongoosejs.com/docs/api.html#model_Model.syncIndexes

Comment (petersg83) [reply packages/strapi-connector-mongoose/lib/mount-models.js:303]: Yeah you're right, I got tricked by the name :p.
Is there a reason to run `handleIndexesErrors` after `syncIndexes` and not before?

Comment (petersg83) [reply packages/strapi-connector-mongoose/lib/mount-models.js:303]: @Convly ?
