### PR TITLE
[Modals]: add in prompt to CTB modals to avoid premature closing and data loss

### LINKED ISSUE #13044: [enhancement]: Admin Modals close without warning when forms have unsaved data in
### Describe the bug

When performing a lot of action on the admin, it's often happening that a miss click occurs while fulfilling forms inside modals, thus resetting the form and losing data.

### Expected behavior

I think that modal containing any form can be only explicitly closed (click on cancel button, the `X` button or `esc` key)
Modals that contain only text content (info or confirm modals) can be safely closable by also clicking on the overlay.

### PR DESCRIPTION
**Pull request by joshuaellis**
### What does it do?

* Adds window confirmation when the user tries to close a CTB modal with unsaved changes

### Why is it needed?

* Because users loose data

### Info

Looking in the future (v5) I think we should address how modals are handled across the application and draw up rules – should they be routed or not and then come up with a powerful modal hook to be used across the app and plugins. Whilst we _could_ do this now, I think we'd run the risk of bugs.

This would hopefully be part of the DS going forward.

### Related issue(s)/PR(s)

* resolves #13044

### CODE REVIEW

**Review by ronronscelestes — APPROVED** [review]
LGTM!

File: packages/core/content-type-builder/admin/src/components/FormModal/index.js [hunk 1]
```diff
@@ -790,13 +791,35 @@ const FormModal = () => {
...
   };
 
+  const handleConfirmClose = () => {
+    // eslint-disable-next-line no-alert
+    const confirm = window.confirm(
+      formatMessage({
+        id: 'window.confirm.close-modal.file',
+        defaultMessage: 'Are you sure? Your changes will be lost.',
+      })
+    );
```
Comment (gu-stav) [inline packages/core/content-type-builder/admin/src/components/FormModal/index.js:801]: Are we using the default window.confirm anywhere else? I thought we always rely on our component?

Comment (joshuaellis) [reply packages/core/content-type-builder/admin/src/components/FormModal/index.js:801]: We use it in the `upload` plugin, I couldn't find "our" component, I could see use of `Prompt` but thats from `react-router-dom`.

Comment (gu-stav) [reply packages/core/content-type-builder/admin/src/components/FormModal/index.js:801]: Ok, so we are using `window.confirm` in 3 places throughout the codebase and `ConfirmDialog` (helpler-plugin) far more often. Maybe it's worth checking what the desired behavior is according to Maeva.

Comment (gu-stav) [reply packages/core/content-type-builder/admin/src/components/FormModal/index.js:801]: If that is a deliberate decision, I'm good with that. :)
