### PR TITLE
Fix update entry when empty date field

### LINKED ISSUE #2783: Can't save entry with empty input date
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: v6.7.0
- **Strapi version**: v3.0.0-alpha.23
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

After update to `v3.0.0-alpha.22` (also after update `v3.0.0-alpha.23`):
When I click on the Save button from an existed User, it doesn't work:

screenshot 2019-02-06 at 22 59 32

> TypeError: Cannot read property 'payload' of undefined

**Steps to reproduce the problem**

Create a project and add this to the User model attributes:

```json
"birthdate": {
  "default": "",
  "type": "date"
},
```

**What is the expected behavior?**

Working :)

### PR DESCRIPTION
**Pull request by soupette**
#### Description:

This PR fixes a bug when trying to update an entry that had an empty date field. The bug was coming from trying to get to know if the value was a `moment` object which couldn't work on a null value.

#### My PR is a:
- [ ] 💥 Breaking change
- [X] 🐛 Bug fix #2783 
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Main update on the:
- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [X] Plugin

#### Manual testing done on the following databases:
- [ ] Not applicable
- [X] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

### CODE REVIEW

File: packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js [hunk 1]
```diff
@@ -155,7 +155,7 @@ export function* submit() {
     yield put(submitSuccess());
 
   } catch(err) {
-    if (isArray(err.response.payload.message)) {
+    if (isArray(get(err, 'responsepayload.message'))) {
```
Comment (Aurelsicoko) [inline packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js]: A dot is missing...

```
get(err, 'response.payload.message');
```

Comment (abdonrd) [inline packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js]: Thanks @Aurelsicoko!

```suggestion
    if (isArray(get(err, 'response.payload.message'))) {
```
