### PR TITLE
Fixes #5564

### LINKED ISSUE #5564: Error after saving an administrator profile
**Describe the bug**

After saving an administrator profile, I receive: "An error occurred during record fetch". The console shows this: `[2020-03-20T23:58:54.222Z] debug GET /content-manager/explorer/strapi::administrator/&_page=0&_limit=0&_sort=id (57 ms) 404`

**Steps to reproduce the behavior**
1. Install strapi using `npx create-strapi-app my-project --quickstart`
2. Create a new admin user
3. Once logged in, click on the user's name and then profile
4. Edit the password and hit save
5. Receive the error.

**Expected behavior**
It should not display the error/hang/404.

**System**
- Node.js version:  v12.16.1
- NPM version: 6.14.2
- Strapi version:  3.0.0-beta.19.3
- Database: sqlite (but that doesn't seem to matter - it also happens with mysql)
- Operating system: Debian (also happens in the strapi docker container)

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril.lpz@gmail.com>

#### Description of what you did:
This PR fixes #5564

### CODE REVIEW

File: packages/strapi-admin/admin/src/components/Logout/index.js [hunk 1]
```diff
@@ -22,8 +22,7 @@ const Logout = ({ history: { push } }) => {
 
     push({
       pathname: `/plugins/content-manager/collectionType/strapi::administrator/${id}`,
-      search:
-        '?redirectUrl=/plugins/content-manager/collectionType/strapi::administrator/&_page=0&_limit=0&_sort=id',
+      search: '?redirectUrl=/plugins/content-manager/collectionType/strapi::administrator',
```
Comment (hg-pyun) [inline packages/strapi-admin/admin/src/components/Logout/index.js:25]: More clearable!
