### PR TITLE
fix: serve admin static file with public cache

### LINKED ISSUE #12763: Serve admin static files efficiency
### Describe the bug

Today, static files `*.{js|css}` are not cached, which makes no sense while webpack add a build hash to the files names, so they get invalidated on each build.

### Expected behavior

`*.{js|css}` should be served with `Cache-Control: public, max-age=604800, immutable` header, so client will be able to serve them from their local disk cache (like `favicon.ico`)

image

### PR DESCRIPTION
**Pull request by stafyniaksacha**
### What does it do?

This add `cache-control: public, max-age=31536000, immutable` to `.js` and `.css` files served for the admin panel.

The `immutable` and long `max-age` can safely be used because [`[contenthash:8]` is used by webpack](https://github.com/strapi/strapi/blob/master/packages/core/admin/webpack.config.js#L63) to generate filenames

### Why is it needed?

As you saw on this screen, the total admin sources take `8.7 MB`, which without this patch are always downloaded on each visit.
With this enabled, transferred size go down to `72.4 kB` on each visit (**which represent a ~120% bandwidth saving**)

image

Save bandwidth, save money, save the planet 👍 

### Related issue(s)/PR(s)

close #12763

### CODE REVIEW

File: packages/core/admin/server/routes/serve-admin-panel.js [hunk 1]
```diff
@@ -46,6 +46,13 @@ const serveStatic = (filesDir, koaStaticOptions = {}) => {
   return async (ctx, next) => {
     const prev = ctx.path;
     const newPath = path.basename(ctx.path);
+    const ext = path.extname(ctx.path);
+
+    // publicly cache static files to avoid unnecessary network & disk access
+    if (ext === '.css' || ext === '.js') {
```
Comment (alexandrebodin) [inline packages/core/admin/server/routes/serve-admin-panel.js:52]: - Do you think we could use the setHeaders method of koaStatic instead?
- Should we also cache fonts and svgs as they are hashed the same way?

Comment (stafyniaksacha) [reply packages/core/admin/server/routes/serve-admin-panel.js]: Hi @alexandrebodin !
- `setHeaders` from koaStatic is now used!
- Good catch about fonts and svgs. After looking more into what is built on `dist` folder, I've found that all files can be cached except `.html` files, can you confirm?


I also ensured that this does not affect `strapi develop --watch-admin`

**Review by alexandrebodin — APPROVED** [review]
Great improvement 💯
