### PR TITLE
Fix for failing SQLite3 issue on windows

### LINKED ISSUE #9120: strapi not installing with yarn create strapi-app my-project --quickstart
### Describe the bug

Hi, I cannot install strapi at all, either using yarn or npx
I get errors installing dependencies but I don't know how to address this. It seems to me at some point (sqlite3) it executes a Python2 script, while my systems runs on Python3, but I've no idea (I'm new to th eecosystem as well)

### Steps to reproduce the behavior

execute
yarn create strapi-app my-project --quickstart
at the CLI

### Screenshots

See errors below

### System

- Node.js version: 14.15.4
- NPM version: 6.14.10
- Strapi version: n/a
- Database: n/a
- Operating system: Windows 10

### Additional context

Creating a quickstart project.
Creating files.
Error while installing dependencies:
warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > koa-ip > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning strapi > chokidar > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
warning strapi-admin > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
warning strapi-admin > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning strapi-admin > @babel/polyfill > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning strapi-admin > react-intl > @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
warning strapi-admin > react-intl > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > react-intl > intl-messageformat > intl-messageformat-parser@5.5.1: backwards incompatible, please upgrade to 6.0 instead
warning strapi-admin > reactstrap > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning strapi-admin > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning strapi-admin > webpack-dev-server > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning strapi-plugin-users-permissions > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning strapi-plugin-users-permissions > request > har-validator@5.1.5: this library is no longer supported
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning knex > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning "strapi-admin > bootstrap@4.5.3" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.5.3" has unmet peer dependency "popper.js@^1.16.1".
warning "strapi-admin > @buffetjs/styles > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
warning "strapi-plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning " > strapi-connector-bookshelf@3.4.2" has incorrect peer dependency "knex@^0.20.0".
error C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.15.4 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\mv68b\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mv68b\\OneDrive - University of Glasgow\\Data\\git\\strapi5\\my-project\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\mv68b\OneDrive - University of Glasgow\Data\git\strapi5\my-project\node_modules\sqlite3\lib\binding\napi-v6-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)

 Keep trying!

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Forced SQLite3 v5.0.0 instead of ^5.0.0

### Why is it needed?

Fixes issue for Windows users and an issue with SQLite3 v5.0.1

### Related issue(s)/PR(s)

fixes #9120 
https://github.com/mapbox/node-sqlite3/issues/1424

### CODE REVIEW

File: packages/strapi-generate-new/lib/utils/db-client-dependencies.js [hunk 1]
```diff
@@ -12,6 +12,11 @@ const sqlClientModule = {
 module.exports = ({ scope, client }) => {
   switch (client) {
     case 'sqlite':
+      return {
+        'strapi-connector-bookshelf': scope.strapiVersion,
+        knex: '<0.20.0',
+        [sqlClientModule[client]]: '5.0.0',
```
Comment (alexandrebodin) [inline packages/strapi-generate-new/lib/utils/db-client-dependencies.js:18]: isn't it the latest already ?

Comment (derrickmehaffy) [reply packages/strapi-generate-new/lib/utils/db-client-dependencies.js:18]: Latest is the issue, I'm trying to force the working version until it's fixed upstream. 

5.0.0 works
5.0.1 (Latest) doesn't

Comment (alexandrebodin) [reply packages/strapi-generate-new/lib/utils/db-client-dependencies.js:18]: Ok I saw that in the issue... I would hope the will  fix sqlite before we release though. Let's wait a bit as we are not going release soon & the users can fix it easily on their side

Comment (derrickmehaffy) [reply packages/strapi-generate-new/lib/utils/db-client-dependencies.js:18]: Just FYI if the users aren't aware of the issue this will cause new project generation to fail on windows

Comment (derrickmehaffy) [reply packages/strapi-generate-new/lib/utils/db-client-dependencies.js:18]: Also, they don't patch very often:

Comment (alexandrebodin) [reply packages/strapi-generate-new/lib/utils/db-client-dependencies.js:18]: Ok I'll merge it for the next release but I won't make a release just right now will wait mid week
