### PR TITLE
Fix wrong axios instance in email plugin

### LINKED ISSUE #12034: Strapi not building with pnpm workspace
### Describe the bug

I tried to build strapi in a monorepo using pnpm. I've seen a issue that strapi is not supporting pnpm but manage to build strapi with a small fix.
The issue is in the file : https://github.com/strapi/strapi/blob/master/packages/core/email/admin/src/pages/Settings/utils/api.js
First line:
`import { axiosInstance } from '../../../../../../admin/admin/src/core/utils';`
is refering to the @strapi/admin package and pnpm does not found it, as it renames the packages.

If you replace it by:
`import { axiosInstance } from '@strapi/admin/admin/src/core/utils';`
and add the admin dependency to the email package
it works correctly.

Furthermore it's best for the package isolations not to refer to another package with a relative path.

### Steps to reproduce the behavior

1. create pnpm monorepo
2. create a strapi app in the apps folder
3. try to build

### Expected behavior

The build is successful

### System

- Node.js version: v16
- PNPM version: 6
- Strapi version: v4.0.2
- Database: PostgreSQL
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by soupette**
Signed-off-by: soupette <cyril@strapi.io>

### What does it do?

It fixes #12034, wrong axios instance in email plugin.

### CODE REVIEW

File: packages/core/email/admin/src/pages/Settings/utils/api.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { axiosInstance } from '../../../../../../admin/admin/src/core/utils';
+import axiosInstance from '../../../utils/axiosInstace';
```
Comment (ronronscelestes) [inline packages/core/email/admin/src/pages/Settings/utils/api.js:1]: "axiosInstance" instead of "axiosInstace" small typo issue from the file name

**Review by HichamELBSI — DISMISSED** [review]
LGTM

**Review by ronronscelestes — APPROVED** [review]
LGTM!
