### PR TITLE
fix: formatErrorMessages array values formatting

### LINKED ISSUE #18810: Bulk publish: media field is required
### Required System information

- Node.js version:  v18.17.0 win32 x64
- NPM version: npm v10.0.0 / yarn v1.22.19 <-- I use yarn
- Strapi version: 4.15.5-alpha.4
- Database: postgresql
- Operating system: Windows x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When trying to bulk publish a content entry i receive an error.
It works completely fine just pressing Publish directly on the entry, but bulk publish does not work.

It only happens when a media property is set to required and nested within a component.

### Steps to reproduce the behavior

1. Go to "Content Type Builder"
2. Create new component "Thumbnail" add property "image" as single media `required`
3. Create new collection type "Test" add property "component" and choose "Thumbnail" and set `required`
4. Go to "Content Manager" select "Test" and create new entry.
5. Set image in thumbnail component and save
6. Click on "Select All" and click on "Publish"
7. See error

### Expected behavior

Since the property Thumbnail.image is set, the publish function should not report an error.
This only happens when the media property is required and nested within a component.

### Screenshots

Component: 

Collection Type:

Content Manager:

*Error:*

### LINKED ISSUE #23606: Bulk Publishing shows entries in  "Waiting for action" for entries that can be published individually
### Node Version

20.19.2

### NPM/Yarn/PNPM Version

10.8.2

### Strapi Version

5.13.0

### Operating System

Docker/Podman/LXC

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Reproduction URL

_No response_

### Bug Description

I have a couple of Collections where I can publish entries individually, but when I use bulk publishing, the dialog show a number of entries as  "Waiting for action" with status "[object Object].withField", which prevents me from publishing them. When I open them individually to publish them, publishing works. See attached file

https://github.com/user-attachments/assets/156b5e15-fe44-4d51-a984-a45a03f3c9f5

### Steps to Reproduce

- Create a collection with nested components and/or floating zones that contain mandatory fields or fields with validations.
- Fill all mandatory fields
- Use bulk publish
- entries are in "Waiting for action", even if everything is valid

### Expected Behavior

- all entries are published

### Logs

```shell

```

### Code Snippets

_No response_

### Media

_No response_

### Additional information

_No response_

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by hood**
Fix #23606 
Fix #18810 

### What does it do?

Fix the formatting of error messages in `PublishAction` when errors are a nested array.

### Why is it needed?

Formatting of errors is broken for nested arrays of errors.

### How to test it?

Try bulk-publishing entries containing dynamic zones which have content with validation errors.

### Related issue(s)/PR(s)

#23606, #18810

### CODE REVIEW

File: packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/PublishAction.tsx [hunk 1]
```diff
@@ -66,39 +66,41 @@ const TableComponent = styled(RawTable)`
...
-          ...formatErrorMessages(
-            // @ts-expect-error TODO: check why value is not compatible with FormErrors
-            value,
-            currentKey,
-            formatMessage
-          )
-        );
-      }
+    if (Array.isArray(value)) {
+      messages.push(...formatErrorMessages(value, currentKey, formatMessage));
```
Comment (Adzouz) [inline packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/PublishAction.tsx]: There's a typing issue here breaking the build. `value` has to be a `FormErrors` and its type is changed because of the Object.entries

File: packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/PublishAction.tsx [hunk 2]
```diff
@@ -66,39 +66,41 @@ const TableComponent = styled(RawTable)`
...
+    } else if (
+      value !== null &&
+      typeof value === 'object' &&
+      'id' in value &&
+      'defaultMessage' in value
```
Comment (Adzouz) [inline packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/PublishAction.tsx]: There's still an issue, I tested with dynamic zones and `value` is an object but doesn't have defaultMessage and id as direct children.

Image

I would probably change the logic to go with something like:


```suggestion
    if (!value) return;

    const isErrorMessageDescriptor =
      typeof value === 'object' && 'id' in value && 'defaultMessage' in value;

    if (isErrorMessageDescriptor || typeof value === 'string') {
      const id = isErrorMessageDescriptor ? value.id : value;
      const defaultMessage = isErrorMessageDescriptor
        ? (value.defaultMessage as string)
        : (value as string);
      messages.push(
        formatMessage(
          {
            id: `${id}.withField`,
            defaultMessage,
          },
          { field: currentKey }
        )
      );
    } else {
      messages.push(
        ...formatErrorMessages(value as unknown as FormErrors, currentKey, formatMessage)
      );
    }
```

**Comment by Adzouz** [comment]
FYI, I created a PR to fix the validation issue with required components in dynamic zones: https://github.com/strapi/strapi/pull/25687

**Comment by Adzouz** [comment]
Hi @hood,
Just so you know, I took the liberty to take over the PR to move forward with resolving the related issue 🙏
