### PR TITLE
Fix date field being parsed with a timezone

### LINKED ISSUE #9576: Date value decreases by one day every time entity is saved
### Describe the bug

I'm in the PST timezone. I have a content type with a Date field (i.e. just the date). When you create a new entity of this type and you select a date, then click Save, the date goes back one day. I assume this is a timezone issue. I've seen other open issues on this. However, I've noticed some unique behavior for date-only fields. If you create the entity, set the date, hit save, you'll see the date go back one day. If you then edit the entity and change a field other than the date and hit save, the date will go back one day again, even though you didn't modify the date. Basically any time the entity is saved, the date will go back a day. This doesn't happen for Datetime fields.

### Steps to reproduce the behavior

1. Set your local timezone to PST (not sure if this is necessary but it might be).
2. Create a content type with a Date field (just the date, not a datetime) and at least one other field.
3. Create a new entity, set the date, save it. Notice that the date goes back one day.
4. Edit the entity and change the field other than the Date. Hit save.
5. You'll notice that the date goes back one day even though it wasn't modified.

### Expected behavior

The date should remain the same on each update.

### Code snippets

Looking at the request from the frontend and response from the server, when an entity is saved, the request date is e.g. `2021-02-22`. The response is `2021-02-21`. Hit save again, the request is `2021-02-21` and the response is `2021-02-20`. Etc.

### System

- Node.js version: 12
- NPM version: 6
- Strapi version: 3.5.2
- Database: SQLite
- Operating system: Macos

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Stops using the built in Javascript date which reads the systems timezone by replacing `new Date()` with the date-fns function `parseISO` [see it's docs here](https://date-fns.org/v2.20.3/docs/parseISO)

### Why is it needed?

if the string value passed from upstream in Strapi is `2021-04-14`:

date-fns function
```js
const cast = parseISO(value);
// returns: 2021-04-14T07:00:00.000Z
```

javascript native function
```js
const cast = new Date(value);
const castString = cast.toString();
// returns: Tue Apr 13 2021 17:00:00 GMT-0700 (Mountain Standard Time)
```

The problem is that the built in Javascript `Date()` will use the local systems timezone, and instead the date-fns has the ability to just parse the raw date string and not pass in the system timezone.

### How to test it?

Your system must be set to a timezone that is +/- GMT by at least 1 hour

1. Create a project
2. Create a model with a date field
3. Add a new date via any means
4. See date doesn't move backwards or forwards

### Related issue(s)/PR(s)

fixes #9576

# [Edit]
I (@petersg83 ) took over this PR. It appears the problem is quite complex and larger than this specific issue. We need to refactor all the way we handle dates (disable timezone in pg for instance) and it would be more of a breaking change than a bug fix. So we won't fix everything now but it will be fixed in V4 (should come in beta ~summer and released before the end of the year).

However, I wrote a small change in the admin. It may fix #9576, not sure.

### CODE REVIEW

**Review by alexandrebodin — COMMENTED** [review]
why isn't it necesssary on the other types like datetime ? 

Seems like the test are breaking now

**Comment by derrickmehaffy** [comment]
> why isn't it necesssary on the other types like datetime ?
> 
> Seems like the test are breaking now

Honestly I have no idea, it's extremely difficult for me to track down how or why the local system timezone is being pulled in. The backend should -only- function in UTC. The Admin panel should be doing the time conversion but the date field specifically is the only field that shouldn't even be working with time but the default JS `Date()` generates a date with a time (and timezone).

**Comment by petersg83** [comment]
In your example, why does it return `2021-04-14T07:00:00.000Z` (with hours to 7)?
Here is what I have on my computer :
Capture d’écran 2021-04-15 à 09 55 52

I'm thinking that the best would be that the front sends a `YYYY-MM-DD` string. At the moment the front sends a datetime with a timezone (see bellow). And no matter how we parse it, we won't be able to know what date was displayed to the user when they save.
Capture d’écran 2021-04-15 à 10 02 57

**Comment by derrickmehaffy** [comment]
> In your example, why does it return `2021-04-14T07:00:00.000Z` (with hours to 7)?
> Here is what I have on my computer :
> Capture d’écran 2021-04-15 à 09 55 52
> 
> I'm thinking that the best would be that the front sends a `YYYY-MM-DD` string. At the moment the front sends a datetime with a timezone (see bellow). And no matter how we parse it, we won't be able to know what date was displayed to the user when they save.
> Capture d’écran 2021-04-15 à 10 02 57

That is the issue @petersg83 is we are using parsing functions which is converting it to a datetime (with TZ information).

Realistically we shouldn't be parsing the date other than maybe to change formats (US uses `mm/dd/year` / Europe uses `dd/mm/year` / programming typically uses `year/mm/dd`).

What we need is for the frontend to only send UTC/GMT and parse it on the server like that without reading the system timezone, but we also need to customize this in case some users for whatever reason change the database timezone (which can be done on SQL databases)

File: packages/strapi-connector-bookshelf/lib/formatter.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ const defaultFormatter = {
     }
   },
   date: value => {
-    const cast = new Date(value);
+    const cast = parseISO(value);
     return isValid(cast) ? formatISO(cast, { representation: 'date' }) : null;
```
Comment (alexandrebodin) [inline packages/strapi-connector-bookshelf/lib/formatter.js:42]: We can extract only the date part from the UTC ISO so it stays consistent all the way. we could consider doing this

```suggestion
    return isValid(cast) ? cast.toISOString().split('T')[0] : null
```

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

**Comment by petersg83** [comment]
@soupette I only changed the input data, not the filter. I think it's good enough for the moment, I don't have time to dig if there is a problem with how we handle the dates with the filter
