### PR TITLE
Titles too long do not render properly in content manager

### LINKED ISSUE #13719: Titles too long do not render properly in content manager
### Required System information

- Strapi version: 4.2.0

### Describe the bug

When titles are longer than 300px, the title is truncated and cannot be seen in full, in the content manager's collection table and relation widgets.

It is especially detrimental when titles use prefixes in them that are longer than 50 chars. (which is a case we encountered recently here...)

### Steps to reproduce the behavior

1. Create an entity with a title of more than 50 characters
2. Go to the corresponding collection table or a relation linking to this entity
3. Check that the title is truncated

### Expected behavior

There should be a way to see the full text of the truncated field.

I think adding tooltips in each case could be sufficient.

### Screenshots

Table case :
image

Relation case : 
image

### PR DESCRIPTION
**Pull request by gitstart**
fixes #13719

### What does it do?
shows the whole text which are truncated

### Why is it needed?

Titles too long do not render properly in content manager

### How to test it?

step1: create a content-builder => with type of any string => add text on the contentmanager and  check it out on the table it will be truncated but when hovering it will show thw whole text both for relation single type select and dynamic table 

[DEMO_link](https://www.loom.com/share/e221b54ec4294d9dbe148e47b1bd120e)

### Related issue(s)/PR(s)

#13719

### CODE REVIEW

**Comment by gitstart** [comment]
@gu-stav any update on this?

**Comment by gu-stav** [comment]
@gitstart Sorry for the delay. For me personally this looks good. We will soon release an alpha version where [relational fields will be moved into the main layout](https://github.com/strapi/strapi/pull/14401): with this iteration connected relations will have the tooltip added.

@maevalienard Is currently on vacation: before merging the CM change, I'd like to check with her, if she thinks the tooltip makes sense from a product/ design-perspective.

Does that work for you?

**Comment by gitstart** [comment]
> @gitstart Sorry for the delay. For me personally this looks good. We will soon release an alpha version where [relational fields will be moved into the main layout](https://github.com/strapi/strapi/pull/14401): with this iteration connected relations will have the tooltip added.
> 
> @maevalienard Is currently on vacation: before merging the CM change, I'd like to check with her, if she thinks the tooltip makes sense from a product/ design-perspective.
> 
> Does that work for you?

No issues @gu-stav

**Comment by maevalienard** [comment]
Thanks for the PR @gitstart and thanks @gu-stav for the ping!

The suggestion looks good to me. Good idea :)

File: packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/index.js [hunk 1]
```diff
@@ -55,6 +56,15 @@ const CellContent = ({ content, fieldSchema, metadatas, name, queryInfos, rowId
 
       return <SingleComponent value={content} metadatas={metadatas} />;
 
+    case 'string':
+      return (
+        <Tooltip description={<CellValue type={type} value={content} />}>
```
Comment (gu-stav) [inline packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/index.js:61]: This creates a prop-type error. Could you pass `content` to `description` instead?

```suggestion
        <Tooltip description={content}>
```

**Review by gu-stav — COMMENTED** [review]
Works well for me. Only one comment before we can merge this to fix a prop-type error. Thank you so much for your contribution.

**Review by gu-stav — APPROVED** [review]
Thank you. I think this PR is ready to be merged :)
