### PR TITLE
Fix relations for MySQL versions below 8

### LINKED ISSUE #14840: Fail to save content types with dynamic zone components at 4.5.0
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.10.0
- Strapi version: 4.5.0
- Database: MySQL 5.7.40-1.el7
- Operating system: macOS

### Describe the bug
After upgrading from 4.4.7 I am no longer able to save content types that include a dynamic zone with some components, that further nest other, repeatable components.

In my example, I have a `course` content type with a dynamic zone containing 3 components from the category `course`. Now one them, called `questionnaire chapter` further includes a repeatable component `question`. Whenever `questionnaire chapter` is being added to the dyn zone and edited, update is failing with the following log:

```
[2022-11-12 23:07:58.197] error: UPDATE
            `components_course_questionnaire_chapters_components` as a,
            (
              SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `components_course_questionnaire_chapters_components`
              WHERE `entity_id` = 1
            ) AS b
          SET `order` = b.src_order
          WHERE b.id = a.id - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `com' at line 3
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `entity_id` ORDER BY `order`) AS src_order
              FROM `com' at line 3
    at Query.Sequence._packetToError (/PATH/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/PATH/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/PATH/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/PATH/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/PATH/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/PATH/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/PATH/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/PATH/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (/PATH/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/PATH/node_modules/mysql/lib/Connection.js:198:25)
    at /PATH/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/PATH/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/PATH/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/PATH/node_modules/knex/lib/client.js:146:12)
    at /PATH/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/PATH/node_modules/knex/lib/execution/transaction.js:358:12)
```
### Additionally
for some reason, `question` component is not present in the list of the components I may use for nesting

### I've tried with no avail
- to completely remove and recreate `questionnaire chapter` and `question` components
- remove `questionnaire chapter` from dyn zone

### Temporary fix
was to revert to 4.4.7

Thank you for looking into this!

### PR DESCRIPTION
**Pull request by petersg83**
### What does it do?

- It makes the database information (name, version) available
- It uses an alternative SQL query for MySQL versions below 8

### Why is it needed?

MySQL versions below 8 don't support ROW_NUMBER and it crashes relations.
Strapi should supports MySQL from 5.7.8

### How to test it?

Try to edit relations in a content-type using MySQL 5.7.8

### Related issue(s)/PR(s)

Fix #14840

### CODE REVIEW

File: packages/core/database/lib/index.js [hunk 1]
```diff
@@ -74,7 +74,12 @@ class Database {
 
 // TODO: move into strapi
 Database.transformContentTypes = transformContentTypes;
-Database.init = async (config) => new Database(config);
+Database.init = async (config) => {
+  const instance = new Database(config);
+  instance.databaseInformation = await instance.dialect.schemaInspector.getDatabaseInformation();
+
+  return instance;
+};
```
Comment (petersg83) [inline packages/core/database/lib/index.js:82]: I'm not a fan of this. Is there a better way?

Comment (nathan-pichon) [reply packages/core/database/lib/index.js:82]: It doesn't look bad, enhancing the instance object with a valuable property. Why don't you like it?

File: packages/core/database/lib/entity-manager/regular-relations.js [hunk 2]
```diff
@@ -273,6 +281,96 @@ const cleanOrderColumns = async ({ id, attribute, db, inverseRelIds, transaction
...
+    await db
+      .getConnection()
+      .raw(
+        `UPDATE ?? as a, (SELECT * FROM ??) AS b
+          SET ?? = b.src_order
+          WHERE a.id = b.id`,
+        [joinTable.name, tempOrderTableName, orderColumnName]
+      )
+      .transacting(trx);
+    await db.getConnection().raw(`DROP TEMPORARY TABLE ${tempOrderTableName}`).transacting(trx);
```
Comment (nathan-pichon) [inline packages/core/database/lib/entity-manager/regular-relations.js:329]: As the other promises can reject, maybe we want there to use a `try {...} finally { DROP }` to be sure to drop the temporary table ?

Comment (petersg83) [reply packages/core/database/lib/entity-manager/regular-relations.js]: Yes good idea. The temporary tables are not dropped when the transaction is rolled back

File: packages/core/database/lib/index.js (hunk 1 above)
Comment (nathan-pichon) [reply packages/core/database/lib/index.js:82]: I know what you can do.
You can add databaseInformation in Database. Or add an async method in Database Class that will return `return this.dialect.schemaInspector.getDatabaseInformation()`.

Comment (petersg83) [reply packages/core/database/lib/index.js:82]: If you're fine with that I'm fine with it too :p I wanted to have it in the constructor but I cannot since it's async.

It's what I did at the beginning but it does a query to the database each time then. I would like to avoid it as it can happen to use databaseInformation several times when editing relations.

Or I can do some kind of "singleton".
```js
Database.getDatabaseInformation();

getDatabaseInformation() {
  if (!this.databaseInformation) {
    this.databaseInformation = this.dialect.schemaInspector.getDatabaseInformation();
  }
  return this.databaseInformation;
}
```

Comment (petersg83) [reply packages/core/database/lib/index.js]: (i did it and pushed it)

File: packages/core/database/lib/index.js [hunk 3]
```diff
@@ -58,6 +60,13 @@ class Database {
     return schema ? trx.schema.withSchema(schema) : trx.schema;
   }
 
+  async getDatabaseInformation() {
+    if (!this.databaseInformation) {
+      this.databaseInformation = this.dialect.schemaInspector.getDatabaseInformation();
```
Comment (nathan-pichon) [inline packages/core/database/lib/index.js:65]: Shouldn't you store the result of the promise ? (is this a promise ?)
```suggestion
      this.databaseInformation = await this.dialect.schemaInspector.getDatabaseInformation();
```

Comment (petersg83) [reply packages/core/database/lib/index.js:65]: Yes, I forgot the await!

File: packages/core/database/lib/entity-manager/regular-relations.js [hunk 4]
```diff
@@ -273,6 +281,103 @@ const cleanOrderColumns = async ({ id, attribute, db, inverseRelIds, transaction
...
+        .raw(
+          `UPDATE ?? as a, (SELECT * FROM ??) AS b
+          SET ?? = b.src_order
+          WHERE a.id = b.id`,
+          [joinTable.name, tempOrderTableName, orderColumnName]
+        )
+        .transacting(trx);
+    } finally {
+      await db.connection
+        .raw(`DROP TEMPORARY TABLE IF EXISTS ${tempOrderTableName}`)
```
Comment (jhoward1994) [inline packages/core/database/lib/entity-manager/regular-relations.js:330]: Should we use the same syntax everywhere rather than passing the table name directly in the query here? (e.g. `raw(query, [vars])`)

**Review by jhoward1994 — DISMISSED** [review]
👏 works well, tested here with mySQL 5.7.8. I just had one minor comment

**Review by nathan-pichon — APPROVED** [review]

File: packages/core/database/lib/entity-manager/regular-relations.js (hunk 4 above)
Comment (petersg83) [reply packages/core/database/lib/entity-manager/regular-relations.js:330]: Yes it would be better for consistency indeed. There is no risk however as we create the variable ourselves (no sql injections) and we are not exposed to [casing](https://www.prisma.io/dataguide/postgresql/short-guides/quoting-rules#quoting-identifiers-and-the-problem-of-case-sensitivity) issues in this context.
I will merge it now to avoid to wait for tests but it's something we can refactor in another PR indeed

File: packages/core/database/lib/dialects/mysql/schema-inspector.js [hunk 5]
```diff
@@ -229,6 +232,19 @@ class MysqlSchemaInspector {
 
     return Object.values(ret);
   }
+
+  async getDatabaseInformation() {
+    const [results] = await this.db.connection.raw(SQL_QUERIES.VERSION);
+    const version = results[0]['version()'];
+
+    const [versionNumber, databaseName] = version.split('-');
+    const database = databaseName && databaseName.toLowerCase() === 'mariadb' ? 'MariaDB' : 'MySQL';
```
Comment (alexandrebodin) [inline packages/core/database/lib/dialects/mysql/schema-inspector.js:241]: You could use constants for the database names to avoid string checks afterwards.
It would be nice to add this in the dialect API instead and get the version info in the init phase of the dialect. 

That would avoid doing this in the schema inspector and make the API cleaner

**Review by alexandrebodin — CHANGES_REQUESTED** [review]

File: packages/core/database/lib/entity-manager/regular-relations.js (hunk 4 above)
Comment (petersg83) [reply packages/core/database/lib/entity-manager/regular-relations.js]: Since we didn't release I made the change :)

File: packages/core/database/lib/dialects/mysql/database-inspector.js [hunk 6]
```diff
@@ -0,0 +1,28 @@
+'use strict';
+
+const { MARIADB, MYSQL } = require('../../utils/constants');
+
+const SQL_QUERIES = {
+  VERSION: `SELECT version()`,
```
Comment (alexandrebodin) [inline packages/core/database/lib/dialects/mysql/database-inspector.js:6]: can you alias it to avoid the `['version()']` line 16?

File: packages/core/database/package.json [hunk 7]
```diff
@@ -36,6 +36,7 @@
     "fs-extra": "10.0.0",
     "knex": "1.0.7",
     "lodash": "4.17.21",
+    "semver": "7.3.8",
```
Comment (alexandrebodin) [inline packages/core/database/package.json:39]: Do we really need semver for this ?

Comment (petersg83) [reply packages/core/database/package.json:39]: I find it is the safest way. For cases like `7.3.8` < `7.3.11` where it's `true` but a simple string comparison would be `false`. Same for when we will have MySQL 11 (`11.0.0` < `8.0.0`):p
We can do without but then we need to do string manipulation

File: packages/core/database/lib/dialects/mysql/database-inspector.js (hunk 6 above)
Comment (petersg83) [reply packages/core/database/lib/dialects/mysql/database-inspector.js]: done

File: packages/core/database/package.json (hunk 7 above)
Comment (alexandrebodin) [reply packages/core/database/package.json:39]: I'm more worried DB versions might not respect this convention instead. but this will work for now.

**Review by alexandrebodin — CHANGES_REQUESTED** [review]
Can you add some error handling in case some goes wrong when getting the version (parsing, query itself...) so it just returns what it can & make sure the semver check can work if version is null or undefined?

**Review by Marc-Roig — APPROVED** [review]

**Review by nathan-pichon — APPROVED** [review]
